### ISSUE TITLE
Configure CopyBara to title PR "GitHub Sync"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1000]
... instead of just the first commit, which is really confusing.

Is this possible @alorenzen?

**Comment by alorenzen** [comment]
I looked at some point in the last few weeks and didn't see anything obvious.

**Comment by matanlurey** [comment]
I'll send an email to the CopyBara team.

**Comment by matanlurey** [comment]
This is available in the next release of CopyBara (pending).

**Comment by matanlurey** [comment]
Done!
