### ISSUE TITLE
Re-enable skipped tests due to analyzer mismatch

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1001]
Some tests are failing at (soon to be HEAD):
https://api.travis-ci.org/v3/job/348472012/log.txt

This is due to a slight change in the analyzer (externally and internally).

We'll be skipping those tests, temporarily, using `tags: ['fails-on-travis']`.

**Comment by matanlurey** [comment]
It's also possible these two particular tests are too brittle.

Maybe we shouldn't test precise offsets?

**Comment by kevmoo** [comment]
We could be silly and just test for the inclusive range 15-16 – handle both cases?

**Comment by matanlurey** [comment]
Seems like a silly amount of work for something that probably isn't important.
