### ISSUE TITLE
Remove use of requestAnimationFrame from setState.

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1004]
This is causing flakes/timeouts on travis for `ngmodel_test` and related.

As discussed offline, this is also not testable (and causes other flakes and timeouts internally), and we don't have any stabilizers or special logic for this. I recommend just a `scheduleMicrotask`.

**Comment by alorenzen** [comment]
I'm not working on `setState`.

**Comment by matanlurey** [comment]
Fixed internally by @ferhatb.
