### ISSUE TITLE
Try using build_node_compilers+JSDom for testing

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1006]
@pulyaevskiy's `build_node_compilers`:
https://github.com/pulyaevskiy/node-interop/tree/master/build_node_compilers

`jsdom`:
https://github.com/jsdom/jsdom

We might be able to run many many of our tests that just rely on being in a JavaScript environment, but not a "real" browser (headless or otherwise) in Node+JSDom, and get much faster run times. Might be worth an experiment.

**Comment by pulyaevskiy** [comment]
Thanks for tagging me. Let me know if I can help with Node-related stuff.
