### ISSUE TITLE
 ngIf not working

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/angular#1015]
* Dart VM version: 2.0.0-dev.32.0 (Thu Mar 1 18:39:53 2018 +0100) on "macos_x64"
* AngularDart 5.0.0-alpha+6 
* MacOSX
* Chrome

Set bool in OnActivate event.
Use the variable in the template with some condition(ngIf)

```
import 'package:angular/angular.dart';
import 'package:angular_router/angular_router.dart';

// AngularDart info: https://webdev.dartlang.org/angular
// Components info: https://webdev.dartlang.org/components

@Component(
  selector: 'my-form',
  template: '''
  is it activated? {{ activated }}, {{ activated == true ? 'YES!' : 'no :(' }}
  <div *ngIf="activated">hello, I am really activated!</div>
  <template [ngIf]="activated">hello template, I am really activated!</template>
  ''',
  directives: const [],
)
class ToppersonComponent implements OnActivate, OnDeactivate {
  String name = 'some name';
  bool activated = false;

  ToppersonComponent() {
    print('Creating ToppersonComponent...');
  }
  void onActivate(RouterState previous, RouterState current) {
    print('activating...');
    activated = true;
  }
  void onDeactivate(RouterState previous, RouterState current) {
    print('deactivating...');
    activated = false;
  }
}

```
[provider.zip](https://github.com/dart-lang/angular/files/1778974/provider.zip)

**Comment by jonahwilliams** [comment]
It looks like you are missing an NgIf in your providers list.  Still, the compiler should probably warn you if you are using a directive which doesn't exist.  Possibly related to [#951](https://github.com/dart-lang/angular/issues/951)

**Comment by jodinathan** [comment]
As it didn’t warn me or threw an exception took me a while to figure it out.
Sorry bothering.

Atenciosamente, 

Jonathan Rezende

**Comment by jonahwilliams** [comment]
Don't worry about it, the compiler should definitely warn you in cases like these.
