### ISSUE TITLE
Can not run in virtual catalog on IIS (404 Not Found)

### ISSUE THREAD

**Issue by Cododoc** [dart-lang/angular#1016]
* Dart VM version: 2.0.0-dev.30.0 (Thu Feb 22 14:08:47 2018 +0100) on "windows_x64"
* AngularDart Version `5.0.0-alpha+6`
* Windows
* Chrome

----

Hello!
I deploy project on iis server in virtual catalog in default web site (c:\inetpub\wwwroot\Budget\).

When i try to open it some part loaded,
```
Request URL:http://webdemo01/budget/main.dart.js
Request Method:GET
Status Code:200 OK
```

but another not:
```
Request URL:http://webdemo01/packages/$sdk/dev_compiler/web/dart_stack_trace_mapper.js
Request Method:GET
Status Code:404 Not Found

Request URL:http://webdemo01/packages/$sdk/dev_compiler/amd/require.js
Request Method:GET
Status Code:404 Not Found
```

It should look at  webdemo01/budget/packages...

**Comment by matanlurey** [comment]
I don't know much about IIS.

You shouldn't be deploying an application with DDC. Could you try Dart2JS?

https://github.com/dart-lang/build/blob/master/docs/getting_started.md#switching-to-dart2js

**Comment by matanlurey** [comment]
This issue was moved to dart-lang/build#1098
