### ISSUE TITLE
Tracking issue: Typed TrackByFn

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1020]
This is just a place-holder until I or someone else has time to fill it.

**Comment by alorenzen** [comment]
Dupe of https://github.com/dart-lang/angular/issues/833?

**Comment by matanlurey** [comment]
Duplicate of #833.

**Comment by chalin** [comment]
FYI, the API page for TrackByFn still refers to this issue (which has been closed): https://pub.dartlang.org/documentation/angular/5.0.0-alpha+10/angular/TrackByFn.html

> NOTE: It is not safe to simply assume that the second parameter is of your custom type (neither TrackByFn nor NgFor allow that) at this time: `https://github.com/dart-lang/angular/issues/1020`.
