### ISSUE TITLE
Add the DISABLED state to form controls

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/angular#1037]
TS pull requrest: https://github.com/angular/angular/pull/10994
TS Design Doc: https://docs.google.com/document/d/1k_iYcgTS1cDJkyXvBWQZGPlkWZhEqAVphC0xyKSAqPs/edit

**Comment by chalin** [comment]
IMHO this is also related to added support for form reset (I thought that there used to be an issue open for form reset but I can't find it atm).

**Comment by alorenzen** [comment]
Yes, it is. Both have been added to the 5.0 milestone, as I'm planning to work on both in the next few weeks.

**Comment by chalin** [comment]
Nice! Is there still an issue that can use to track the progress of form reset?

**Comment by alorenzen** [comment]
https://github.com/dart-lang/angular/issues/216

**Comment by alorenzen** [comment]
This is now supported, via a `[ngDisabled]` attribute. There were too many existing, conflicting usages of `[disabled]` to support that directly.

See https://github.com/dart-lang/angular/commit/3ca1de175d213986d4733aedb2025e9b37c3e262 for an example of how to use it.
