### ISSUE TITLE
We need a v4->v5 migration guide for external users

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1038]

**Comment by eredo** [comment]
Currently working on something similar for us internally, but from v3.1 to v5, maybe I can contribute here. Where will it be stored?

**Comment by kwalrath** [comment]
We have some info in https://webdev-dartlang-org-dev.firebaseapp.com/dart-2, but we'd be happy to point to anywhere we more info.

**Comment by eredo** [comment]
@matanlurey  is this somewhat near to what you had in mind: https://github.com/eredo/angular/blob/doc-migration-v4-v5/doc/migration/v5.md ?

**Comment by matanlurey** [comment]
@eredo Sorry it took so long to follow-up here. Why don't you send a PR for what you have so far?

**Comment by eredo** [comment]
@matanlurey will do later today.

**Comment by matanlurey** [comment]
Ping @eredo :)

**Comment by matanlurey** [comment]
I'm happy with the doc and CHANGELOG we have today. It could always be improved, of course.
