### ISSUE TITLE
Refactor _flattenProviders for ReflectiveInjector

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1045]
As @leonsenft pointed out in code review, it's difficult to follow.

**Comment by leonsenft** [comment]
I don't think a refactor is warranted. I was just suspect that multi providers are also added to all providers here.

https://github.com/dart-lang/angular/blob/7a4b6afb8bbee8adb2c3ae24157eafb46bd541c4/angular/lib/src/di/injector/runtime.dart#L256-L261

My intuition is that the second statement should be in an `else` clause.

**Comment by leonsenft** [comment]
Literally just adding an else.

```dart
if (_isMultiProviders(item)) {
  multiProviders.add(item);
} else {
  allProviders[item.token] = item;
}
```

I'll run this through our tests. Perhaps this supports a feature I'm not aware of which is why I asked.

**Comment by matanlurey** [comment]
Closed upstream by @leonsenft.
