### ISSUE TITLE
Support testability with static app initialization

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#1048]
I've converted some of the Angular example apps so that they are initialized w/o `initReflector()`: e.g., see the toh-0 source in https://github.com/dart-lang/site-webdev/pull/1380.

While the apps and component tests build and run w/o issues, protractor-based E2E is failing because at runtime the app no longer initializes the globally defined function `getAngularTestability()`. This function is set at [angular/lib/src/platform/browser/testability.dart:48](https://github.com/dart-lang/angular/blob/9510572e79c5c0281c80bd88eeda8e3168a8f997/angular/lib/src/platform/browser/testability.dart#L48):

<img width="682" alt="screen shot 2018-03-08 at 11 41 13" src="https://user-images.githubusercontent.com/4140793/37164055-504e8f1c-22c7-11e8-8951-fab40b745ee2.png">

To repro:

- Use the toh-0 source in https://github.com/dart-lang/site-webdev/pull/1380
- Dart 2-dev.32
- Angular 5-alpha+7

**Comment by matanlurey** [comment]
Yes, the "very static" initialization currently doesn't support testability.

As a workaround you could set this up yourself.

**Comment by leonsenft** [comment]
Isn't this WIA? I thought we decided this should never have been included in the bootstrapped module, but didn't want to remove it and break users. Since moving to bootstrapFactory is a conscious decision teams would have to make, they'd be required to provide Testability themselves if needed?

**Comment by matanlurey** [comment]
True. We do need to at minimum (a) provide documentation _how_ to do that (b) add a test or two ourselves verifying that it works. I'm going to modify this and make it a docs/feature instead.

**Comment by chalin** [comment]
> As a workaround you could set this up yourself.

I've tried adding it myself, but it seems like I'd need access to the following function, but it isn't currently exported:

```
angular/src/platform/browser_common.dart:4:Function createInitDomAdapter(TestabilityRegistry testabilityRegistry) {
```

**Comment by matanlurey** [comment]
FWIW, this is going to be fixed in the `runApp` migration, as it was required for internal users.
