### ISSUE TITLE
let should be changed to final to match dart syntax

### ISSUE THREAD

**Issue by jrote1** [dart-lang/angular#105]
Should `let` be changed to `var` to match dart syntax?

**Comment by zoechi** [comment]
isn't `let` more like `final`?
I also don't like `let` because it has no equivalent in Dart at all.

**Comment by jrote1** [comment]
@zoechi sorry yeah `final` would be more appropriate

**Comment by ferhatb** [comment]
There was a discussion around this and we decided to keep template syntax as compatible as we can unless there is a *very* good reason and user benefit. There was a deliberate commit to change to let and keep things in sync.

**Comment by jrote1** [comment]
@ferhatb if this angular is for dart only, if its made that dart syntax is what you use in the templates then confusion should be pretty minimal, that's my thought anyway

**Comment by olostan** [comment]
Just a small addition - `*ngFor` uses `let hero of heroes` and Dart's syntax for iteration is `var fruit in fruits` (notice "of" and "in"). 

If 'let' should be changed, then 'of' as well should be changed

**Comment by matanlurey** [comment]
Closing this as not planned.

Future versions of Dart (`> 2.0.0`) might make changes here anyway, so we're not going to invest the time in changing the compiler (and current users) if this will again change soon. Sorry for the inconvenience.
