### ISSUE TITLE
Rename `APP_BASE_HREF`

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#1059]
With the Dart 2 shift from SCREAMING CAPS constant names to regular camel case, will `APP_BASE_HREF` be renamed as well?

cc @alorenzen @matanlurey @kwalrath

**Comment by chalin** [comment]
`APP_BASE_HREF` has been deprecated via https://github.com/dart-lang/angular/commit/6927eedd101c9c049878c9aa1a6fddad6e1cc949

**Comment by matanlurey** [comment]
This is done as of HEAD, and will be removed in the next release.
