### ISSUE TITLE
Update to build_runner ^0.8.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#1061]
_benchmarks/pubspec.yaml:16:  build_runner: ^0.7.9
_goldens/pubspec.yaml:16:  build_runner: ^0.7.9
_tests/pubspec.yaml:24:  build_runner: ^0.7.9
angular_ast/pubspec.yaml:20:  build_runner: ^0.7.9
angular_compiler/pubspec.yaml:28:  build_runner: ^0.7.9
angular_forms/pubspec.yaml:16:  build_runner: ^0.7.9
angular_router/pubspec.yaml:19:  build_runner: ^0.7.9
angular_test/pubspec.yaml:21:  build_runner: ^0.7.9
examples/hacker_news_pwa/pubspec.yaml:12:  build_runner: ^0.7.9
examples/hello_world/pubspec.yaml:10:  build_runner: ^0.7.9
examples/hello_world_no_reflector/pubspec.yaml:10:  build_runner: ^0.7.9
examples/registration_form/pubspec.yaml:12:  build_runner: ^0.7.9

**Comment by matanlurey** [comment]
I'll tackle this today assuming other dependencies are ready.

**Comment by kevmoo** [comment]
Sweet!

**Comment by matanlurey** [comment]
Done.

**Comment by kevmoo** [comment]
Thanks!
