### ISSUE TITLE
Move ComponentState updates to ApplicationRef

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1071]
As discussed offline with @ferhatb.

The current logic for `ComponentState` is faulty:

https://github.com/dart-lang/angular/blob/b318c8cf5653f2a8a25b40db4a0df5baa2834fdf/angular/lib/src/core/application_ref.dart#L184-L219

1. `PlatformRef.injector` never has an `ExceptionHandler` (this is per-application)
2. If we got this to work, it could report errors to the _wrong_ app.
3. It doesn't respect the error reporting behavior (detectCrash, state.Errored).

We'll need the following refactors (and tests around it):

* [x] Add a top-level `ApplicationRef` instance, i.e. `currentApplication`.
* [x] Move the `scheduleViewUpdate` methods to `ApplicationRef`.
* [x] Report errors on a per-component basis, setting `.Errored` state.

**Comment by ferhatb** [comment]
LGTM. As long as we have cost amortized across all view updates instead of extra cost on each viewUpdateCallback, this should be fine.

**Comment by matanlurey** [comment]
Landed in #1128.
