### ISSUE TITLE
Lexer doesn't support Unicode supplementary planes

### ISSUE THREAD

**Issue by daftspaniel** [dart-lang/angular#1094]
I am moving an app from v4 to v5 and have an issue with templates:
https://github.com/daftspaniel/np8080/blob/master/lib/src/toolbar/toolbar.html

This template contains special characters marked up for HTML(` &#8617;`).

In angulardart 5, the expected character is not displayed - the hex code does e.g. `&#8617`;

angular: 5.0.0-alpha+7
Linux
Chrome
Dart VM version: 2.0.0-dev.39.0 
Dart VM version: 2.0.0-dev.39.0 (Fri Mar 16 00:17:07 2018 +0100) on "linux_x64"

**Comment by alorenzen** [comment]
The new `angular_ast` template parser only supports HTML characters in raw text. For attributes, like in your example, we no longer de-escape those characters. Instead, you should use the standard dart unicode support, via `\u`

So `[menutitle]="'&#x1f440; View'"` becomes `[menutitle]="'\u{1f440} View'"`

**Comment by daftspaniel** [comment]
@alorenzen Thanks for responding.

I tried your suggestion but got the error:
Lexer Error: Invalid unicode escape [\u{1f4] at column 2 in expression ['\u{1f440} View']

The same escape sequence works correctly in a print statement.

**Comment by leonsenft** [comment]
It looks like our lexer doesn't support code points from supplementary planes, which are those of the form `\u{xxxxxx}`, as it assumes all `\u` sequences are followed by exactly four hexadecimal digits.

https://github.com/dart-lang/angular/blob/6c03a3e73bbacc951d80fe4b9ccec61de81e1299/angular/lib/src/compiler/expression_parser/lexer.dart#L322-L326

Also @alorenzen, what if the escaped code point is in static DOM, and not part of a binding? Is the only pattern to use an interpolation?

**Comment by matanlurey** [comment]
@leonsenft I am making this a release blocker as it looks like it could block migrations, right?

**Comment by matanlurey** [comment]
Closed by #1111.
