### ISSUE TITLE
Our build_{*} packages need update notifications

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1095]
It's incredibly easy to use an out-of-date set of `build_runner`, `build_web_compilers`, and `build_test` - which, coupled with https://github.com/dart-lang/pub/issues/912, means that users frequently use out of date development dependencies, and when they try and upgrade, hit deadlocks or incomprehensible error messages, i.e (as an example only):

```
Resolving dependencies...
Package angular_components has no versions that match >=0.9.0-alpha+8 <0.10.0 derived from:
- merck_crm_mashup depends on version ^0.9.0-alpha+8
Process finished with exit code 1
```

For the final v5.0.0 release we need to solve this, somehow. Ideas:

* The `webdev` CLI checks.
* We add the concept of [peer dependencies][peer] to `pub` so `angular` can express:

```yaml
peer_dependencies:
  build_runner: ...
  build_test: ...
```

[peer]: https://github.com/npm/npm/blob/2e3776bf5676bc24fec6239a3420f377fe98acde/doc/files/package.json.md#peerdependencies

**Comment by kevmoo** [comment]
`webdev` does  verify versions https://github.com/dart-lang/webdev/blob/8696973a95167f54140abd587c9677dd95def21d/webdev/lib/src/pubspec.dart#L104

IntelliJ will update `webdev` (via `pub global activate webdev`) once per "session"
We also plan to add outdated checking to `webdev`

**Comment by matanlurey** [comment]
@kevmoo Any updates here?

**Comment by kevmoo** [comment]
> Any updates here?

Nope. Please add a tracking issue to `webdev` – this can be the beginning of `doctor`

**Comment by matanlurey** [comment]
I think its fair to say this isn't worse than it was before. Removing as a release blocker.
