### ISSUE TITLE
angular_forms pubspec refers to angular_test alpha+8 which DNE

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#1097]
The angular_forms pubspec for version alpha+8 contains this dependency:
https://github.com/dart-lang/angular/blob/75b62a6dbb3ddbec590ec8e459245aa2e7bd6d08/angular_forms/pubspec.yaml#L15

But, AFAIK, angular_test alpha+8 does not exist. This is preventing me from building the dartdocs for angular_forms.

cc @kwalrath @alorenzen

**Comment by alorenzen** [comment]
@matanlurey looks like you bumped from `-alpha+5` to `-alpha+8` by accident.
