### ISSUE TITLE
hacker_news_pwa: Hitting reload while on "new" tab leaves the list empty

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/angular#1100]
When I run hacker_news_pwa via https://dart-hn.firebaseapp.com/ in Chrome on MacOS, I get the following behavior:

1) Go to https://dart-hn.firebaseapp.com/
2) Click "new"
3) Hit reload in the browser
4) Observe a list with 19 entries, no contents in any of the entries, and no next page link (see image below)
5) Hitting any sequence of "reload", "top", and "new" again doesn't change anything.
6) Hitting any of "show", "ask", and "jobs" takes you back to a healthy state.

Similarly going straight to either 
  https://dart-hn.firebaseapp.com/new or
  https://dart-hn.firebaseapp.com/top
gives the same result, i.e., a list with 19 empty entries

![image](https://user-images.githubusercontent.com/3276024/37702103-c91a834a-2cf1-11e8-88ac-647473ef4c78.png)

**Comment by jensjoha** [comment]
In chrome on linux it's the same --- also if opening anything in a new tab for instance.

**Comment by matanlurey** [comment]
@leonsenft is working on a fix for this!
