### ISSUE TITLE
Compiler bad state exception: Failed to parse @Component

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#1102]
Excerpt from this log https://travis-ci.org/dart-lang/site-webdev/jobs/356348669:

```nocode
hierarchical-dependency-injection > pub run build_runner build --fail-on-severe --delete-conflicting-outputs --output=build
[INFO] Generating build script completed, took 225ms
[INFO] Reading cached asset graph completed, took 176ms
[INFO] Checking for updates since last build completed, took 366ms
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
Bad state: Failed to parse @Component annotation for AppComponent:
One or more of the following arguments were unresolvable: 
* coreDirectives
* carComponents
* HeroesListComponent
* VillainsListComponent
The root cause could be a mispelling, or an import statement that 
looks valid but is not resolvable at build time. Bazel users should 
check their BUILD file to ensure all dependencies are listed.
```

The updated `hierarchical-dependency-injection` example code is from https://github.com/dart-lang/site-webdev/pull/1416, specifically: https://github.com/dart-lang/site-webdev/tree/2cea12e299da9f2c8c738158d8b8c0a24224ad25/examples/ng/doc/hierarchical-dependency-injection

Environment:
* Dart SDK 2.0.0-dev.40.0 (Fri Mar 16 00:17:07 2018 +0100) on "macos_x64"
* AngularDart Version 5.0.0-alpha+8

cc @kwalrath

**Comment by matanlurey** [comment]
Are you sure all 4 of those arguments were resolved, i.e. no missing imports?

I won't be able to address this without a repro case.

**Comment by chalin** [comment]
Repro:

- Download https://github.com/angular-examples/hierarchical-dependency-injection/archive/5-dev.zip, then unzip and cd into folder
- `pub get`
- `pub run build_runner build`

```
hierarchical-dependency-injection-5-dev > pub run build_runner build
[INFO] Generating build script completed, took 237ms
[INFO] Building new asset graph completed, took 588ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
Bad state: Failed to parse @Component annotation for AppComponent:
One or more of the following arguments were unresolvable: 
* coreDirectives
* carComponents
* HeroesListComponent
* VillainsListComponent
The root cause could be a mispelling, or an import statement that 
looks valid but is not resolvable at build time. Bazel users should 
check their BUILD file to ensure all dependencies are listed.


[SEVERE] build_web_compilers|entrypoint on web/main.dart:
 Unable to find modules for some sources, check the following imports:

`import 'package:hierarchical_di/app_component.template.dart' as _ref2;` from hierarchical_di|web/main.template.dart at 13:1

[INFO] Running build completed, took 5.5s
[INFO] Caching finalized dependency graph completed, took 83ms
[INFO] Succeeded after 5.6s with 428 outputs
```

Note that the analyzer doesn't report any issues:

```
hierarchical-dependency-injection-5-dev > dartanalyzer --preview-dart-2 lib web
Analyzing lib, web...
No issues found!
```

**Comment by matanlurey** [comment]
@chalin There is an error:

```
[SEVERE] build_web_compilers|entrypoint on web/main.dart:
 Unable to find modules for some sources, check the following imports:

`import 'package:hierarchical_di/app_component.template.dart' as _ref2;` from hierarchical_di|web/main.template.dart at 13:1
```

... we really need `--fail-on-severe` as the default :-/

**Comment by chalin** [comment]
As you can see from the [opening comment](https://github.com/dart-lang/angular/issues/1102#issue-307268671), I am using `--fail-on-severe`:

```console
> pub run build_runner build --fail-on-severe --delete-conflicting-outputs --output=build
```

Running this command generates output in the following order (see https://github.com/dart-lang/angular/issues/1102#issuecomment-375627392)):

- Firstly there is the message:
  _Unhandled exception in the AngularDart compiler!_
  **Please report a bug**
- Only after is there the error [you highlighted in the previous comment](https://github.com/dart-lang/angular/issues/1102#issuecomment-376360194).

I'm not claiming that there might not be an error in the code, but the compiler message says that there _is_ a bug in the compiler and to **Please report a bug**. This is it :)

**Comment by matanlurey** [comment]
Ah, thanks. Yes, looks like we have a bug.

**Comment by matanlurey** [comment]
Fixed by https://github.com/dart-lang/angular/pull/1244/commits/ce14ebe4226ac68d637579d1fc22e14966a3f786.
