### ISSUE TITLE
Add a favicon to hacker_news_pwa example

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#1104]
See https://dart-hn.firebaseapp.com/favicon.ico

**Comment by leonsenft** [comment]
That's because there is no favicon.ico asset there, so this rewrite kicks in:

https://github.com/dart-lang/angular/blob/9e69d5a6f52cf1f563ffc360a35f03f84843a90b/firebase.json#L9-L14

**Comment by kevmoo** [comment]
Might could we add a favicon?

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/angular/commit/a95fcad085abee29f2c19775fe0c65630cb95edc
