### ISSUE TITLE
We need IDEs/Analyzer to resolve .template.dart files

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1107]
Internally, we have modifications to the analysis server that understands the generated directory (i.e. `bazel-bin`), and upon a full build allows us to at least be able to resolve/check imports to `*.template.dart` files, which are common to import in AngularDart v5.0.0.

Externally, we have no such logic, so we rely on users ignoring analysis warnings.

This is a tracking issue. We can go into more detail as needed, but tl;dr, open some of our examples in IntelliJ, and notice where warnings are present (or ignored with a `// ignore: ...`). Thanks!

/cc @MichaelRFairhurst

**Comment by eredo** [comment]
Is this already implemented? I was surprised today when Intellij started to autocomplete components generated in the `.template.dart` file.

**Comment by MichaelRFairhurst** [comment]
This is indeed already implemented for the analysis server, but you will still get 'generated file not found' (or something like that) warnings if you use dartanalyzer. So IDE support only at the moment, unfortunately. Glad that the existing support was useful already though :)

**Comment by matanlurey** [comment]
I think we are going to just say what is released so far is all we are doing for a while.
