### ISSUE TITLE
Meta: How to keep travis green with external deps?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1114]
* `examples/github_issues` uses `ng_bootstrap`.
* `examples/registration_form` uses `angular_components`.

... neither of these point to us at HEAD, which means that we can't make a breaking change on MASTER without our travis becoming red. I'm considering making both of these projects an "allowed failure" - i.e. its just an FYI when broken and we don't block merges.

Thoughts? @alorenzen @leonsenft  @nshahan

**Comment by nshahan** [comment]
Realistically, if you made them allowed failures and your build was green, would you ever look at the details to see if there were any failures that were allowed?

**Comment by matanlurey** [comment]
No. I'm thinking we'd need some sort of dashboard, realistically.

(I sort of want one anyway, so maybe this is a good reason to start)

**Comment by matanlurey** [comment]
I think we can close this. We just ignore those failures, for now.
