### ISSUE TITLE
Which temporary files are generated by Angular 5 builds?

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#1119]
Should we be dropping the  [Remove unneeded build files][] from the Angular [Deployment][] page?

TL;DR

---

As described in the [Remove unneeded build files][] from the [Deployment][] page, the build process _used to_ create:

> many intermediate files (with suffixes like `.ng_meta.json` and `.ng_summary.json`) that you don't need when deploying your app.

I don't believe that these particular files are created anymore, but are there others? How about files like these:

```nocode
foo.template.linked.sum
foo.template.module
foo.template.unlinked.sum
foo.unlinked.sum
```

Are these files (and `.js.map`) only produced by dartdevc?

cc @kwalrath @kevmoo 

[Deployment]: https://webdev.dartlang.org/angular/guide/deployment
[Remove unneeded build files]: https://webdev.dartlang.org/angular/guide/deployment#remove-unneeded-build-files

**Comment by matanlurey** [comment]
Closing in favor of https://github.com/dart-lang/angular/issues/1123, as we don't expect users to have to delete any files manually - the infrastructure just doesn't exist for us to do an (automated) cleanup.
