### ISSUE TITLE
Specify & test proper escaping behavior in angular_ast

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular#1122]
See #1109 for what raised this issue up.

We need to be careful in what `lexeme` values angular_ast exposes for quoted tokens when they have escapes.

This is not affecting users for now, I don't think, but a matter of correctness so I wanted to put those correctness notes somewhere we can track.

I think we should:
* treat `\"` and `\'` as a escaped quotes within double & single strings respectively
* test that we remove the escapes in this case *before* performing dart parsing or it will fail[1]
* leave all other escapes alone[2]
* including treating `\\"` as a backslash in front of an escaped quote[3]

[1] Do we have tests that confirm we correctly handle `[x]="\"y\""`? Naively, the `quotedToken.lexeme` will be literally `\"y\"` which is not valid dart. To do what the users want, we should remove the \ in this case.

[2] We need to leave the other escapes alone. Take `[x]="'\n'"`. If we parse this and turn `\n` into an actual newline character, this is no longer valid dart. We need to leave it as-is for the dart parser in this case, and all other cases, including '\\'[3].

[3] We don't need to handle `\\` as an escape and doing so would be annoying to users
- You need it if you want a `\` in front of a `"` without escaping the `\`, like so: `[x]="foo\\"`, but this is not valid dart so we don't need to support it.
- If we treat `\\` as `\`, then it gets painful to write `[x]="'a backslash: \\\\'"` so we probably should not do this unless we have to
- You could in theory want to put a `\\` before an escaped `"`, which would be `\\\"` in dart ie `[x]="\"a quote: \\\" \""` but if we treat `\\"` as a `\` before a `\"`, then its still possible albeit unexpected `[x]="\" a quote: \\" \""` which is probably OK since its still well specified.
- this means our regex requires some tinkering, though, as we're using the "standard" escapes-in-a-string regex which will treat `"\\"` as a backslash in quotes rather than as a backslash before an escaped quotes character with no matching close quote.

**Comment by matanlurey** [comment]
We are deleting the expression parser in https://github.com/dart-lang/angular/issues/1121, so I'm not sure this is relevant anymore.

**Comment by matanlurey** [comment]
Oops, this is not related to expressions. Sorry!

**Comment by matanlurey** [comment]
So... I don't think any of us plan on working in this area for quite some time.
