### ISSUE TITLE
Release builds should be able to delete/hide unneeded files

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1123]
This is a tracking bug for work here: https://github.com/dart-lang/build/issues/1010.

In our case, we want the final release build to just be:
* Static assets (minus the original `.dart` code, which has been compiled to JS)
* No source maps
* No `.ng_placeholder`
* No summaries (linked, or unlinked)
* No other intermediate files

Marking this is as a (final) release blocker.

**Comment by kevmoo** [comment]
https://github.com/dart-lang/build/issues/1010 is fixed now. What's left here?

**Comment by matanlurey** [comment]
Closed as of closing https://github.com/dart-lang/angular/issues/1282.
