### ISSUE TITLE
Router v1 -> v2 migration page updates needed

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#1133]
Followup to: https://github.com/dart-lang/angular/issues/1127#issuecomment-375814891.

The [router migration page](https://github.com/dart-lang/angular/blob/master/angular_router/g3doc/migration_guide.md) should be updated to mention the following:

1. The new way that the **router matches paths**, and how this affects component instantiation (including the fact that components can be instantiated but not rendered).

2. A component can be **reusable** only if it is either

   - A top-level component, i.e., one whose route path doesn't have a parent.
   - A child of a reusable component.

   This wasn't a constraint with the 1.x router: a child component could be reusable w/o the parent being reusable. This is related to #732, #733; though it isn't clear if these will be addressed before 5-final.

Both (1) and (2) should be listed in the **Major changes** section.

cc @kwalrath @leonsenft 

Related: #1038

**Comment by leonsenft** [comment]
> This wasn't a constraint with the 1.x router: a child component could be reusable w/o the parent being reusable.

It's possible we pull the caching behavior out of the router-outlet, and maintain it separately in the router. That way if a component is reusable we could detach it from it's current outlet then reattach it to its new parent.

This has a major flaw however. If your component injects anything, those dependencies may no longer be valid if it's parent is destroyed. Services could be torn down, DOM references could be invalidated, or you may unintentionally be using the wrong implementation of a service that different parents provide.

The current behavior is unexpected and even undesirable at times, but arguably safer as none of these concerns exist. Do you know if the old router addressed this?

**Comment by matanlurey** [comment]
Closed as obsolete. I don't think we intend to work on this any further.
