### ISSUE TITLE
Wrong route component instance gets deactivation notice

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#1134]
This is a followup to #1127, though there is **no** component reuse attempted in this example.

**Repro**:

- Environment:
  - Dart 2-dev.42
  - Angular 5-alpha+8.
- Download https://github.com/angular-examples/router/archive/5-dev.zip, then 
  - `unzip` and 
  - `cd` into folder
- `pub get`
- `pub run build_runner serve`
- **Launch** chrome over http://localhost:8080/#crises, and **open the JS console**.
  Note the number in parentheses after the _Crisis Center_ title: `(0)`. That number is the instance ID of the `CrisisListComponent` that is rendering.
- **Click** the first crisis in the list. Note:
  - The `CrisisListComponent` instance ID displayed is now 1.
  - The `CrisisComponent` instance ID is 1.
  - The `CrisisComponent` instance 0 that was created was used during path matching.
- **Edit** the crisis name by prefixing it with an "x".
  - Console logs the name change of `CrisisComponent` instance 1.
- **Click** _Cancel_ in the crisis detail view. Note:
  - `CrisisComponent` instance 0 (the **instance used for path matching**) receives the `canDeactivate()` and `onDeactivate()` calls.
  - `CrisisComponent` instance 1 (the instance that was actually rendered), receives no messages.

**Expected behavior**: A dialog should have appeared asking if you'd like to save changes to the name.
What actually happens: no dialog appears.

This is the JS console output that is generated:

```
[0] CrisisListComponent created
>> [0] CrisisList onActivate null (null) -> crises ...
>> [0] CrisisList _selectHero null
>> [0] CrisisList onActivate selected null
>> [0] CrisisList onSelect selected 1
[0] CrisisComponent created
>> [0] CrisisList onDeactivate crises -> crises/1
[1] CrisisListComponent created
>> [1] CrisisList onActivate crises (null) -> crises/1 ...
[1] CrisisComponent created
>> [1] CrisisList _selectHero 1
>> [1] CrisisList onActivate selected 1
>> [0] CrisisList onSelect selected 1, after gotoDetail
>> [1] Crisis onActivate crises (null) -> crises/1 ...
>> [1] Crisis name changed to Dragon Burning Cities
>> [1] Crisis onActivate name = Dragon Burning Cities
>> [1] Crisis name changed to xDragon Burning Cities
>> [0] Crisis canDeactivate crises/1 -> crises; null == null
>> [0] CrisisList onDeactivate crises/1 -> crises
>> [0] Crisis onDeactivate crises/1 (null) -> crises
[2] CrisisListComponent created
>> [2] CrisisList onActivate crises/1 (null) -> crises ...
>> [2] CrisisList _selectHero null
>> [2] CrisisList onActivate selected null
```

cc @kwalrath

**Comment by leonsenft** [comment]
Thanks for reporting @chalin. This definitely looks like a bug!
