### ISSUE TITLE
Pub not installed in appdata

### ISSUE THREAD

**Issue by Coder-Ashish** [dart-lang/angular#1135]
hey i installed DART latest stable version for windows but when i installed it pub folder in not installed with because of that i cant use dart . could you please tell me how to install angular dart.

**Comment by zoechi** [comment]
See https://www.dartlang.org/install/windows for installation instructions for Windows

**Comment by matanlurey** [comment]
As @zoechi mentioned, please follow the installation instructions above. We're not able to give support in this issue tracker for installing the SDK.
