### ISSUE TITLE
Template directive errors go unreported

### ISSUE THREAD

**Issue by dineshbhosale** [dart-lang/angular#1143]
From this official example :
https://github.com/angular-examples/toh-2/tree/5-dev

remove `coreDirectives` from `lib/app_component.dart`

no errors, no warnings, no errors in console, `ngFor` doesn't work,

Add `coreDirectives`, everything works.

when you remove `formDirectives` , it clearly shows an error message, this doesn't happen when `coreDirectives` is removed.

Operating system:
Arch Linux 64-bit

Angular:
angular: ^5.0.0-alpha

build_runner version : 
version: "0.8.0"

dart --version output :
Dart VM version: 2.0.0-dev.38.0 (Thu Mar 15 16:53:42 2018 +0100) on "linux_x64"

**Comment by chalin** [comment]
Hi @dineshbhosale: as was mentioned elsewhere, this issue should be open over site-webdev because it concerns an example from that repo. Also note that I've created https://github.com/dart-lang/site-webdev/issues/1436 to track the issue of use of the Angular Analyzer plugin.
