### ISSUE TITLE
Need integration test for analysis server/IDEs

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1145]
We're tracking a series of crashes that make IntelliJ/analysis server unusable at HEAD:
* https://github.com/dart-lang/sdk/issues/32599 
* https://github.com/dart-lang/sdk/issues/32693 
* https://github.com/dart-lang/sdk/issues/32692 

It would be great to be able to track these in our CI. This would also help validate `angular_analyzer_plugin` regressions, at least until we host it in the this repository (/cc @MichaelRFairhurst  - maybe we should just do this now?).

Ideas:
* Launch analysis server
* Analyze/index the entire mono repo, similar to how IntelliJ would
* Ensure no crashes or errors

**Comment by MichaelRFairhurst** [comment]
We can do this internally, and maybe apply that testing externally too
