### ISSUE TITLE
Easy way to run our tests at an edge SDK

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1146]
For example, for developers of DDC, Dart2JS, Analyzer, et al.

I'd also love a way to temporarily set `dependency_overrides` for the build folks to iterate, but that might be much more work.

Thoughts? @natebosch @alorenzen

**Comment by alorenzen** [comment]
So I've always envisioned having a single `versions.yaml` file that we could modify and then update all pubspecs in the mono_repo to those versions.

So if we want to bump `build_runner` to `^X.Y.Z`, we only have to manually change `versions.yaml`.

This could support `dependency_overrides` and the SDK as well.

**Comment by matanlurey** [comment]
I like that idea. It already plays in well with our `dev:deps` check:
https://github.com/dart-lang/angular/blob/master/dev/bin/deps.dart

**Comment by matanlurey** [comment]
One thing we'd need is to make sure `build_runner` supports a custom SDK.

@natebosch is that something that is supported already, say, with an environment variable?

**Comment by matanlurey** [comment]
@natebosch brought up in https://github.com/dart-lang/build/issues/1205 this is just based on what SDK executes `pub run`, so I suppose you could point to one - i.e. `/my/custom/sdk/bin/pub run`, should do what we want.
