### ISSUE TITLE
Unhandled exception in AngularDart alpha+9 compiler: pipe cannot be found

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#1163]
**Environment**: Angular 5-alpha+9, Dart 2-dev.43, MacOS.

Here is the error:

```
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
Template parse errors:
line 3, column 12 of HeroListComponent: ParseErrorLevel.FATAL: The pipe 'fetch' could not be found.
      <div *ngFor="let hero of ('heroes.json' | fetch) ">
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
line 7, column 26 of HeroListComponent: ParseErrorLevel.FATAL: The pipe 'fetch' could not be found.
      <p>Heroes as JSON: {{'heroes.json' | fetch | json}}</p>
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This occurs when attempting to build the `examples/ng/doc/pipes` project in https://github.com/dart-lang/site-webdev/pull/1446. Here is the travis log showing the error: https://travis-ci.org/dart-lang/site-webdev/jobs/360062832

cc @kwalrath

**Comment by matanlurey** [comment]
You wrote `pipes: [commonPipes, const ClassProvider(FetchJsonPipe)])`.

... `Provider`s do not work in this list.

**Comment by chalin** [comment]
Doh! Sorry for the noise.
