### ISSUE TITLE
Warning after changing COMMON_PIPES to commonPipes

### ISSUE THREAD

**Issue by hentoesch** [dart-lang/angular#1165]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* [x] Dart SDK Version (`dart --version`)
Dart VM version: 2.0.0-dev.43.0 (Wed Mar 28 01:04:15 2018 +0200) on "linux_x64"

* [x] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
5.0.0-alpha+9

* [x] Whether you are using Windows, MacOSX, or Linux (if applicable)
Linux, Ubuntu 16.04

After upgrade to 5.0.0-alpha+9 and changing "COMMON_PIPES" to "commonPipes" i get the warning:
A type literal expected

**Comment by matanlurey** [comment]
@hentoesch Sorry, we'll need more information here.

Can you share the file you are seeing the error or, or a smaller reproduction case? Thanks!

**Comment by hentoesch** [comment]
all i did was changing alpha+8 to alpha+9 and COMMON_PIPES to commonPipes.


the source file extract:

import 'dart:html';
import 'dart:async';
import 'package:angular/angular.dart';
import 'package:angular_components/angular_components.dart';

@Component(
    selector: 'billing-list',
    directives: const [
      materialDirectives,
      coreDirectives,
    ],
    pipes: const [commonPipes],
    providers: const [materialProviders],
    templateUrl: "billing_list.html")
class BillingList implements OnInit, OnDestroy { 
...
}

pubspec.yaml

version: 0.0.1

environment:
  sdk: ">=2.0.0-dev.28.0 <2.0.0"

dependencies:
  angular: 5.0.0-alpha+9
  angular_components: 0.9.0-alpha+9
  angular_forms: ^2.0.0-alpha+1
  angular_router: 2.0.0-alpha+9

**Comment by matanlurey** [comment]
Can you share an exact copy-paste of the analysis error you are getting?

**Comment by hentoesch** [comment]
warning: A type literal expected (type_literal_expected at [...] lib/views/billing/billing_list.dart:39)

**Comment by hentoesch** [comment]
with COMMON_PIPES i i get thes messages:

error: Arguments of a constant creation must be constant expressions. (const_with_non_constant_argument at [] lib/views/billing/billing_list.dart:39)
error: The values in a const list literal must be constants. (non_constant_list_element at [] lib/views/billing/billing_list.dart:39)
error: Undefined name 'COMMON_PIPES'. (undefined_identifier at [] lib/views/billing/billing_list.dart:39)

so according to changelog: i changed COMMON_PIPES to commonPipes

**Comment by matanlurey** [comment]
Thanks. I'm seeing another bug locally preventing me from repro'ing. I'll follow up.

**Comment by matanlurey** [comment]
So I'm not sure what local issues you are having, but it works just fine for me.

Here is the example code:
https://github.com/matanlurey/angular_scratch/tree/master/use_common_pipes

Please re-open if you can give me more information on how to reproduce for you.

**Comment by hentoesch** [comment]
after putting the 

pipes: const [commonPipes]
directly after the selector: 
and before the directives:

the warning disappeared.

**Comment by fredtma** [comment]
I don't understand how exactly you resolved the `type literal expected` warning
But I am getting the same with `formDirectives`

- [x] Dart VM version: 2.0.0-dev.49.0
- [x] AngularDart Version (5.0.0-alpha+10)
- [x] Ubuntu 16.04

```
@Component(
  selector: 'user-form',
  templateUrl: 'user_form_component.html',
  directives: const [coreDirectives, formDirectives]
)
```
`coreDirectives` is fine though
