### ISSUE TITLE
Could not resolve the package 'angular'

### ISSUE THREAD

**Issue by Cododoc** [dart-lang/angular#1166]
When I try to build progject on new version of Dart I have error "Could not resolve the package 'angular'"

Run as `pub run build_runner build --config release --output build`

**build.release.yaml**
```
targets:
  $default:
    sources:
      - lib/**
      - web/**
    builders:
      config_budget:
        options:
          mode: release
      build_web_compilers|entrypoint:
        generate_for:
        - web/**.dart
        options:
          compiler: dart2js
          dart2js_args:
          - --fast-startup
          - --minify
          - --trust-type-annotations
          - --trust-primitives
```

I can build and serve project using command `pub run build_runner serve`

It build correct on dart version 2.0.0-dev.36.0.

---

Dart VM version: 2.0.0-dev.43.0 (Wed Mar 28 01:04:15 2018 +0200) on "windows_x64"
Angular 5.0.0-alpha+9
Windows
Output:
```
[WARNING] Throwing away cached asset graph due to Dart SDK update.
[INFO] build_web_compilers|entrypoint on web/main.dart:Running dart2js with --fast-startup --minify --trust-type-annotations --trust-primitives -ppackages -oweb/main.dart.js web/main.dart
[SEVERE] build_web_compilers|entrypoint on web/main.dart:
Dart2Js finished with:

Error: Could not resolve the package 'angular' in 'package:angular/angular.dart'.
Error: Could not resolve the package 'angular_router' in 'package:angular_router/angular_router.dart'.
Error: Could not resolve the package 'angular' in 'package:angular/src/bootstrap/run.dart'.
Error: Could not resolve the package 'budget' in 'package:budget/app_component.dart'.
Error: Could not resolve the package 'budget' in 'package:budget/app_component.template.dart'.
Error: Could not resolve the package 'http' in 'package:http/browser_client.dart'.
Error: Could not resolve the package 'budget' in 'package:budget/src/security/security.service.dart'.
package:angular/angular.dart@0+1:
Error: Not found: package:angular/angular.dart.
Error: Compilation failed.

[INFO] Succeeded after 57.1s with 1299 outputs
```

**Comment by zoechi** [comment]
have you tried running `pub get`?

**Comment by matanlurey** [comment]
This sounds a lot like a class of bug that was fixed in a newer version of Dart2JS/build_web_compilers.

Please share the results of your `pubspec.lock` file, if possible, privately or publicly.

**Comment by matanlurey** [comment]
OK. I noticed you have `build_web_compilers: 0.3.4`, not the latest `0.3.4+2`.

Can you try a `pub upgrade` (get latest compatible versions), and tell me if the problem persists?

**Comment by Cododoc** [comment]
Yes. But it does not update.
`build_web_compilers 0.3.4 (0.3.4+2 available)`

**Comment by matanlurey** [comment]
It sounds like your SDK version is too old.
https://github.com/dart-lang/build/blob/c9b7dc0fc9eef0505d61702289f12a419fecfd48/build_web_compilers/pubspec.yaml#L8

... make sure you have the latest `-dev`.

**Comment by Cododoc** [comment]
@matanlurey  Thank you. It work.
