### ISSUE TITLE
Router should queue navigation requests

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#1171]
Currently the router makes no attempt to synchronize calls to `navigate()`. Because this method is async and often awaits the result of other async methods outside the router's control, it's possible for a later invocation of `navigate()` to complete first. Furthermore, calls to `navigate()` modify the state of router outlets, so multiple requests being active simultaneously could completely break the state of the router.

This also makes redirecting on `canActivate()` failures very clunky because you're guaranteed to have two live requests active temporarily.

The router should queue any invocations of `navigate()` if a previous request is still pending. This will ensure only one invocation of `navigate()` is active at a time.

**Comment by chalin** [comment]
🎉
