### ISSUE TITLE
Support class and attribute selectors in a Component annotation

### ISSUE THREAD

**Issue by chances** [dart-lang/angular#1197]
Though the [Directive `selector` docs](https://webdev.dartlang.org/api/angular/angular/Directive/selector) give an example of multiple selectors, an exception is thrown with the following component declaration:

```dart
@Component(
  selector: 'material-card, .material-card',
  templateUrl: 'material_card.html',
  styleUrls: const [
    'material_card.css',
  ],
  directives: const [coreDirectives, NgClass],
)
class MaterialCardComponent {}
```

```
EXCEPTION: InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('material-card, .material-card') is not a valid name.
```

Both selectors are useful because, in some cases, instead of wrapping some content in a `material-card` element I need to apply Card styles and `ng-content` slots to a different component.

## Other Cases

Also observed with these other cases:

### `.material-card` Selector
```
EXCEPTION: InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('.material-card') is not a valid name.
```

### `[material-card]` Selector
```
EXCEPTION: InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('') is not a valid name.
```

## Details

* Dart VM version: 2.0.0-dev.44.0 (Mon Apr 2 16:14:58 2018 +0200) on "macos_x64"
* AngularDart Version : `5.0.0-alpha+8`
* Chrome 65

<details>
<summary>Stack trace</summary>
package:$sdk/dev_compiler/amd/dart_sdk.js 73526:19                                               [_createElement_2]
package:$sdk/dev_compiler/amd/dart_sdk.js 73523:81                                               createElement]
package:portal/app/src/components/ui_components/card/material_card.template.dart 30:44           new
package:portal/app/src/components/user_page_component/user_page_component.template.dart 175:19   build
package:angular/src/core/linker/app_view.dart 248:12                                             create
package:portal/app/src/components/user_page_component/user_page_component.template.dart 1955:16  build
package:angular/src/core/linker/app_view.dart 258:12                                             createHostView
package:angular/src/core/linker/component_factory.dart 111:15                                    create
package:angular_router/src/directives/router_outlet_directive.dart 126:37                        async.async.<fn>.<fn>.dart.fn
package:$sdk/dev_compiler/amd/dart_sdk.js 16416:21                                               putIfAbsent
package:angular_router/src/directives/router_outlet_directive.dart 125:41                        prepare
package:$sdk/dev_compiler/amd/dart_sdk.js 23886:34                                               body
package:stack_trace                                                                              parent.registerCallback.dart.fn
package:$sdk/dev_compiler/amd/dart_sdk.js 29704:56                                               _rootRun
package:$sdk/dev_compiler/amd/dart_sdk.js 29331:14                                               run
package:angular/src/core/zone/ng_zone.dart 191:20                                                [_run]
package:$sdk/dev_compiler/amd/dart_sdk.js 29532:14                                               run
package:$sdk/dev_compiler/amd/dart_sdk.js 29452:14                                               runGuarded
package:$sdk/dev_compiler/amd/dart_sdk.js 29488:33                                               dart.fn
package:angular/src/core/zone/ng_zone.dart 177:9                                                 safeMicrotask
package:stack_trace                                                                              parent.registerCallback.dart.fn
package:$sdk/dev_compiler/amd/dart_sdk.js 29707:14                                               _rootRun
package:$sdk/dev_compiler/amd/dart_sdk.js 29331:14                                               run
package:angular/src/core/zone/ng_zone.dart 191:20                                                [_run]
package:$sdk/dev_compiler/amd/dart_sdk.js 29532:14                                               run
package:$sdk/dev_compiler/amd/dart_sdk.js 29452:14                                               runGuarded
package:$sdk/dev_compiler/amd/dart_sdk.js 29488:33                                               async._AsyncCallbackEntry.new.dart.fn
package:$sdk/dev_compiler/amd/dart_sdk.js 26289:13                                               _microtaskLoop
package:$sdk/dev_compiler/amd/dart_sdk.js 26296:13                                               _startMicrotaskLoop
package:$sdk/dev_compiler/amd/dart_sdk.js 26370:11                                               internalCallback

-----async gap-----
package:$sdk/dev_compiler/amd/dart_sdk.js 25418:42  _completeWithErrorCallback
package:$sdk/dev_compiler/amd/dart_sdk.js 23908:17  body
package:stack_trace                                 parent.registerCallback.dart.fn
package:$sdk/dev_compiler/amd/dart_sdk.js 29704:56  _rootRun
package:$sdk/dev_compiler/amd/dart_sdk.js 29331:14  run
package:angular/src/core/zone/ng_zone.dart 191:20   [_run]
package:$sdk/dev_compiler/amd/dart_sdk.js 29532:14  run
package:$sdk/dev_compiler/amd/dart_sdk.js 29452:14  runGuarded
package:$sdk/dev_compiler/amd/dart_sdk.js 29488:33  dart.fn
package:angular/src/core/zone/ng_zone.dart 177:9    safeMicrotask
package:stack_trace                                 parent.registerCallback.dart.fn
package:$sdk/dev_compiler/amd/dart_sdk.js 29707:14  _rootRun
package:$sdk/dev_compiler/amd/dart_sdk.js 29331:14  run
package:angular/src/core/zone/ng_zone.dart 191:20   [_run]
package:$sdk/dev_compiler/amd/dart_sdk.js 29532:14  run
package:$sdk/dev_compiler/amd/dart_sdk.js 29452:14  runGuarded
package:$sdk/dev_compiler/amd/dart_sdk.js 29488:33  async._AsyncCallbackEntry.new.dart.fn
package:$sdk/dev_compiler/amd/dart_sdk.js 26289:13  _microtaskLoop
package:$sdk/dev_compiler/amd/dart_sdk.js 26296:13  _startMicrotaskLoop
package:$sdk/dev_compiler/amd/dart_sdk.js 26370:11  internalCallback
</details>

**Comment by matanlurey** [comment]
@hterkelsen @leonsenft Do we have a resolution here? Issue or WAI?

**Comment by leonsenft** [comment]
I don't know, it's our choice whether we want to support it or not. I'm not aware of any limitations as to why the component selector _has_ to match an element, although perhaps it's to discourage attempting to put multiple components on the same element.

> instead of wrapping some content in a material-card element I need to apply Card styles and ng-content slots to a different component.

This use case will likely never be possible. Components are responsible for rendering their view, thus two components can't control the same one (which is the implication of having two rooted at the same element).

Also, we currently use the selector to create the component host element. We could likely change it to be the tag name of the element the component matched in a static template, however this doesn't cover the case for dynamically created components. For dynamic components we could just use any tag like a `div`, but it would make inspecting the DOM less obvious as to what component got rendered there.

**Comment by matanlurey** [comment]
I'm going to close this as WAI today, as I don't see an obvious bug or FR. 

Please re-open if I'm mistaken.

**Comment by chances** [comment]
@matanlurey If this is WAI, then please update the docs to reflect the fact that you cannot use class or attribute selectors for the Directive `selector`. The exception thrown should also be clear about this if I "incorrectly" use a class or attribute selector.

**Comment by leonsenft** [comment]
@chances They're still supported for `@Directive` selectors, since those aren't responsible for rendering the element. It's just `@Component` selectors that have this limitation.
