### ISSUE TITLE
Rename `OpaqueToken` to `InjectionToken`, or drop it in favor of abstract class types

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#1236]
Issue #288 had been created to cover this, but it was repurposed.

The name `OpaqueToken` is very general, and not indicative of what the token class is meant to be used for. As you know, AngularTS **switched to the [InjectionToken](https://angular.io/guide/dependency-injection-in-action#injectiontoken) name** a while ago.

Another thought might be to **do away with `OpaqueToken` altogether**, and suggest that developers use an abstract class type as a token instead. E.g.

```dart
abstract class SomeUrlToken {}

class Foo {
  String _someUrl;
  Foo(@Inject(SomeUrlToken) this._someUrl);
  // ...
}

// Instead of
const someUrlToken = const OpaqueToken('someUrl');
// ...
```

I think that the use of an abstract class in this way would have all the benefits of what `OpaqueToken` has to offer. Since abstract classes are built-in, dropping the `OpaqueToken` feature would simplify usage of Angular.

cc @kwalrath

**Comment by chalin** [comment]
Actually, dropping `OpaqueToken` might also allow us to drop `@Inject()`.

**Comment by chalin** [comment]
Replacing `MultiToken` (a subtype of `OpaqueToken`) might be a bit trickier. Maybe multi-token support could be generalize to any subtype of `List`?

```dart
abstract class UsStatesToken implements List<String> {}

@Component(
  providers: [
    const ValueProvider(UsStatesToken, 'California'),
    const ValueProvider(UsStatesToken, 'New York'),
  ]
)
class Foo {
  Foo(UsStatesToken usStates);
}
```

**Comment by matanlurey** [comment]
I think we decided this wasn't worth the churn for v5.x (we already deprecated/changed a lot), and given the addition of `MultiToken`, as you mentioned, it makes it difficult to make a truly great replacement API. I don't see us doing this in the foreseeable future (there are a lot more important things to focus on).

**Comment by chalin** [comment]
Ok, fair enough.
