### ISSUE TITLE
`OpaqueToken` Map injected as null

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#1238]
The following code builds and runs w/o errors or warnings under Angular 5-alpha+10 (Dart 2-dev.47):

```dart
const appConfigMapToken = const OpaqueToken('app.config');
const appConfigMap = {
  'apiEndpoint': 'api.heroes.com',
  'title': 'Dependency Injection'
};

@Component(
  selector: 'map-token-test',
  template: 'App config title: {{title}}',
  providers: [const ValueProvider.forToken(appConfigMapToken, appConfigMap)],
)
class MapTokenTestComponent {
  dynamic _config;
  String get title =>
      _config == null ? 'oops' : _config is String ? _config : _config['title'];

  MapTokenTestComponent(@Inject(appConfigMapToken) this._config);
}
```

When run, the component view shows `App config title: oops` because `null` is injected for the app config Map.

If you change the provided value of the `appConfigMapToken` to a string (and make no other changes):

```dart
    providers: [const ValueProvider.forToken(appConfigMapToken, 'this works')]
```

Then the value gets injected as expected.

I've seen this warning in the code https://github.com/dart-lang/angular/blob/41624e89a4613317de67d000b8947bf500b18497/angular/lib/src/di/providers.dart#L314-L318

But IMHO, the compiler should issue a warning and/or the runtime should report an error rather than just injecting null. FYI, I encountered this problem while converting the Angular docs DI example app.

cc @kwalrath

**Comment by matanlurey** [comment]
We do not support optional const, which is the most likely suspect.

**Comment by chalin** [comment]
I had the const there before and it didn't work. But I'll check again. Regardless, it would be nice to be warned that something has gone wrong.

**Comment by chalin** [comment]
You were right: adding the const back works. Sorry about that. As agree offline, I'll not remove those new/const tokens.
