### ISSUE TITLE
build_runner [INFO]: Found 2 constructors for class ...; using constructor .

### ISSUE THREAD

**Issue by supermuka** [dart-lang/angular#1251]
After that updated to `angular 5.0.0-alpha+10` and `Dart 2.0.0-dev.47.0` (run on Windows), when `pub run build_runner serve` is ran, the following message is presented **Found 2 constructors for class ANYCLASS; using constructor .**. See examples:

> [INFO] angular on package:angular_components/material_input/material_number_accessor.dart:Found 2 constructors for class MaterialNumberValueAccessor; using constructor .
> [INFO] angular on package:angular_components/material_input/material_auto_suggest_input.dart:Found 2 constructors for class MaterialAutoSuggestInputComponent; using constructor .
> [INFO] angular on package:angular_components/material_menu/material_fab_menu.dart:Found 2 constructors for class MenuItemGroupsComponent; using constructor .

**Comment by matanlurey** [comment]
Thanks for filing. This was unintentional and it's fixed at HEAD (and in the next release).
