### ISSUE TITLE
Compiler needs to support --preview-dart-2

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#1255]
https://github.com/dart-lang/angular/blob/5d700edd1ce5cc211e7a67b0fd8e83e5b67c6c15/angular/lib/src/compiler/output/dart_emitter.dart#L330

This is just running `build_runner` in checked mode at this commit

Yes, checked mode is going away. But guessing this will blow up w/ --preview-dart-2

**Comment by matanlurey** [comment]
Unfortunately most of our compiler is likely unsound right now.

I know @hterkelsen and @leonsenft were looking at what is required to fix some of these, so I am repurposing this issue instead of filing issues for specific lines that aren't working.

**Comment by kevmoo** [comment]
> I know @hterkelsen and @leonsenft were looking at what is required to fix some of these, so I am repurposing this issue instead of filing issues for specific lines that aren't working.

SGTM

**Comment by alorenzen** [comment]
Yeah, I tried to use `--preview-dart-2` last week, and filed two issues around it: https://github.com/dart-lang/build/issues/1293 and https://github.com/dart-lang/sdk/issues/32871

Really need help on getting CFE more stable before we can make a huge push here. 

/cc @JekCharlsonYu

**Comment by alorenzen** [comment]
This is also blocked by https://github.com/dart-lang/sdk/issues/32188

**Comment by matanlurey** [comment]
I believe we determined this is working now. We might still fail on corner/error-recovery cases, but I don't think there is specific work for us to do anymore at this time.
