### ISSUE TITLE
Experiment with providing a `*ngForOnce`

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1263]
Fork off of https://github.com/dart-lang/angular/issues/1262.

@hterkelsen and I discussed creating another directive, `*ngForOnce`:

* It would not use `DoCheck`, and instead only check if the _identity_ of the list changes.
* It would treat `null` as an empty list and clear all contents (if any)
* It would do a simple for-loop iteration over the list
* It would not support (or need to support) `trackBy`

For cases like the HNPWA, this would perfectly sub-in for `ngFor`. The feeds are coming from an RPC (or cache), and the underlying `List` will never change, but the default implementation will keep checking to see if it changes (plus the code-size of shipping the `*ngFor` differ).

_NOTE: Naming wise, we might want to choose something else, not `ngForOnce`._

**Comment by jonahwilliams** [comment]
How about `NgForYourEyesOnly`?

On a serious note, I've written this class a few times on my own, would be happy to contribute an implementation and tests.

**Comment by zoechi** [comment]
I'd expect a parameter to `ngFor` would be more discoverable. `ngFor="let item of items;check=identity"` (default `content`)

This would also work well with `built_value` in fact with all immutable collections. 

A common interface for immutable lists would be helpful, then `ngFor` could recognize itself if identity checks are enough. 
As far as I know there is not such thing currently.

**Comment by matanlurey** [comment]
> I'd expect a parameter to `ngFor` would be more discoverable.

It also wouldn't let smaller applications that didn't need the complexity of `ngFor` tree-shake the differs, which can be substantial (xKb).

> A common interface for immutable lists would be helpful, then `ngFor` could recognize itself if identity checks are enough. As far as I know there is not such thing currently.

Yes, and it is unlikely that we will get such a thing prior to this directive.

**Comment by matanlurey** [comment]
This landed as `ngForIdentity`.
