### ISSUE TITLE
HNPWA: Replace AngularDart logo w/ Dart Logo

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#1264]
Less confusion. Emphasize the Dart brand.

CC @timsneath

**Comment by chalin** [comment]
The new logos are live at https://github.com/dart-lang/logos.

**Comment by leonsenft** [comment]
This was already done in https://github.com/dart-lang/angular/commit/c96cce765ed7b3a7de6b65d18a672eb5728f6173.
