### ISSUE TITLE
Test & update/remove the examples in the API docs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/angular#1267]
I happened to notice that a code snippet in an API doc comment (https://github.com/dart-lang/angular/blob/master/angular/lib/src/core/di/decorators.dart#L175) uses `throws`, which has been deprecated in favor of `throwsA()`. If we tested and auto-included the examples in dartdocs, this would've been caught.

/cc @chalin

**Comment by matanlurey** [comment]
No longer planned.
