### ISSUE TITLE
Support custom regex for matching parameters in route paths

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/angular#1270]
I believe this has been confirmed as coming in the Gitter chat but thought it would be useful having a ticket to know when it's landed.

I'd like to be able to do something like this:

```dart
final RoutePath yearRoute = new RoutePath(
  path: ":year{4}",
);
final RoutePath countryRoute = new RoutePath(
  path: ":countryCode{3}",
);
```
Supporting more regex syntax would be good too so you could limit to alpha or numeric characters etc. Not sure how it would look, `path: ":year[0-9]{4}",` ?

Would be good if you could do something like (sorry my regex is probably wrong) but allow for optional matching on a language parameter:
` path: "((:language[a-z]{2}\/)*):countryCode[A-Z]{3}",`

**Comment by leonsenft** [comment]
Thanks for filing, this is indeed planned!

**Comment by leonsenft** [comment]
FYI regular expressions in route path's _are_ supported, just not for parameters like you've requested.

**Comment by jimmyff** [comment]
Ohh that's great @leonsenft - where can I find documentation about how to use this?

**Comment by leonsenft** [comment]
The path of each route definition is interpreted as a regex. There's no configuration needed. The only issue is that `toUrl()` doesn't work nicely if you do put regex symbols in the path.

**Comment by matanlurey** [comment]
We don't plan this enhancement.

**Comment by jimmyff** [comment]
👎  @matanlurey If you want a nice URL schema then I think this is missing functionality. I've been checking this ticket weekly hoping for an update. I have a load of hacks in my AngularDart projects to work around this and allow me to route to different components using similar paths.

**Comment by matanlurey** [comment]
I understand. We don't plan this enhancement ourselves. 

The router sub-package is quite small and could easily be forked and other features or enhancements added, but I think it would be a disservice to keep this ticket open indefinitely if we don't plan on doing the work.

**Comment by jimmyff** [comment]
fair enough. I'll look in to creating a solution at this end then.
