### ISSUE TITLE
Switch all docs and uses of build_runner to webdev

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1274]
This is a tracking issue for our own repository and internal documentation, for now.

We've decided for v5 final we will no longer document how to use `pub run build_runner`, and instead document (and rely on) users using [`webdev`](https://pub.dartlang.org/packages/webdev), which is a thin wrapper that includes validation and other utilities.

(It is still required to have `dev_dependencies` on these packages, however)

**Comment by matanlurey** [comment]
FYI @chalin this is _on hold_ as of right now.

I have some follow-up questions about usage/commitments/docs before I do this.

**Comment by chalin** [comment]
Got it (I had some questions too).

**Comment by chalin** [comment]
@kevmoo, @kwalrath, @matanlurey - is this off hold yet?

**Comment by kevmoo** [comment]
Off hold!

We should discuss with @kwalrath how to discuss how to message it.

We we have a webdev page, etc etc

**Comment by chalin** [comment]
@matanlurey - this is done on the site-webdev site, e.g., see https://webdev-dartlang-org-dev.firebaseapp.com/tools/webdev. /cc @kwalrath

**Comment by matanlurey** [comment]
I think we can consider this closed.
