### ISSUE TITLE
Add a PostProcessBuilder which removes placeholder files and .css and .html

### ISSUE THREAD

**Issue by natebosch** [dart-lang/angular#1282]
My initial thought is we should:

- Remove all `*.ng_placeholder` files, always
- In release (deployed) mode by default, remove `*.css` and `*.html` files from the `lib/` directory
- Allow configuring a list of globs to keep `*.css` or `*.html` files that are needed at deploy time (but are unused by AngularDart). For example, if you rely on `lib/global.css` instead of `web/global.css`.

**Comment by matanlurey** [comment]
To clarify, this is for release builds (where we would be deploying the artifacts).

I'd love the input of some of the heavier AngularDart users externally, because from my perspective this totally makes sense, but maybe we are missing something or some defaults that would help most users.

**Comment by jakemac53** [comment]
Note that you could use a heuristic to only delete the files that seem obviously safe to remove.

- For `.html` files you could check if they look like an angular template, or at least don't look like an entrypoint (don't have a `<html>`, `<head>`, `<body>`, or `<script>`) for instance.
- For `.css`  files you could check for a corresponding `.css.shim.dart` file, and/or do as suggested above and only remove files under `lib`.

**Comment by natebosch** [comment]
> you could check for a corresponding 

Not with the current `PostProcessBuildStep` interface. We only give access to the primary input.

**Comment by corporateselect** [comment]
we already have a quite big angular project now and we rely on some css in lib that is unused by ang - but instead of configuring a list for that globs isnt a more convention over configuration approach better? like a directory, prefix, ... ? Or could there be disadvantages im missing

**Comment by matanlurey** [comment]
One more question. For _release_ builds, is there _any_ reason to retain the `lib/` folder of any package at all? Or am I missing something?

**Comment by corporateselect** [comment]
>Does that sound OK?

sure, that sounds perfect. was thinking bit selfish :)

>One more question. For release builds, is there any reason to retain the lib/ folder of any package at all? Or am I missing something?

Was thinking about that too, like i said we have html/css in lib that we want to retain right now - but, were thinking about to separate it to web/ because it seems a cleaner approach

**Comment by natebosch** [comment]
> is there _any_ reason to retain the `lib/` folder of any package at all?

Some packages vend `.css`, `.json` or other data with your package that needs to be fetched at runtime from a `packages/` path. For example if you wanted to use the quantum theme for charted you'd [load the css file](https://github.com/google/charted/blob/6e2fc88d95373eb2e5b16a5f82108ad96e6be8a9/examples/selection/transitions_demo.html#L7). It's not compiled like angular styles.

> like i said we have html/css in lib that we want to retain right now - but, were thinking about to separate it to web/ because it seems a cleaner approach

For html or css in the root package we highly recommend this. It's only the cases where you want to allow other packages to use it from a published package that it should go in `lib/`

**Comment by jakemac53** [comment]
> One more question. For release builds, is there any reason to retain the lib/ folder of any package at all? Or am I missing something?

If you do a release build with dartdevc, (or fetch any external js from another package like `packages/test/dart.js`), then you need to have those available. Also assets like icons etc are often shared this way I think (even if a static server or something would probably be better).

**Comment by jakemac53** [comment]
> I'd also like to see a few tests - @jakemac53 is this testable with build_test or what is the best way to do that?

I don't think we have anything specific in build_test at this time, but we are adding several of these so it would make sense to have a common utility I think. I think we actually need a more general utility for testing PostProcessBuilders really which can validate deletes and adds.

**Comment by jakemac53** [comment]
Also note that we are adding a general builder you can use, so all you have to do is create the builderFactory function and configure it with your build extensions (and add it to your build.yaml).

**Comment by matanlurey** [comment]
@natebosch @jakemac53 Let me know when we should start (or pair) on this.

**Comment by natebosch** [comment]
I've got a change prepped for this but holding off on sending it for review until we get https://github.com/dart-lang/build/issues/1402 resolved.

**Comment by natebosch** [comment]
> my initial thought is "Oh. great more configuration!".

Our hope is that the vast majority of users will not need additional configuration. This is saving extra work that many users were already doing outside of the build system to clean things up before deploying.

> It sounds like by default without any globs being defined, all of my .css and .html files will be removed when I generate a release build?

All of your `.css` and `.html` _in your lib directory_ will be removed for a release build. At this step we don't know whether it was referenced by a component or not which is why it's only done in the lib directory.
If you have `.css` or `.html` that gets loaded directly by the browser rather than being used for the build we highly recommend you put it in the web directory instead of lib. If you must keep it in lib that's when you need extra configuration.

Keep in mind that if you want to opt-out entirely you can skip the globs.

```yaml
targets:
  $default:
    builders:
      angular|component_source_cleanup:
        options:
          enabled: false
```

> It sounds like you are suggesting removing the majority of my codebase anytime I create a release build. That sounds absurd to me.

> If the above is true, what's the benefit for removing the dart files and other resources under project_root/lib?

We believe there is usually little reason to retain lib directories, for either your project root or dependencies, _after_ compiling to javascript (specifically with dart2js, with ddc you need some .js files from the lib directory too) because all of the code is now represented by `web/main.dart.js`. If you're using source maps the `.dart` files and other stuff in lib is meaningful - but we expect _most_ users won't want to expose source maps in production, which is why we only remove it on release builds.

For deployment most users only want to use the files that are loaded by the browser in the client, which typically is not most stuff under lib.

**Comment by natebosch** [comment]
Oh, I just realized there might also be some confusion on what this does.

We definitely won't delete your code base in your source directory - this is in reference to what gets _copied_ to the `--output` directory during a build.
