### ISSUE TITLE
why angular dart is too slow in development?

### ISSUE THREAD

**Issue by loveship00** [dart-lang/angular#1302]
tooooo slow, every time i change a page code , i have to wait at least 10 seconds.

**Comment by zoechi** [comment]
Please provide more details. Dart version, Angular version, project structure, how do you build/serve, build configuration, ...

I have ~1 sec in a medium-sized Angular 5 project for reloads (initial load takes longer)

**Comment by matanlurey** [comment]
Unfortunately, as @zoechi mentioned, this isn't an actionable issue.

I would say the median reload time for most small to medium projects is somewhere between a second to seconds. 10 seconds might be totally reasonable for giant monolithic projects. There is a [performance measuring guide](https://github.com/dart-lang/build/blob/master/docs/measuring_performance.md) over at `build_runner`.

If you follow the steps there and can give us a trace we'd be happy to investigate further.

**Comment by loveship00** [comment]
```
name: untitled5
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: hey jude <email@example.com>

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.8.0
  english_words: "^3.1.0"

dev_dependencies:
  angular_test: ^1.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

transformers:
- angular:
    entry_points:
      - web/main.dart
      - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc

```

hi , this is my pub configuration, and i just generate app template by webstorm, thank you very much.

**Comment by hentoesch** [comment]
you are using angular4/dart1 which does not work well with dartdevc. 
to get better build times with dart devc you should switch to angular5/dart2

as a starting point to do so you could use one of the examples in:
https://github.com/dart-lang/angular/tree/master/examples

the dart plugin for webstorm will be adapted to these new versions and build system the coming days.

**Comment by loveship00** [comment]
thx alot

**Comment by Cododoc** [comment]
@matanlurey what can you say about this build process?
![image](https://user-images.githubusercontent.com/861256/39693708-463791ca-51e5-11e8-808e-1a108514077c.png)

**Comment by matanlurey** [comment]
I'm closing this since @loveship00 has already been helped.

@Cododoc Please open a new bug with your particular issues (and details, like OS, SDK version, resources on the machine, etc). Thanks!

**Comment by SYip** [comment]
Is the command to track the performance like this?
`pub run build runner_serve -o /tmp/my_project --live-reload --no-release --track-performance`

I tried this and the I can't find the /$pref page.

Changing single line of code takes 10~20 sec and I am just starting the project.

**Comment by lukepighetti** [comment]
I'm seeing 24s with this as my only code. Machine is a iMac 27" retina with 3.5 GHz i5 and 8gb of ram.

```
import 'package:angular/angular.dart';
import 'package:angular_forms/angular_forms.dart';
import 'hero.dart';

@Component(
  selector: 'my-app',
  template: '''
    <h1> {{ title }} </h1>
    <h3> {{ hero.name }} </h3>
    <div>
      <label>id: </label> {{ hero.id }} 
    </div>
    <div>
      <label>name: </label> 
      <input [(ngModel)]="hero.name" placeholder="name">
    </div>
  ''',
  styles: [
    '''
    h1 {
      color: maroon;
    }

    h3 {
      color: cornflowerblue;
    }
  '''
  ],
  directives: [formDirectives],
)
class AppComponent {
  final title = 'Tour of Heroes';
  final hero = Hero(1, 'Windstorm');
}

```

**Comment by Timmmm** [comment]
I am also curious why a "hello world" AngularDart app takes so long to build. `webdev build` or `webdev serve` always seems to spend over 10 seconds "Creating build script". What on earth is it doing that can take so long?

There's even stuff like this:

    [INFO] Cleaning up outputs from previous builds. completed, took 1.1s

How can it take an entire second to delete a few files?! Something is seriously wrong here. It's a shame because it's in complete contrast to the rest of the Dart experience which is nice and fast.

**Comment by natebosch** [comment]
> always seems to spend over 10 seconds "Creating build script". What on earth is it doing that can take so long?

Most of this is parsing the Dart source of the build script and all transitive builders. Since packages can provide source code used for building, we can't ship a precompiled binary to do the building. This is similar to the startup delay that you encounter when you try to run any script from source with the `dart` command and there are many transitive Dart source files imported.

> How can it take an entire second to delete a few files?! 

We delete the entire `.dart_tool/build/generated` directory which may have _many_ files in it. It's possible that on windows this may be slower than other oses.

**Comment by rudolfolah** [comment]
Specifically for dart with webdev/build_runner, this is just a slow process for *development* and doesn't impact launching a dart web app after it's been built for production?
