### ISSUE TITLE
HNPWA broken in latest SDK due to casting issue in pkg:service_worker

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#1305]
See https://github.com/isoos/service_worker/issues/17

![screen shot 2018-05-07 at 12 30 08 pm](https://user-images.githubusercontent.com/17034/39720840-6a921b6e-51f2-11e8-9421-0ea5dc966fb4.png)

Seems only to be in DDC (for now)

**Comment by leonsenft** [comment]
+1 just hit this.

**Comment by matanlurey** [comment]
I _think_ `service_worker` is fixed @HEAD. Want to verify @leonsenft?

**Comment by leonsenft** [comment]
This is fixed at head.
