### ISSUE TITLE
Template reference variable not recognized when *ngIf is on the tag as well

### ISSUE THREAD

**Issue by grundid** [dart-lang/angular#1307]
In the following example the drawer variable is not recognized when I have the *ngIf directive on the material-drawer tag. When I click on the icon I can see a NoSuchMethodError. Without the *ngIf directive this is working.

```html
<material-drawer persistent #drawer="drawer" *ngIf="userService.isLoggedIn()" >
    <material-list>
    </material-list>
</material-drawer>
<material-content>
    <header class="material-header">
        <div class="material-header-row">
            <material-button icon
                             class="material-drawer-button" (trigger)="drawer.toggle()">
                <material-icon icon="menu"></material-icon>
            </material-button>
        </div>
    </header>
    <div>
    </div>
</material-content>

```

* [Dart VM version: 2.0.0-dev.53.0 (Thu May 3 12:35:47 2018 +0200) on "macos_x64"
] Dart SDK Version (`dart --version`)
* [5.0.0.alpha+11] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
* [chrome ] Whether you are using Chrome, Safari, Firefox, Edge (if appplicable)

**Comment by matanlurey** [comment]
So, this is WAI, but I'll explain. `*ngIf` is a form of _sugar_ of typing the following:

```html
<template [ngIf]="userService.isLoggedIn()">
  <material-drawer #drawer>...</material-drawer>
</template>
<material-content>...</material-content>
```

As you can see from the (partially) de-sugared form, the `#drawer` reference is out of scope in the `<material-content>` section. I'm not sure of the best way to use this pattern though.

/cc @nshahan @TedSander any ideas?

**Comment by MichaelRFairhurst** [comment]
I haven't tested this, but I would maybe suggest using `@ViewChild`:

```
class MyComponent {
  @ViewChild(MaterialDrawerComponent)
  MaterialDrawerComponent drawer;
}
```

```
<material-drawer *ngIf="userService.isLoggedIn()"></material-drawer>
...
            <material-button icon
                             class="material-drawer-button" (trigger)="drawer?.toggle()">
...
</material-content>
```

Note that I added a `?.toggle()` to handle the case where the drawer isn't shown.

You can also do:

```
@ViewChild('foo')
MaterialDrawerComponent bar;
```

```
<material-drawer *ngIf="..." #foo="drawer"></material-drawer>
...
            <material-button icon
                             class="material-drawer-button" (trigger)="bar?.toggle()">
...

I used the extreme names `foo` and `bar` to demonstrate where each variable is used. I'm not sure if they could both be named `drawer`, but that *may* work. Or you may want to think of clever names to make it clear....so most likely, better to use the former approach than the latter.
