### ISSUE TITLE
Release angular-5 beta

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/angular#1315]
This is a tracking bug for actually releasing angular-5 beta.

We will release a beta once the Dart SDK supports `--preview-dart-2` in all contexts (DDC, Dart2JS, VM, pub, build_runner, etc.), and we have verified internally that there are no issues.

Known blocking issues:
* [x] https://github.com/dart-lang/sdk/issues/32188
* [x] https://github.com/dart-lang/webdev/issues/54
* [x] https://github.com/dart-lang/angular/issues/1353
* [x] https://github.com/dart-lang/angular/issues/1360
* [x] https://github.com/dart-lang/sdk/issues/33296

**Comment by alorenzen** [comment]
Note, this is blocked on https://github.com/dart-lang/sdk/issues/32188 and https://github.com/dart-lang/webdev/issues/54 right now.

**Comment by matanlurey** [comment]
Removed PRIORITY flag since there is nothing for us to do but wait for other blocking issues.

**Comment by handicraftsman** [comment]
https://github.com/dart-lang/sdk/issues/32188#issuecomment-390324601

**Comment by handicraftsman** [comment]
https://github.com/dart-lang/webdev/issues/54#issuecomment-393334658
Closed too.

**Comment by handicraftsman** [comment]
https://github.com/dart-lang/angular/issues/1360 is redirected to https://github.com/dart-lang/sdk/issues/33304
https://github.com/dart-lang/sdk/issues/33296 is closed.

**Comment by matanlurey** [comment]
I think we are more or less ready to release beta at the next -dev. SDK.

At least there are no more blocking issues. It's more of a question for @kevmoo now.

**Comment by kevmoo** [comment]
Woo hoo!

**Comment by matanlurey** [comment]
We did release.
