### ISSUE TITLE
Add an option to the angular builder to not emit `initReflector`

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/angular#1316]
If you are using the `runApp` bootstrapping, then this code shouldn't be necessary.

Note that in my experiments this has no effect on dart2js size, but it does have a significant effect on the amount of code that dartdevc will ship to the browser.

As an example, for the `angular_components` package this reduces the cost of importing `package:angular_components/angular_components.dart` significantly, by only shipping the modules for the components you _actually use_, even if you use the general import.

As an example, the actual difference when only using `MaterialButton`:

- with `initReflector`:
  - browser stats: 553 requests, 13.9MB, Finish: 2.62s
  - build stats:  44.6s with  3899 outputs (8285 actions)
- without `initReflector`:
  - browser stats: 48 requests, 6.6MB, Finish: 448ms
  - build stats:  28.9s with 1838 outputs (5030 actions)

All I did to reproduce the above was actually remove this line https://github.com/dart-lang/angular/blob/master/angular_compiler/lib/src/emitter/reflector.dart#L200. So that's not even completely eliminating the entire initReflector method.

**Comment by matanlurey** [comment]
Yes, but then I'm not sure of the value (I don't really want to add features that only work in 1 place)

**Comment by alorenzen** [comment]
Allows us to start collecting metrics as a carrot for internal teams?

**Comment by jakemac53** [comment]
I was actually envisioning a global blaze flag to toggle this (we already have that ability). That way if your app uses `runApp` you can just use this flag. However, I don't know how much benefit you would get internally because the modules are not structured the same way, there is already no general angular components import at all.

**Comment by matanlurey** [comment]
Ah I see. That sounds reasonable.

**Comment by matanlurey** [comment]
The plan right now, if it is OK with you, is actually to have _2_ flags. If you specify

```bash
--no-emit-component-factories --no-emit-injectable-factories
```

... we will emit a no-op `void initReflector() {}` (with no transitive imports). Will that do?

I could add a `--no-init-reflector` that turns both of these off, but not sure if worth it, especially if we want to make the default externally "--no" sooner rather than later.

**Comment by jakemac53** [comment]
> The plan right now, if it is OK with you, is actually to have 2 flags. If you specify
> `--no-emit-component-factories --no-emit-injectable-factories`

Yep should be fine, we need to make sure its supported via the `BuilderOptions` config which will look a little different than the blaze args but will actually go through the same codepath I believe?

> ... we will emit a no-op void initReflector() {} (with no transitive imports). Will that do?

Yes, this is effectively what I did when validating this approach. You can get a lot of value by just not referencing all the `initReflector` methods from all direct imports/exports.

> I could add a --no-init-reflector that turns both of these off, but not sure if worth it, especially if we want to make the default externally "--no" sooner rather than later.

I don't have a strong opinion here.

**Comment by matanlurey** [comment]
> Yep should be fine, we need to make sure its supported via the `BuilderOptions` config.

I believe it should "for free". Only Bazel requires a bit of additional hookup.

**Comment by matanlurey** [comment]
Ok this is now done (at MASTER), but not yet documented:

```yaml
builders:
  angular:
    options:
      emit-component-factories: false
      emit-injectable-factories: false
```

... I'll sanity check.

**Comment by matanlurey** [comment]
OK. Landed at MASTER for real now. Here is an example output when specified:

```dart
// **************************************************************************
// Generator: Instance of 'Compiler'
// **************************************************************************

// ignore_for_file: cancel_subscriptions,constant_identifier_names,duplicate_import,non_constant_identifier_names,library_prefixes,UNUSED_IMPORT,UNUSED_SHOWN_NAME
import 'main.dart';
export 'main.dart';
import 'dart:async';
import 'dart:html';
import 'package:angular/angular.dart';
import 'package:angular_router/angular_router.dart';
import 'package:pwa/client.dart' as pwa;
import 'package:examples.hacker_news_pwa/app_component.template.dart' as app;
import 'package:examples.hacker_news_pwa/hacker_news_service.dart';
import 'main.template.dart' as ng;

import 'package:angular/src/di/injector/injector.dart' as _i1;
import 'package:angular/src/di/injector/hierarchical.dart' as _i2;
import 'package:angular_router/src/location/path_location_strategy.dart' as _i3;
import 'package:angular_router/src/location/browser_platform_location.dart' as _i4;
import 'package:angular_router/src/location/location.dart' as _i5;
import 'package:angular_router/src/router/router_impl.dart' as _i6;
import 'main.dart' as _i7;
import 'package:angular_router/src/location/platform_location.dart' as _i8;
import 'package:angular/src/core/di/opaque_token.dart' as _i9;
import 'package:angular_router/src/location/location_strategy.dart' as _i10;
import 'package:angular_router/src/router_hook.dart' as _i11;
import 'package:examples.hacker_news_pwa/hacker_news_service.dart' as _i12;
import 'package:angular_router/src/router/router.dart' as _i13;

_i1.Injector hackerNewsApp$Injector([_i1.Injector parent]) => new _Injector$hackerNewsApp._(parent);

class _Injector$hackerNewsApp extends _i2.HierarchicalInjector {
  _Injector$hackerNewsApp._([_i1.Injector parent]) : super(parent);

  dynamic _field0;

  _i3.PathLocationStrategy _field1;

  _i4.BrowserPlatformLocation _field2;

  _i5.Location _field3;

  _i6.RouterImpl _field4;

  dynamic _getdynamic$0() => _field0 ??= _i7.getNewsService();
  _i3.PathLocationStrategy _getPathLocationStrategy$1() => _field1 ??= new _i3.PathLocationStrategy(inject(_i8.PlatformLocation), injectOptional(const _i9.OpaqueToken<String>('appBaseHref'), null));
  _i4.BrowserPlatformLocation _getBrowserPlatformLocation$2() => _field2 ??= new _i4.BrowserPlatformLocation();
  _i5.Location _getLocation$3() => _field3 ??= new _i5.Location(inject(_i10.LocationStrategy));
  _i6.RouterImpl _getRouterImpl$4() => _field4 ??= new _i6.RouterImpl(inject(_i5.Location), injectOptional(_i11.RouterHook, null));
  _i1.Injector _getInjector$5() => this;
  @override
  Object injectFromSelfOptional(Object token, [Object orElse = _i1.throwIfNotFound]) {
    if (identical(token, _i12.HackerNewsService)) {
      return _getdynamic$0();
    }
    if (identical(token, _i10.LocationStrategy)) {
      return _getPathLocationStrategy$1();
    }
    if (identical(token, _i8.PlatformLocation)) {
      return _getBrowserPlatformLocation$2();
    }
    if (identical(token, _i5.Location)) {
      return _getLocation$3();
    }
    if (identical(token, _i13.Router)) {
      return _getRouterImpl$4();
    }
    if (identical(token, _i1.Injector)) {
      return _getInjector$5();
    }
    return orElse;
  }
}

// No initReflector() linking required.
void initReflector() {}
```

NOTE:

* `initReflector()` is a no-op.
* There is no imports to other libraries to `initReflector()` them.

Marking as closed! @jakemac53

**Comment by jakemac53** [comment]
awesome, thanks @matanlurey !
