### ISSUE TITLE
Publish pkg:angular with properly constrained dependencies

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#1325]
Just hit an issue with Stagehand due to `pub upgrade` getting a version of `angular_compiler` not compatible with `angular_components`.

This issue tracks **publishing** the package, not just the commit with the fix.

**Comment by matanlurey** [comment]
I can publish a `+13` today. Will that help?

**Comment by kevmoo** [comment]
Yup!

**Comment by matanlurey** [comment]
I won't get to this this week. Should be trivial for anyone who wants to take a shot.

**Comment by kevmoo** [comment]
Ack

**Comment by kevmoo** [comment]
@matanlurey – how quickly do you plan to publish?

**Comment by matanlurey** [comment]
Our build is red, so, when it is green, I guess.

**Comment by kevmoo** [comment]
Going to leave this open until the package is published – just for tracking

**Comment by matanlurey** [comment]
Fixed and published.
