### ISSUE TITLE
CookieXSRFStrategy support

### ISSUE THREAD

**Issue by jhonToni** [dart-lang/angular#1331]
* [ 2.0.0-dev.53.0 ] Dart SDK Version (`dart --version`)
* [5.0.0-alpha+11 ] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
* [Windows ] Whether you are using Windows, MacOSX, or Linux (if applicable)
* [ Chrome] Whether you are using Chrome, Safari, Firefox, Edge (if appplicable)
* [ ] Any other packages or constraints we should know about

There is a CookieXSRFStrategy support in Angular dart ?
If CookieXSRFStrategy support not exist, which library can I use ?

**Comment by matanlurey** [comment]
Sorry it's not clear what you are asking. AngularDart does not handle anything specific with HTTP, including Cookies or XSRF. You will want to look at `dart:html` or `package:http` for those bits. Thanks!
