### ISSUE TITLE
Support for animations between routes

### ISSUE THREAD

**Issue by saibotma** [dart-lang/angular#1336]
It would be really nice to have out of the box support for animations between routes. That would be really useful to create e.g. a circular reveal effect or sliding effects between two routes. It´s actually possible in AngularJS but i have not found any documentation about this feature for AngularDart hence my feature request.
I think about something like [this](https://stackoverflow.com/questions/37909208/angular-2-slide-in-animation-of-a-routed-component).

**Comment by matanlurey** [comment]
Thanks for filing. I don't see us prioritizing animations at this time, unfortunately.

For routing specifically, it's probably not too much work to create your own wrapper component/directive that does the animation effects you'd like.

**Comment by zoechi** [comment]
@matanlurey and hints about what approach you'd take?

My idea was to use a custom RouterOutlet that only removes the previous component from the DOM after the animation was completed.
Are there better ideas?
