### ISSUE TITLE
Change "pub run build_runner serve" to "webdev serve" in hacker_news_pwa README.md 

### ISSUE THREAD

**Issue by bcko** [dart-lang/angular#1341]
Changing `pub run build_runner serve` to `webdev serve` in https://github.com/dart-lang/angular/blob/master/examples/hacker_news_pwa/README.md, 

According to https://webdev-dartlang-org-dev.firebaseapp.com/tools/webdev, 
> The webdev tool is built on build_runner and replaces pub build and pub serve. If you’ve previously used build_runner, you should no longer need to use it directly

submitted a pull request #1342

Thank you.

**Comment by alorenzen** [comment]
Was fixed in #1342
