### ISSUE TITLE
Unhandled exception in the AngularDart compiler

### ISSUE THREAD

**Issue by saibotma** [dart-lang/angular#1343]
```
NoSuchMethodError: Class 'CompilerFlags' has no instance getter 'useNewPreserveWhitespace'.
Receiver: Instance of 'CompilerFlags'
Tried calling: useNewPreserveWhitespace
```

Dart SDK Version: 2.0.0-dev.58.0 (Wed May 23 20:44:51 2018 +0200) on "windows_x64"
AngularDart Version: 5.0.0-alpha (latest)
Running `webdev serve` on Windows

**Comment by eredo** [comment]
I think there was an issue with the dependency constraints in +12. Make sure to upgrade on +13 and check the applied angular_compiler dependency, it needs to be the latest.

**Comment by matanlurey** [comment]
Yup, what @eredo said. We will have the constraint fixed in the latest version.
