### ISSUE TITLE
Implement showing an alternative template using else in *ngIf

### ISSUE THREAD

**Issue by Lisenish** [dart-lang/angular#1346]
Would be nice if we had such feature as in AngularTS. Small syntax sugar makes templates more concise.

I think you're aware of this feature, but just in case, here documentation from TS version:
https://angular.io/api/common/NgIf#showing-an-alternative-template-using-else

**Comment by matanlurey** [comment]
I think it is unlikely we will do this, unfortunately.

The compiler has special logic for `*ngIf` that currently will not specialize to an `else` block.
