### ISSUE TITLE
This argument *may* have not been resolved

### ISSUE THREAD

**Issue by xavierhainaux** [dart-lang/angular#1349]
Dart VM version: 2.0.0-dev.58.0 (Wed May 23 20:44:51 2018 +0200) on "windows_x64"
angular: 5.0.0-alpha+12
build_runner: 0.8.9
build: 0.12.6

I see this kind of error hundreds of times:
```
[SEVERE] angular on lib/extranet/extranet.dart:
Compiling @Component-annotated class "ExtranetComponent" failed.

Try the following when diagnosing the problem:
  * Check your IDE or with the dartanalyzer for errors or warnings
  * Check your "import" statements for missing or incorrect URLs

If you are still stuck, file an issue and include this error message:
https://github.com/dart-lang/angular/issues/new

line 1, column 1346 of asset:client/lib/extranet/extranet.dart: This argument *may* have not been resolved
coreDirectives
^^^^^^^^^^^^^^
line 1, column 1369 of asset:client/lib/extranet/extranet.dart: This argument *may* have not been resolved
routerDirectives
^^^^^^^^^^^^^^^^
line 1, column 1394 of asset:client/lib/extranet/extranet.dart: This argument *may* have not been resolved
ErrorPopupComponent
^^^^^^^^^^^^^^^^^^^
line 1, column 1422 of asset:client/lib/extranet/extranet.dart: This argument *may* have not been resolved
MessageManagerComponent
^^^^^^^^^^^^^^^^^^^^^^^
```

My "Dart Analysis" tab has no error (except `uri_has_not_been_generated` that is ignored with analysis_options.yaml).
Each time I have this error, I have to do a bit of magic: restart `pub run build_runner serve`, add a white space in a source file and wait for the (long) rebuild.

Any idea how to debug this?

**Comment by matanlurey** [comment]
Ping @xavierhainaux

**Comment by xavierhainaux** [comment]
I'll try to extract a small reproduction case out of my app but it will take a few days.
There is definitely a bug hidden there. I'm able to fix the problem without changing a single line of code in my app: just restarting the build_runner or sometime I need to delete entirely the .dart_tool folder.

**Comment by matanlurey** [comment]
Please feel free to re-open when you have a reproduction case.

**Comment by dougreese** [comment]
I know this is closed, but I ran into a similar problem and found this issue in a search.  In my case, I had neglected to include `angular_components.dart`.  Adding
```
import 'package:angular_components/angular_components.dart'; 
```
solved the issue for me.  Maybe this will help someone in the future.
