### ISSUE TITLE
Use Dart2 VM for travis test

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/angular#1353]
We should be able to set `DART_VM_OPTIONS=--preview-dart-2 pub run build_runner ...` to run all of our tests with the new semantics.

**Comment by matanlurey** [comment]
I'm nervous about running with this on travis only:

* We aren't likely to see this developing locally, externally, only on travis
* From results from @natebosch and @jakemac53 this makes test significantly slower
* We don't run with this logic internally, meaning any CL/dep change can break us

... ultimately it feels like this just creates more work for whoever does the sync process (i.e. me, right now), without creating a lot of security. I'd rather more time/effort is put into switching our test cases internally to use `--preview-dart-2` _before_ our external build process.

**Comment by alorenzen** [comment]
We already had one regression here, so having *any* test coverage is better than none, even if it is only externally.

Also, @keertip thinks we can turn this on internally soon. I'm in favor of turning it on externally only for 1 week or less. But if we think it will be longer than that to enable internally, then I'd agree with you here.

**Comment by matanlurey** [comment]
We were told "1 week" weeks ago :). I don't think 1 week of travis coverage is significant anyway.

**Comment by matanlurey** [comment]
I think we can mark this closed given that it is now the only option.
