### ISSUE TITLE
Using allowInterop() fails in Dart2JS with --preview-dart-2

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#1359]
Error running an app w/ --preview-dart-2 in dart2js

BrowserGetTestability.addToWindow$1

This is w/ angular @ 53907981.

Error is here: https://github.com/dart-lang/angular/blob/539079816e89ed1e2d9079632850b12e2bc69396/angular/lib/src/platform/browser/testability.dart#L31-L51

![screen shot 2018-05-31 at 8 13 56 am](https://user-images.githubusercontent.com/17034/40790761-9c204686-64aa-11e8-8a3e-2053ab28a8c0.png)

Related to https://github.com/dart-lang/sdk/issues/33134 ?

**Comment by kevmoo** [comment]
angular/lib/src/paltform/browser/testabliity.dart

Around line 51

```dart
      js_util.setProperty(_self, 'getAllAngularTestabilities',
          allowInterop(getAllAngularTestabilities));
```

**Comment by kevmoo** [comment]
@sigmundch @rakudrama @efortuna FYI

**Comment by kevmoo** [comment]
With Dart 2.0.0-dev.59.0

**Comment by rakudrama** [comment]
```dart
F allowInterop<F extends Function>(F f) {
  if (JS('bool', 'typeof(#) == "function"', f)) {
    // Already supports interop, just use the existing function.
    return f;
  } else {
    return _convertDartFunctionFast(f);
  }
}
```

F is `List Function()`.
It is the returned type where the check fails (by line number).
F needs to be at the return type for type inference, so we can't widen it to `Function`.

We can make the return check go away, but the JavaScriptFunction could flow to another equivalent type check.

```dart
F allowInterop<F extends Function>(F f)
-->
Function allowInterop<F extends Function>(F f)
```

If we want to make the type check pass, we need to answer the question "What is the Dart type of a JavaScript function?". It is not clear what the answer should be. A 'safe' type for the check would be
```dart
Null Function([dynamic, dynamic, ... , dynamic])
```
for some large number of arguments, but that type mischaracterizes the return type.

Perhaps we need a special type rule for JavaScriptFunction - it 'is' any type with positional arguments.

**Comment by matanlurey** [comment]
Blocked by https://github.com/dart-lang/sdk/issues/33296.

**Comment by matanlurey** [comment]
https://github.com/dart-lang/sdk/issues/33296 was closed.
