### ISSUE TITLE
DDC needs to stop skipping type build/runtime checks

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1360]
As hit internally:

```dart
import 'package:angular/angular.dart';

const windowBindings = const [ ... ];

const tableBindings = const [
  windowBindings,
  const ClassProvider(OtherClass),
];

const tableModule = const Module(
  provide: tableBindings,
);
```

See the error? Well, `Module.provide` only takes a `List<Provider>`, but is being passed a `List<Object>` (or is it `List<dynamic>`?). This passes type-checking during build-time (and DDC runtime), but will fail in Dart2JS - and will fail otherwise in our actual framework code, because I assume every element is a `Provider`.

I think this is due to `List` currently being a white-listed "skip checks on me", thing. The CFE has no such concept, and `Dart2JS` with `--preview-dart-2`, will fail.

**Comment by matanlurey** [comment]
This is not related to DDC

**Comment by kevmoo** [comment]
> This is not related to DDC

Huh? Different title?

**Comment by matanlurey** [comment]
Closing. This is actually https://github.com/dart-lang/sdk/issues/33304.
