### ISSUE TITLE
Stability has no concept of deferred libraries

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1362]
_(Internal bug is [b/62414314](b/62414314))_

@hterkelsen wrote:

> It's possible for deferred components not to be ready by the time [`fixture.update()`](https://github.com/dart-lang/angular/blob/539079816e89ed1e2d9079632850b12e2bc69396/angular_test/lib/src/frontend/fixture.dart#L136-L144) completes. We should wait for [deferred loads](https://github.com/dart-lang/angular/blob/539079816e89ed1e2d9079632850b12e2bc69396/_goldens/test/_files/deferred/container_component.template_release.golden#L49) to complete.

While writing this bug, I noticed `Testability` (for e2e tests) suffers from a similar issue.

We have a few options, as usual, none of them a slam dunk:

1. Somehow integrate with a public API that both DartDevC/Dart2JS would emit for this purpose.
2. `angular_test` only: Add a `DeferredLibraryStabilizer`, JS-interop monkey patch "stuff".
3. `angular_test` only: In dev-mode, change `loadDeferred`:

```dart
// lib/src/runtime.dart
List<Future<void>> pendingDeferredLibraries = [];

// lib/src/.../app_view.dart
void loadDeferred(Future<void> Function() load1, Future<void> Function load2) {
  final waitFor = new Future.wait([load1, load2]).then((_) {
    _finishDeferLoad();
  });
  if (isDevMode) {
    pendingDeferredLibraries.add(waitFor);
  }
}
```

... and use `pendingDeferredLibraries` as a signal for stability by default in `angular_test`.

4. Add a generic `trackAsyncWork` function for stability:

```dart
F trackAsyncWork<F extends Future<void> Function()>(F func) {
  if (isDevMode) {
    return () async {
      knownAsyncWork++;
      try {
        return func();
      } finally {
        knownAsyncWork--;
      }
    };
  }
  return func;
}
```

... and use the counter of `knownAsyncWork` as a signal for stability. We could use `trackAsyncWork` by default for all calls to `loadDeferred`, and let users use it as well for their own events (loading from `IndexedDB`, XHRs, etc).

_To be honest, I haven't _heard_ folks request support for `Testability`, but I also know very little about it (or e2e testing, in general) - maybe there are other mechanisms like waiting for XHRs using web driver that are better suited for that purpose. In my head **3** makes the most sense, but doesn't generalize well (where **4** does)._

/cc @TedSander @liuming0 for additional input.

**Comment by TedSander** [comment]
Where did this come from? Was it from a client having a problem? or something else?

So I don't think this happens in practice today for a couple of reasons which we won't always be able to rely on:
a) For component tests DDC doesn't really defer code. So the timing isn't the same as Dart2js and might not come up there.
b) For web driver tests they typically wait for an element to be shown, or disappear before continuing on in the test. Some examples could include waiting for a progress spinner or bar to hide, or waiting for the specific element to show.

That said there is some testabilities for things such as activities which may end up catching some of these.

That said I think we shouldn't rely on this. It would be nice for angular to add this to the list of things it knows needs to be stable.

Without diving in too deep 4 sounds the best to me.

**Comment by matanlurey** [comment]
@TedSander:

> Where did this come from? Was it from a client having a problem? or something else?

Actually from @hterkelsen, who was trying to test `loadDeferred`.

> a) For component tests DDC doesn't really defer code.

That's true, but you still _do_ need to wait for the future to complete, I think?

/cc @jmesserly @vsmenon 

> b) For web driver tests they typically wait for an element to be shown

Ah, then I'm not too concerned.

**Comment by matanlurey** [comment]
Let's close this, for now. I don't see this being acted on, or else we should track general instability.
