### ISSUE TITLE
Avoid allocating `new Text` where possible

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1364]
@ferhatb wrote:

> When we have text element that doesn't change compile to [`appendText`][1] instead of [`new Text('...') `][2].

[1]: https://api.dartlang.org/stable/1.24.3/dart-html/Element/appendText.html
[2]: https://github.com/dart-lang/angular/blob/539079816e89ed1e2d9079632850b12e2bc69396/_goldens/test/_files/change_detection.template_release.golden#L36-L38

i.e. we'd want to see:

```dart
    _el_0.appendText('CheckOnce');
```

instead of:

```dart
    import2.Text _text_1 = new import2.Text('CheckOnce');
    _el_0.append(_text_1);
```

**Comment by leonsenft** [comment]
There's no reason to make this change, as [`appendText()`](https://api.dartlang.org/dev/2.0.0-dev.60.0/dart-html/Element/appendText.html) is simply a wrapper around the exact same allocation.

Both

```dart
import 'dart:html';

void main() {
  final div = new DivElement();
  final text = new Text('hello world');
  div.append(text);
}
```

and

```dart
import 'dart:html';

void main() {
  final div = new DivElement()..appendText('hello world');
}
```

emit identical JavaScript

```js
main: function() {
  var t1 = document;
  t1.createElement("div").appendChild(t1.createTextNode("hello world"));
}
```
