### ISSUE TITLE
Should we throw/fail to compile if token=FunctionType?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1365]
_(Internally this is [b/69866909](b/69866909))._

@hterkelsen writes:

> In Dart 2, it is very likely that typedefs used as constants will be canonicalized if they refer to the same function type. This is a change from the Dart 1 behavior and could cause issues with customers who use typedefs as the token in their providers. We should deprecate using typedefs as a provider token to prepare for the change.

First, should we clarify - did this happen?

```dart
class Provider<T> {
  const Provider<T>();
}

typedef Formatter = String Function();
typedef Stringifier = String Function();

const providerA = const Provider<Formatter>();
const providerB = const Provider<Stringifier>();
```

... if I inspect `providerA` and `providerB` in the AngularDart compiler, will they be "the same"?

... and what about at runtime?

```dart
void main() {
  print(identical(Formatter, Stringifier));
  print(Formatter == Stringifier);
}
```

... elsewhere @leafpetersen writes:

> Yes, I believe typedefs, parameterized class types, and function types are not required by the spec to be canonicalized.

I looked into uses internally, and there is enough to be annoying - but possible - to migrate. We should clarify what we want to accomplish, and how we should proceed (i.e. big-bang, with a flag, etc).

**Comment by natebosch** [comment]
My hope is that we won't start seeing a bunch of violations of https://www.dartlang.org/guides/language/effective-dart/design#avoid-defining-a-one-member-abstract-class-when-a-simple-function-will-do if we remove this support...

**Comment by hterkelsen** [comment]
It looks like typedefs aren't canonicalized in either the VM or dart2js (2.0.0-dev.53.0) with no plans that I know of to make them canonical. I think we can close this.

**Comment by matanlurey** [comment]
I think the big issue might be if the analyzer considers the FunctionType==
unfortunately

**Comment by matanlurey** [comment]
@hterkelsen:

https://github.com/dart-lang/sdk/blob/1bc9b8d00c7d3b5ea091ac9df2252e8aff3e3620/pkg/analyzer/lib/src/dart/element/type.dart#L758-L785

**Comment by hterkelsen** [comment]
Even if it considers the FunctionType defined by two different Typedefs (in the analyzer I think they're called FunctionTypeAliasElement) as equal, it should still consider the typedefs as equal only if they are literally the same declaration. So it shouldn't be a problem unless people are putting raw function types as the token.

**Comment by matanlurey** [comment]
Ah OK. Lets close this then!
