### ISSUE TITLE
Exception on angular_router:  Can't create an instance of malbounded type 'Future<void>'

### ISSUE THREAD

**Issue by supermuka** [dart-lang/angular#1401]
* [x] Dart SDK Version (`dart --version`)
2.0.0-dev.61.0
* [x] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
angular: 5.0.0-alpha+14
angular_router:  2.0.0-alpha+13
* [x] Whether you are using Windows, macOS, or Linux (if applicable)
Windows 7

* [x] Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
Chrome

* [x] Any other packages or constraints we should know about
No, I think!

The following error occurs after **SDK** upgrade from _2.0.0-dev.60.0_ to _2.0.0-dev.61.0_ and _last version_ of the **angular** and **angular_router** package:

> core_patch.dart:566 EXCEPTION: TypeError: Can't create an instance of malbounded type 'Future<void>': 'void' is not a subtype of bound 'Object' type variable 'Future.T' of type 'Future<Future.T>'.
> STACKTRACE: 
> TypeError: Can't create an instance of malbounded type 'Future<void>': 'void' is not a subtype of bound 'Object' type variable 'Future.T' of type 'Future<Future.T>'.
>     at Object.wrapException (http://localhost:8080/main.dart.js:3577:17)
>     at Object.throwTypeError (http://localhost:8080/main.dart.js:4535:15)
>     at Object.RouterImpl$ (http://localhost:8080/main.dart.js:52716:18)
>     at _Injector$rootInjector.injectFromSelfOptional$2 (http://localhost:8080/main.dart.js:99547:20)
>     at _Injector$rootInjector.injectOptional$2 (http://localhost:8080/main.dart.js:28105:23)
>     at _Injector$rootInjector.$get$2 (http://localhost:8080/main.dart.js:28128:23)
>     at _ViewAppComponentHost0.injectorGet$3 (http://localhost:8080/main.dart.js:27084:33)
>     at _ViewAppComponentHost0.injectorGet$2 (http://localhost:8080/main.dart.js:27093:21)
>     at _ViewAppComponentHost0.build$0 (http://localhost:8080/main.dart.js:57820:42)
>     at ComponentFactory.create$2 (http://localhost:8080/main.dart.js:27369:57) 

I think the problem is in _pub.dartlang.org\angular_router-2.0.0-alpha+13\lib_ on line 40 where is the following code:

`var _lastNavigation = new Future<void>.value();`

**Comment by leonsenft** [comment]
Thanks for filing! Looks like the latest Dart dev release changed void semantics a bit. If you're blocked you can try rolling back to 2.0.0-dev.60.0, it should work.

**Comment by supermuka** [comment]
When I go back to the previous version of the **angular_router** package from _'2.0.0-alpha+13'_ to _'2.0.0-alpha+12'_, it works!

I think the issue is under '2.0.0-alpha+13'. 

[Here is the Web App](https://github.com/supermuka/auge) that which is throwing the exception.

**Comment by leonsenft** [comment]
@supermuka That's because the line that appears to be broken was added in +13 to fix a bug :smile: 

Thanks for the app to reproduce, I'll investigate!

**Comment by leonsenft** [comment]
I rolled back to 2.0.0-dev.61.0 to reproduce, but your application doesn't build:

```
[INFO] Generating build script completed, took 352ms
[INFO] Building new asset graph completed, took 1.7s
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[SEVERE] build_web_compilers|entrypoint on web/main.dart:

Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:auge/web/src/group/groups_component.template.dart' as groups_component;` from auge|lib/web/src/app_layout/app_layout_component.dart at 37:1
`import 'package:auge/web/src/group/groups_component.template.dart' as groups_component;` from auge|lib/web/src/app_layout/app_layout_component.template.dart at 34:1
`import 'package:auge/web/src/group/group_service.dart';` from auge|lib/web/src/initiative/initiative_detail_component.dart at 24:1
`import 'package:auge/web/src/group/group_service.dart';` from auge|lib/web/src/initiative/initiative_detail_component.template.dart at 24:1
`import 'package:auge/web/src/group/group_service.dart';` from auge|lib/web/src/objective/objective_detail_component.dart at 20:1
`import 'package:auge/web/src/group/group_service.dart';` from auge|lib/web/src/objective/objective_detail_component.template.dart at 21:1

[INFO] Running build completed, took 32.9s
[INFO] Caching finalized dependency graph completed, took 306ms
[SEVERE] Failed after 33.2s
```

The `/lib/web/src/group` directory does not exist. Perhaps I caught your repo during a refactor, could you please provide a stable tag or branch for me to try?

**Comment by supermuka** [comment]
I push this package to repository now. This was the last package that I was working...

I tested and know the app build fine with the repository version.

**Comment by leonsenft** [comment]
@supermuka It appears as though the `--checked` flag you're passing to `dart2js` is the issue. I'm not sure if this behavior is a bug, so I've filed https://github.com/dart-lang/sdk/issues/33467.

I'm curious why you're using dart2js for development, have you tried DDC? You'll have a much better edit-refresh cycle using DDC, and at least in the meantime will avoid this error.

**Comment by matanlurey** [comment]
"Checked" mode in Dart2JS is unsupported and is being deleted shortly.

**Comment by leonsenft** [comment]
Alright it seems like there isn't an issue in Angular here; you can follow https://github.com/dart-lang/sdk/issues/33467 for any further discussion.
