### ISSUE TITLE
Changelog for 5.0.0-alpha+15 should mention new min SDK

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#1414]
From +14 to +15 the min SDK was changed from 2-dev.56 to 2.dev.60. This should probably be mentioned in the [changelog](https://github.com/dart-lang/angular/blob/master/angular/CHANGELOG.md).

https://github.com/dart-lang/angular/blob/0176f2f4420a289f31f0fbe9455342eb9ca54815/angular/pubspec.yaml#L7-L8

cc @kwalrath

**Comment by matanlurey** [comment]
We decided we aren't making this part of our changelog for -dev releases.
