### ISSUE TITLE
Cannot implement both the DoCheck and OnChanges lifecycle events

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#1420]
The [lifecycle-hooks example app](https://webdev-dartlang-org-dev.firebaseapp.com/angular/guide/lifecycle-hooks), used to build and [run](https://webdev-dartlang-org-dev.firebaseapp.com/examples/lifecycle-hooks/) w/o issues prior to Angular 5.0.0-alpha+15.

As of +15, we get the following SEVERE error when attempting to build (as shown towards the end of [this Travis log](https://travis-ci.org/dart-lang/site-webdev/jobs/392835656)):

```console
> webdev build
[INFO] Building new asset graph completed, took 758ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[SEVERE] angular on lib/src/peek_a_boo_parent_component.dart:
line 34, column 7 of asset:lifecycle_hooks/lib/src/peek_a_boo_component.dart: Cannot implement both the DoCheck and OnChanges lifecycle events. By implementing "DoCheck", default change detection of inputs is disabled, meaning that "ngOnChanges" will never be invoked with values. Consider "AfterChanges" instead.
class PeekABooComponent extends PeekABoo
      ^^^^^^^^^^^^^^^^^
...
```

Is this important breaking change mentioned in the changelog? If so, I haven't found it.

Btw, with Angular +14 or earlier, the `PeekABooComponent` had both of its `DoCheck` and `OnChanges` hooks called, as we can see of the `PeekABooComponent` log

```nocode
Peek-A-Boo
...
-- Lifecycle Hook Log --
#1 name is not known at construction
#2 OnChanges (1): name initialized to "Windstorm"
#3 OnInit
#4 DoCheck
#5 AfterContentInit
#6 AfterContentChecked (1)
#7 AfterViewInit
#8 AfterViewChecked (1)
#9 DoCheck
#10 AfterContentChecked (2)
#11 AfterViewChecked (2)
#12 OnChanges (2): name changed to "Windstorm!"
#13 DoCheck
#14 AfterContentChecked (3)
#15 AfterViewChecked (3)
#16 DoCheck
#17 AfterContentChecked (4)
#18 AfterViewChecked (4)
#19 OnChanges (3): name changed to "Windstorm!!"
#20 DoCheck
#21 AfterContentChecked (5)
#22 AfterViewChecked (5)
```

cc @kwalrath

**Comment by matanlurey** [comment]
It looks like the CHANGELOG was clobbered, but it originally was there. I'll re-add it.

(`DoCheck` + `OnChanges` is effectively the same thing as `DoCheck` + `AfterChanges`)

**Comment by matanlurey** [comment]
BTW, this is yet another reason the example apps should really live in the mono repo :(

/cc @alorenzen
