### ISSUE TITLE
Feature request: allow dots in `APP_ID`

### ISSUE THREAD

**Issue by cedx** [dart-lang/angular#1433]
Dart : 2.0.0-dev.64.1
Angular : 5.0.0-alpha+15
OS : Windows 10 and Ubuntu 18.04
Browser : Chrome 67 and Firefox 60

I'm using `APP_ID` as a mean to identify uniquely my apps. I use this value in third party libraries that require it (for example : send a "screen view" in Google Analytics requires to send an application identifier).

It's very common to use the reversed Internet domain name as prefix for an application identifier. For example : `io.belin.my_app`.

`APP_ID` is used internally to apply CSS scoping behavior. The issue is that if I use some characters like the dot (`.`), the application rendering breaks.

My request : either document the allowed/forbidden characters by `APP_ID`... or much better, replace the invalid characters during the rendering to avoid the issue (for example : `io.belin.my_app` could become `io--belin--my_app`).

**Comment by matanlurey** [comment]
I think it's unlikely we'll do this. We're trying to reduce the amount of implicit magic that happens.

You could always write a replace function yourself, though.

**Comment by cedx** [comment]
No problem, I was trying :smiley_cat: Thanks for the reply.

**Comment by matanlurey** [comment]
You're welcome. Thanks for understanding!
