### ISSUE TITLE
Update README to say beta, not alpha

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/angular#1445]
https://pub.dartlang.org/packages/angular/versions/5.0.0-beta says "the currently in development release is 5.0.0-alpha" (and mentions alpha at least one other place). It should be beta.

Fix it here: https://github.com/dart-lang/angular/tree/master/angular/README.md

**Comment by matanlurey** [comment]
Anything that is "fix the README" should really just a PR, not an issue

(It took more work to write this issue than just send a PR 👅)

**Comment by matanlurey** [comment]
Will fix upstream.

**Comment by kwalrath** [comment]
> Anything that is "fix the README" should really just a PR, not an issue
> 
> (It took more work to write this issue than just send a PR 👅)

Yeah, I considered that, but I was in a groove. :) Editing is like quicksand for me.
