### ISSUE TITLE
Optimize ViewChild (and probably ContentChild)

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#1455]
The code generated for `ViewChild` looks like:

```dart
  if (_query_foo_1_0_isDirty) {
    ctx.foo = (_appEl_0.mapNestedViews((_ViewAppComponent1 nestedView) {
      return [nestedView._el_2];
    }).isNotEmpty
        ? _appEl_0.mapNestedViews((_ViewAppComponent1 nestedView) {
            return [nestedView._el_2];
          }).first
        : null);
    _query_foo_1_0_isDirty = false;
  }
```

The first `mapNestedViews` isn't reused, but rather used to check if there is a matching query. This could be simplified and optimized by caching the query with a local variable:

```dart
  if (_query_foo_1_0_isDirty) {
    var foo = _appEl_0.mapNestedViews((_ViewAppComponent1 nestedView) {
      return [nestedView._el_2];
    });
    ctx.foo = foo.isNotEmpty ? foo.first : null;
    _query_foo_1_0_isDirty = false;
  }
```

@matanlurey is there perhaps some subtlety I'm missing here?

**Comment by matanlurey** [comment]
No subtlety, I think this is just a bug/missed optimization. A fix is very welcome:
https://github.com/dart-lang/angular/blob/0b7878f81b8441e290e436a0f651fbe1e667e522/angular/lib/src/compiler/view_compiler/compile_query.dart#L440-L455

**Comment by matanlurey** [comment]
Ok, this the former is a pretty easy optimization. I'll send a PR.

**Comment by matanlurey** [comment]
Added to the `=5.0.0` milestone since the PR is already out.
