### ISSUE TITLE
Force pure pipe to be refreshed

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/angular#1481]
Copied from the AngularJS repo: https://github.com/angular/angular/issues/15041

[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
Current behavior
Currently I have a stateful pipe that wraps a service and subscribes to an observable, and then stores the value and returns it every time the pipe's transform function is called. The issue is that I have to make the pipe impure and so it gets called on each change detection cycle.

Expected behavior
What I would like to be able to do is mark the pipe as dirty when I know the data has changed.

I have injected the change detector ref into the pipe, and have marked it for check and then detected changes, however none of the inputs have changed so the pipe doesn't get called again.

Because I know when the data has changed (as it is whenever the "next" function used to subscribe to the observable is called) I would like to be able to set the pipe as dirty to force it to be reevaluated when I call detect changes.

I have trawled the docs and source and can't find this behaviour currently, and if it is agreed that it would be worth implementing I would be happy to create a PR with some guidance.

What is the motivation / use case for changing the behavior?
To stop stateful pipes being polled especially when we know when the data has changed, in favour of a more push-based mechanism.

**Comment by matanlurey** [comment]
This wouldn't line up well with our ultimate goals for change detection - i.e., not trying to re-observe changes. It's possible we would spend effort on alternative ways to express computed properties (i.e. pipes) that would solve your issue, but nothing is known at this time.
