### ISSUE TITLE
@HostBinding('attr.draggable.if') doesn't work with a static const

### ISSUE THREAD

**Issue by TedSander** [dart-lang/angular#1484]
This works:
```
@HostBinding('attr.draggable.if')
final bool hostDraggable = true;
```

This doesn't:
```
@HostBinding('attr.draggable.if')
static const hostDraggable = true;
```

I get the following error: The argument type 'bool' can't be assigned to the parameter type 'String'.

Maybe one of the paths wasn't covered in the compiler?

**Comment by matanlurey** [comment]
Thanks! Working on this now

**Comment by matanlurey** [comment]
Closed at HEAD.
