### ISSUE TITLE
Allow access to static members without `MyComp.`

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1493]
Reproduction case:

```dart
@Component(
  selector: 'my-comp',
  template: r'''
    Hello {{getName()}}!
  ''',
)
class MyComp {
  // Silly, but real user-code is more complex.
  static final getName = () => 'Matan';
}
```

I expected this to work without using `MyComp.getName`. Instead we generate incorrect code that fails during DDC/Dart2JS compilation.

**Comment by matanlurey** [comment]
@leonsenft mentioned this might be a bug, rather than a missing feature.

**Comment by leonsenft** [comment]
This is particular to it being a closure. For example, both the following work.

```dart
@Component(
  selector: 'my-comp',
  template: r'''
    Hello {{getName()}}!
  ''',
)
class MyComp {
  // A static method.
  static getName() => 'Matan';
}
```

```dart
@Component(
  selector: 'my-comp',
  template: r'''
    Hello {{name}}!
  ''',
)
class MyComp {
  // A static property.
  static final name = 'Matan';
}
```

I suspect the code path used for binding an invocation "()" doesn't lookup static properties or something like that.

**Comment by matanlurey** [comment]
Thanks! I'm adding this to the 5.0.0 milestone because otherwise it will make it tough to document when statics work and don't work.
