### ISSUE TITLE
Intl localization doesn't work after compile to Javascript build

### ISSUE THREAD

**Issue by zkcode** [dart-lang/angular#1499]
Running environment:
- Dart VM version: `2.0.0-dev.67.0` (Unknown timestamp) on "linux_x64"
- AngularDart Version: `5.0.0-beta`
- Linux_x64 (`ubuntu 16.04`)
- `Chrome` to show the web page
-   pub packages used: `intl: ^0.15.6`, ` intl_translation: ^0.16.8`

Symptom:
1. one page use material-stepper components, the `continue` label of material-yes-no-button contained in material-stepper component can automatically adapt to right locale setting (Chinese message) after run `webdev serve`
2. but after building with command `webdev build -r -o web:build`, everything works fine, except the material-yes-no-button  still keep the English label. 

note: 
during initialization, I apply the code:
      `initializeMessages('zh_CN');`
     `Intl.defaultLocale = 'zh_CN';`

**Comment by matanlurey** [comment]
This is related to the components, not AngularDart.

**Comment by matanlurey** [comment]
This issue was moved to dart-lang/angular_components#293
