### ISSUE TITLE
Fix RouterHook example that implies it may inject Router

### ISSUE THREAD

**Issue by joshuaimmanuel** [dart-lang/angular#1511]
The following code snippet which extends `RouterHook` and specifies  `Router` as its dependency, 

```dart
class MyHook implements RouterHook {
  final Router _router;

  MyHook(this._router);
}

@GenerateInjector(const [
  routerProviders,
  ClassProvider(RouterHook, useClass: MyHook),
])
final InjectorFactory rootInjector = ng.rootInjector$Injector;

void main() {
  runApp(ng_app.AppComponentNgFactory, createInjector: rootInjector);
}
```

fails with a runtime exception on circular dependency.

```
dart_sdk.js:101652 EXCEPTION: Invalid argument: Maximum call stack size exceeded
STACKTRACE: 
../packages/angular/src/core/change_detection/change_detection.ddc.js 85:27   get _assertionsEnabled
../packages/angular/src/core/change_detection/change_detection.ddc.js 93:42   get isDevMode
../packages/angular/src/core/change_detection/change_detection.ddc.js 106:48  debugInjectorEnter
../packages/angular/src/core/change_detection/change_detection.ddc.js 698:23  inject
../main.ddc.js 86:91                                                          [_getRouterImpl$6]
../main.ddc.js 112:38                                                         injectFromSelfOptional
../packages/angular/src/core/change_detection/change_detection.ddc.js 709:25  injectOptionalUntyped
../packages/angular/src/core/change_detection/change_detection.ddc.js 699:25  inject
../main.ddc.js 70:67                                                          [_getMyHook$2]
../main.ddc.js 100:34                                                         injectFromSelfOptional
../packages/angular/src/core/change_detection/change_detection.ddc.js 709:25  injectOptionalUntyped
../main.ddc.js 86:222                                                         [_getRouterImpl$6]
../main.ddc.js 112:38                                                         injectFromSelfOptional
../packages/angular/src/core/change_detection/change_detection.ddc.js 709:25  injectOptionalUntyped
../packages/angular/src/core/change_detection/change_detection.ddc.js 699:25  inject
../main.ddc.js 70:67                                                          [_getMyHook$2]

...

Uncaught RangeError: Maximum call stack size exceeded
    at Object.get _assertionsEnabled [as _assertionsEnabled] (change_detection.ddc.js:85)
    at Object.get isDevMode [as isDevMode] (optimizations.dart:23)
    at Object.src__di__errors.debugInjectorEnter (errors.dart:20)
    at main$46template._Injector$rootInjector.__.inject (hierarchical.dart:30)
    at main$46template._Injector$rootInjector.__.[_getRouterImpl$6] (main.template.dart:64)
    at main$46template._Injector$rootInjector.__.injectFromSelfOptional (main.template.dart:87)
    at main$46template._Injector$rootInjector.__.injectOptionalUntyped (hierarchical.dart:45)
    at main$46template._Injector$rootInjector.__.inject (hierarchical.dart:31)
    at main$46template._Injector$rootInjector.__.[_getMyHook$2] (main.template.dart:60)
    at main$46template._Injector$rootInjector.__.injectFromSelfOptional (main.template.dart:75)
    at main$46template._Injector$rootInjector.__.injectOptionalUntyped (hierarchical.dart:45)
```

Dark SDK Version: 2.0.0-dev.68.0
AngularDart: angular-5.0.0-beta+1
angular_router: 2.0.0-alpha+16

**Comment by leonsenft** [comment]
This is because the `Router` implementation injects `RouterHook`, so you have a cyclic dependency that can't be resolved:

```
┌─> Router (RouterImpl) ─┐
│                        │
└─ RouterHook (MyHook) <─┘
```

I realize there's a mistake in the documentation that suggests this is possible, which we'll fix:

https://github.com/dart-lang/angular/blob/221c5a986e129d0737a17425d3b4aeb7a757de98/angular_router/lib/src/router_hook.dart#L57-L60

Can I ask what you need the router for in your router hook? Perhaps there's another solution.

**Comment by joshuaimmanuel** [comment]
In `canActivate` I check whether a particular user is authenticated, if not I redirect him to the login page. If he is authenticated, then I check for whether he has the permission to view the particular url. The permission string I am supplying as `additionalData` in `RoutePath` in order to generalize the permission checking pattern. If he doesn't have the required permission, I redirect him to his dashboard page.

So, I need `Router` in the `RouterHook`.

Is there any other way to accomplish this?

**Comment by joshuaimmanuel** [comment]
The other option that I thought, was to inject `Router` in all the components and access the router instance from `componentInstance` parameter of `canActivate` method in `RouterHook`. 

https://github.com/dart-lang/angular/blob/221c5a986e129d0737a17425d3b4aeb7a757de98/angular_router/lib/src/router_hook.dart#L101-L105

But, I don't see a way to convert `Object` to the actual component type. 
Or am I missing something?

**Comment by joshuaimmanuel** [comment]
Right now, I am using a dirty hack to inject the `Router` manually in `RouterHook`

```dart
class AuthGuard implements RouterHook {
  final AuthService _authService;
  Router _router;

  AuthGuard(this._authService);

  void setRouter(Router _router) {
    this._router = _router;
  }
}

// In main.dart
@GenerateInjector(const [
  routerProviders,
  ClassProvider(AuthGuard),
  ExistingProvider(RouterHook, AuthGuard),
])
final InjectorFactory rootInjector = ng.rootInjector$Injector;

void main() {
  runApp(ng_app.AppComponentNgFactory, createInjector: rootInjector);
}

// In app_component.dart
@Component(
  selector: 'my-app',
  templateUrl: 'app_component.html',
  ...
)
class AppComponent implements OnInit {
  final Routes routes;
  final Router _router;
  final AuthGuard _authGuard;

  AppComponent(this.routes, this._router, this._authGuard);

  void ngOnInit() {
    _authGuard.setRouter(_router);
  }
}
```
Please suggest the **right** way of checking permissions on each `RoutePath`

**Comment by leonsenft** [comment]
> The other option that I thought, was to inject Router in all the components and access the router instance from componentInstance parameter of canActivate method in RouterHook.

Your second approach is better. If you were going to go with this approach, it would make more sense to just inject the `AuthService` into each component instead.

> But, I don't see a way to convert Object to the actual component type.

If you really want to use this approach, you could make all of your routed components implement a common interface, which exposes the router and then safely cast to that interface to access it.

> Right now, I am using a dirty hack to inject the Router manually in RouterHook

I'd actually say this is a good workaround. I'd suggest setting the router in your constructor to ensure it's set before the view is instantiated (ngOnInit is called later):

```dart
class AuthGuard implements RouterHook {
  Router _router;

  set router(Router value) => _router = value;
}

@Component(...)
class AppComponent {
  AppComponent(Router router, AuthGuard authGuard) {
    authGuard.router = router;
  }
}
```

I admit the router hook APIs don't facilitate redirection. Rather than returning a boolean result to allow/block navigation, these APIs should provide more options such as allow/block/redirect. Unfortunately such a change would be majorly breaking so it's unlikely we'll implement that soon.

**Comment by joshuaimmanuel** [comment]
@leonsenft Thanks for your detailed response

> I'd actually say this is a good workaround. I'd suggest setting the router in your constructor to ensure it's set before the view is instantiated (ngOnInit is called later):

Okay. I will use this approach, this way I don't need to modify each and every component in order facilitate permission check on them.
