### ISSUE TITLE
Remove usage of pkg:tuple

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#1513]
We only use one class in one file. This also pulls in pkg:quiver_hashcode.

Seems a slam-dunk

https://github.com/dart-lang/angular/blob/221c5a986e129d0737a17425d3b4aeb7a757de98/angular/lib/src/compiler/selector.dart#L176-L180

**Comment by matanlurey** [comment]
PRs welcome. We just published a release, so I don't want to release one just for this.
