### ISSUE TITLE
router-outlet directive not found with <template> parent

### ISSUE THREAD

**Issue by sestegra** [dart-lang/angular#1516]
* Dart VM version: 2.0.0-dev.69.0 (Tue Jul 17 14:57:16 2018 +0200) on "macos_x64"
* angular-5.0.0-beta+2
* angular_router-alpha+17

Template for component.
``` html
<template>
    <h1>App</h1>
    <router-outlet [routes]="routes.all"></router-outlet>
</template>
```

When calling `router.navigate(pathToComponent)`, no router-outlet is found from `_resolveStateForOutlet`method in `lib/src/router/router_impl.dart`.
As a result,NavigationResult is INVALID_ROUTE.
``` dart
          RouterOutlet nextOutlet =
              componentRef.injector.get(RouterOutletToken).routerOutlet;
          // The route's component has no outlet. Continue search.
// HERE: nextOutlet is null when template is present
          if (nextOutlet == null) {
            continue;
          }
```

If I remove `<template>` tag, it's working well.

**Comment by sestegra** [comment]
Another component's template trigs this issue.
When `isLoading == false`, the router-outlet isn't found by router.

``` html
<ng-container *ngIf="isLoading == false">
    <app-navbar></app-navbar>
    <router-outlet [routes]="routes.all"></router-outlet>
</ng-container>
<ng-container *ngIf="isLoading == true">
    <div class="loading-spinner"></div>
</ng-container>
```

**Comment by matanlurey** [comment]
A `<template>` tag is somewhat identical to writing `*ngIf="false"`, in that it does not (eagerly) create the enclosed content (including the `<router-outlet>`), and thus this is expected behavior:

... however, I'll leave this open in case @leonsenft has suggestions/patterns for this case.

**Comment by zoechi** [comment]
I'd use `[hidden]="isLoading == true"` instead of `*ngIf`

**Comment by leonsenft** [comment]
Unfortunately this is working as intended. We're aware of this issue, as it has been raised before for `*ngIf` (https://github.com/dart-lang/angular/issues/1321).
