### ISSUE TITLE
doc/migrating-to-v5.md should use `webdev` commands

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#1523]
The doc currently refers to use of `build_runner`:

> In order to create a release build run `pub run build_runner build --release --output <directory>`. This will create the  ...

Should we promote use of `webdev build` instead here, or is webdev not used internally? @kevmoo @matanlurey 

cc @kwalrath

**Comment by alorenzen** [comment]
We should promote `webdev`. 

(And neither `webdev` nor `build_runner` is used internally. We use `build`, but with `bazel` instead of `build_runner`.)
