### ISSUE TITLE
AppVeyor tests every commit in a PR rather than the latest 

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#1524]
Take https://github.com/dart-lang/angular/pull/1515 for example. This was a rather large PR (in terms of number of commits). Taking a look at the AppVeyor History shows that every individual commit is queued up and tested, rather than skipping right to the latest commit of the PR.

Is this a shortcoming of AppVeyor, or is our https://github.com/dart-lang/angular/blob/master/appveyor.yml poorly configured?

**Comment by leonsenft** [comment]
I'll look into https://www.appveyor.com/docs/build-configuration/#rolling-builds, this sounds like what we want.

**Comment by leonsenft** [comment]
@kevmoo It looks like rolling builds can only be configured via the AppVeyor UI (similar to Travis). Could you please enable rolling build for our project?

**Comment by kevmoo** [comment]
Fixed – I think!
