### ISSUE TITLE
Search engine indexing issue for routes that require data to be fetched

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/angular#1525]
I have an angular app and I've submitted sitemaps to Google. The app uses a firebase back-end and content is located in Firestore so fetched for each route/url.

**The issue:** The vast majority of results indexed in Google appear to be processing the page before the remote content has been retrieved so Google indexes a blank page. This results in the page becoming an 'omitted' from google results.

If you want to see an example of this then you look through some of the pages here: https://goo.gl/tDqKcu

Is there a way I can announce a page as loaded or declare a page as loading until the content is ready? (I guess the http 200 code is only sent once with it being a single page app).

**Comment by matanlurey** [comment]
I do not think this has anything to do with AngularDart, sorry. You'd have to see how other SPAs handle it.

**Comment by jimmyff** [comment]
I do think that this is to do with the Angular Dart framework. Other SPA frameworks have created solutions such as server side rendering to solve this problem such as 'Angular Universal'. I don't know what the solutions are for AngularDart but this is/will become an issue for anyone who chooses people using this framework. Indexing and search prominence is after all a fundamental cornerstone of any web app.

I do believe as a framework, Angular Dart should at very least have a documentation around this subject, even if it's just recommending approaches if there is nothing baked in to the actual framework. 

I had hoped that introducing sitemaps would solve the issue but it hasn't it's just highlighted the issue I described above where the page isn't fetched quick enough for GoogleBot to snapshot it. 

My personal concern is due to the fact that I'm readying the launch a large Angular Dart project which will replace a successful web service that has a very strong search presence. I would feel more comfortable about this if I had a solution to the search & indexing issue of Angular Dart apps.
