### ISSUE TITLE
Questionable evaluation of Map expressions in ngClass

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/angular#1529]
I have this expression in my template:

```html
<div [ngClass]="{ 'alert':true, colorClass: true, 'margin--bottom': true, 'border': type == 'info'}">
```
colorClass is a String attribute of my component. I would expect that resulting classes would look like:

```html
<div class="alert bg--green margin--bottom">
```

But the result is:

```
<div class="alert colorClass margin--bottom">
```

Which in my opinion corresponds with:

```html
<div [ngClass]="{ 'alert':true, 'colorClass': true, 'margin--bottom': true, 'border': type == 'info'}">
```
(colorClass in apostrophes).

Needless to say - when I move the map to the component, it works as expected.

* Dart VM version: 2.0.0-dev.69.3 (Wed Jul 25 17:21:20 2018 +0200) on "macos_x64"
* angular 5.0.0-beta+2
* MacOS, Chrome

**Comment by zoechi** [comment]
Seems code is not shown. ``` might be missing

**Comment by matanlurey** [comment]
Yes, it looks like we are evaluating maps how they are represented in JS, not Dart.

**Comment by matanlurey** [comment]
We are removing collection literal support in the template, so this will no longer be addressed.
