### ISSUE TITLE
Import additional compiler code with a prefix

### ISSUE THREAD

**Issue by olostan** [dart-lang/angular#153]
If in the dart file where Angular 2 Dart component is, define (declare, import etc) `document` symbol, Angular 2 application falls (as it try to use this symbol from compiled templates. 

Example of `app_component.dart` from angular 2 stagehand project that stop app from working:

``` dart
import 'package:angular2/core.dart';

document() {
}

@Component(
    selector: 'symbol',
    template:'<div [id]="name"><ng-content></ng-content></div>'
)
class SymbolComponent {
  @Input('name') String name;
}

@Component(
    selector: 'my-app',
    styleUrls: const ['app_component.css'],
    directives: const [SymbolComponent],
    templateUrl: 'app_component.html')
class AppComponent {}
```

gives:

```
ORIGINAL EXCEPTION: NoSuchMethodError: Closure call with mismatched arguments: function 'createElement'
Receiver: Closure: () => dynamic from Function 'document': static.
Tried calling: createElement("div")
Found: createElement()
```

**Comment by matanlurey** [comment]
Blocked by https://github.com/dart-lang/angular2/issues/48

(We don't know where things are imported, yet)

**Comment by matanlurey** [comment]
This is now planned for the 4.0 release.

**Comment by matanlurey** [comment]
This is unlikely to be in the 4.0 release. Some of the groundwork will be, though.

**Comment by olostan** [comment]
Is it possible to list somewhere in documentation list of "forbidden words"? Would be useful

**Comment by matanlurey** [comment]
Upate: We've agreed to prefix `dart:html` for `4.0.0`.

**Comment by matanlurey** [comment]
This made it into `4.0.0-alpha+1`.
