### ISSUE TITLE
A story for more consistent lifecycle events

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1531]
(Based on an internal request)

Some of the current lifecycle events (other than `OnInit` and `OnDestroy`) have a fairly fatal flaw - they only work if the component or directive (or pipe, I guess) are created and managed declaratively (i.e. through the view compiler/template). For example, imagine the following code:

```dart
import 'main.template.dart' as ng;

class FooComponent implements AfterChanges {
  @override
  void ngAfterChanges() {
    print(name);
  }

  @Input()
  String name;
}

void main() {
  // Faux API.
  FooComponent c = createComponentImperatively(ng.FooComponent);
  c.name = 'Matan';
}
```

... the `ngAfterChanges()` lifecycle event is never invoked.

**Comment by jonahwilliams** [comment]
Just a thought: If you are managing a component imperatively, it would make sense to manage change detection imperatively too, right? Maybe not the raw component instance unless there was a real base component object. I just realized I have no idea if this works though

```dart
// This should call ngOnInit, right?
ComponentRef<FooComponent> ref = createComponentImperatively(ng.FooComponent);
c.name = 'Jonah';
c.foo = 23;
c.changeDetectorRef.detectChanges(); // calls change detection, and ngAfterChanges?
// also markForCheck() ? which one should I use?
..
c.destroy(); // calls ngOnDestroy(), right?
```

Presumably if there was a `Component` type, then it could just have these methods with base implementations so that you could ditch the `ComponentRef` indirection.

**Comment by alorenzen** [comment]
Using `ComponentRef.update()` added in `6.0.0-alpha+1`, this is now fixed for imperative component loading.

```
import 'main.template.dart' as ng;

class FooComponent implements AfterChanges {
  @override
  void ngAfterChanges() {
    print(name);
  }

  @Input()
  String name;
}

var main() {
  final componentRef = ng.FooComponentNgFactory.create();
    componentRef.update((FooComponent component) {
      component.name = "new value";
    }); // calls ngAfterChanges() and change detection.
```

There are still *other* ways that a component might be interacted with imperative (via ViewChild/ContentChild, parent injection, etc.) But for the main case referenced in this issue, I'm going to mark this bug as fixed.
