### ISSUE TITLE
@deferred silently does nothing if host also has structural directive

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#1538]
The following pattern silently drops the `@deferred`:

```html
<my-comp *ngIf="showExample @deferred></my-comp>
```

A correct solution is to move the structural directive to a parent element:

```html
<div *ngIf="showExample">
  <my-comp @deferred></my-comp>
</div>
```

Given this restriction, the compiler should warn or error if `@deferred` and a structural directive are placed on the same element.

**Comment by alorenzen** [comment]
We already have an error if there are two structural directives on the same element. I think it's reasonable to treat `@deferred` as a structural directive and error in this case as well.

**Comment by matanlurey** [comment]
Agree with @alorenzen, though it is confusing because it is an `@` and not a `*`.

**Comment by matanlurey** [comment]
We agreed making this a static error is acceptable, and not strictly speaking a breaking change.

**Comment by matanlurey** [comment]
@leonsenft @alorenzen I guess that we'd have to do this in `desugar_visitor.dart`:

```dart
    if (astNode.annotations.isNotEmpty) {
      final i = astNode.annotations.indexWhere((ast) => ast.name == 'deferred');
      if (i != -1) {
        final deferredAst = astNode.annotations.removeAt(i);
        final origin = _toolFriendlyAstOrigin ? deferredAst : null;
        return EmbeddedTemplateAst.from(
          origin,
          childNodes: [astNode],
          hasDeferredComponent: true,
        );
      }
    }
```

... right?

**Comment by leonsenft** [comment]
Yeah, I think so.

**Comment by matanlurey** [comment]
It looks like this is less than straightforward, because:

1. We de-sugar `*directives` before parsing annotations.
2. The code that parses `<template>` doesn't even parse annotations.

Thoughts?

**Comment by leonsenft** [comment]
Why not check the annotations before de-sugaring `*directives`? Essentially swap these blocks: https://github.com/dart-lang/angular/blob/5ad73932b7885ce78b1371bbe79628f5fec3d6d6/angular_ast/lib/src/visitors/desugar_visitor.dart#L87-L102

**Comment by matanlurey** [comment]
That solves the `*` case but not the `<template>` one :)

**Comment by leonsenft** [comment]
Oh sorry I think I misunderstood your second point. You're concerned about

```html
<template @deferred>
  ...
</template>
```

right?

`<template>` elements wouldn't have supported annotations at the time `@deferred` was added, but I think they now do to support `@preserveWhitespace` right?

Why not add the check for `@deferred` to `visitEmbeddedTemplate()` in `desugar_visitor.dart`?

**Comment by matanlurey** [comment]
I could, it just seemed messy. But reading this discussion, it probably is not. Thanks!

**Comment by matanlurey** [comment]
Fixed in https://github.com/dart-lang/angular/commit/703fbdac00712244ac63196c446a493b6bacae2d.
