### ISSUE TITLE
<router-outlet> causing FormatException during test

### ISSUE THREAD

**Issue by richehmer** [dart-lang/angular#1543]
When I run tests on a component with `<router-outlet>` in the template, I get a FormatException. When I remove `<router-outlet>`, or test a sub-component that doesn't use `<router-outlet>`, the test passes.

`pub run build_runner test --verbose --fail-on-severe -- -p chrome` leads to a:

FormatException: Scheme not starting with alphabetic character (at character 1)
  %7B%22metadata%22:%7B%22testOn%22:%22browser%22,%22timeout%22:%7B%22duratio...
  ^

I replicated the issue with the 'tour of heroes' tutorial code ([stage 6](https://webdev.dartlang.org/angular/tutorial/toh-pt6)), and have noticed that none of the testing examples involved a component with `<router-outlet>` Here's the test file:

### Test file 'app_test.dart'
```
@TestOn('browser')
import 'package:angular/angular.dart';
import 'package:angular_test/angular_test.dart';
import 'package:angular_router/angular_router.dart';
import 'package:nc_tutorial_app/app_component.dart';
import 'package:nc_tutorial_app/app_component.template.dart' as ng;
import 'package:test/test.dart';

import 'app_test.template.dart' as self;

@GenerateInjector([
  routerProvidersHash,
])
final InjectorFactory rootInjector = self.rootInjector$Injector;

void main() {
  final testBed = NgTestBed.forComponent<AppComponent>(ng.AppComponentNgFactory,
      rootInjector: rootInjector);

  NgTestFixture<AppComponent> fixture;

  setUp(() async {
    fixture = await testBed.create();
  });

  tearDown(disposeAnyRunningTest);

  test('Default greeting', () {
    expect(fixture.text, contains('Tour of Heroes'));
  });

}
```

### Full error output:
 Command: `pub run build_runner test --verbose --fail-on-severe -- -p chrome`

00:01 +0 -1: test/app_test.dart: Default greeting [E]                                                                                        
  FormatException: Scheme not starting with alphabetic character (at character 1)
  %7B%22metadata%22:%7B%22testOn%22:%22browser%22,%22timeout%22:%7B%22duratio...
  ^
  
  dart:sdk_internal                                                          parse
  package:angular_router/src/url.dart 13:20                                  parse
  package:angular_router/src/router/router_impl.dart 80:20                   registerRootOutlet
  package:angular_router/src/directives/router_outlet_directive.dart 102:12  ngOnInit
  package:nc_tutorial_app/app_component.template.dart 129:24                 detectChangesInternal
  package:angular/src/core/linker/app_view.dart 398:7                        detectChanges
  package:nc_tutorial_app/app_component.template.dart 196:16                 detectChangesInternal
  package:angular/src/core/linker/app_view.dart 398:7                        detectChanges
  package:angular/src/core/linker/view_ref.dart 106:12                       detectChanges
  package:angular/src/core/change_detection/host.dart 168:18                 [_runTick]
  package:angular/src/core/change_detection/host.dart 144:15                 tick
  package:angular_test/src/bootstrap.dart 119:11                             loadComponent
  package:angular_test/src/bootstrap.dart 131:12                             _runAndLoadComponent
  package:angular_test/src/bootstrap.dart 63:12                              async.Future$._check.appRef.run.dart.fn
  package:angular/src/core/change_detection/host.dart 250:18                 runInZone.dart.fn
  package:angular/src/core/zone/ng_zone.dart 178:16                          parent.run.dart.fn
  dart:sdk_internal                                                          run
  package:angular/src/core/zone/ng_zone.dart 175:18                          [_run]
  dart:sdk_internal                                                          run
  package:angular/src/core/zone/ng_zone.dart 327:22                          run
  package:angular/src/core/application_ref.dart 140:51                       runInZone
  package:angular/src/core/change_detection/host.dart 248:5                  run
  package:angular_test/src/bootstrap.dart 62:16                              bootstrapForTest
  package:angular_test/src/frontend/bed.dart 294:14                          FutureOfNgTestFixtureOfT.sync.dart.fn
  dart:sdk_internal                                                          sync
  package:angular_test/src/frontend/bed.dart 285:12                          [_createDynamic]
  package:angular_test/src/frontend/bed.dart 264:26                          create
  app_test.dart 64:28                                                        <fn>
  dart:sdk_internal                                                          async
  app_test.dart 63:9                                                         test$.setUp.dart.fn
  ===== asynchronous gap ===========================
  package:angular_test/src/frontend/bed.dart 285:12                          [_createDynamic]
  package:angular_test/src/frontend/bed.dart 264:26                          create
  app_test.dart 64:28                                                        <fn>
  dart:sdk_internal                                                          async
  app_test.dart 63:9                                                         test$.setUp.dart.fn

### System Info
* [2.0.0-dev.69.4] Dart SDK Version (`dart --version`)
* [^5.0.0-beta+2] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
* [macOS ] Whether you are using Windows, macOS, or Linux (if applicable)
* [chrome] Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
* [ ] Any other packages or constraints we should know about

**Comment by leonsenft** [comment]
Both `routerProviders` and `routerProvidersHash` aren't intended for testing.

Please try importing `'package:angular_router/testing.dart'` and providing `routerProvidersTest` instead. Feel free to reopen if your issue persists.
