### ISSUE TITLE
Refactor `@defered` to a synthetic structural directive

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1561]
The source of https://github.com/dart-lang/angular/issues/1539 is that `@deferred` tries to be clever, and implements itself _similar_ to a structural directive but doesn't go through all of the steps. It's trivial to add a workaround to fix #1539, but in the future it would be nice if:

```html
<custom-comp @deferred></custom-comp>
```

... was basically a direct sugar of:

```html
<template>
  <custom-comp></custom-comp>
</template>
```

... where `<custom-comp>` is constructed lazily (using the `loadDeferred()` logic).

**Comment by leonsenft** [comment]
Isn't it already a direct sugar for

```html
<template>
  <custom-comp></custom-comp>
</template>
```

?

https://github.com/dart-lang/angular/blob/75d190d59efd7795355649d995e94403ce351e59/angular_ast/lib/src/visitors/desugar_visitor.dart#L101-L105

**Comment by matanlurey** [comment]
You're right. Then I have no idea why it generates different code than a typical `<template>`. :)
