### ISSUE TITLE
CSP unsafe eval

### ISSUE THREAD

**Issue by marian-soltys** [dart-lang/angular#1589]
I'm writing application in angular dart and have problem with CSP unsafe-eval.
On server, we have:
```
Content-Security-Policy: default-src 'self'; object-src 'none'; style-src 'self'; script-src 'self';
X-Content-Security-Policy: default-src 'self'; object-src 'none'; style-src 'self'; script-src 'self';
```
Dart fails, the message is:
```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
at new Function (<anonymous>)
    at tearOffGetter (main.dart.js:270)
    at tearOff (main.dart.js:272)
    at addStubs (main.dart.js:231)
    at processClassData (main.dart.js:170)
    at processStatics (main.dart.js:198)
    at setupProgram (main.dart.js:299)
    at main.dart.js:10980
    at main.dart.js:11469
```
The offending line from `main.dart.js:270`:
```
...
function tearOffGetter(d,e,f,g,a0){return a0?new Function("funcs","applyTrampolineIndex","reflectionInfo",...
...
```

Details:
* Dart VM version: `2.1.0-dev.1.0 (Unknown timestamp) on "linux_x64"`  
`(installed via apt https://storage.googleapis.com/download.dartlang.org/linux/debian unstable/main amd64 dart amd64 2.1.0-dev.1.0-1)`
* AngularDart Version `angular: ^5.0.0`
* Tested on Chromium 67.0.3396.99 and Firefox 61.0.1, OS linux xbuntu
* To reproduce, create `web-angular` via stagehand, do a `webdev build`, put on server with CSP headers metioned above.

I know i can put unsafe-eval directive to CSP resp. headers on sever like this: `... script-src 'self' 'unsafe-eval'`,
but by reading closed `CSP issue #30` i'm assuming this is dart-angular bug, so here is the report.

**Comment by matanlurey** [comment]
You'll need to enable CSP mode for Dart2JS:
https://webdev.dartlang.org/tools/dart2js#analysis-options
