### ISSUE TITLE
Release angular_router v2 GA

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#1590]
- It's more popular than angular_forms
- It's core to our getting started docs - https://webdev.dartlang.org/angular/tutorial/toh-pt5#update-the-pubspec
- It's certainly in better shape than angular_router v1.x

**Comment by matanlurey** [comment]
We talked offline and agreed (?) that nothing is blocking releasing v2 GA, but at the same time we realize it is very incomplete with many open issues that can't be easily addressed.
