### ISSUE TITLE
Built-in and custom form validation behave differently

### ISSUE THREAD

**Issue by joe776** [dart-lang/angular#1595]
Built-in validation HTML (for example `required`) sets the state in the DOM (CSS `:valid`/`:invalid`) and of the Angular `Control` state. For a custom validation, set via a `@Directive` that implements `Validator` or as a `ValidatorFn`, only sets the state of the Control and _not_ in the DOM.

I created a quick example here:
https://github.com/joe776/angular-custom-form-validaton

* [x] Dart SDK Version (`dart --version`) -> 2.1.0-dev.2.0
* [x] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`) -> 5.0.0
* [x] Whether you are using Windows, macOS, or Linux (if applicable) -> macOS 10.13
* [x] Whether you are using Chrome, Safari, Firefox, Edge (if applicable) -> tested in Chrome stable and FF

**Comment by TedSander** [comment]
I don't see this being fixed. There are performance costs for setting classes/psuedo classes for validity on the elements. We used to have a directive that changed classes in angular here:
https://github.com/dart-lang/angular/blob/master/angular_forms/lib/src/directives/ng_control_status.dart

Each of these bindings had a weight on the performance of large applications. You can still use these bindings, but when we removed them most people weren't using that API but we saved a lot of bindings per control instance.

If you wanted this enabled I'd suggest creating a directive in your project that can be used with any control that sets the invalid/valid pseudo classes. That said I don't see us putting them in the native directives as they are a performance drag for everyone, and most weren't finding the CSS selectors useful.

**Comment by joe776** [comment]
Thanks for the clarification!
In that case, I propose to improve to documentation for the `Control` and `Validator` classes, to state that custom validation _only_ affects validity in Angular, and just incidentially coincides with built-in HTML validation in the case of `required`, for example.
