### ISSUE TITLE
@i18n attribute doesn't override component host attribute

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#1600]
During compilation, we attempt to merge the HTML attributes declared on an element with the attribute `@HostBinding`s of its directives.

This process technically only merges the values of `class` and `style` attributes. Any other collisions are simply overriddn in the following priority (lowest to highest):

1. Component host attributes.
2. HTML attributes.
3. Directive host attributes.

Due to some technical challenges, internationalized (`@i18n:`) attributes aren't merged in the same manner, and are instead handled separately after this process. A consequence of this process means we're not able to discern component host attributes from directive host attributes, and must give both priority above the `@i18n:` attribute.

**Comment by alorenzen** [comment]
I'm working on a refactoring that should fix this issue.
