### ISSUE TITLE
View not refreshing (No change detection)

### ISSUE THREAD

**Issue by chstrong** [dart-lang/angular#1614]
- Angular 5.0.0
- Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "macos_x64"
- MacOS X 10.13.6
- Chrome

pubspec.yaml:
-----------------------------
name: places
description: Cool Places
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha
  http: ^0.11.0            
  stream_transform: ^0.0.6
  angular_components: ^0.9.0

dev_dependencies:
  sass_builder: ^2.0.0
  angular_test: ^2.0.0-beta
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0

I want to notify a parent component from a child component to update a view in the parent component, after saving an entry. I'm using the @output annotation to parse back an event.

In the parent component the function "loadPosts()" is actually invoked, but the view is not updated. Not even with ChangeDetectorRef.

What happens:

- place_component contains a "list-post" directive, which displays all posts.
- place_component contains a modal, to add a new post with a directive "new-post"
- When a new post is saved, a message is parsed back over @output to the "new-post" directive in the modal: (doneIt)="loadPosts()"
- The loadPosts() function is executed, but the "list-post" directive does not reload.

See following Stackoverflow for details:
https://stackoverflow.com/questions/52295624/how-to-notify-parent-component-of-change-and-refresh-view

**Comment by chstrong** [comment]
I have also tried with an EventBus: https://stackoverflow.com/questions/44170126/angulardart-how-do-you-pass-an-event-from-a-child-component-to-a-second-level-p

It's the same behaviour, loadPosts function is executed, but the view is not updated.

**Comment by chstrong** [comment]
This also didn't do the trick....

  PlaceComponent(this._placeService, this._location, this._postEvent, this.cdRef) {
    _postEvent.onEventStream.listen((int id) => loadPosts().then((_){cdRef.markForCheck();}));
  }

**Comment by matanlurey** [comment]
Unfortunately we aren't going to be able to debug your code for you on this repository.

Feel free to file again with a _minimal reproducible sample_ (i.e. one we can run ourselves).
