### ISSUE TITLE
Unable to configure nested routing 

### ISSUE THREAD

**Issue by drbcode** [dart-lang/angular#1615]
Example:
https://github.com/drbcode/ng_dart_nested_routing

For some reason `RoutePath.toUrl` is not pretending path of parent component.

#### What works:
- Opening links manually works fine, for example opening these links will work and route you to 
correct component

```
http://localhost:8080/#hi/bye
http://localhost:8080/#hi/bio
```

#### What does not work:

Using the links defined in `/lib/src/comp/hi/hi.dart` at line <a href="https://github.com/drbcode/ng_dart_nested_routing/blob/2f249281a775b14cc7d040418a90061f5ac76ad4/lib/src/comp/hi/hi.dart#L13">13</a>

```
<a [routerLink]="Routes.bye.toUrl()">bye</a>
<a [routerLink]="Routes.bio.toUrl()">bio</a>
```

Links that are generated are:

```html
<a href="#/bye">bye</a>
<a href="#/bio">bio</a>
```

Above lines do not add path for parent even when parent component is defined in `/lib/src/routes/nested/nested_route_paths.dart` at <a href="https://github.com/drbcode/ng_dart_nested_routing/blob/2f249281a775b14cc7d040418a90061f5ac76ad4/lib/src/routes/nested/nested_route_paths.dart#L10">10</a>:

```dart
class RoutePaths {
  static final bye = RoutePath(
    path: 'bye',
    parent: parent.RoutePaths.hi,
  );
  static final bio = RoutePath(
    path: 'bio',
    parent: parent.RoutePaths.hi,
  );
}
```

links should be:
```html
<a href="#hi/bye">bye</a>
<a href="#hi/bio">bio</a>
```

Dart version: 2.0.0
angular: version: "5.0.0"
angular_router: version: "2.0.0-alpha+19"

**Comment by jhfbosman** [comment]
Just replace your **Routes** with **RoutePaths** as follow:

<a [routerLink]="RoutePaths.bye.toUrl()">bye</a>
<a [routerLink]="RoutePaths.bio.toUrl()">bio</a>

**Comment by drbcode** [comment]
Thanks a lot!
