### ISSUE TITLE
Unhandled exception in compiler

### ISSUE THREAD

**Issue by RonKaminsky** [dart-lang/angular#1619]
* [ ] Dart SDK Version = Dart VM version: 2.1.0-dev.4.0 (Fri Sep 7 16:44:38 2018 +0200) on "linux_x64"
* [ ] AngularDart Version = 5.0.0
* [ ] Using Linux
* [ ] Using Firefox

Apologies if this is already a closed issue, I do not have enough experience with AngularDart to understand if this issue is already closed, and the compiler explicitly requests a bug report.

When running the Tour of Heroes tutorial, I forgot to import the hero_service.dart file. The compiler complains with:

[INFO] Running build...
[WARNING] angular on lib/app_component.dart:
Could not resolve an OpaqueToken on a Provider!
[SEVERE] angular on lib/app_component.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
NoSuchMethodError: The method 'toTypeValue' was called on null.
Receiver: null
Tried calling: toTypeValue()

Step 4 of the tutorial; app_component.dart is:

    import 'package:angular/angular.dart';
    import 'package:angular_forms/angular_forms.dart';
    
    import 'src/hero.dart';
    // import 'src/mock_heroes.dart';
    import 'src/hero_component.dart';
    // import 'src/hero_service.dart';
    
    @Component(
      selector: 'my-app',
      directives: [coreDirectives, formDirectives, HeroComponent],
      providers: [ClassProvider(HeroService)],
      styleUrls: ['app_component.css'],
      templateUrl: 'app_component.html',
    )
    
    class AppComponent implements OnInit {
      final title = 'Tour of Heroes';
      Hero selected;
      List<Hero> heroes;
      final HeroService _heroService;
      AppComponent(this._heroService);
    
      void _getHeroes() {
        heroes = _heroService.getAll();
      }
      
      void onSelect(Hero hero) => selected = hero;
    
      void ngOnInit() => _getHeroes();
    }

**Comment by matanlurey** [comment]
It looks like you likely have missing imports. Could you verify that?

**Comment by leonsenft** [comment]
Yep, looks like your import statement for `HeroService` is commented out, so it can't be resolved at compile time which leads to the error you're seeing. To fix just uncomment this line:

```dart
// import 'src/hero_service.dart';
```

**Comment by leonsenft** [comment]
Sorry, I somehow missed that you had already identified the problem! Yes you're right, given that there's a warning we could possibly throw an intentional build error instead.

@matanlurey Is it possible we upgrade this warning to a build failure?

https://github.com/dart-lang/angular/blob/714c5dec40b10d06fb989b7acade0a7793540192/angular/lib/src/source_gen/template_compiler/compile_metadata.dart#L336-L339

Or are there cases where this is valid?

**Comment by jbdeboer** [comment]
The error message is improved with 354d1883ff037a3844d44ac07a3b63871083a792

The compiler error new includes a source location pointing to the unresolved "HeroService" token in the providers list.
