### ISSUE TITLE
build erroor:FormatException: Bad UTF-8 encoding 0xb5 (at offset 4)

### ISSUE THREAD

**Issue by woaisancai** [dart-lang/angular#1623]
i build the project under window10 using 'webdev build'。And i got the error:
D:\quickstart>webdev build
Creating build script, took 12882ms
[INFO] Reading cached asset graph completed, took 1.4s
[INFO] Checking for updates since last build completed, took 2.3s
[INFO] Running build completed, took 992ms
[INFO] Caching finalized dependency graph completed, took 529ms
[SEVERE] build_web_compilers|entrypoint on web/main.dart (cached):

Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:quickstart/app_component.template.dart' as ng;` from quickstart|web/main.dart at 2:1

[SEVERE] angular on lib/app_component.dart (cached):
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
FormatException: Bad UTF-8 encoding 0xb5 (at offset 4)
[SEVERE] Failed after 1.6s

who can help me solve the problem?

**Comment by TedSander** [comment]
What is the name of the file that has your root component? and what is the name of the package as specified by your pubspec.yaml?

Is it app_component.dart, and quickstart? If not those need to be changed in the import to match.

**Comment by woaisancai** [comment]
my pubspec.yaml file:
name: quickstart
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0

the file list that has on my root component:

 D:\quickstart's directory

2018/09/26  09:28    <DIR>          .
2018/09/26  09:28    <DIR>          ..
2018/09/26  10:09    <DIR>          .dart_tool
2018/09/25  10:05               236 .gitignore
2018/09/25  15:21             9,561 .packages
2018/09/25  10:05               556 analysis_options.yaml
2018/09/25  10:05                50 CHANGELOG.md
2018/09/26  10:33    <DIR>          lib
2018/09/25  15:21            14,215 pubspec.lock
2018/09/25  10:05               399 pubspec.yaml
2018/09/25  10:05               296 README.md
2018/09/25  10:05    <DIR>          test
2018/09/26  15:08    <DIR>          web

**Comment by matanlurey** [comment]
Unfortunately this isn't enough information to help. If you have a reproduction, we can take a look.
