### ISSUE TITLE
Documentation broken on pub.dartlang.org

### ISSUE THREAD

**Issue by pschiffmann** [dart-lang/angular#1641]
Angular 5.1.0, released last week on pub.dartlang.org, has an SDK constraint of `>=2.1.0-dev.5.0`, which causes the analysis and dartdoc tools to fail.
Additionally, if you try to open the [5.0.0 docs](https://pub.dartlang.org/documentation/angular/5.0.0/) (for example via the [versions tab](https://pub.dartlang.org/packages/angular#-versions-tab-)), you get redirected to the version overview page again, making it impossible to view the current Angular docs online.

**Comment by chalin** [comment]
Thanks for reporting this issue. In the meantime (as you might already know), you can view the 5.0.0 API docs from https://webdev.dartlang.org/api. If you are looking for the usual Angular API landing page, it is here: https://webdev.dartlang.org/api/angular/angular/angular-library.

**Comment by matanlurey** [comment]
I don't think we plan on fixing this ourselves. It will be organically will be fixed when 2.1.0 is published.
