### ISSUE TITLE
@i18n seems not to work for properties of components

### ISSUE THREAD

**Issue by zreptil** [dart-lang/angular#1643]
* [x] Dart SDK Version 2.1.0-dev.7.1
* [x] AngularDart Version 5.1.0
* [x] Windows XP
* [x] Chrome
* [x] build_runner 1.0.0

When internationalizating a webapp, the material-components seem to miss the feature of being localized. In the template i use a material-input and want to assign a localized label to it. I tried it with the usual @i18n annotation like this:

<material-input floatingLabel @i18n:label="English Input"></material-input>

But when compiling this, it gives me the following error message:

ParseErrorLevel.FATAL: Attempted to internationalize "label", but no matching attribute or property found

label is a property of MaterialInputComponent so this error is a little confusing. Is it possible to localize material-components with the @i18n annotation or have i to do something like this?

<material-input floatingLabel [label]="msgEnglishInput"></material-input>

where msgEnglishInput is a member of the component using the template and is defined as 

String msgEnglishInput => Intl.message("English Input");

**Comment by leonsenft** [comment]
The value of a `@i18n` annotation is the _description_ of the message, not the message itself. You need both the property binding to `label`, and the annotation `@i18n:label` to describe the message.

```html
<material-input
    floatingLabel
    label="My message."
    @i18n:label="A description of my message to help translators.">
</material-input>
```

That's why you get the error _no matching attribute or property found_ when only using `@i18n:label`.
