### ISSUE TITLE
AngularDart 5 ComponentFactory<A<T>>

### ISSUE THREAD

**Issue by 6f6c646d616e** [dart-lang/angular#1647]
* Dart SDK Version 2.0.0-1 || 2.1.0-dev.8.0-1
* AngularDart Version 5.0.0 || 5.1.0

Am I wrong or there is no way, in AngularDart 5, to get ComponentFactory for ***generic component***???

**Comment by alorenzen** [comment]
As of right now, that is correct. We are currently exploring a few different ways to support this, but have not settled on a direction yet.

**Comment by 6f6c646d616e** [comment]
Well AngularDart sucks!

Since AngularDart 1, how people do without??? So we have to copy and paste all the time for all Component (among material component)??? Are you serious???

Looks like an extremely poor design. Man, AngularDart sucks!
