### ISSUE TITLE
Stable Angular 5.1.0 needs unstable dev SDK 2.1.0

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/angular#1648]
_From @quizzmaster on October 26, 2018 23:4_

I'm new to Dart and AngularDart. I want to use the stable branch of the dart SDK with version 2.0.0. The homepage mentions angular version 5.1.0 to be the latest stable version for dark 2.0.0, but pub says it needs SDK >=2.1.0-dev.5.0. It's really confusing for me, because the package manager should serve the packages for the stable sdk. If I switch to the dev branch of the SDK an other package I use in a different project `rpc_mongo_mapper` won't work anymore, because it relies on the stable SDK.

Such a behaviour is predestined to scare new developers of dart.

_Copied from original issue: dart-lang/sdk#34945_

**Comment by matanlurey** [comment]
This is WAI. We decided it was more important for (some) users who are tracking dev to get earlier access to 5.1.0. As soon as a 2.1.0 final is released, it will still be supported for 5.1.0. So you can choose what/when you'd like to use 5.1.0.
