### ISSUE TITLE
How to Generate Code Coverage Report

### ISSUE THREAD

**Issue by felangel** [dart-lang/angular#1654]
Project created using stagehand:
`stagehand web-angular`

Tests run using build_runner:
`pub run build_runner test --fail-on-severe`

How can I generate a coverage report? I have not found any documentation or examples online.
Ideally, I'd like to be able to do something like:
`pub run build_runner test --fail-on-severe --coverage` and have an lcov.info be generated in `./coverage/lcov.info`.

* [`Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "macos_x64"`] Dart SDK Version (`dart --version`)
* [ `"5.0.0"`] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
* [`macOS`] Whether you are using Windows, macOS, or Linux (if applicable)
* [`Chrome`] Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

**Comment by matanlurey** [comment]
You will want to file this elsewhere. AngularDart has nothing to do with code coverage.

**Comment by felangel** [comment]
How does this have nothing to do with AngularDart? When I use AngularJS I get testing configured out of the box with coverage reporting.

It’s not a dart issue because I can generate coverage reports for my dart code no problem.
