### ISSUE TITLE
Element.createShadowRoot deprecated

### ISSUE THREAD

**Issue by michalpie** [dart-lang/angular#1657]
We are using an old version of AngularDart: 1.1.2+2. Recently, the Chrome browser started to display the following warning:

> [Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.

Our application is quite big and rewriting it to the newest Angular Dart version is at the moment impossible. Are you going to provide a fix? Should we worry about it? Are polyfills going to be used automatically?

* [ 1.24.3] Dart SDK Version
* [1.1.2+2] AngularDart Version
* [Windows] 
* [Chrome v.70 ] Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

**Comment by leonsenft** [comment]
Sorry, we have no plans to update version 1.x. It's essentially a different framework from version 2 on wards, that was developed by a different team.
