### ISSUE TITLE
Using identical() function in select_control_value_accessor causes a lot of problems

### ISSUE THREAD

**Issue by rafbermudez** [dart-lang/angular#1659]
Using identical() to compare values in select_control_value_accessor is not the best scenario when you are using  two-way binding with select tags.

For example:

- aselected is type of A with aselected.id = 1
- aList is a type of  List< A > with elements:   a1.id = 1,  a2.id = 3, a3.id = 3
- aselected.id == a1.id but they are not the same instance 

Although you override A Class (equality and hashcode) the select [(ngModel)]="aselected" it will never work as expected. 

I propose redefine _getOptionId using == instead of identical()
```
String _getOptionId(dynamic value) {
    for (var id in _optionMap.keys) {
      if (identical(_optionMap[id], value)) return id;
    }
    return null;
}
```
File: [select_control_value_accessor.dart](https://github.com/dart-lang/angular/blob/master/angular_forms/lib/src/directives/select_control_value_accessor.dart)

**Comment by alorenzen** [comment]
We use identical() for change detection in the core angular package. I'm not sure why we should switch to == just for select_control_value_accessor?

I'm going to mark this as working as intended.
