### ISSUE TITLE
Consider exposing navigation errors on Route

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/angular#1661]
Angular 5.0
Dart 2.0

As we were preparing our Angular app for a release, we decided to switch from ```HashLocationStrategy``` to ```PathLocationStrategy```.

We proceeded to update the server, so that all paths were redirected to index.html.

So far so good,
Now when adding an Angular 404 handler, some issues arose.

The Routes guide mentions simply adding a wildcard path for 404, i.e. ```"path: '.+'"```.
This works, but unfortunately it also wrongly returns 404 for static folders (like assets, or scripts, ...).

Excluding these folder names in the wildcard ```RegExp``` feels... a bit ugly.

Proposal:
Add an extra ```Stream``` to ```Router```, ```onNavigationError``` for example.
Or do actually throw an ```Error``` when an invalid route is encountered.

Currently, upon entering an invalid route, I simply get a blank page with no console error at all.

**Comment by zoechi** [comment]
I haven't done much with the router in the current Angular version.
Previously there was a way to add a catch-all route.
You could show a 404 info on such a route if this is still supported.

**Comment by leonsenft** [comment]
`NavigationResult.Invalid` is returned from `Router.navigate()` when an imperative navigation fails, but you're right that the initial navigation will load a blank page if no matching route is defined. That said, I don't understand what this has to do with having a 404 route? You can use a catch all route like you've suggested on your client to display a 404 page. Make sure this is declared last so your valid routes can match before it.

>We proceeded to update the server, so that all paths were redirected to index.html.
> ...
> This works, but unfortunately it also wrongly returns 404 for static folders (like assets, or scripts, ...).

So is your server redirecting requests to /assets or /scripts to /index.html? Your server shouldn't do that. Any valid resources on your server should take precedence over the rewrite rule. The rewrite rule should kick in, only when the server doesn't have a matching resource.
