### ISSUE TITLE
Support for Server-Side Rendering

### ISSUE THREAD

**Issue by gbrlsnchs** [dart-lang/angular#1664]
Hi there. Do you plan to add SSR support? I like Dart just as much as I dislike JavaScript (and consequently TypeScript), so this is the only thing making me opt for the TypeScript implementation. I have also considered other frameworks with SSR support, but since I've started messing with Flutter, I would prefer to also use Dart for this purpose.

If you're not considering implementing it, would you mind guiding me (or whoever is reading this) where to start implementing it?

Thanks!

**Comment by matanlurey** [comment]
No. See https://github.com/dart-lang/angular/issues/225.

We would likely not take an implementation of this as part of `dart-lang/angular`. Of course you are free to fork or find alternatives for your projects, and we'd be happy to be kept in the loop.

**Comment by dalu** [comment]
This puts this project at a severe disadvantage vs. typescript angular
mobile application visitors may be at 80% but even if you share your pages on social networks you'll need them be a scrapeable by at least the primitive Facebook scraper who can't deal with es5.
And even in Angular this feature is not just plug and play, where rivals like ember have fastboot that apparently works very well (discourse is just one popular example).

Many pick React over Angular for this reason.
And judging by the amount of issues and starts many pick Typescript Angular over Dart Angular.

SEO is a big deal. If you have a web facing framework you can't ignore it.
