### ISSUE TITLE
Router, lost feature: class on active routerLink

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/angular#1667]
Hey guys!

In the previous version of router (ng2) the [routerLink] directive added 'router-link-active' css class to the element, when the current route matched the [routerLink] route.

That was very usefull, please return that feature back :-) Or similar.

Thanks!

**Comment by rich-j** [comment]
Check out the [RouterLinkActive directive](https://webdev.dartlang.org/api/angular_router/angular_router/RouterLinkActive-class).

    <a routerLink="/user/bob" routerLinkActive="active-link">Bob</a>

This directive is more flexible, it allows you to specify the CSS class to add on an active link. It also allows the CSS class to be placed on a parent element.
