### ISSUE TITLE
Dynamically change required directive of input does not revalidate form.

### ISSUE THREAD

**Issue by Cododoc** [dart-lang/angular#1674]
Hello!
I found a problem, that was closed some time ago (#792).
Example code to show problem:
```
@Component(
  selector: 'my-app',
  template: '''
    <button type="button" (click)="isRequired = !isRequired">isRequired = {{isRequired}}</button>

    <input #textValueCtrl="ngForm" type="text" [required]="isRequired" [(ngModel)]="textValue">

    control valid = {{textValueCtrl.valid}}
  ''',
  directives: [formDirectives],
)
class AppComponent {
  bool isRequired = true;

  String textValue;
}
```

When you click button valid state should change.

---

Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"
angular_forms 2.0.0
angular 5.0.0
Chrome

**Comment by matanlurey** [comment]
It is not supported to change whether an element is required:
https://github.com/dart-lang/angular/issues/792

**Comment by alorenzen** [comment]
We did add support for changing the required value dynamically. However, it is a known issue that all validators are only run when the underlying Control requests them. Thus, just changing the state in the validator does nothing until the user attempts to change the value of a field.

This would require a more significant change in the way angular forms works. We've had some initial thoughts on refactors here, but nothing to the point that would actually fix this issue.
