### ISSUE TITLE
Directive usages are not rebuilt correctly when those directives are changed and referenced through nested import/exports

### ISSUE THREAD

**Issue by rich-j** [dart-lang/angular#1676]
The Angular build `pub run build_runner serve` doesn't correctly recognize/rebuild directive usages when those directives are changed and are referenced through nested imports and exports.

Top-level library `package:proj/lib.dart` exports a lower-level library:

    export 'package:proj/src/directives.dart';

The lower-level common library `src/directives.dart` declares a list of reusable directives:

    import 'reusable.dart';
    const List<Object> appDirectives = [ Reusable ];

An application component imports the **top-level library** to reference the nested exported `Reusable` component:

    import `package:proj/lib.dart`;
    @Component(
      directives: const [appDirectives]
      ... template references the `reusable` component ...

The above works with a clean complete build. Problems occur when working on directives in the common library. Adding a new directive (e.g. `Reusable2`) to the `appDirectives` list usually isn't found by application components without "prodding" (e.g. clean build, direct reference). Adding Angular "lifecycle events" (`AfterChanges`, `OnDestroy`) to an existing directive (e.g. `Reusable`) are also not recognized without "prodding". Note that code changes to the common library directives are compiled by Dart. What seems to be missing is recompiling of application components' Angular templates that reference directive lists referenced through nested references.

A workaround is to flatten the import hierarchy - replace the top-level `export` with the contents of the lower-level referenced library (with appropriate path adjustments). Changes to directives are now correctly picked up by the application components.

Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "macos_x64"
angular: '^5.1.0'

**Comment by jakemac53** [comment]
It sounds like somehow the exported library isn't being treated as a dependency as it should - we can try and see if we can reproduce it.

**Comment by jakemac53** [comment]
We should move this to the build repo yes. This slipped through the cracks with the holidays etc but we should be able to take a look soon.

**Comment by matanlurey** [comment]
Closing due to lack of action.
