### ISSUE TITLE
User request for casts & is checks in templates

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular#1677]
Now that we support exports, this should be fairly easy to support (right?)

Per customer:

> Is it supported to run type check or type cast in dart template?
>
```
<cat-component *ngIf="animal is Cat" 
                           [catTail]="(animal as Cat).tail">
<cat-component>
```
> 
> Where in dart file, 
```
Animal animal = Cat();

class Cat implements Animal {...}
```
> in Dart template?

Source: https://groups.google.com/a/dartlang.org/forum/#!topic/analyzer-discuss/hjSI1Te_OKs

**Comment by matanlurey** [comment]
No, it is not supported.

**Comment by MichaelRFairhurst** [comment]
Oof, yes, sorry. To clarify I told them it's not but then also filed this request on their behalf. Not sure how important it is to them exactly, but I think at least somewhat important based on them taking the time to find an official place to ask

**Comment by YiqunJi** [comment]
It would be great to support it. 

This comes from a real example:
Model:
Cat implements Animal, HasLegs, HasTail, Built<Cat,CatBuilder> {}
Dog implements Animal, HasLegs, HasTail, Built<Cat,CatBuilder> {}
Fish implements Animal, HasTail, Built<Fish, FishBuilder> {}
Where 
@BuiltValue(instantiagble: false, nestedBuilders: false)
class HasLegs {
  int get legsCount;
}

Dart:
class AnimalView<T extends Animal> {
  @Input()
  set Animal(Animal animal) => builder = _createBuilder(animal);
 
  T builder;

  AnimalBuilder _createBuilder(Animal animal) {
    if (animal is Cat)  return (animal as Cat).toBuilder;
    if (animal is Dog)  return (animal as Dog).toBuilder;
    if (animal is Fish)  return (animal as Fish).toBuilder;
   }
}

Without this feature,  feel impossible to access simply like
<material-legs  *ngIf="animal is Cat || animal is Dog"
                         [(ngModel)]="builder.legsCount">
</material-legs>

Therefore, a lot more code has to be added to bypass this issue.

**Comment by matanlurey** [comment]
We don't plan to support this.

We will have an updated roadmap and description of our supported syntax sometime this Q.
