### ISSUE TITLE
Dartdevc throws when trying to parse syntactically incorrect two-way binding expression

### ISSUE THREAD

**Issue by szepeshazi** [dart-lang/angular#1681]
Using
* Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"
* Angular 5.1

when dartdevc compiler encounters the following, syntactically invalid code (closing bracket of two-way binding is misplaced):

`<material-toggle [label]="label" [(checked)="enabled"]></material-toggle>`

it throws the following exception:

```
[SEVERE] angular on lib/src/admin/library_plan/components/library_plan_edit/library_plan_edit.dart (cached):
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
type 'ParsedBananaAst' is not a subtype of type 'EventAst'
```

**Comment by leonsenft** [comment]
Thanks for reporting!
