### ISSUE TITLE
Failed to construct 'ResizeObserver': The callback provided as parameter 1 is not a function.

### ISSUE THREAD

**Issue by shenkaige** [dart-lang/angular#1684]
* [x]  Dart SDK Version 2.2.0-dev.0.0
* [x] AngularDart Version ^5.1.0
* [x] build on macOS
* [x] Browser Chrome and Safari

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  angular_router: ^2.0.0-alpha+20
  ng_bootstrap: any

dev_dependencies:
  angular_test: ^2.1.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^0.4.4
  test: ^1.5.1

----
when I use "webdev server" anything is ok.But the "webdev build -r" output files can't work fine after angular upgrade to v5.1. I got the error msg  like this:

EXCEPTION: Error: Failed to construct 'ResizeObserver': The callback provided as parameter 1 is not a function.
STACKTRACE: 
TypeError: Failed to construct 'ResizeObserver': The callback provided as parameter 1 is not a function.

-----

**Comment by shenkaige** [comment]
make the checkbox checked. :p

**Comment by shenkaige** [comment]
the project work fine when I remove all ResizeObserver function relative code.

    resizeObserver = new ResizeObserver((List<ResizeObserverEntry> entries, ResizeObserver observer){
      canvas.width = reputationRootEl.clientWidth;
      //canvas.height = reputationRootEl.clientHeight;
      print("observer resize ...");
      draw();
    });
    resizeObserver.observe(reputationRootEl);
`

**Comment by matanlurey** [comment]
`ResizeObserver` is not part of AngularDart, so we aren't able to offer support here.
