### ISSUE TITLE
Add reactive form

### ISSUE THREAD

**Issue by xvrh** [dart-lang/angular#1685]
Angular/typescript has 2 ways to handle forms: template-driven (`ngModel`) and reactive-form (`FormControl`): https://angular.io/guide/forms-overview

Angular/Dart seems to implements only the template-driven forms with `ngModel`.

The `ControlForm` approach seems to have some advantages (it seems simpler).
Any plan to add it to Angular/Dart?

**Comment by matanlurey** [comment]
AngularDart also has an imperative model for forms:
https://webdev.dartlang.org/api?package=angular_forms
