### ISSUE TITLE
Can angulardart be used to perfectly develop flutter?

### ISSUE THREAD

**Issue by DreamPWJ** [dart-lang/angular#1690]
Can angulardart be used to perfectly develop flutter?

**Comment by kevmoo** [comment]
Could you explain a bit more here, @DreamPWJ ?

**Comment by DreamPWJ** [comment]
I like angualr and am used to dislike dart. I want to use angualr for cross-platform development. May I ask whether angular dart code can run perfectly in flutter?@kevmoo
