### ISSUE TITLE
Can we use ngProjectAs for projecting through the layers

### ISSUE THREAD

**Issue by bunopus** [dart-lang/angular#1691]
Hello. Few questions about `ngProjectAs`

### Preconditions
**[Source code](https://github.com/bunopus/angular-dart-ngprojectas)**

I want to pass something through the layers with ng-content. Main idea is to pass some attribute to nested ng-content with renaming. Here, in main component, i pass two spans to `child-component`, one with attribute `primary-span`.

```dart
import 'package:angular/angular.dart';
import 'package:check_projection/src/child_component.dart';

@Component(
  selector: 'my-app',
  template: '''
    <child-component>
      <span primary-span>This is main span!</span><br>
      <span>Ordinary span</span>
    </child-component>
  ''',
  directives: [ChildComponent],
)
class AppComponent {
}
```
In `child-component` i select one span (`primary-span`) and pass it further to `grand-child-component` but with another attribute `span-content`
```dart
import 'package:angular/angular.dart';

@Component(
  selector: 'child-component',
  template: '''
      <grand-child-component><ng-content ngProjectAs="[span-content]" select="[primary-span]"></ng-content></grand-child-component>
  ''',
  directives: [],
)
class ChildComponent {
}
```

And in the `grand-child-component` i just select `span-content`
```dart
import 'package:angular/angular.dart';

@Component(
  selector: 'grand-child-component',
  template: '<div><ng-content select="span-content"></ng-content></div>',
  directives: [],
)
class GrandChildComponent {
}
```
### Questions
1. Can we use `ngProjectAs` and rely on it? I'm asking because there is no documentation about it https://github.com/dart-lang/angular/issues/422. And we actually found it by accident. Is it safe to use it in production code?
2. What about `ng-container`? According to this [article](https://medium.com/claritydesignsystem/ng-content-the-hidden-docs-96a29d70d11b), it works for typescript version, but for AngularDart i get an error
```bash
line 1, column 44 of ChildComponent: Only '*' bindings are supported on <ng-container>
   <grand-child-component><ng-container ngProjectAs="[span-content]" select="[primary-span]"></ng-container></grand-child-component>
```

**Comment by leonsenft** [comment]
1. Yes it's safe to use in production, we have no plans to remove this.
2. The implementation details and thus capabilities of `<ng-container>` differ slightly between Angular and AngularDart. In AngularDart `<ng-container>` doesn't support `ngProjectAs`.
