### ISSUE TITLE
Unable to run demo app as Firebase webapp

### ISSUE THREAD

**Issue by bostone** [dart-lang/angular#1692]
I'm having issue trying to run demo app on the Firebase web (locally). Here are the steps:

1. Generate demo project following angulardart guide
2. Run `webdev serve` to verify that code works (it does)
3. Create Firebase web starter project in the same top directory and run `firebase serve --only hosting` to verify that the default Firebase code shows at `localhost:5000` (it does serving `public/index.html`)
4. Modify firebase.json to run app from `web` folder rather than `public`. Simply set `"public": "web"`
5. Now run `webdev build` just to make sure that the dart code is built
6. Run `firebase serve --only hosting` again and goto `localhost:5000`

At this point you will see `Loading...` and`Uncaught SyntaxError: Unexpected token <` message in console. That is because generated `main.dart.js` is a not a JS file but exact copy of index.html which starts with `<!DOCTYPE html>`

* Dart SDK Version (`art VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "macos_x64"`)
* AngularDart Version (`MASTER`)
* macOS
* Chrome, Safari, Firefox

**Comment by bostone** [comment]
It works if I point Firebase to `"public": "build"` but I'm not sure if that is the right solution

**Comment by matanlurey** [comment]
> It works if I point Firebase to `"public": "build"` but I'm not sure if that is the right solution

It is. That's the default output directory. You could `webdev build <some arg?>` to write it to `web` instead, but FWIW, you did everything fine.
