### ISSUE TITLE
unable to build toh* examples

### ISSUE THREAD

**Issue by starbugs2008** [dart-lang/angular#1698]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:
name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0

* [ ] Dart SDK Version (`dart --version`)
* [ x] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
* [ x] Whether you are using Windows (if applicable)
* [ ] Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
* [ ] Any other packages or constraints we should know about

Missing some or all of the above might make the issue take longer or be impossible to act on.

----

INFO] Checking for unexpected pre-existing outputs. completed, took 2ms
[SEVERE] angular on package:angular/src/core/di.dart:

FileSystemException: Creation failed, path = 'c:\dev\dart\toh-4\.dart_tool/build/generated/angular/lib/src' (OS Error: The system cannot find the path specified.
, errno = 3)
[SEVERE] angular on package:angular/src/core/application_tokens.dart:

FileSystemException: Creation failed, path = 'c:\dev\dart\toh-4\.dart_tool/build/generated/angular/lib/src' (OS Error: The system cannot find the path specified.
, errno = 3)
[SEVERE] angular on package:angular/src/platform/dom/events/dom_events.dart:

FileSystemException: Creation failed, path = 'c:\dev\dart\toh-4\.dart_tool/build/generated/angular/lib/src/platform' (OS Error: The system cannot find the path specified.
, errno = 3)
[SEVERE] angular on package:angular/src/core/linker/app_view_utils.dart:

FileSystemException: Creation failed, path = 'c:\dev\dart\toh-4\.dart_tool/build/generated/angular/lib/src/core/linker' (OS Error: The system cannot find the path specified.
, errno = 3)
[SEVERE] angular on package:angular/src/bootstrap/modules.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
AssetNotFoundException: angular_tour_of_heroes|.dart_tool/build/generated/angular/lib/src/core/di.ng_placeholder
[SEVERE] angular on package:angular/src/bootstrap/modules.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
AssetNotFoundException: angular_tour_of_heroes|.dart_tool/build/generated/angular/lib/src/core/application_tokens.ng_placeholder
[WARNING] No actions completed for 15.1s, waiting on:
  - pageloader on test/app_test.dart

[WARNING] No actions completed for 15.1s, waiting on:
  - pageloader on test/app_test.dart

[WARNING] No actions completed for 15.1s, waiting on:
  - pageloader on test/app_test.dart

[WARNING] No actions completed for 15.0s, waiting on:
  - pageloader on test/app_test.dart

[WARNING] No actions completed for 15.1s, waiting on:
  - pageloader on test/app_test.dart

[WARNING] No actions completed for 15.1s, waiting on:
  - pageloader on test/app_test.dart

[WARNING] No actions completed for 15.1s, waiting on:
  - pageloader on test/app_test.dart

-----

**Comment by chalin** [comment]
This issue was moved to dart-lang/site-webdev#1884
