### ISSUE TITLE
HN PWA example app has empty lists

### ISSUE THREAD

**Issue by gc435** [dart-lang/angular#1699]
Using http://hnpwa.dartlang.org in Chrome 71.0.3578.99 on Android 9 sometimes results in empty article lists:

1. Go to **Top -> Next** and then pull to refresh.  The article list will be blank.
2. Go to **Top -> Next** and then click on an article.  Return to the PWA, and the article list will be blank.

Issue #1100 might be related.

**Comment by leonsenft** [comment]
Thanks for reporting! There was a bug with our prefetching logic. Fix has landed internally and will be deployed on next sync.

**Comment by gc435** [comment]
When will the next sync happen?  As of today, I still experience this issue.

**Comment by leonsenft** [comment]
We synced the fix, but haven't deployed the update yet. I'll do so tomorrow!

**Comment by leonsenft** [comment]
Fix deployed, should be working again. Thanks for filing.
