### ISSUE TITLE
`Component.preserveWhitespace = false` works inconsistently

### ISSUE THREAD

**Issue by kapod** [dart-lang/angular#1700]
While migrating our product to Ng5 from Ng4 we faced with deviations in templates rendering: various elements noticeably moved. The reason — changes in the way flag `preserveWhitespace: false`  works (ref issue https://github.com/dart-lang/angular/issues/804)

```
<footer
  class="some-component__footer">

  <button
    foo-component
    [someInput1]="input1"
    [someInput2]="input2"
    [someInput3]="input3"
    (click)="someClick()"
    class="some-component__control">
    {{ title1 }}
  </button>

  <button
    foo-component
    [someInput1]="input1"
    [someInput2]="input2"
    [someInput3]="input3"
    (click)="someClick()"
    class="some-component__control">
    {{ title2 }}
  </button>

  <button
    foo-component
    [someInput1]="input1"
    [someInput2]="input2"
    [someInput3]="input3"
    (click)="someClick()"
    class="some-component__control">
    {{ title3 }}
  </button>
</footer>
```

With changes in Angular 5 we get unexpected spaces.

<img width="539" alt="whitespace" src="https://user-images.githubusercontent.com/8384211/50560757-015f2e00-0d15-11e9-8c51-e11507140986.png">

Yes, there are some known workarounds, how to get rid of them — https://davidwalsh.name/remove-whitespace-inline-block And this is either a template change or css hacks

Changing in templates leads to readability degradation. CSS hack by using `font-size: 0;`  is obviously bad solution hack — all child elements inherit zero font-size, and that leads to various unwanted side effects.

And yes, we have few templates with inline text, where it is important to preserve white spaces. And in that cases we are using `&ngsp;` / `&nbsp;` But in most cases, text content is transmitted through variables `{{ someText }}`  and we did not face the problem with a large number of `&ngsp;`

On the other hand, in general, template implements part of user interface. `button`, `input` and `span` are common in such templates, even if they are not the part of inline text. All kinds of forms are good example. 

We develop really big app, there is more than 2000 templates at this moment. And we have strict design system and UI guidelines, so we can not rely on magic values of whitespace size (text node) for elements positioning. Codestyle and the way developers (a lot of them) work with templates are also very important for us. We even have linters for templates. And we want templates to be readable and ease to support.

We agree with https://github.com/dart-lang/angular/issues/804#issuecomment-363217553 — it is better to insert required spaces by using `&ngsp;` than use any hacks.

Current implementation of `preserveWhitespace: false`  ruins our codestyle and ui-development practices.

So we believe, that you need to listen to the community and make the preserveWhitespace setting more flexible, to satisfy different needs in different projects. Examples of some proposals:
https://github.com/angular/angular/issues/21049#issue-282536622
https://github.com/dart-lang/angular/issues/804#issuecomment-360986971

**Comment by DisDis** [comment]
@matanlurey fyi

**Comment by meowsha** [comment]
@ninachen @rainboxx I saw you have similar opinion in #804. You might be interested in this one too

**Comment by ninachen** [comment]
> We agree with [#804 (comment)](https://github.com/dart-lang/angular/issues/804#issuecomment-363217553) — it is better to insert required spaces by using &ngsp; than use any hacks.

Since I'm being cited :), I think the intent of my comment (although I don't entirely remember) was that, if I am forced between an either/or choice of having preserveWhitespace behave the way it did in #804 vs. changing to be more "HTML-like" in that newlines could cause spaces between DOM elements, I would have chosen the former.

That said, the real options were not quite as binary as that, and I believe the AngularDart team had come up with a nice middle ground solution (for #804).

I don't remember if the behavior reported here is unexpected or not for the current implementation of `preserveWhitespace: false`.

**Comment by bunopus** [comment]
Hello, @matanlurey.
You have tagged this issue as "intended." Does this mean that we shouldn't hope that in the future we will return to the question of the non-binary option for 'preserveWhitespace'? I believe this will be very useful for users who want to have more control over their templates.
