### ISSUE TITLE
angular_cli generates projects with a buggy version of build_runner (the version 0.9.2). 

### ISSUE THREAD

**Issue by denis-beurive** [dart-lang/angular#1703]
The CLI tool `angular_cli` generates projects with a buggy version of `build_runner` (the version 0.9.2). See #79 and #1696. This can lead to waste of time.

It should be nice to have an option like :

    ngdart new myapp --with-last-stables

Or (for one component only):

    ngdart new myapp --with build_runner:last

Note : the point is that there is no reason to install a buggy component.

I use the version [0.2.0](https://pub.dartlang.org/packages/angular_cli#-versions-tab-) of `angular_cli` (see at the end of this post)

Demonstration:

    denis@lab /tmp $ ngdart new myapp
    INFO: Saving ./myapp/web/index.html
    INFO: Saving ./myapp/web/main.dart
    INFO: Saving ./myapp/web/styles.css
    INFO: Saving ./myapp/analysis_options.yaml
    INFO: Saving ./myapp/.gitignore
    INFO: Saving ./myapp/pubspec.yaml
    INFO: Saving ./myapp/lib/app_component.dart
    INFO: Saving ./myapp/lib/app_component.html

    denis@lab /tmp/myapp $ pub get
    Resolving dependencies... (15.1s)
    + analyzer 0.32.6 (0.34.1 available)
    + angular 5.0.0 (5.2.0 available)
    + angular_ast 0.5.6 (0.5.8 available)
    + angular_compiler 0.4.0 (0.4.2 available)
    ...
    + yaml 2.1.15
    Downloading protobuf 0.10.6...
    Changed 84 dependencies!
    Precompiling executables... (30.2s)
    Precompiled build_runner:graph_inspector.
    Precompiled build_runner:build_runner.
    Precompiled test:test.

    denis@lab /tmp/myapp $ pub deps | grep build_runner
    |-- build_runner 0.9.2
    |   |-- build_runner_core 0.2.2+2

* [x] Dart SDK Version (`dart --version`):   ̀Dart VM version: 2.1.0 (Unknown timestamp) on "linux_x64"`
* [x] AngularDart Version: `5.0.0`
* [x] Whether you are using Windows, macOS, or Linux: `linux`

`angular_cli` version:

    denis@lab ~/Documents/github/angulardart-playground/forms $ pub global activate angular_cli
    Package angular_cli is currently active at version 0.2.0.
    Resolving dependencies... (4.5s)
    + analyzer 0.32.6 (0.34.1 available)
    + angular_cli 0.2.0
    + ansicolor 1.0.2
    + args 1.5.1
    + async 2.0.8
    + charcode 1.1.2
    + collection 1.14.11
    + convert 2.1.1
    + crypto 2.0.6
    + csslib 0.14.6
    + front_end 0.1.4+2 (0.1.8 available)
    + glob 1.1.7
    + html 0.13.3+3
    + kernel 0.3.4+2 (0.3.8 available)
    + logging 0.11.3+2
    + meta 1.1.7
    + mustache 1.0.2
    + package_config 1.0.5
    + path 1.6.2
    + plugin 0.2.0+3
    + resource 2.1.5
    + source_span 1.4.1
    + string_scanner 1.0.4
    + typed_data 1.1.6
    + utf 0.9.0+5
    + watcher 0.9.7+10
    + yaml 2.1.15
    Precompiling executables... (14.1s)
    Precompiled angular_cli:ngdart.
    Installed executable ngdart.
    Activated angular_cli 0.2.0.

**Comment by leonsenft** [comment]
The `angular_cli` tool isn't a part of the AngularDart framework, nor is it maintained by any of its contributors. That project lives [here](https://github.com/google/angular_cli).
