### ISSUE TITLE
Compilation time and high memory usage with webdev

### ISSUE THREAD

**Issue by hkoktay** [dart-lang/angular#1704]
## Summary
Starting `webdev serve` or `build_runner serve` with a default stagehand generated web-angular project takes 4-5 minutes and uses the whole system memory, which makes my desktop unresponsive. Also after adding a html tag to `app_component.html` and saving the file, angular takes 7 sec to recompile and reloading the browser tab takes 3-6 sec. The main problem is the high memory usage.

To reproduce create a project with `stagehand web-angular` and start the development server with `webdev serve` or `pub run build_runner serve`.

## Additional information
The development webserver starts with two dart processes and after some time spawns multiple dart processes using the rest of remaining system memory. I guess these are dart isolates utilising all processors to speed up compilation. Together with vscode and chrome the amount of memory used is around 7.5GB and the amount of free memory left is 100-150MB - according to `free -m`. The additional dart processes are alive after the end of the compilation; so I'm stuck with just 100-150MB memory.

Dart version and dependency versions:
```
  dart vm version: 2.1.0 linux_x64
  angular version: ^5.2.0
  angular_components: ^0.11.0
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.4
  build_web_compilers: ^1.0.0
  test: ^1.5.1
  stagehand: 3.1.5
```

CPU, OS, Memory and Desktop Environment:
```
- CPU model name: AMD FX(tm)-8300 Eight-Core Processor
- OS: Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27)
- RAM: 8GB
- Gnome 3.22.2
```

I looked at the `track-performance` visualization and most of the build time is spend on these files: `test/app_test.dart`, `web/main.dart` and `test/app_test.dart.browser_test.dart`. 

I think such high memory usage is a bug but I could be wrong. Has anybody else this issue and can confirm this? Is this kind of compilation time and memory usage expected?

**Comment by matanlurey** [comment]
This should be filed elsewhere (on webdev, build, etc).
