### ISSUE TITLE
Compiler error: "Invalid constant value" when importing a constant from a parent folder

### ISSUE THREAD

**Issue by cedx** [dart-lang/angular#1707]
* Dart SDK : 2.1.0 (Unknown timestamp) on "linux_x64"
* AngularDart : 5.2.0
* OS : Ubuntu 18.10
* Other packages : `build_runner` 1.1.2, `build_version` 2.0.0, `build_web_compilers` 1.0.0

I don't have any idea if it's a problem with Angular or rather with the `build` system.
I'm using the `build_version` package to generate a file `lib/src/version.dart` that contains:

```dart
// Generated code. Do not modify.
const packageVersion = '1.0.0';
```

My Angular app is located in the `lib/src/client` folder. I'm injecting the `packageVersion` constant in a component template by using `@Component.exports` property, like this:

```dart
import '../version.dart';

@Component(
  exports: [packageVersion],
  selector: 'my-application',
  template: '<div>{{packageVersion}}</div>'
)
class AppComponent {}
```

When I try to compile the application (with `webdev serve` or `webdev build`), I always get this error:

```
Compiling @Component-annotated class "AppComponent" failed.
lib/src/client/app_component.dart: Invalid constant value.
packageVersion
^^^^^^^^^^^^^^
```

If I move the `version.dart` file next to the component file, and use `import 'version.dart';`, the application compiles as expected.

EDIT : the issue is really with `@Component.exports`. Using the `packageVersion` constant in a different context (for example, a property of the component returning this value) does not trigger the compiler error.

**Comment by jbdeboer** [comment]
@cedx Bonus points if you can reproduce this in a "compileExcepts" within the invalid_component_test integration test.  Most likely we are not following ".." correctly in the compiler and have no information about packageVersion.

**Comment by matanlurey** [comment]
Closing due to lack of response.

**Comment by cedx** [comment]
@matanlurey What kind of response did you expect? No question was asked, and there is no trace of `compileExcepts` or `invalid_component_test` in the repository.

**Comment by jbdeboer** [comment]
I was referring to https://github.com/dart-lang/angular/blob/master/_tests/test/compiler_integration/invalid_component_test.dart

I would also be happy with a pointer to a demo repository that exhibits this behaviour.

**Comment by cedx** [comment]
Thanks for the explanation. Unfortunately I haven't enough time to contribute (and this issue is very minor).
