### ISSUE TITLE
Investigate using DocumentFragment

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#1708]
Consider this example where the inner embedded view has no root node since it consists of only text:
https://github.com/dart-lang/angular/blob/a217e0a34213dd10ecfefcb49733a508e628ee25/_goldens/test/_files/interpolation.dart#L66-L70

Today we omit the following code to initialize the inner embedded view:
https://github.com/dart-lang/angular/blob/a217e0a34213dd10ecfefcb49733a508e628ee25/_goldens/test/_files/interpolation.template.golden#L530-L537

Notice the need to pass a list of top-level nodes to `init()`. This differs from embedded view with a single root level node which can be passed to `init0()`.

This led to the idea that a `DocumentFragment` could be passed in place of a list of nodes to handle the former case, thus unifying both under a single API. Unfortunately this approach might not work, since we need references to all of the top level nodes of an embedded view so that they can be removed when the view is removed.

However there still could be cases where `DocumentFragment` could be used. Historically appending nodes to a fragment was faster than appending to the DOM. Depending on whether this is still the case in the latest browser versions, it could be beneficial for `AppView.build()` to construct a fragment, which can later be appended.

Imagine if the root `build()` call recursively builds a hierarchy of fragments, which are appended together, before the root finally appends itself to the DOM. This would result in only a single DOM insertion for the initial build, rather than one per node in your app.

**Comment by matanlurey** [comment]
We decided not to investigate more here.
