### ISSUE TITLE
Inconsistent description in CHANGELOG (preserveWhitespace)

### ISSUE THREAD

**Issue by bunopus** [dart-lang/angular#1712]
Hello! 
There are typo or error in https://github.com/dart-lang/angular/blob/master/angular/CHANGELOG.md#breaking-changes-2, in the _breaking changes_ section for 5.0.0 version:
>The default for \@ Component(preserveWhitespace: ...) is now true. Many improvements were put into the whitespace optimziation in order to make the results easier to understand and work around.

It's saying that `preserveWhitespace` now true by default, but actually it's false

Thanks!

**Comment by matanlurey** [comment]
Thanks!
