### ISSUE TITLE
EXCEPTION: NoSuchMethodError: method not found: 'db' on null

### ISSUE THREAD

**Issue by vintzl** [dart-lang/angular#1721]
* Dart SDK Version 2.1
* AngularDart Version 5.2.0

When I build for release, I get this error:
 > EXCEPTION: NoSuchMethodError: method not found: 'db' on null
STACKTRACE: 
TypeError: Cannot read property 'db' of null

The code does not contain any `db` mention, but I can see that `main.dart.js` does.

**Comment by matanlurey** [comment]
This is nothing related to AngularDart, unfortunately.
