### ISSUE TITLE
Adding filtering value capabilities on Form Control

### ISSUE THREAD

**Issue by e-belair** [dart-lang/angular#1729]
Hi, It should be useful to add a filter into the control configuration, so we could filter the value before the validation process like this example:

```dart
// An example to automatically convert value to uppercase format
var myForm = FormBuilder.controlGroup({
  'name': ['', Validators.pattern('[A-Z]+'), Filters.toUppercase]
});
```

**Comment by matanlurey** [comment]
We don't plan to add this, thanks for the initiative though!
