### ISSUE TITLE
Add ability to put index.html in separate location from everything else

### ISSUE THREAD

**Issue by olfek** [dart-lang/angular#1735]
Please add ability to put the `index.html` file in separate location from everything else.

A part of being able to do this, is to add the functionality of `--deploy-url` that the `ng build` command has with the normal Angular to `webdev` build tool, or if that isn't possible, create a dedicated Angular Dart build tool that has this functionality.

Unrelated issue, but another reason why there should be a dedicated Angular Dart build tool, is so we can watch files without having to serve them. This is especially useful if we are using another piece of software to serve files, instead of `webdev`. For my project for example, I served the files using Django, and just so the files were being watched and updated while I developed, I also had to start the `webdev` server.

```
* Dart VM version: 2.2.0 (Unknown timestamp) on "linux_x64"
* Angular 5.2.0
```

[see this comment for more info](https://github.com/angular/angular-cli/issues/2688#issuecomment-466818183)

PS. Moving back to the normal Angular for now.

**Comment by leonsenft** [comment]
Angular has no concern for where your `index.html` files live. The Angular builders only concern themselves with your component files (e.g. Dart components, CSS styles, and HTML templates), which are compiled into `.template.dart` and `.css.dart` files.

These Dart files are then compiled to JavaScript (by https://pub.dartlang.org/packages/build_web_compilers), which you're free to include as a `<script>` from any HTML files you would like.

Have you read https://webdev.dartlang.org/tools/webdev? Both `webdev` and `build_runner` (the tool which `webdev` wraps) support deploying and serving to a directory of your choice. If I've misinterpreted your request, or these tools lack the functionality you desire, I suggest filing an issue with the appropriate repository.

- https://pub.dartlang.org/packages/webdev
- https://pub.dartlang.org/packages/build_runner
