### ISSUE TITLE
is it supported angular 8.x ?

### ISSUE THREAD

**Issue by find456789** [dart-lang/angular#1737]
i have a plan that to learning dart-angular

 

😊
 thank you very much

**Comment by leonsenft** [comment]
Hi! It would appear that you're asking about the latest version of https://github.com/angular/angular, which is implemented in TypeScript and altogether a different project. AngularDart has diverged from Angular and is not simply a port. While the two share many similarities, there's no longer any correlation in the versioning between the two.

**Comment by find456789** [comment]
thank you very much
