### ISSUE TITLE
ng-include doesn't work

### ISSUE THREAD

**Issue by nasserkhosravi** [dart-lang/angular#1741]
Dart: 2.1.0
Angular: ^5.2.0
OS: macos_x64 high sierra
Browser: Chrome v 72.0.3626.121 (Official Build) (64-bit)

I'm trying to include a template in my component but nothing show:
File structure:
hawasil.html
project_detail.dart
project_detail_pattern.html

project_detail.dart
```
@Component(
    selector: 'hawasil',
    templateUrl: 'hawasil.html',
    directives: [NgFor, NgIf])
class HawasilComp {
}
```

hawasil.html
```
<div ng-include="'project_detail_pattern.html'"></div>
```

Is angular dart support ng-include or I'm in wrong way?
thanks.

**Comment by leonsenft** [comment]
No it's not supported. If you want to dynamically load content, you can read about [imperative component loading](https://github.com/dart-lang/angular/blob/master/doc/faq/component-loading.md).
