### ISSUE TITLE
Links to migration guide are failing

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/angular#1745]
I know of two links to https://github.com/dart-lang/angular/blob/master/doc/router/migration.md, which no longer exists:

* https://github.com/dart-lang/angular/blob/master/angular_router/CHANGELOG.md
* https://github.com/dart-lang/angular/blob/master/doc/migrating-to-v5.md (which is mirrored in https://webdev.dartlang.org/angular/note/migrating-to-v5)

More info: https://github.com/dart-lang/site-webdev/issues/1917

**Comment by matanlurey** [comment]
We don't plan to track any updates to the site from our repository going forward.

(This repo is only about docs on our own site)

**Comment by kwalrath** [comment]
This bug is about broken links within your own docs, not about webdev.dartlang.org.

**Comment by matanlurey** [comment]
Realistically we are not going to be tackling docs on the router externally, so I'm closing to reflect that.

**Comment by kwalrath** [comment]
Not a problem for me. You might want to remove the link, though, just so people don't try to click it.
