### ISSUE TITLE
Support subclassing @Component() annotation

### ISSUE THREAD

**Issue by pschiffmann** [dart-lang/angular#1778]
The Angular compiler will only recognize annotations on component classes if they are exactly of type `Component`. I would like to request that Angular also recognizes annotations of subtypes of `Component`.

Here is my use case:

```dart
class GenericEditorComponent extends Component {
  const GenericEditorComponent(String selector)
      : super(
          selector: selector,
          templateUrl: 'generic_editor_component.html',
          styleUrls: const ['generic_editor_component.scss.css'],
          directives: const [
            coreDirectives,
            formDirectives,
          ],
          exports: const [InputType],
        );
}

@GenericEditorComponent('user-editor')
class UserEditor extends GenericEditorBase<User> {
  @override
  final editorDefinition = const {
    'name': 'text',
    'email': 'email',
    'active': 'checkbox',
  };
}

@GenericEditorComponent('address-editor')
class AddressEditor extends GenericEditorBase<Address> {
  @override
  final editorDefinition = const {
    'street': 'text',
    'postalCode': 'text',
    'country': 'text',
  };
}
```

Background: I'm working on an application with lots of models that each need their own edit form, but the forms are very simple, so I can generate the individual `<input>`s from a simple list of properties. But right now, I have to copy&paste the `@Component()` annotation to every `GenericEditorBase` subclass, which is more boilerplate code than the actual component.

If Angular uses package source_gen to find the annotated classes, it might just be change from [LibraryReader.annotatedWithExact](https://pub.dartlang.org/documentation/source_gen/latest/source_gen/LibraryReader/annotatedWithExact.html) to [LibraryReader.annotatedWith](https://pub.dartlang.org/documentation/source_gen/latest/source_gen/LibraryReader/annotatedWith.html).

**Comment by matanlurey** [comment]
We don't plan to support this, intentionally, as it makes it very difficult to change in the future.
