### ISSUE TITLE
latest package angular 5.3.0 requires a dev release of pub

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/angular#1780]
From the dartdoc generation logs:
```
Dartdoc generation for angular 5.3.0

runtime: 2019.04.02
toolEnv Dart SDK: 2.2.0
runtime Dart SDK: 2.2.0
pana: 0.12.14
dartdoc: 0.28.2
flutter: 1.4.7
usesFlutter: false
started: 2019-04-05T18:39:23.151523Z

Running pub upgrade:
STDOUT:
MSG : Resolving dependencies...

STDERR:
ERR : The current Dart SDK version is 2.2.0.
    | 
    | Because angular requires SDK version >=2.2.1-dev.3.0 <3.0.0, version solving failed.

Dependencies were not resolved, skipping dartdoc.

No content found!

entry created: a7f37a3d-7d16-4e4a-8fa7-e0b55a48bcbe

completed: 2019-04-05T18:39:24.257563Z
```

This means that dartdoc documentation is not available on pub.dartlang.org.

I only noticed because it's one of the few packages we monitor :)

I would suggest you publish such releases as pre-releases (5.3.0-dev) until the required dart-sdk is published. But if you want users to be installing -dev versions of the dart-sdk, then that's probably also fine. Since you have a documentation url k your pubspec and host your own docs. In this case we should probably just stop monitoring your package :)

**Comment by srawlins** [comment]
@jonasfj what do you mean by "monitoring"?

**Comment by jonasfj** [comment]
We have an alert that fires if dartdoc for package angular isn't available..

I think we have that because we have to pick some package to monitor, and we consider angular an important package :)

But if you're happy doing your own docs and don't care that generation on pub.dartlang.org is failing then maybe it's no big deal.

However, other packages with a dependency on angular 5.3.0 won't get docs either... Because we can't generate for those. Or maybe we should consider fixing this, I just doubt it's a quick 2 line fix to support arbitrary dart-sdk versions.

**Comment by leonsenft** [comment]
This also causes issues with pana (the package which scores Pub releases): https://pub.dartlang.org/packages/angular#-analysis-tab-

The issue is that we develop internally first, often making use of the latest SDK features. So when we publish, we set our minimum SDK constraint to the corresponding release used internally (which is almost always a dev release) to guarantee there are no SDK compatibility issues externally.

A few ideas:

1. Should we wait for dartdoc and pana to accommodate our SDK constraints before publishing?

1. Should we work with the dartdoc and pana maintainers to ensure they support the latest internal SDK release to avoid this problem for all internally developed packages?

1. Should we only publish with stable SDK releases? This is tricky, because it either means
    1. our internal changes need to be backwards compatible with the latest SDK release, which we don't know until we push to GitHub, or
    1. our releases get blocked until the next stable SDK release, which could otherwise unnecessarily delay releases.

1. If we take no action, will Pub know to generate documentation and score our release again once those tools support our SDK constraint? I'm guessing not today, but perhaps Pub could support an API to trigger documentation generation and scoring?

**Comment by jonasfj** [comment]
>1.  Should we wait for dartdoc and pana to accommodate our SDK constraints before publishing?

For the most part they do. They do sometimes need tweaks for the latest SDKs, but afaik, it would likely work if we installed them on a -dev SDK.

> If we take no action, will Pub know to generate documentation and score our release again once those tools support our SDK constraint? I'm guessing not today, but perhaps Pub could support an API to trigger documentation generation and scoring?

When we upgrade the SDK used for analysis and dartdoc generation, we re-analyze all the latest packages. That that should fix your package score. We strive to bump the dart-sdk used by pub.dartlang.org when a new dart-sdk is released, typically same day.

> Should we work with the dartdoc and pana maintainers to ensure they support the latest internal SDK release to avoid this problem for all internally developed packages?

I think the hard part of this would be for `pub.dartlang.org` to support multiple SDKs for analysis and dartdoc generation. I'm open to filing an issue, but I think this gets complicated and it's unlikely to be resolved anytime soon (as we have other priorities).

------
**Option (3.iii)**: So long as your release depends on a `-dev` SDK you could release it as a pre-release on pub. This is done by appending `-dev..` or `-beta..` to the `version` number in the `pubspec.yaml`.
The `pub.dartlang.org/packages/<package>` always displays the latest stable, and the package score is computed from the latest stable release. If you do a pre-release the main package page and package score will remain the same, but a link to the pre-released version will be present on the package page.

Obviously, you would have to re-publish your packages as normal releases (ie. no pre-release postfix) when the SDK becomes stable. So that's a bit more work on your part.

On the other hand, right now, users will see version `5.3.0`, but they'll be unable to install it unless they use a dev release of the dart-sdk. I'm suggesting you release it as `5.3.0-dev` until such time that dart-sdk `2.2.1` is released and then re-publish it as `5.3.0`.

**Comment by matanlurey** [comment]
We don't plan to change our publishing timeline or guidelines at this time. Thanks!

**Comment by jonasfj** [comment]
That's perfectly fine, thanks for the resolution :)
