### ISSUE TITLE
[ngSwitch] in <ng-container>

### ISSUE THREAD

**Issue by qholi** [dart-lang/angular#1782]
I tried using [ngSwitch] in <ng-container> and got the error below, but all is well replace \<ng-container\> with \<div\>.

`Only '*' bindings are supported on <ng-container>`

----
Dart Version: 2.2.0
AngularDart Version: 5.2.0
OS: Windows
Browser: Chrome

**Comment by leonsenft** [comment]
As the error suggests, `<ng-container>` only supports structural directives (those that bound with a `*` such as `*ngIf` and `*ngFor`). Unfortunately `[ngSwitch]` itself isn't structural (the `ngSwitchWhen` cases are), so it can't be used on `<ng-container>`.

**Comment by MickL** [comment]
@leonsenft  For me `<ng-container [ngSwitch]="...">` always works fine
