### ISSUE TITLE
GPG error: The following signatures were invalid

### ISSUE THREAD

**Issue by geniusunil** [dart-lang/angular#1788]
* [x] Dart SDK Version (`dart --version`) - 2.2(trying to install)
* [x] AngularDart Version - 5.2.0
* [x] OS - linux mint cinnamon
* [x] Browser - NA, chrome

Hi, I am trying to install angulardart from https://webdev.dartlang.org/guides/get-started (step 2), but 'sudo apt-get update' results in the following and I am unable to install :

W: GPG error: https://storage.googleapis.com/download.dartlang.org/linux/debian stable Release: The following signatures were invalid: EXPKEYSIG 1397BC53640DB551 Google Inc. (Linux Packages Signing Authority) linux-packages-keymaster@google.com
E: The repository 'https://storage.googleapis.com/download.dartlang.org/linux/debian stable Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by leonsenft** [comment]
It looks like you mean you're trying to install Dart, correct? AngularDart is just a package dependency that `pub` will manage. This belongs in dart-lang/sdk, I'll open an issue and point to this one for you.
