### ISSUE TITLE
Fix logo in readme

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#1791]
May have to copy the image to this repo

**Comment by kevmoo** [comment]
![Screen Shot 2019-04-18 at 12 06 00 PM](https://user-images.githubusercontent.com/17034/56384850-59da0e80-61d2-11e9-9fb9-8383e187cc76.png)

**Comment by jesselpalmer** [comment]
The logo link at the bottom of the README.md file in the [Resources](https://github.com/dart-lang/angular/blob/master/README.md#resources) is section broken as well. I'm more than happy to fix both links if someone attaches the logo to this issue.

**Comment by benhalverson** [comment]
@kevmoo The logo is here https://github.com/dart-lang/angular/blob/master/doc/angulardart-logo.png
