### ISSUE TITLE
Implement Material Components for Web wrappers in dart angular compoents library

### ISSUE THREAD

**Issue by tobytraylor** [dart-lang/angular#1792]
The landscape is tough for Flutter developers trying to figure out how to reuse their code and build a web app.  AngularDart and VueDart area really the only two options and both have problems when it comes to the component set.  Angular has a well documented but aged set of components without many things that engineers need to implement what they have in their flutter app.  Also, the way of managing styles and themes is really trying.  Then there is VueDart.  It has 4 different material librarys that are wrapping google material components for web library.  Each of them has varying levels of completeness and some owners disappear for months at a time.  I've implemented 20% of my functionality in angulardart before giving up and heading over to Vue Dart to realize how messed up it's landscape is.  

Could we get an angulardart wrapper for material design components implemented so that flutter bloc developers can hit the ground running?

**Comment by matanlurey** [comment]
I don't see this happening. We welcome external contributions, but don't work on specific wrappers.
