### ISSUE TITLE
some way to animate between routes

### ISSUE THREAD

**Issue by insinfo** [dart-lang/angular#1794]
I need to do transition animation between routes, I'm new to AngularDart, I have a way to do this.

* [ ] Dart SDK Version ^2
* [ ] AngularDart Version ^5
* [ ] Whether you are using Windows
* [ ] Whether you are using Chrome

**Comment by leonsenft** [comment]
AngularDart isn't opinionated about animations and in general leaves them up to the user to implement.

[package:angular_router](https://pub.dartlang.org/packages/angular_router/versions/2.0.0-alpha+22) has no such support for transition animations, nor are there plans to add them.
