### ISSUE TITLE
I need a dataTable

### ISSUE THREAD

**Issue by insinfo** [dart-lang/angular#1795]
I need a dataTable, in my application, I'm new to AngularDart.
I am trying to migrate a web application from the company where I work for AngularDart, and I did not find a dataTable and I do not know how to create an angular, I have a dataTable that I created for jquery but I do not know if I can use it together with AngularDart.

**Comment by leonsenft** [comment]
This is the repository for the AngularDart framework, which itself doesn't not provide any component implementations.

https://github.com/dart-lang/angular_components would be a better place to file such a request, although a table component is already on the road map, albeit a little outdated: https://github.com/dart-lang/angular_components/issues/356.
