### ISSUE TITLE
'webdev serve` error on some examples

### ISSUE THREAD

**Issue by ValeriusGC** [dart-lang/angular#1823]
`pub get && pub upgrade` passed OK. on all **/examples/**

But `webdev serve` issues error on
* registration_form
* hacker_news_pwa
* github_issues

```
webdev could not run for this project.
The `build_runner` version – 1.3.3 – is not within the allowed constraint – >=1.5.0 <2.0.0.
```

**OS**: Ubuntu 18.04
**Dart**: Dart VM version: 2.3.2 (Unknown timestamp) on "linux_x64"
**Webdev**: 2.0.7

**Comment by joe776** [comment]
Angular 5.3.1 still requires webdev 1.0.1. You can install it with this command: `pub global activate webdev 1.0.1`.

**Comment by ValeriusGC** [comment]
Thanxxx, @joe776 , really )) this works.
