### ISSUE TITLE
[SEVERE]build_web_compilers:entrypoint on web/main.dart (cached): AssetNotFoundException:

### ISSUE THREAD

**Issue by hpoit** [dart-lang/angular#1830]
* Dart SDK Version (`dart --version`): 2.3.2 on macos x64
* AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`): 5.3.0 
* Chrome

https://gist.github.com/hpoit/50943a844f970e7b7ad910c0584dac89

**Comment by leonsenft** [comment]
Was this a fresh project? Had you run `pub get` yet?

**Comment by hpoit** [comment]
Fresh project yup. Did `pub get` too. I don't remember what made this error go away, but I'm currently facing the versioning issue on https://gitter.im/dart-lang/sdk

**Comment by alorenzen** [comment]
There are several analyzer errors listed in your output. This will need to be fixed before the compile can complete.
