### ISSUE TITLE
Is TOH Angular version dependent? 

### ISSUE THREAD

**Issue by hpoit** [dart-lang/angular#1833]
As in https://github.com/dart-lang/webdev/issues/473. Thanks.

**Comment by alorenzen** [comment]
Those examples were written by an outside contributor, and not a member of the AngularDart team. That contributor is no longer maintaining the examples, so they are likely out of date.

**Comment by hpoit** [comment]
I see! Will there be a TOH made by the AngularDart team?

**Comment by alorenzen** [comment]
We have no plans to write one at this time.

**Comment by alorenzen** [comment]
We do maintain a few examples in the angular repo: https://github.com/dart-lang/angular/tree/master/examples

**Comment by hpoit** [comment]
Thanks
