### ISSUE TITLE
@deferred directive doesn't work in DDC mode

### ISSUE THREAD

**Issue by Lisenish** [dart-lang/angular#1836]
It looks like lazy-loading with `@deferred` annotation doesn't work in DDC mode. 
If fix for DDC is impossible or difficult maybe we should at least update documentation about that nuance?

**Comment by alorenzen** [comment]
DDC doesn't actually lazy-load libraries. https://github.com/dart-lang/sdk/issues/27777

I couldn't find anywhere that this is explicitly documented, though. I filed https://github.com/dart-lang/site-www/issues/1749 to see if they can add something to the DDC docs.

**Comment by Lisenish** [comment]
@alorenzen Great, thanks!

**Comment by kwalrath** [comment]
I’ve updated the dartdevc FAQ — and the language tour. (Flutter and the Dart VM don’t support deferred libraries either.) https://github.com/dart-lang/site-www/pull/1761
