### ISSUE TITLE
How to use Web Worker in AngularDart

### ISSUE THREAD

**Issue by dennougorilla** [dart-lang/angular#1852]
I try web worker in AngularDart.
I can listen message from worker. but message is minified.
how turn off minified? Or Can't use webWorker in AngularDart?

Dart VM version: 2.5.0-dev.1.0 (Tue Jul 9 15:27:01 2019 +0200) on "macos_x64"

**Comment by dennougorilla** [comment]
I found to disable minify. `-O0` option work it.
But Worker doesn't work.
```
Uncaught TypeError: Instance of 'UnknownJavaScriptObject': type 'UnknownJavaScriptObject' is not a subtype of type 'ImageData'
```
How do I use `ImageData` in worker?
Should I encode send message to str, json, blob, base64?

**Comment by vitaliy-bobrov** [comment]
You can check [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Transferring_data_to_and_from_workers_further_details) for details
