### ISSUE TITLE
Webstorm Ultimate Edition for `path: '.*'` module files, or issue? 

### ISSUE THREAD

**Issue by andesappal** [dart-lang/angular#1861]
* [x] Dart SDK Version (`dart --version`): 2.6.0-dev.0.0
* [x] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`): ^6.0.0-alpha+1
* [x] Whether you are using Windows, macOS, or Linux (if applicable): macOS Mojave
* [x] Whether you are using Chrome, Safari, Firefox, Edge (if applicable): Chrome

Hiya! I have a weird issue where `path: '.*'` works in the [Router example](https://github.com/angular-examples/router/blob/master/lib/src/routes.dart#L36), but in my project, with the exact same code lines and files as the example, it doesn't, claiming I need to acquire IntelliJ's Ultimate Edition:
![image](https://user-images.githubusercontent.com/54340176/65168382-c1fb7d80-da1a-11e9-98e7-58e0c66776af.png)

Is this an issue, or do I really need the Ultimate Edition?

**Comment by leonsenft** [comment]
No, you absolutely don't need a specific edition of IntelliJ to use `.*` in a router path. I believe that screenshot is referring to IntelliJ's support for files with a `.module` extension which is nothing you need to worry about.

It seems like you have another build error, I'd suggest looking at the console or the log file described in the WARNING shown in your screenshot in the bottom panel.
