### ISSUE TITLE
PathLocationStrategy (RouterProvider) in development

### ISSUE THREAD

**Issue by stanislasdrg** [dart-lang/angular#1863]
* Dart SDK Version : 2.5.0
* AngularDart Version : 5.3.0
* Whether you are using Windows, macOS, or Linux : macOS
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable) : All browsers
* Auth0

Hello everyone, I am trying to use PathLocationStrategy (RouterProvider) in development, as I am using Auth0 for auth and it has a callback which will pass query URL parameters back to my app.
I cannot use HashProviders, as some query params need to be retrieved from the callback url, which does not work when using a hash url.
I have read that [webdev does not support deep linking](https://angulardart.dev/guide/router/1#which-location-strategy-to-use) and also that [it is recommended to pick an adequate strategy early on](https://angulardart.dev/guide/router/appendices#which-strategy-is-best).
I can build the app with `webdev build` and have it working as expected, however this is a terrible workflow.

I am coming from Angular Ts, where ng serve would handle both strategies correctly.
Is there any way I can run the app in development while using PathLocationStrategy ?
Many thanks.

**Comment by leonsenft** [comment]
> I cannot use HashProviders, as some query params need to be retrieved from the callback url, which does not work when using a hash url.

HashLocationStrategy should support query parameters. If you can provide a reproduction, please file another issue detailing what doesn't work.

> Is there any way I can run the app in development while using PathLocationStrategy ?

I'm not sure if webdev provides this capability, but it sounds like a feature request (or clarification) for https://github.com/dart-lang/webdev/issues. Perhaps it could provide a means to define rewriting URL requests. We use such a feature for our HNPWA Firebase deployment to support deep linking with PathLocationStrategy: https://github.com/dart-lang/angular/blob/44d8ee96f03e54fadb1fbdf0e021570f8d88f6da/examples/hacker_news_pwa/firebase.json#L9-L14
