### ISSUE TITLE
angular dart plugin not showing origin of method correctly

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/angular#1878]
* [ ] Dart SDK Version (`dart --version`)
2.7
* [ ] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
5.3.1
* [ ] Whether you are using Windows, macOS, or Linux (if applicable)
macOS

I am using VSCode and when I command + click a method or variable, it shows two definitions, however, one of them is pointing to the HTML file of a component as in the attached image.
<img width="734" alt="view dart----guaraci_admin-Workspace-2020-01-17-14-25-01" src="https://user-images.githubusercontent.com/6199518/72636727-77ddc680-393e-11ea-8278-49773497d4bf.png">

Can I fix this somehow?
Maybe some configuration?

I talked to the VSCode dart plugin author and he suggested me to fill an issue here.

<img width="977" alt="Dart-Code - Gitter 2020-01-17 15-31-58" src="https://user-images.githubusercontent.com/6199518/72636795-9d6ad000-393e-11ea-8b0c-0b4937585cc4.png">

**Comment by kevmoo** [comment]
We are no longer supporting the plugin
