### ISSUE TITLE
Are you guys going to abandon this framework?

### ISSUE THREAD

**Issue by dngo10** [dart-lang/angular#1890]
The latest commit was around 6 months ago ?

We have not seen anything changed since. I wonder whether this project is still active or not. Long idle time is making me (as well as others) worried.

Thank you.

**Comment by leonsenft** [comment]
https://github.com/dart-lang/angular/issues/1866#issuecomment-571851626
https://github.com/dart-lang/angular/issues/1866#issuecomment-603947916
