### ISSUE TITLE
<ng-container> and [class.some] is not recognized by angular plugin

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/angular#1907]
![fZlAfy2](https://user-images.githubusercontent.com/6199518/91677675-c92b7680-eb19-11ea-99f2-b614587c1ae5.png)

I have the .dartServer folder, it has a hash and the analyzer_plugin folder, pub get runs there etc.

It works with most stuff, but not with ng-container and class.someClass as you can see in the image.

**Comment by kevmoo** [comment]
We are no longer supporting the plugin
