### ISSUE TITLE
webdev serve doesn't work for basic AngularDart project

### ISSUE THREAD

**Issue by HyperFluxYT** [dart-lang/angular#1929]
My Dart SDK version is 2.10.1 (installed through Chocolatey)
AngularDart version 6.0.0-alpha (as given by the pubspec.yaml)
I am using Windows
I am using Microsoft Edge for my browser
I use `stagehand` for creating projects

As said above I used `stagehand web-angular` command to create an AngularDart project. It was an empty project which I had not modified after creation. I tried to use the `webdev serve` command in my PowerShell to run my project. I opened the link given in the output but it was taking FOREVER to load. The output was:-
```
[INFO] Building new asset graph completed, took 4.7s
[INFO] Checking for unexpected pre-existing outputs. completed, took 3ms
[INFO] Serving `web` on http://<ip_address here>:8080
[INFO] Generating SDK summary completed, took 8.1s
[INFO] 37.1s elapsed, 499/520 actions completed.
```
The numbers in the last `[INFO]` block started to grow uptil `4532/4800` after which I lost my patience and terminated the command. I have even tried reinstalling Dart but it hasn't worked. It didn't work even when I ran `pub get` and tried to `serve` it again. How to fix this?

**Comment by lejard-h** [comment]
Related Stackoverflow with answer

https://stackoverflow.com/questions/64412240/webdev-serve-doesnt-work-for-basic-angulardart-project?noredirect=1#comment113920344_64412240

```
An initial compilation of 2 or 3 minutes is not something strange, it gets better after with DDC refreshing only updated modules (5-10 seconds)
```

**Comment by aadarshadhakalg** [comment]
It generally requires 3 minutes initially. After that it reloads in about 5 seconds. .
