### ISSUE TITLE
Update stagehand template

### ISSUE THREAD

**Issue by lejard-h** [dart-lang/angular#1931]
Stagehand is still generating Angular 5 template.

Do you have any plan to update it since it will be replace by `dart create` command (https://github.com/dart-lang/stagehand/issues/671).

Related StackOverflow
https://stackoverflow.com/questions/64383299/how-to-create-and-run-angulardart-6-web-application/64393335#64393335

**Comment by lejard-h** [comment]
Note that an Angular CLI already exist, but not up to date
https://github.com/google/angular_cli

**Comment by domesticmouse** [comment]
I'm happy to release a new version of stagehand with updated dependency versions.

@lejard-h do you want to propose the change to stagehand for the version bump, or do you want me to drive it?

**Comment by aadarshadhakalg** [comment]
How do I update stagehand?

**Comment by ykmnkmi** [comment]
> How do I update stagehand?

activate it again

**Comment by aadarshadhakalg** [comment]
> I'm happy to release a new version of stagehand with updated dependency versions.
> 
> @lejard-h do you want to propose the change to stagehand for the version bump, or do you want me to drive it?

Please do that

**Comment by lejard-h** [comment]
@domesticmouse I will send a PR, I was just wondering where to address it and if the angular_cli is still a thing, I know it's working find but I have a few ideas for it, should I see with you ? The Angular team ? Or directly on the repo ?

**Comment by lejard-h** [comment]
@kevmoo did it :)
https://github.com/dart-lang/stagehand/pull/678

**Comment by kevmoo** [comment]
just need to publish it!

**Comment by kwalrath** [comment]
It's published! https://pub.dev/packages/stagehand/changelog
