### ISSUE TITLE
Introduce a new package:angular_router API

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#202]

**Comment by franklinyu** [comment]
### Feature request: Port `RouterLinkActive` from TypeScript.

See [documentation](https://angular.io/docs/ts/latest/api/router/index/RouterLinkActive-directive.html) and [source](https://github.com/angular/angular/blob/2.3.0/modules/%40angular/router/src/directives/router_link_active.ts). For usage, refer to [this answer on StackOverflow](http://stackoverflow.com/questions/34323480/in-angular-2-how-do-you-determine-the-active-route/#37947435).

**Comment by matanlurey** [comment]
This isn't planned for 4.0 (it might happen, but it might not in time).

We are currently gathering feedback from internal users before making a decision.

**Comment by matanlurey** [comment]
Done.
