### ISSUE TITLE
Ability to reset form

### ISSUE THREAD

**Issue by Adamovskiy** [dart-lang/angular#216]
[TS implementation](https://github.com/angular/angular/blob/master/modules/@angular/forms/src/directives/ng_form.ts) of `ngForm` directive has `resetForm()` method, but in Dart version looks like the only way to reset is to re-create it.

**Comment by chalin** [comment]
Here is the updated reference to the TS implementation: https://github.com/angular/angular/blob/master/packages/forms/src/directives/ng_form.ts

cc @kwalrath

**Comment by cedx** [comment]
From the docs, to reset a form:
> You have to clear all of the flags imperatively [...]

How can we do that? I don't find any `ngControl` API for marking a control as pristine.

**Comment by chalin** [comment]
@cedx That feature isn't currently available (which is what this issue is about). Until this issue is resolved, and to avoid further confusion, I'll be removing that section of the docs very soon.

**Comment by cedx** [comment]
@chalin Thanks for the clarification.

**Comment by matanlurey** [comment]
Ping @alorenzen is this still WIP?

**Comment by alorenzen** [comment]
Yup, still WIP.

I've added the ability to mark `Control`s as `untouched` / `pristine`. I'm working on added the ability to update the value for a `ControlGroup`/`ControlArray`. And then all the pieces are in place to add `reset()` method.
