### ISSUE TITLE
Templates can't contain certain Unicode symbols

### ISSUE THREAD

**Issue by ArgentiApparatus** [dart-lang/angular#223]
I'm using Unicode symbols in component templates. On upgrading from Angular 2.1.0 to 2.1.1 I started getting compilation errors. I see the same errors with 2.2.0 also.

Trvialized example

````
@Component(
  selector: 'app',
  template: '''
    <div>🎂</div>         <!-- Misc symbols: causes compilation error -->
    <div>&#x1f382;</div>  <!-- Escaped cake symbol code: OK -->
    <div>ΓΔ</div>         <!-- Greek: OK-->
    <div>↔↕</div>         <!-- Arrows: OK-->
  '''
)
class App {
}
````
error message is:

    Transform DirectiveProcessor on symbols|web/main.dart threw error: Invalid argument(s): Text "≡ƒÄé<" must be 2 characters long.

Environment is Windows 7, editor is Sublime Text 3 build 3126. I checked the validity encoding of the source code file and it seems fine.

**Comment by leonsenft** [comment]
This looks like we're not handling surrogate pairs properly. Of the examples given, the only failing one is a surrogate pair.

**Comment by matanlurey** [comment]
Good news: This looks auto-fixed by more recent infrastructure.

I'll have a PR with a test merged upstream soon.
