### ISSUE TITLE
User request: Strip [debugId=...] in release mode.

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#238]
... Or provide an alternative syntax we can strip.

This allows users to annotate their HTML without incurring a production cost:

```html
<div debugId="customer-panel">...</div>
```

**Comment by alorenzen** [comment]
Proposal: What if we added some flag to `@Directive` to make it debug-only? 

Then, we only generate code for those directives on in debug mode?

**Comment by matanlurey** [comment]
@alorenzen: That might generalize better. I don't think we plan on doing this soon though.
