### ISSUE TITLE
Meta issue: Docs for how to deploy to gh-pages

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#242]
Not related directly to Angular, but useful for any Dart for Web application.

**Comment by jimmyff** [comment]
This isn't the most elegant way of doing it but it works. I have this shell script in the root of the leeds.dart angular2 site:

```
# Clone gh-pages
git clone git@github.com:leeds-dart/leeds-dart.github.io.git gh-pages
pushd gh-pages
git checkout -t origin/master

# Out with the old in with the new
rm -rf *
# Copy build
cp -r ../build/web/* .

# Add and commit
git add -A
git commit -m "Update build files"
git push
popd

rm -rf gh-pages
```

**Comment by kwalrath** [comment]
There's also peanut: https://pub.dartlang.org/packages/peanut

**Comment by matanlurey** [comment]
I don't think we need specific documentation here.
