### ISSUE TITLE
AngularDart in DartPad

### ISSUE THREAD

**Issue by kulshekhar** [dart-lang/angular#243]
One of the pain points I find with AngularDart is that to test out any small thing, I need to create a new project or use a 'meta' angular project. Because of this, I've caught myself, several times, mentally putting off or postponing trying out new things with AngularDart.

I can't back this up with any data but it seems like this would also be something of an issue for people who want to try out AngularDart but are new not just to AngularDart but to Dart itself. 

For these reasons, I think having AngularDart work in DartPad would be immensely helpful.

**Comment by matanlurey** [comment]
As much as a I agree we don't have a lot of direct control over this right now :-/

Will keep open for triage when possible. Another issue is we only support a pre-compiled mode (no runtime compiler) formally, which means we'd need something a little more sophisticated than even just `package:` support.

**Comment by matanlurey** [comment]
It's unlikely this will happen at this point from _our_ end (it requires a lot of coordination across the SDK we don't currently have). I'd love to explore other ways to give new users a way to try AngularDart without too much work (i.e. hosted on StackBlitz, etc).
