### ISSUE TITLE
`Control#registerOnChange` doesn't work?

### ISSUE THREAD

**Issue by mehaase** [dart-lang/angular#247]
The [API docs for `Control`](https://webdev.dartlang.org/angular/api/angular2.common/Control-class) show a `registerOnChange(Function fn)` method, but this callback doesn't seem to ever get called. E.g. in my component:

    void ngAfterContentInit() {
        this.control.registerOnChange(() => print('control changed')));
    }

Then I try typing something into the input associated with the control, but the message is never printed. I know that the control is associated with the form input because I am able to use `control.valid`, etc. to check the input's value.

Am I using this wrong? Or is this not supposed to be a public API?

**Comment by zoechi** [comment]
what about `control.valueChanges.listen(...)`?

**Comment by mehaase** [comment]
Thank you! I don't know how I overlooked that, but that's exactly what I needed.

**Comment by TedSander** [comment]
We should probably change the documentation. This is used by the ValueAccessors to get an update on the model change and push that value to the View. There can only be one of them so it should probably only be used internally here: https://github.com/dart-lang/angular2/blob/master/lib/src/common/forms/directives/shared.dart#L38

**Comment by kwalrath** [comment]
Reopening as a doc bug.

**Comment by matanlurey** [comment]
Pushed to 5x.

**Comment by alorenzen** [comment]
Does anything still need to be done here? 

@TedSander updated the comment on `Control.registerOnChange` to indicate that it is intended for internal use only.

**Comment by matanlurey** [comment]
@alorenzen @TedSander Is this done?

**Comment by alorenzen** [comment]
I'm fine closing this. If there are other changes that people want to see, then we can re-open or start a new issue.
