### ISSUE TITLE
Update documentation for Query.read to include an example

### ISSUE THREAD

**Issue by leiboldm** [dart-lang/angular#249]
https://webdev.dartlang.org/angular/api/angular2.core/Query/read

The existing documentation isn't easy to understand unless you already know what this property does (especially considering how ambiguous the name "read" is).

Similarly, the documentation for ViewChild doesn't even attempt to explain what "read" is: https://webdev.dartlang.org/angular/api/angular2.core/ViewChild/ViewChild

**Comment by matanlurey** [comment]
I'm making a bunch of helpful changes here this quarter, so I'll help co-own this w/ docs.

**Comment by matanlurey** [comment]
Related: https://github.com/dart-lang/angular/issues/537

**Comment by matanlurey** [comment]
Sorry it took so long to get to this, I have a PR out now.

**Comment by matanlurey** [comment]
Fixed in #1462.
