### ISSUE TITLE
`Validator` becomes type safe.

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#268]
Due to some dynamic trickery, even though `Validator` is typed as returning `Map`, we rely on this returning `Future<Map>` when used as an async validator.

Changes required (sign off by @TedSander):

- [ ] Drop the return type on `Validator` temporarily
- [ ] Add a new `AsyncValidator` class
- [ ] Move users of `Validator` w/ a `Future` to `AsyncValidator`
- [ ] Re-type `Validator`

**Comment by matanlurey** [comment]
Pushed to 5x.

**Comment by eftikharEmad** [comment]
Can you please provide me with an example about it I did long time search about that in angular4 dart

**Comment by matanlurey** [comment]
I'm wondering if this is needed in practice anymore. Closing for now.
