### ISSUE TITLE
Move tests into a standalone package

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#272]
At fe30f89bacd34f75936fe397b5865f4f386090fc on mac
Also hitting this on travis: https://travis-ci.org/dart-lang/angular2/jobs/200125560#L750

As part of `tool/run_codegen_tests.sh` this is run: `pub serve test --port 8283`

Output
```
Loading source assets...
Transformer cycle detected:
  angular2 is transformed by angular2/transform/reflection_remover
  angular2 depends on angular_test
  angular_test is transformed by angular2/transform/codegen
```

**Comment by matanlurey** [comment]
FWIW I'm not sure this is solvable - there is no concept of dev_transformers - but that's basically what angular_test does. What I could do is remove the transformers from angular_test and edit the file in the presubmit to add them instead of checking in a presubmit

**Comment by kevmoo** [comment]
Do we just delete this code path then?

I'd love to have *some* tests that validate the transformers...

**Comment by matanlurey** [comment]
I don't think we have a resolution here @kevmoo - WDUT?

**Comment by matanlurey** [comment]
OK I have a solution.

**Comment by matanlurey** [comment]
Are you hacking on this @kevmoo?

**Comment by kevmoo** [comment]
Sure. After https://github.com/dart-lang/angular2/pull/320

**Comment by natebosch** [comment]
@jakemac53 might also have some insight since he's been looking at the internals of pub applying transformers.

I'm  not sure this is going to be possible to solve without either improving `pub` to understand sub-package level modules, or splitting up the angular2 package.

**Comment by jakemac53** [comment]
Ya I think you would have to split up the angular2 package so that the transformer is separate. However there is additional shared code so you would also need an angular2_common package or something... and I don't think you would be able to run the transformer on that.

**Comment by natebosch** [comment]
After some discussion: solving this within `pub` is cost prohibitive if it's even possible at all.

I think long term the solution here is to have the tests on angular live in a separate (unpublished) package within the same repo. The only way that really works is if we solve all the problems around multi-package repos, so I think we're effectively blocked on that.

**Comment by matanlurey** [comment]
@natebosch Does this still hold true? If we end up re-organizing our [sub]-packages this should be a consideration.

**Comment by natebosch** [comment]
Yes, I don't think we're going to be able to have a `dev_dependency` that introduces a cycle using the transformer while we're building with pub.

The only options I can think of are:
1. Build out bazel support for testing (will take a while) and use that on travis since we can specify non-cyclical targets
2. Pull out the actual tests to a separate package like `_test_angular` which has a `path` dependency on both `angular` and `angular_test` within the same repo.

**Comment by matanlurey** [comment]
I will bring this up with the team internally. Thanks!

**Comment by matanlurey** [comment]
Closed by @alorenzen.
