### ISSUE TITLE
Stop using `this` to access fields

### ISSUE THREAD

**Issue by filiph** [dart-lang/angular#278]
It's probably still a remnant of the TypeScript era, but I noticed we have a lot of code using `this`. [For example](https://github.com/dart-lang/angular2/blob/v2.1.0/lib/src/core/change_detection/differs/default_iterable_differ.dart#L56):

```dart
  void forEachItem(Function fn) {
    CollectionChangeRecord record;
    for (record = this._itHead;
        !identical(record, null);
        record = record._next) {
      fn(record);
    }
  }
```

`_itHead` is a private member of that class and there is no name collision with a local variable.

This isn't P0, obviously, but as AngularDart is now increasingly acting as one of the model Dart projects, removing `this` would help. The code without `this` will be more readable, more terse, and more familiar to non-JS developers.

**Comment by kevmoo** [comment]
Use this lint - http://dart-lang.github.io/linter/lints/unnecessary_this.html

Although it won't be in the SDK until 1.24-dev.1

**Comment by matanlurey** [comment]
I think we made some good progress towards here.

I'm not sure its worth refactoring lots of the legacy code/parsing, though.
