### ISSUE TITLE
Information on size of compiled CSS/template/code?

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/angular#285]
Is there any way to determine how much of the compiled `.dart.js` the
- template
- CSS
- Dart

is?

The question I am trying to answer: had I sent the CSS separately, what would have been the size of all the CSS files? (network traffic without gzip)

**Comment by matanlurey** [comment]
I am not sure we can get that exact information, though perhaps we could emit it as a diagnostic step. I'm going to file this as a P3 and hopefully I can get more information for you on how we could add this (perhaps with your help).

**Comment by daniel-v** [comment]
I am happy to help! I've got an assumption I'd like to run by you. 

* Once compilation finished, currently there is nothing dumped or saved that could be aggregated to retrieve this information.
* Am I right assuming that collecting/recording such information should be part of the compilation process? 
* [Dump info visualizer](https://dart-lang.github.io/dump-info-visualizer/) would be of no help here, would it?

**Comment by hterkelsen** [comment]
You can get some information on how much of your code is template files using the `dart2js_info` `library_size_split` tool. If you pass `--dump-info` to `dart2js` you will get back a `.info.json` file (suppose it's called `out.js.info.json`). Then you can create a yaml file called `groups.yaml`

```yaml
groups:
- { name: "Templates", regexp:  "package:.*.template.dart", cluster: 1 }
- { name: "All packages", regexp: "package:.*", cluster: 2 }
```

and do

```
$ pub global activate dart2js_info
$ dart2js_info_library_size_split out.js.info.json groups.yaml
 ----------------------------------------------------------------------
 Templates                                               292433  21.25%
 ----------------------------------------------------------------------
 All packages                                            839802  61.01%
 ----------------------------------------------------------------------
 All libraries (excludes preambles, statics & consts)   1189783  86.44%
 Shared consts                                            84944   6.17%
 Total accounted                                        1274727  92.61%
 Program Size                                           1376445    100%
```

You can see that in my example app, templates are about 21% of the generated code.

As for CSS, that's more difficult. CSS is compiled into a constant list. If you're super motivated you can write your own analysis using the `dart2js_info` API to search for constant lists that are CSS, and compare the total size of those to the size of the starting CSS.

**Comment by daniel-v** [comment]
Nice! Thanks for the info.

**Comment by matanlurey** [comment]
@kwalrath @chalin Maybe we should document this?

**Comment by matanlurey** [comment]
Pushed to 5x.

**Comment by matanlurey** [comment]
@natebosch @jakemac53 

Trying to figure out if we should punt this to >5.0.

I have some ideas:
* Add a flag to output a `.output.json` file per `.template.dart` with details.
  * ... and use a post-compile step (?) to summarize them.
* Something complicated with source maps

Anything else in the terms of the build system?

**Comment by jakemac53** [comment]
I think you would have everything you need to do this in the existing build system - but is it necessary? The regular dump_info suggestions seems to have pretty much accomplished this?

That is also more representative than the original dart size for instance.

**Comment by matanlurey** [comment]
I think thats fair. I'll skip that for now.
