### ISSUE TITLE
Replace `OpaqueToken` with `Inject`

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#288]
In ngTS, OpaqueToken has been replaced by InjectionToken<T>, see https://github.com/angular/angular/commit/d169c2434e3b5cd5991e38ffd8904e0919f11788.

In a recent meeting it was felt that this could be a good thing to do in ngDart as well.

cc @kwalrath

**Comment by matanlurey** [comment]
I like this change, and we have a volunteer to make it, but it will be post-V3 (new compiler).

**Comment by chalin** [comment]
Just a clarification: as is explained in #35, `const` instances are canonicalized, and so only certain values should be used as arguments to an `InjectionToken` constructor if we want to guarantee uniqueness of `InjectionToken`.

The most useful values are `Type`s. So I'd suggest not having a generic type argument, and constraining the constructor argument type as follows:
```dart
class InjectionToken {
  final Type type;
  const InjectionToken(this.type);
}
```
(Cf. https://github.com/dart-lang/site-webdev/issues/256)

Relates to #364.

**Comment by matanlurey** [comment]
Blocked by https://github.com/dart-lang/angular2/issues/404.

**Comment by leonsenft** [comment]
@matanlurey Is this in progress now that #404 is resolved? Do we still have a volunteer for this?

**Comment by matanlurey** [comment]
Pushed to 5x.

**Comment by matanlurey** [comment]
Straw-man design: Use `Inject` for both an annotation and a token. For example:

```dart
class Inject<T> {
  final Symbol _name;
  const Inject([this._name]);
}
```

Use in a `Provider`:

```dart
const cachedRpcService = const Inject<RpcService>(#cachedRpcService);

const [ 
  const Provider(cachedRpcService, useClass: CachedRpcServiceImpl);
  // Can type-check at compile-time this is-a `RpcService`
];
```

Use in a `Component`:

```dart
class Comp {
  Comp(@cachedRpcService RpcService rpcService) { ... }
  // Can type-check at compile-time this is-a `RpcService`
}
```

**Comment by matanlurey** [comment]
One more potential requirement is that internal users are sometimes scared of using a single application global (i.e. `#...`) as the identifying token. We should explore allowing users to sub-class `Inject`:

```dart
class XsrfToken extends Inject<String> {
  const XsrfToken();
}
```
