### ISSUE TITLE
radio input: support for `ngModel` and `value`

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#293]
Add support for `ngModel` and `value` radio input properties, matching the functionality available under AngularDart Material's [`<material-radio-group>`][mrg].

[mrg]: https://www.dartdocs.org/documentation/angular2_components/0.2.2/angular2_components/MaterialRadioGroupComponent-class.html

**Comment by chalin** [comment]
Cf. https://github.com/dart-lang/angular2_components/issues/61

**Comment by matanlurey** [comment]
We already support this:

```html
<input type="radio" name="food" [(ngModel)]="foodChicken">
```

What else is needed exactly @chalin?

**Comment by chalin** [comment]
While there is ng2 support for ngModel over radio inputs, the current support isn't practical.

Let me illustrate this using the the example from [lib/src/common/forms/directives/radio_control_value_accessor.dart](https://github.com/dart-lang/angular2/blob/master/lib/src/common/forms/directives/radio_control_value_accessor.dart#L57-L66):
```dart
@Component(
  template: '''
    <input type="radio" name="food" [(ngModel)]="foodChicken">
    <input type="radio" name="food" [(ngModel)]="foodFish">
  '''
)
class FoodCmp {
  RadioButtonState foodChicken = new RadioButtonState(true, "chicken");
  RadioButtonState foodFish = new RadioButtonState(false, "fish");
}
```
Notice that developers are forced to have **a model variable of type `RadioButtonState` for _each_ radio button** and that **only `String` values** can be associated with radio buttons.

In ACX and ngTS, **any type** can be associated with radio button values, and **only one ngModel** is necessary. Here is an ngTS example of a list of radio buttons for selecting heroes:

```html
  <label *ngFor="let h of heroes">
    <input type="radio" name="heroes" [(ngModel)]="currentHero" [value]="h">{{h.name}}
  </label>
```

The ngModel is bound to the `currentHero`; this is much easier to deal with than a collection of `RadioButtonState` fields.

Here is the same example in ACX (slightly adapted from [webdev examples/ng/doc/template-syntax/lib/app_component.html](https://github.com/dart-lang/site-webdev/blob/master/examples/ng/doc/template-syntax/lib/app_component.html#L660-L665):

```html
<material-radio-group [(ngModel)]="currentHero">
  <material-radio *ngFor="let h of heroes" [value]="h">
    {{h.name}} ({{h.id}})
  </material-radio>
</material-radio-group>
```

cc @kwalrath @nshahan

**Comment by matanlurey** [comment]
Pushed to 5x.

**Comment by matanlurey** [comment]
I'm going to remove this from the 5x milestone since (a) I don't see many users hitting this and (b) we'd like to really get close to 5x as soon as possible. This could always be done in 5.1+.

**Comment by matanlurey** [comment]
We don't plan on working on this in the short/medium term.
