### ISSUE TITLE
Proposal: Angular Static Analysis Annotations

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#305]
Similar to `package:meta/meta.dart`, we might want to have custom annotations that have no runtime semantics, but that help static analysis tools (like the upcoming `angular_analyzer_plugin`) and the BUILD process warn the user when something unintended is found.

### `@atBootstrapOnly`

Designates a class (or possibly an `OpaqueToken`) that is only understood by the framework if it is provided at the `bootstrap(...)` of the DI hierarchy. This is important because user's might think they are able to override something like`ExceptionHandler`,`NgZone`, etc, down the chain, but in reality that will at best do nothing, at worst cause issues.

```dart
@atBootstrapOnly
abstract class ExceptionHandler {}
```

(More annotations to come)

**Comment by natebosch** [comment]
How many cases do we expect to crop up? Do we think the annotation is overall less effort than hardcoding behavior for the cases we would annotate? Is this something we expect clients to also use when they define special injectables?

**Comment by MichaelRFairhurst** [comment]
I'm not sure how easily we can statically guarantee something is at bootstrap only....Though we could try to do our best. I can't seem to find the API clearly stated anywhere...

is it that its a provider which can't be part of component declarations?

Last I heard angular DI was not statically analyzable :( but I do want to look into that deeper at some point. So that could be an issue until we move to package:inject.

Overall, I'm happy to analyze more, and I prefer hardcoding annotation names to classes (we currently hardcode ngFor, and I've always cringed about that)

**Comment by matanlurey** [comment]
> @natebosch:
>
> How many cases do we expect to crop up? Do we think the annotation is overall less effort than hardcoding behavior for the cases we would annotate? Is this something we expect clients to also use when they define special injectables?

Obviously internal services are the most error prone, but looking at the material components, and services like `DomService`, or the popup/overlay related UI services, there are definitely a lot of user-land code that could have better static analysis about misuse.

> @MichaelRFairhurst:
> 
> I'm not sure how easily we can statically guarantee something is at bootstrap only....Though we could try to do our best. I can't seem to find the API clearly stated anywhere...

We don't need a guarantee, we just need to warn if we see it in a `@Directive` or `@Component` - that should be relatively easy(-ier), right?

> 
> is it that its a provider which can't be part of component declarations?

Rather a provider that should _not be_ (i.e. will not work or will cause problems)

> 
> Last I heard angular DI was not statically analyzable :( but I do want to look into that deeper at some point. So that could be an issue until we move to package:inject.

This is less about static analysis of the DI tree and more about giving simple warnings if we detect a known bad usage pattern.

> 
> Overall, I'm happy to analyze more, and I prefer hardcoding annotation names to classes (we currently hardcode ngFor, and I've always cringed about that)

Agreed! Please propose more in this thread.

**Comment by matanlurey** [comment]
This hasn't gotten a lot of traction, so I'm closing for now.
