### ISSUE TITLE
RFC: Compile-time dependency injection.

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#364]
We'd like an Angular application to be able to use almost entirely compile-time dependency injection (no runtime checks or lookups). We'll need to be able to make more closed-world assertions about the state of your application and remove or deprecate parts of the API that make this impossible (and de-optimize in those cases).

The result is just a series of `get()` calls across your application:

```dart
class Bootstrap$Injector implements Injector {
  Foo _fooService;

  @override
  get(token) {
    switch (token) {
      case Foo: 
        return _fooService ??= new Foo();
      default: 
        return noProviderFound;
    }
  }
}

class RootComponent$View {
  RootService _rootService;

  @override
  injectorGet(token) {
    switch (token) {
      case RootService:
        return _rootService ??= new RootService();
      default:
        return super.inejctorGet(token);
    }
  }
}
```

## Deprecated

* [`ReflectiveInjector`](https://webdev.dartlang.org/angular/api/angular2.core/ReflectiveInjector-class): This relies on using the static `Reflector` to find and create arbitrary classes from previously generated factories.

Possible replacements:

* `MapInjector`
* Some sort of additional code generation in an `@Component`:

```dart
@Component(
  selector: 'comp',
)
class Comp {
  @Resolve(const [ ... ])
  set injector(Injector generated) { ... }
}
```

* Using `bootstrap(<root component>, <providers>)`. We need to resolve at compile-time:

```dart
@Bootstrap(RootComponent, const [
  // Providers go here.
])
void main(Bootstrapper<RootComponent> bootstrap) {
  bootstrap();
}
```

* Using `provide()`, just `T` (type), or  `new/const Provider()` (with multiple optional parameters):

  * `const Provider<Foo>()`
  * `const Provider<Foo>.useExisting(AbstractFoo)`
  * `const Provider<Foo>.useClass(FooImpl)`
  * `const Provider<Foo>.useFactory(createFoo)`
  * `const Provider<Foo>.useValue(const Foo())`

* Replace `OpaqueToken` with `InjectionToken`:

```dart
const baseUrl = const InjectionToken<String>(#baseUrl);

/// Now can `@Inject<String>(baseUrl)`
const Provider<String>.useValue('Hello World', token: baseUrl);
```

* Using `Provider(multi: true)`. Not sure about replacement yet! 

/cc @alorenzen.

**Comment by yjbanov** [comment]
> remove or deprecate parts of the API that make this impossible (and de-optimize in those cases)

Sorry for pedantry, but I'm a little confused by this part. If conflicting APIs are to be removed, why the need to de-optimize in those cases if there won't be such cases any more? Did you mean "remove _or_ de-optimize"?

> `return super.inejctorGet(token);`

`RootComponent$View` is direct descendant from `Object`, so there's no `super.injectorGet`.

> `@Bootstrap`

Why not reuse the existing `@AngularEntrypoint`?

**Comment by matanlurey** [comment]
No problem re-using `@AngularEntrypoint` :)

**Comment by chalin** [comment]
Good proposal. I just have one comment about a suggested class definition for `InjectionToken `: see https://github.com/dart-lang/angular2/issues/288#issuecomment-301084173.

**Comment by matanlurey** [comment]
This will not be in 4.0.0, but I am looking at getting in part of the API:

> * Using `provide()`, just `T` (type), or  `new/const Provider()` (with multiple optional parameters):
>    * `const Provider<Foo>()`
>    * `const Provider<Foo>.useExisting(AbstractFoo)`
>    * `const Provider<Foo>.useClass(FooImpl)`
>    * `const Provider<Foo>.useFactory(createFoo)`
>    * `const Provider<Foo>.useValue(const Foo())`

So I've opened https://github.com/dart-lang/angular2/issues/407.

**Comment by matanlurey** [comment]
Thanks everyone for your feedback. A summary of accepted ideas is now here:

https://github.com/dart-lang/angular/projects/4
