### ISSUE TITLE
Routing not working correctly with trailing slash and query parameters

### ISSUE THREAD

**Issue by rinukkusu** [dart-lang/angular#369]
Routing to https://domain/route?orderby=xy works, but https://domain/route/?orderby=xy doesn't.

I just came to discover this, since I'm rewriting a website and Google indexed it with that slash in front of the query parameters. I think it shouldn't make a difference if there's a slash or not.

**Comment by matanlurey** [comment]
@leonsenft is this covered by the new router?

**Comment by leonsenft** [comment]
Yes it is! @rinukkusu the upcoming router release doesn't have this issue. You can try the alpha release now if you'd like: https://pub.dartlang.org/packages/angular_router/versions/2.0.0-alpha%2B1
