### ISSUE TITLE
Request: AngularDart with Sentry.io (or similar service).

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#413]
One awesome feature of Dart and AngularDart is centralized exception handling. Google has its own (internal) services for logging errors and stack traces that occur in production, so we haven't hit this issue, but this would be a great small project for some folks in the community to tackle.

Please contact me or post on this thread if you are interested in contributing.

**Comment by jimmyff** [comment]
@zoechi created a nifty sentry.io raven js interop client for a project we're working on. We open sourced it & you can find it here: https://github.com/jimmyff/raven.dart

It's working however I believe there is currently an issue with building due to dartojs & the js interop. Also I should probably move it under my organisations github profile rather than having it sitting on my personal one.

**Comment by matanlurey** [comment]
Cool! Let me know if you have any questions maybe I can help.

**Comment by yjbanov** [comment]
FYI, I'm going to try and wire up Sentry.io for Flutter apps. I think I might have to write a pure Dart client (hopefully this is not too hard 🤞). Perhaps there's room for collaboration. I'll report back as I find out more.

**Comment by matanlurey** [comment]
That would be great!

**Comment by yjbanov** [comment]
Update: I have a working pure Dart Sentry.io client: https://github.com/yjbanov/sentry

However, it does not yet work on the web because I haven't found a graceful way to handle request payload compression (https://github.com/yjbanov/sentry/issues/2).

**Comment by matanlurey** [comment]
One more thing: folks would love to see an example of deobsfucating stack traces too.

**Comment by yjbanov** [comment]
Update: the sentry client repo has moved to https://github.com/flutter/sentry. Pull requests are welcome 😃

**Comment by alorenzen** [comment]
Good enough to close this issue?

**Comment by stanislasdrg** [comment]
Reopening this issue here, as the Flutter repo does not feel like the proper place to do discuss it.
Importing the Sentry lib in Angular Dart crashes the app :
Web console :
`Uncaught SyntaxError: Unexpected token '<'`

Webdev build :
```
build_web_compilers:entrypoint on web/main.dart: Skipping compiling volya_app_dart|web/main.dart with dart2js because some of its
transitive libraries have sdk dependencies that not supported on this platform:

sentry|lib/sentry.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings
```

Any breaking changes since this was posted ?

**Comment by lejard-h** [comment]
I submitted a PR a long time ago on https://github.com/flutter/sentry/pull/22 (that I need to update)

But this repo https://github.com/leftyio/angular_sentry contain a working version for the last stable version of Angular.

It works even if sometimes, sentry failed to unminify stacktrace
