### ISSUE TITLE
Request for documentation ngProjectAs

### ISSUE THREAD

**Issue by mdragus** [dart-lang/angular#422]
The feature ngProjectAs is very useful for addressing certain limitations of ngContent. Context: https://github.com/dart-lang/angular2/issues/195. 

It would be extremely useful if we could get some documentation of how the ngProjectAs directive can be used.

**Comment by matanlurey** [comment]
/cc @chalin @kwalrath 

Are we able to copy over the Angular/TS docs, if available, for this feature?

**Comment by kwalrath** [comment]
_Are_ there any TS docs for this? https://github.com/angular/angular.io/issues/3099 implies that it's in the new site (https://aio-staging.firebaseapp.com), but I don't know where.

**Comment by chalin** [comment]
I'll look into it shortly.

**Comment by chalin** [comment]
I'm not finding the TS-side documentation either, so I assume that it is still in development. 

We'll use https://github.com/dart-lang/site-webdev/issues/617 to track this request for documentation, so you can close this issue @matanlurey.

**Comment by leonsenft** [comment]
@kwalrath @chalin This was never documented in TS. They still have an [open issue](https://github.com/angular/angular.io/issues/1683) for it. Someone even submitted a [PR](https://github.com/angular/angular.io/pull/2851) to document it, but it wasn't accepted.
