### ISSUE TITLE
In TrackByFn typedef, index parameter should be an int not a num

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#431]
Under Dart 1.24-dev, when compiling https://github.com/angular-examples/template-syntax using the dartdevc I get this errors:

```nocode
[error] A value of type '(int, Hero) → int' can't be assigned to a variable of type 'TrackByFn(num, dynamic) → dynamic'. (package:template_syntax/app_component.template.dart, line 4013, col 35)
```

This is because the app declares the following function used as an argument to an `ngFor trackBy`:
```dart
int trackByHeroes(int index, Hero hero) => hero.id;
```

But Angular seems to expect the `index` to be a `num`; see [lib/src/core/change_detection/differs/default_iterable_differ.dart#L10](https://github.com/dart-lang/angular2/blob/master/lib/src/core/change_detection/differs/default_iterable_differ.dart#L10)
```dart
typedef dynamic TrackByFn(num index, dynamic item);
```

Should `index` not just be an `int`? It seems to only [ever be called](https://github.com/dart-lang/angular2/blob/master/lib/src/core/change_detection/differs/default_iterable_differ.dart#L210) with an [`index` that is an `int`](https://github.com/dart-lang/angular2/blob/master/lib/src/core/change_detection/differs/default_iterable_differ.dart#L202).

cc @kwalrath

**Comment by matanlurey** [comment]
Yep I'll update it for 4.0!

**Comment by matanlurey** [comment]
Will be fixed in the next sync, but that will be a little while :-/

**Comment by Kleak** [comment]
i got the same problem yesterday and if you change the Hero to dynamic and the returned type to dynamic it work. but that is not really good

**Comment by matanlurey** [comment]
Landed.
