### ISSUE TITLE
Conditionally listen to an event

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#440]
i.e. something like:

```html
(click:<expression>)="handler()"
```

This is primarily to avoid making lots of expensive listen calls if they aren't always used.

**Comment by leonsenft** [comment]
Closing until further discussion.

- Relying on change detection to conditionally subscribe means it's possible to miss an event dispatched programmatically after the condition changes, but before change detection runs.
- Ensuring no events are missed relies on subscribing immediately when the condition changes. This means any Angular-assisted solution would require some sort of generated hook user code would have to invoke which isn't ergonomic.
