### ISSUE TITLE
Replace ElementRef with Element

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#442]
Any SSR-type solution we create will likely use conditional imports, so it's (a) not important we have this extra abstraction and (b) clumsy and extra boiler-plate for both the runtime and user experience.

~~-Type `ElementRef.nativeElement` as `Element`.~~ Will not do
- [x] Support injecting `Element` directly (as an alias) in the compiler and DI runtime.
- [x] Support `@Query` types with `Element` instead of `ElementRef`.
- [x] Mark `ElementRef` deprecated, saying to inject `Element` instead.
- [ ] Remove `ElementRef`.

**Comment by daniel-v** [comment]
> Any SSR-type solution we create

Is SSR on roadmap now or is this just a preparation to it if it gets prio?

**Comment by zoechi** [comment]
@daniel-v I think `ElementRef` is just some remnant from the TS heritage that doesn't fulfil a purpose in Dart

**Comment by matanlurey** [comment]
Replaced by https://github.com/dart-lang/angular/issues/692.
