### ISSUE TITLE
Either optimize or replace ngOnChanges

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#443]
We could detect, for example, that the user omits the `ngOnChanges` map:

```dart
@override
void ngOnChanges(_) { ... }
```

We could also support a new interface that is cheaper:

```dart
abstract class AfterChanges {
  void ngAfterChanges(); // No parameter. Lightweight alternative to ngOnChanges.
}
```

**Comment by ranquild** [comment]
This is common case in our application. I have written few hundred components and I use ngOnChanges hook but don't use parameter. Thousands of `Map<String, SimpleChange>` are created and not used.

**Comment by matanlurey** [comment]
I agree! @hterkelsen and I have talked a little about this, we agree on some sort of fix.

I've actually been leaning more of having methods that accept sets of inputs:

```dart
int sum = 0;

/// Invoked whenever either `foo`, `bar,` or `baz` changes.
void onFooAndBarAndBaz(@Input() int foo, @Input() int bar, @Input() int baz) {
  sum = foo + bar + baz;
}
```

**Comment by alorenzen** [comment]
@matanlurey Why can't we do both? There are some cases where the input methods make sense, but others where you want afterChanges().

**Comment by matanlurey** [comment]
We can definitely do both!

**Comment by matanlurey** [comment]
@ferhatb is tackling `ngAfterChanges`.
