### ISSUE TITLE
Improve IterableDiffer/KeyValueDiffer

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#445]
[To be filled in]

Because this is no longer part of the public API it is not a breaking change.

**Comment by ranquild** [comment]
You can remove differs and update DOM directly within diff function. For example, like this https://github.com/localvoid/uix/blob/master/lib/src/vdom/vnode.dart#L838 . It will require less memory and in most common cases no memory are allocated at all during diff. You could also adopt algorithm for DOM node reuse.

**Comment by matanlurey** [comment]
It's not so straight forward, because we'd have to (a) run change detection in a such a way that it doesn't render [none of our CD is currently setup that way] and (b) diff that virtual tree against either the real DOM (expensive) or yet-another virtual tree (that we don't currently have).

I don't know if I want to be prescriptive in the solution to this problem as a result.

**Comment by matanlurey** [comment]
We are leaning towards just supporting simpler directives that don't need any enhancements.
