### ISSUE TITLE
Type check bound @Outputs

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#449]
From an internal user:

> From what I see there is currently no type check, so if you have a widget doing:
> 
> ```html
>   <foo (x)="do($event)">
> ```
> 
> in you code you can have ``do(AnyType event)`` and it will compile just fine. As we are now moving to compiled templates, could this be made into a typed interface that would cause actual type error if it doesn't match the widget `@Output`?

**Comment by matanlurey** [comment]
@leonsenft WDUT?

**Comment by leonsenft** [comment]
This was probably a Dartium issue as it won't compile in DDC.
