### ISSUE TITLE
nested svg components don't work after upgrade to v3.0.0

### ISSUE THREAD

**Issue by tomas-rokos** [dart-lang/angular#459]
If you clone the repository https://bitbucket.org/tomas-rokos/worklog/src and run web/index.html
you will see that it doesn't work. 

- when you change angular2 version to 2.2.0 everything works fine
- output complains that selector of ClockComponent doesn't have tag name, when I add the tag name, it still works on 2.2.0 and doesn't work on 3.0.0
- I tested also 3.1.0 with the same result as with 3.0.0

Note: While inspecting elements in DOM in the version 3.1.0 and alsovwith tag name, it looks like it was created properly, just not showing and Dartium is not even showing boundary box.

**Comment by ilfa** [comment]
Looks like the same problem as https://github.com/dart-lang/angular/issues/481

**Comment by tomas-rokos** [comment]
This is not the same problem, I don't have a problem to specify element's name, however it doesn't help.

**Comment by matanlurey** [comment]
Closing, I don't expect we're acting on this for now.
