### ISSUE TITLE
Remove Testability and TestabilityRegistry from default providers

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#462]
`Testability` and `TestabilityRegistry` are added to the default list of providers when an application is bootstrapped, even in release builds.

We can't remove them outright just yet, as there are users who depend on these providers to test release builds with WebDriver, but we'd like to.

We should provide an alternative, opt-in mechanism for this functionality to test release builds, and prevent other applications from paying the cost of these unused providers.

**Comment by matanlurey** [comment]
I wonder if the newer `bootstrapFactory` (better name pending) is good enough here?

**Comment by leonsenft** [comment]
Closed since `bootstrapFactory` doesn't provide these services. :smile:

**Comment by leonsenft** [comment]
Well it does provide null for `Testability`, but this is necessary until we resolve the original problem. I suggest we revisit this in the future when (hopefully) everyone has migrated to `bootstrapFactory` and thus removed any dependency on these services.
