### ISSUE TITLE
Explain how change detection works, best practices

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#464]
Specifically, we should outline:

- [x] How we check for changes (broadly) by default
- [x] How 'push' change detection works, and where it doesn't
- [x] What "expression has changed since checked" means and how to act on it
- [x] How to avoid expensive change detection patterns
- [x] What is the best way to "observe" changes to collections
- [x] Using immutable objects efficiently with AngularDart

**Comment by zoechi** [comment]
some info about how to observe collections and objects would be great as well

**Comment by matanlurey** [comment]
@zoechi:

> some info about how to observe collections and objects would be great as well
> and maybe also how to use built_value and built_collection efficiently with Angular

Added to list.

**Comment by alorenzen** [comment]
Did we address all of these with your recent doc?

**Comment by matanlurey** [comment]
@alorenzen No, AFAIK @hterkelsen was going to try and work on this.

**Comment by hterkelsen** [comment]
I wrote a doc which covers some of these topics. I'll update it to include the rest

**Comment by hterkelsen** [comment]
Closed with a86b2f0910a79250f67af0dc9916db70fc333699
