### ISSUE TITLE
Add a --pub-serve argument

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#469]
_From @matanlurey on June 19, 2017 16:30_

This would disable launching `pub serve` by default, and instead delegate to an instance:

```bash
$ pub serve --port 1234
```

```bash
$ angular_test --pub-serve=1234
```

This is important because some "transformers" like dartdevc take quite a bit on first-use, and will often exceed `pkg/test`'s timeouts. Only running as a daemon (incremental rebuilds) makes it worth it, and adding daemon support for `angular_test` is quite a bit of work to get right.

_Copied from original issue: dart-lang/angular_test#74_

**Comment by chalin** [comment]
Fixed via the new `--serve-arg`.

**Comment by matanlurey** [comment]
@chalin Not quite, this basically means "do not run pub serve, the user will spin up pub serve itself". Having `angular_test` emulate daemon-like behavior is going to be expensive to maintain, so it's probably best we just support and document running pub serve manually.
