### ISSUE TITLE
Testing guide should use --test-arg=--platform

### ISSUE THREAD

**Issue by StepFischer** [dart-lang/angular#480]
Hi,

I've tried the [advanced angular testing](https://webdev.dartlang.org/angular/guide/testing) with the [quickstart example](https://github.com/angular-examples/quickstart). Unfortunately executing `pub run angular_test` outputs:

```
The pub serve output is at /tmp/angular_test_pub_serve_output.log.
Run with --verbose to get this output in the console instead.
pub serve test --port=0
Pub "serve" started on http://localhost:46447
Finished compilation. Running tests...
pub run test --pub-serve=46447
No tests ran.
Shutting down...
`pub serve` was not terminated
```

Executing with `--verbose`` results in:

```
pub serve test --port=0
Loading source assets...
Loading angular2, angular2/transform/reflection_remover, test/pub_serve and dart_to_js_script_rewriter transformers...
Pub "serve" started on http://localhost:34653
Serving angular_app test on http://localhost:34653
Finished compilation. Running tests...
pub run test --pub-serve=34653
No tests ran.
Shutting down...
`pub serve` was not terminated
```

any clues, what's wrong?

**Comment by matanlurey** [comment]
As of the latest version of `angular_test` you have to specify a platform manually:

```bash
$ angular_test --test-arg=--platform=dartium
```

Usage: https://github.com/dart-lang/angular/tree/master/angular_test

I'll try to get the docs updated. /cc @kwalrath and @chalin

**Comment by chalin** [comment]
I haven't updated the Testing page because there is already a PR over it with more significant changes (https://github.com/dart-lang/site-webdev/pull/673). I'll discuss with @kwalrath about how to best move forward with this.

**Comment by chalin** [comment]
This issue was moved to dart-lang/site-webdev#792

**Comment by matanlurey** [comment]
Duplicate of https://github.com/dart-lang/site-webdev/issues/792.
