### ISSUE TITLE
Broken attribute selector for component

### ISSUE THREAD

**Issue by ilfa** [dart-lang/angular#481]
In Angular 2 it is correct to create component with attribute selector like this:

```
@Component(
    selector: '[my-selector]',
```

In Angular 3 update, that got broken by this commit https://github.com/dart-lang/angular/commit/c917cc36b6c1612bec70e06dc76149acb7e4393c#diff-ee27b8acd84dc52a6e6ca9be762a0b37R776

Now we can declare component selector only this way (tag is required):

```
@Component(
    selector: 'div[my-selector]',
```

This behaviour limits usage of varied native elements as the component host.

Is it a bug or a feature? There is no info about it in the changelog.

**Comment by matanlurey** [comment]
Yes, I'll have to update the changelog, this is not supported. Thanks!

**Comment by ilfa** [comment]
What the reason not to support this mechanics?
It cause some pain until we are waiting for https://github.com/dart-lang/angular/issues/231

**Comment by matanlurey** [comment]
Good news is #231 landed in master. 

Supporting components that can potentially collide with other components or directives made the compilation process much more complicated (and we emitted worse code).

**Comment by ilfa** [comment]
Great news!

But we've found another bug. Problem with `input`.

```
@Component(
    selector: 'input[my-selector]',
```

This cause error `SmallRectComponentHost: ParseErrorLevel.FATAL: Void elements do not have end tags "input"`
Is it possible to fix it?

**Comment by matanlurey** [comment]
`@Component` with attributes is no longer supported. Sorry.
