### ISSUE TITLE
Possibility for http cache

### ISSUE THREAD

**Issue by eloyleonardo** [dart-lang/angular#485]
Is there any possibility for cache http request ? 
Using angular 1.0 and js i used to use [this lib](https://github.com/jmdobry/angular-cache). 
How can i do this with angular 2 dart ? Or is that planned to be supported ?

**Comment by matanlurey** [comment]
AngularDart doesn't handle any HTTP logic with your logic.

I'd recommend using a first-class HTTP library like [`package:http`](pub.dartlang.org/packages/http). Cheers!
