### ISSUE TITLE
Shim multiple :host-context() selectors correctly

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#500]
In native Shadow DOM, `:host-context(A):host-context(B)` matches all permutations of A and B on the host element or any ancestor element.

The Angular Shadow DOM CSS shim generates rules that match only two permutations: A and B both on the host element, or both on the same ancestor element.

To paraphrase, Angular treats `:host-context(A):host-context(B)` and `:host-context(AB)` equivalently, whereas native Shadow DOM does not.

**Comment by matanlurey** [comment]
@leonsenft Do we intend to act on this?

**Comment by leonsenft** [comment]
@matanlurey Considering the original design was based on a Shadow DOM specification draft which is now irrelevant, I don't see any reason to conform to it. This doesn't seem to be causing our users any issues either, so I'll close it.
