### ISSUE TITLE
Add option to subscribe to event handlers out of angular zone within template

### ISSUE THREAD

**Issue by ranquild** [dart-lang/angular#502]
There are cases when you want to subscribe to event but don't want angular change detection to happen. Common cases are events like scroll, mousemove. They are fired very frequently and subscribing to them deep in component tree will ruin application performance. The only option we have now is to manually subscribe to events outside of zone. This is very verbose. 

What I would like to have is template syntax so subscribe to even outside of angular zone. For example `(:click)="handleClick()`, `@click="handleClick()"`, etc.

**Comment by matanlurey** [comment]
Closing, as we've discussed and having a better on-push/stateful component story will give this to you for free without adding additional complexity to the the template compiler.
