### ISSUE TITLE
Implicit bool bindings for @Input

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#505]
In HTML, it's common to write elements like `<fancy-button raised disabled></fancy-button>`.

In Angular though, this binds I believe either null or empty string if you have @Inputs for raised or disabled. Instead we should follow this pattern:

```dart
@Component(selector: 'fancy-button')
class FancyButtonComponent ]{
  @Input()
  bool raised = false;

  @Input()
  bool disabled = false;
}
```

```html
<fancy-button raised> <-- 'raised' will be true
<fancy-button [raised]> <-- 'raised' will be true
<fancy-button [raised]="true"> <-- 'raised' will be true
<fancy-button [raised]="false"> <-- 'raised' will be false
```

Open questions, but how do we deal with these?

```html
<fancy-button raised="true">
<fancy-button raised="false">
```

Internal issue b/63525768.

**Comment by zoechi** [comment]
Is this only when the type of the input is `bool`? 
What about when it's `String`?

I would require for
```html
<fancy-button raised> <-- 'raised' will be true
<fancy-button [raised]> <-- 'raised' will be true
<fancy-button [raised]="true"> <-- 'raised' will be true
<fancy-button [raised]="false"> <-- 'raised' will be false
```
the input field to be `bool`

and for
```html
<fancy-button raised="true">
<fancy-button raised="false">
```
to be `String` (or `dynamic`, `Object`)
and otherwise rise an error

```html
<fancy-button [attr.raised]="false"> 
```
should remove the attribute

I'm not sure about

```html
<fancy-button [attr.raised]="null"> 
```

**Comment by matanlurey** [comment]
@zoechi:

> Is this only when the type of the input is `bool`? 

Yes.

> What about when it's `String`?

Then we do nothing currently.

> I would require for
> ```html
> <fancy-button raised> <-- 'raised' will be true
> <fancy-button [raised]> <-- 'raised' will be true
> <fancy-button [raised]="true"> <-- 'raised' will be true
> <fancy-button [raised]="false"> <-- 'raised' will be false
> ```
> the input field to be `bool`

👍 

> and for
> ```html
> <fancy-button raised="true">
> <fancy-button raised="false">
> ```
> to be `String` (or `dynamic`, `Object`)
> and otherwise rise an error

Just chatted with @hterkelsen about this and I think that is the plan!

> ```html
> <fancy-button [attr.raised]="false"> 
> ```
> should remove the attribute

I'm not sure how this proposal changes that :)

> I'm not sure about
>
> ```html
> <fancy-button [attr.raised]="null"> 
> ```

I think that's probably out of scope of this FR as well.

**Comment by hterkelsen** [comment]
Closed with https://github.com/dart-lang/angular/commit/44be80868f6b56c4e81d286dd6f61f84250db975
