### ISSUE TITLE
Deprecate: facade/async.dart#EventEmitter

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#52]
`EventEmitter` should be marked `@Deprecated(...)` as it only existed to merge JS/Dart world.

Functionally, an `EventEmitter` is a `StreamController`, except that it implements the `Stream` interface to save you the `controller.stream` call, but also exposes the controller to listeners if they cast, which seems at best, ugly.

Timeline is to mark '@Deprecated()` for a release, and then remove in a future release. We don't have any SLA's around this API, and it should be fairly easy for clients to update since it's just a wrapper API. We won't remove until all internal code is cleaned up, which will take a bit anyway.

**Comment by zoechi** [comment]
It was mentioned several times (Misko, ....) that `EventEmitter` only currently extends `Observable` and is subject to change at any time without notice and it should only be used for `@Output()` and nothing else.

Removing the would make `Stream` and it's full API the "official" `@Output()` API. 

Just dropping what I gathered. It's your call of course if this is relevant at all ;-)

**Comment by matanlurey** [comment]
Yeah, I remember those conversations. Not sure I agree with him since it's clear in Dart you'd use Streams for these type of events... Thanks though!

**Comment by kevmoo** [comment]
@matanlurey something to put in the v3 bucket?

**Comment by matanlurey** [comment]
Pushed to V4.

**Comment by matanlurey** [comment]
This is a large change for most clients, so we're planning to have a migration tool available.

It won't handle 100% of use cases, but will help. It might not be removed by `4.0.0` as a result.
