### ISSUE TITLE
Change in behavior of overriding the attr value assigned by host bindings

### ISSUE THREAD

**Issue by nshahan** [dart-lang/angular#522]
This used to work. Now the host binding has precedence over the the ngFor.

```
@Component(
  selector: 'foo-element',
  template: '<p>Foo Component bar: {{ bar }}</p>',
  host: const {'[attr.bar]': 'bar'},
)
class FooComponent {
  var bar = 'FIVE';
}
```

FooComponent in an ngFor:
```
<div *ngFor="let bar of ['One', 'Two', 'Three']">
  <foo-element [attr.bar]="bar"></foo-element>
  <div>Value of bar: {{ bar }}</div>
</div>
```

Output: 
```
<div class="_ngcontent-pwn-1">
  <foo-element class="_ngcontent-pwn-1" bar="FIVE"><p>Foo Component bar: FIVE</p></foo-element>
  <div class="_ngcontent-pwn-1">Value of bar: One</div>
</div><div class="_ngcontent-pwn-1">
  <foo-element class="_ngcontent-pwn-1" bar="FIVE"><p>Foo Component bar: FIVE</p></foo-element>
  <div class="_ngcontent-pwn-1">Value of bar: Two</div>
</div><div class="_ngcontent-pwn-1">
  <foo-element class="_ngcontent-pwn-1" bar="FIVE"><p>Foo Component bar: FIVE</p></foo-element>
  <div class="_ngcontent-pwn-1">Value of bar: Three</div>
</div>
```

**Comment by leonsenft** [comment]
Just to clarify, we confirmed this has nothing to do with `NgFor` right? You tested this outside of the loop with a single value and the host's `[attr.bar]` binding still overrode the `<foo-element [attr.bar]="...">` binding, correct?

**Comment by nshahan** [comment]
Yes, same problem. That would be a more simple repro.

```
<foo-element [attr.bar]="'HELLO'"></foo-element>
```
Output:
```
<foo-element class="_ngcontent-ndw-1" bar="FIVE"><p>Foo Component bar: FIVE</p></foo-element>
```

**Comment by leonsenft** [comment]
Thanks!

**Comment by leonsenft** [comment]
Hey, could you please confirm if this behavior still occurs when you use `HostBinding` instead of the `host` property in the class annotation:

```dart
@Component(
  selector: 'foo-element',
  template: '<p>Foo Component bar: {{ bar }}</p>',
)
class FooComponent {
  @HostBinding('attr.bar')
  var bar = 'FIVE';
}
```

I suspect it will, but `host` is deprecated so if `HostBinding` happens to fix it, then I suggest you use it instead.

**Comment by leonsenft** [comment]
Actually, there was never a contract that explicitly guaranteed order of bindings. 

Consider the case where you have multiple directives on the same element, and all of them bind the same attribute; what would you expect the behavior to be?

We don't intend to reverse this behavior, as guaranteeing order is complex and can limit or hinder future optimizations.

In the example you gave, using an input on the component which is then bound as an attribute is a suitable solution if you need to override an attribute binding.
