### ISSUE TITLE
RouteParams.get() failed with 'int' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by alescdb** [dart-lang/angular#528]
Hi,

There seems to be a bug in `RouteParams`. 
`RouteParams.params` is defined as `Map<String, String>` but it accepts `int` as parameter.

If I wan't to navigate to my component via  `_router.navigate(['Page', {'page': 1}]);` and in my `PageComponent` I wan't to get the page argument with :

> int _page = int.parse(_routeParams.params['page']);

I got an exception :

> EXCEPTION: type 'int' is not a subtype of type 'String' of 'source' where
> int is from dart:core
> String is from dart:core

So we have an `int` stored inside a `Map<String, String>` which (in my opinion) should have triggered an error before getting there, most likely when `params['page']` is assigned with an `int` instead of `String`.

PS : I know I'm not supposed to pass an `int` to navigate(), but this still looks like a bug

**Comment by zoechi** [comment]
Not sure why you think it's a bug. You do get an exception.

https://github.com/dart-lang/angular/blob/0bb611387d29d65b5af7f9d2515ab571fd3fbee4/angular/lib/src/router/router.dart#L172 is defined as `List<dynamic>`, therefore it can't be checked statically.

**Comment by alescdb** [comment]
Assigning a `int` to a `String` is not a normal behaviour and should not be possible.
I do get an exception, but when accessing `Map<String, String>`, which is in fact something like a `Map<String, dynamic>`.
Accessing a `String` and getting an exception `'int' is not a subtype of type 'String'` is not something we should expect.

This might not specific to RouteParams, since this code produce the same result :

```
main() {
  int myint = 123;
  dynamic mydyn = myint;
  String mystr = mydyn as String;
  print("mystr : ${mystr}");
}
```

In this case, `as String` should have trigger an exception, or return `null` (this is C# behaviour)

**Comment by zoechi** [comment]
This line 
```
String mystr = mydyn as String;
```
does cause the exception.
[DartPad example](https://dartpad.dartlang.org/fbcbce76b72dfe828b47eb332aabe7b9)

**Comment by alescdb** [comment]
Yup, my bad, sorry : 
```
main() {
  int myint = 123;
  dynamic mydyn = myint;
  String mystr = mydyn;

  print("mystr : ${mystr.runtimeType}");
  print("mystr : " + mystr);
}
```

results in :

```
mystr : int
Unhandled exception:
Invalid argument(s): 123
#0      _StringBase.+ (dart:core-patch/string_patch.dart:239)
#1      main (http://localhost:52574/test.dart:7:20)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

**Comment by zoechi** [comment]
And you expect already `String mystr = mydyn;` to throw?
It does when I run it in the console? (haven't tried in Dartium or Chrome)
```
type 'int' is not a subtype of type 'String' of 'mystr' where
```
Did you run in checked mode?

**Comment by alescdb** [comment]
It does throw an exception if I add `--checked`, so this corroborate my first point, `RouteParams.params` should trigger this exception when an `int` is assigned to it ?

**Comment by zoechi** [comment]
Without checked mode, type annotations are ignored (except with strong mode, but strong mode is currently only supported by DDC).

**Comment by matanlurey** [comment]
@zoechi is correct. We only support developing AngularDart in either DDC or Dartium in `--checked` mode. Choosing to use Dartium without `--checked` means we can't do much for you.
