### ISSUE TITLE
Add Scroll Event detector

### ISSUE THREAD

**Issue by yuanjianlg** [dart-lang/angular#533]
It has been a legacy problem reported.

https://github.com/angular/angular/issues/17015
https://github.com/angular/angular/issues/13048

Do we have any plan to resolve it in angular dart?

**Comment by zoechi** [comment]
These linked issues are both invalid.
There is nothing to do. Why do you think there needs something to be resolved?
See also https://github.com/angular/angular/issues/17015#issuecomment-315971676

**Comment by matanlurey** [comment]
I don't think we'll doing anything specific here in AngularDart.

You could look at `angular_components` and see how they handle the problem.
