### ISSUE TITLE
Small, fast, efficient AngularDart apps: the guide

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#545]
Leaving this issue for tracking/discussion.

An internal team mentioned they saw their app drop *5%* in size when they flipped `preserveWhitespace: false` across all components. There are likely other tips/tricks we could publish, so I'd really like to have an even unofficial guide published this quarter.

**Comment by jimmyff** [comment]
Would it be possible that `preserveWhitespace` could be implemented as a build step/flag? It would be ideal if we were able to continue developing with whitespace in templates however like `dart2js`, stripping the whitespace becomes a build step that we can do when deploying to staging & production environments?

**Comment by alorenzen** [comment]
Pinging this as we work on Best Practices docs.

**Comment by matanlurey** [comment]
@jimmyff:

> Would it be possible that `preserveWhitespace` could be implemented as a build step/flag? 

Not likely. Are you OK With the proposal in https://github.com/dart-lang/angular/issues/804 instead?

@alorenzen:

> Pinging this as we work on Best Practices docs.

@leonsenft @hterkelsen, would you be interested in starting a short doc here?
