### ISSUE TITLE
WISH: provide public getter for NgTestFixture::_applicationRef

### ISSUE THREAD

**Issue by tomas-rokos** [dart-lang/angular#559]
I would like to ask for public getter for NgTestFixture::_applicationRef, now I need to wrap every component with class which captures ApplicationRef pointer in constructor. I need it to have an access to injector object for tested component.

**Comment by matanlurey** [comment]
Could you explain your use case? When do you find this useful? Do you have some examples?

**Comment by tomas-rokos** [comment]
Sure, maybe it's just my way of improperly using angular_test package.

In general: I use services to feed my components. Inside tests I use stubbed override of such service. During testing I need to setup initial state or manipulate the state and observe component if reacting properly.

Now let's have one real example. I have component which displays if there is any new message, it's simple envelope.  When regular, no new messages, when special css-class applied (filled, bold) there are new messages. I have service which has opened query to my firebase database and provides Stream<int> to component, with number of unread messages. During testing, I derive the service and do not connect to firebase, but have special method to supply new # of messages explicitly. 
Now the need of get to the instance of stubbed service is present. 

I could provide sample code if necessary.

**Comment by matanlurey** [comment]
> Sure, maybe it's just my way of improperly using `angular_test` package.

/shrug. `angular_test` is relatively new and we don't have a lot of publish examples so I don't blame your usage. I just want to understand it.

> In general: I use services to feed my components. Inside tests I use stubbed override of such service. During testing I need to setup initial state or manipulate the state and observe component if reacting properly.

Sounds reasonable.

> Now let's have one real example. I have component which displays if there is any new message, it's simple envelope.  When regular, no new messages, when special css-class applied (filled, bold) there are new messages. I have service which has opened query to my firebase database and provides `Stream<int>` to component, with number of unread messages. During testing, I derive the service and do not connect to firebase, but have special method to supply new # of messages explicitly. 

> Now the need of get to the instance of stubbed service is present. 

> I could provide sample code if necessary.

That would be very useful!

**Comment by matanlurey** [comment]
Ping @tomas-rokos could I have some example code?

**Comment by tomas-rokos** [comment]
[ng_testing.zip](https://github.com/dart-lang/angular/files/1179449/ng_testing.zip)

Sorry, took me a day, as playing with multiple balls :)

Here is a sample library I created for this purpose. You see that there is component num-updates feed by DataProvider. In library (web) version I have timer for two seconds which mimic query to database. In testing I have DataProviderStub, where I have explicit method to send a new data.

**Comment by matanlurey** [comment]
Doesn't `useValue` work?

```dart
NgTestBed<ComponentTest> testBed;
DataProviderStub stub; 

setUp(() async {
  stub = new DataProviderStub();
  testBed = new NgTestBed<ComponentTest>().addProviders([
    new Provider(DataProvider, useValue: stub),
  ]);
});

test('...', () {
  // configure stub
});
```

**Comment by matanlurey** [comment]
Ping @tomas-rokos

**Comment by tomas-rokos** [comment]
This approach looks fine, I am validating it right now with all of the usage I made so far, so it takes a time, to be clearly sure. Let's close this ticket right now and we could reopen it when necessary.

Thank you for your help!
Tomáš
