### ISSUE TITLE
Remove multiple transformers

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/angular#562]
Right now, we have a main angular transformer with multiple phases, as well as the ability to run each phase as a separate transformer.

However, due to the way that barback runs, having multiple transformers spans multiple isolates and does too much duplicative work. Thus, the benefit of being specific on what work needs to be done is outweighed by the overhead of barback.

Thus, we should just remove the more specific transformers and only support the main one.

**Comment by matanlurey** [comment]
Done.
