### ISSUE TITLE
Ng form validate

### ISSUE THREAD

**Issue by arcas0803** [dart-lang/angular#565]
When ng-controls does not validate the onSubmit does not fire. That ok, but if the inputs are empty (using material-input) the onSubmit function fires up while ng-form.valid is false.

**Comment by TedSander** [comment]
Sorry some clarification here would help? are you talking about when using the required attribute on material-input? If so I have a fix for this pending.

**Comment by arcas0803** [comment]
yes thats what i mean. Thanks. I close this.
