### ISSUE TITLE
Passing a String to AbstractControl.find throws exception navigating into ControlArray

### ISSUE THREAD

**Issue by joshua-i** [dart-lang/angular#569]
It's easy to see the problem from looking at the code, but I think the simplest repro is
```dart
new ControlArray([new Control()]).find('0');
```
This should return the inner control, but it just throws an exception downcasting to num [here](https://github.com/dart-lang/angular/blob/e06c3c53054270a32699c50ad8f15159fc4b4c35/angular/lib/src/common/forms/model.dart#L19). When a string path was passed in, it is just split along "/", so the name will be a String, not a num, and the cast will fail. It should probably check whether name is a string and attempt to parse an int from it.

This also affects more complex paths like 'foo/2/bar' and methods like setErrors, which uses find.

As a side note, it would be nice to document find to describe the expected argument. The only way to know what it expects you to pass it (e.g. that the path separator is '/') is to dig through the impl.

**Comment by TedSander** [comment]
ControlArray has a lot of holes on working with the rest of the forms system. There is no really way to use it only from a template syntax for example.

I think we will get around fixing these holes, but it won't be in the near term. Contributions are welcome to help make it more consistent with the rest of forms.

**Comment by alorenzen** [comment]
I've been making some other changes in this code, so this should be easy to address while I'm there.
