### ISSUE TITLE
Improve library descriptions

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/angular#580]
All the libraries in the angular package (e.g. https://webdev-dartlang-org-dev.firebaseapp.com/angular/api/angular/angular-library, https://webdev-dartlang-org-dev.firebaseapp.com/angular/api/angular.security/angular.security-library) should have a description that includes at least:

* A brief description of the library and when you'd use it
* An example of importing the library
* Info/examples (or link(s) to info/examples) to help the reader find & use the library's most important/useful APIs

Related to dart-lang/site-webdev#787

**Comment by alorenzen** [comment]
Internally, we've settled on angular.dart, security.dart, and di.dart, and I suppose experimental.dart as the only available libraries.

We still need to do some refactoring on the code before we can remove the other libraries in the external repo (core.dart and source_gen.dart). So you can ignore those.

**Comment by kwalrath** [comment]
I've created internal changelists for angular.dart, security.dart, and di.dart, but we've decided not to include di.dart in the API reference, because it's not something we want to encourage people to use.

/cc @chalin

**Comment by chalin** [comment]
Ok, FYI, the DI package isn't published as part of the webdev API reference (under webdev nor the temporary 4.x site ); e.g. https://webdev-dartlang-org-dev.firebaseapp.com/angular/api.

**Comment by kwalrath** [comment]
Fixed by:

* ce8a45ee3647adafc03e76f002f6008b7d588f55 (angular.dart description)
* 3b6c5dccb60b6fbdb532324651c1c835cff8a30f (security.dart description)
* 17290b4a20799ac273edb6786e6f3e841a7f4cf9 (experimental.dart description; stops doc generation for remaining libraries)
