### ISSUE TITLE
can't use a combination of `dart:js` and `package:js`

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/angular#583]
Any component with children using a combination of dart:js and package:js will cause the following error when running `callMethod(methodName)`

To reproduce:

1. create an angular2 app with a component parent_component
2 create a child component that uses dart:js (e.g. codemirror)
3. create a child component that uses package:js (e.g. chart.js)
4. observe codemirror dart:js child component returns JsObjectImpl that is not a subtype of JsObject

**Comment by zoechi** [comment]
Is this only in Dartium or also in Chrome?

**Comment by johnpryan** [comment]
also in chrome

**Comment by johnpryan** [comment]
In fact, there are simpler steps to reproduce:

1. create an angular2 component that uses `dart:js` (e.g. codemirror)
2. observe the component works correctly
3. import a package that uses `package:js` (e.g. chartjs`)
4. observe the component now breaks even though `package:js` is not being used directly, just imported.

**Comment by matanlurey** [comment]
I don't know if this is something specific to AngularDart unfortunately.

Would you mind filing this in the core repo?

**Comment by johnpryan** [comment]
I'll make an effort to create a two sample projects (angular and non-angular) to see how they differ

**Comment by matanlurey** [comment]
Please re-open if end up finding anything specific to AngularDart here.
