### ISSUE TITLE
TemplateGenerator reports errors, but pub build returns exit code 0

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#584]
When I run `pub build` over the Angular doc examples, it exits with a status of 0 even if the `TemplateGenerator` reports errors. E.g.:

```nocode
toh-1 > pub build
Loading source assets... 
Loading angular, test/pub_serve and dart_to_js_script_rewriter transformers... 
Building angular_tour_of_heroes... (25.1s)
[BuilderTransformer: Instance of 'LibraryBuilder' on angular_tour_of_heroes|primary]:
Error running TemplateGenerator for angular_tour_of_heroes|lib/app_component.dart.
Error: Template parse errors:
line 6, column 14 of AppComponent: ParseErrorLevel.FATAL: Can't bind to 'ngModel' since it isn't a known native property or known directive. Please fix typo or add to directives list.
[(ngModel)]="hero.name"
^^^^^^^^^^^^^^^^^^^^^^^
...
Built 518 files to "build".
toh-1 > echo $?
0
```

I'm unsure if this is an issue with the transformer or pub.

Of course, this is a problem when running `pub build` as part of build scripts on Travis, etc.

Angular: 4.0.0-alpha+3

cc @kwalrath

**Comment by alorenzen** [comment]
NgModel is now part of angular_forms. Did you add an import / dependency on that?

**Comment by chalin** [comment]
Yes, but this issue isn't about the specifics of the failure (which were easy to solve). It asks why pub returns an exit status of 0 (i.e., that everything is fine), when the template generator actually failed.

**Comment by matanlurey** [comment]
This issue was moved to dart-lang/pub#1691
