### ISSUE TITLE
Selector for @ContentChild/@ContentChildren

### ISSUE THREAD

**Issue by ilfa** [dart-lang/angular#587]
Hi!

It looks like @ContentChild/@ContentChildren doesn't support common selectors like `.my-class` `my-element`, `[my-attribute]`. And `selector` find only elements like this `<my-element #selector></my-element>`.

Is it OK, or will be fixed in future?

**Comment by zoechi** [comment]
`@ContentChild()` and `@ViewChild()` are not supposed to allow querying for arbitrary elements.
It has to be statically known which one it queries for. Class and attribute selectors don't match this criteria.
Just add a template variable to the elements you want to query for, and query for that instead.

```html
<div #myTmpl>div1</div>
<div #myTmpl>div2</div>
```
```dart
@ViewChild('myTmpl') QueryList<Element> divs;
```
To query for arbitrary elements, you can inject `Element` (Angular 4) or `ElementRef` (Older Angular versions) and use

```dart
Element hostElement;
MyComponent(this.Element);
hostElement.querySelector('.my-class');
```

**Comment by ilfa** [comment]
Thanks! Now it's clear for me.
Do you have plans to add this info in documentation?

**Comment by zoechi** [comment]
@ranquild @aeter @ilfa any comment what you don't like about my above comment?

**Comment by ilfa** [comment]
It looks not good that `<ng-content>` and `@ContentChildren` use different mechanics for item selection.

**Comment by ranquild** [comment]
@zoechi It seems to me that querySelector can introduce side effects and it is better to avoid it in SPA as much as possible.

**Comment by Aetet** [comment]
@zoechi I think angular must move towards to dynamic api creation components wherever it could be happened. And not rely on render once component tree structure.

**Comment by zoechi** [comment]
@Aetet sounds to me like you are looking for something different than Angular ;-)

**Comment by Aetet** [comment]
@zoechi virtual dom now helps resolve all issue with dom representation. It optimize operation with large collections out of the box. Also it helps to use composition more often and bring new effectiveness to create community reusable components.

**Comment by matanlurey** [comment]
AngularDart has no plans to implement or use virtual-dom.
