### ISSUE TITLE
The example in ComponentLoader#loadNextToLocation docs has some mistypings

### ISSUE THREAD

**Issue by furrary** [dart-lang/angular#598]
Is this the right place to report document issues?

On this [page](https://webdev-dartlang-org-dev.firebaseapp.com/api/angular/angular/ComponentLoader/loadNextToLocation), the constructor should be `AdViewComponent` instead of `AdViewDirective` and the quotation is quite off.

**Comment by kwalrath** [comment]
Thanks for the bug report. This *is* the right place to report API doc issues.
