### ISSUE TITLE
API docs: OnInit has inlined code and no longer links to Lifecycle docs

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#602]
@matan: The APIs to some of the lifecycle hook interfaces were updated in this commit https://github.com/dart-lang/angular/commit/0f1abe5b9e2abfd537956271eead6ee6786c1b3c#diff-d9e2200e3226057f249e806a7e95d1adL76.

Consider OnInit as an example. Under [3.x, the OnInit documentation](https://webdev.dartlang.org/api/angular2/angular2/OnInit-class) has an "Example" section with

- A(n auto-updatable) code excerpt of (CI tested) code from the AngularDart doc examples
- A link to the AngularDart docs "Lifecycle Hooks" page.

In the [4.x OnInit API page](https://webdev-dartlang-org-dev.firebaseapp.com/api/angular/angular/OnInit-class), this has been replaced by inlined code block. Admittedly, the old example wasn't as good as it could be, but better ones can be found.

**My question is**: do we still want to stick to the old format of API docs along the lines of (the current 3.x docs):

> ## Examples
>
> Try the [live example](#) from the [Some docs page](#):
>
> \<?code-excerpt "docs/lifecycle-hooks/lib/spy_directive.dart (spy-directive)"?>
> [auto-updated codeblock]

cc @kwalrath

**Comment by kwalrath** [comment]
Oops, this should be @matanlurey, not that other Matan...

**Comment by chalin** [comment]
Oops indeed. Thanks for noticing!
