### ISSUE TITLE
Changelog: note between 4.x and 3.x section the package rename

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#609]
Otherwise, folks may be confused...

**Comment by alorenzen** [comment]
Um, didn't we mention this first line of the changelog?

**Comment by kevmoo** [comment]
Yeah – but if you're scrolling down to 3.x it might be worth reminding folks – that it's a version for another package

**Comment by matanlurey** [comment]
Feel free to send a CL/PR, but I don't know what else to do myself.
