### ISSUE TITLE
Tag release as 4.0.0, rather than 4.0

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#611]
The release is currently tagged as [4.0](https://github.com/dart-lang/angular/releases/tag/4.0).
Could it be retagged as 4.0.0 to be consistent with all other version tags? (This is currently causing problems on the doc generation site.)

cc @matanlurey @kwalrath @kevmoo

**Comment by kevmoo** [comment]
Happily!

**Comment by kevmoo** [comment]
Done!
