### ISSUE TITLE
[4.0.0] injector.get(tokenDNE, default) returns null instead of default

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#612]
The following code from the AngularDart doc [dependency-injection](https://github.com/dart-lang/site-webdev/tree/4-dev/examples/ng/doc/dependency-injection) example used to work under 4.0.0-alpha (maybe also -beta):

```dart
@Component(
    selector: 'my-injectors',
    template: '''
      <h2>Other Injections</h2>
      <div id="car">{{car.drive()}}</div>
      ...
      <div id="rodent">{{rodent}}</div>''',
    providers: const [...])
class InjectorComponent {
  final Injector _injector;
  Car car;
  ...
  InjectorComponent(this._injector) {
    car = _injector.get(Car);
    ...
  }

  String get rodent =>
    _injector.get(ROUS, "R.O.U.S.'s? I don't think they exist!");
}
```

That is, the default string `"R.O.U.S.'s? I don't think they exist!"` would be displayed for ROUS (which isn't being provided at any level of the app).

Now, in 4.0, `_injector.get(ROUS, "R.O.U.S.'s? I don't think they exist!")` returns null.

cc @kwalrath @kevmoo

**Comment by kevmoo** [comment]
CC @matanlurey @alorenzen

**Comment by matanlurey** [comment]
Yup, this is a bug, and I think I have a fix. Thanks!
