### ISSUE TITLE
Changelog should say angular requires 1.24

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/angular#615]
As of https://github.com/dart-lang/angular/commit/991eab32a663604d6f76488b8becf75f4371b32b, the `angular` package requires the 1.24 SDK. We should explicitly say so in the changelog.

Maybe it should be under breaking changes?

**Comment by matanlurey** [comment]
Given that we are unlikely to push another 4.x, I'm closing as infeasible :-/
