### ISSUE TITLE
*ngFor broken in angular(4)

### ISSUE THREAD

**Issue by rickbsgu** [dart-lang/angular#616]
See StackOverflow issue: https://stackoverflow.com/questions/46008662/ngfor-not-working-in-dart-angular4

**Comment by rickbsgu** [comment]
Answered.  Need to add NgFor to directives list.  I'm sure this is documented somewhere, but I couldn't find it.

**Comment by kwalrath** [comment]
/cc @chalin 

In the AngularDart guide, [Displaying Data](https://webdev.dartlang.org/angular/guide/displaying-data) & [Structural Directives](https://webdev.dartlang.org/angular/guide/structural-directives) show using ngFor and specifying the directives list, but they don't explicitly link them. [Template Syntax](https://webdev.dartlang.org/angular/guide/template-syntax) doesn't seem to show `directives:` at all. The main place where this is covered seems to be the [Component directives](https://webdev.dartlang.org/angular/tutorial/toh-pt1#!#componentdirectives-) section of the tutorial.

In the API docs, [NgFor](https://webdev.dartlang.org/api/angular/angular/NgFor-class) doesn't mention the directives list, although it does refer to [Template Syntax's ngFor section](https://webdev.dartlang.org/angular/guide/template-syntax#!#ngFor).

We should mention the directives list in both the guide and the API docs, wherever appropriate. It could be a standard note that links to the Component directives section. I'll open a couple of doc bugs about this.

**Comment by kwalrath** [comment]
There's already a webdev bug for this: dart-lang/site-webdev#857

**Comment by jonahwilliams** [comment]
This is also a good case for better error messages.  Unless someone is already very familiar with Angular, then `ParseErrorLevel.FATAL: Property binding ngForOf not used by any directive on an embedded template` Is unlikely to be helpful in anyway.  Related bug: #447

**Comment by kwalrath** [comment]
I believe that https://github.com/dart-lang/angular_analyzer_plugin will help people find these errors early. But we should still cover this in the docs.
