### ISSUE TITLE
Deprecate COMMON_DIRECTIVES

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#617]
Given that COMMON_DIRECTIVES is now just an [alias for CORE_DIRECTIVES](https://github.com/dart-lang/angular/blob/e22f0e9ef32dd162c2ce0c9d17271341ef4c40d9/angular/lib/src/common/common_directives.dart#L56-L58), should COMMON_DIRECTIVES be deprecated?

cc @kwalrath

**Comment by zoechi** [comment]
better deprecate both and add `coreDirectives` instead
