### ISSUE TITLE
Add directives: note to all directives' API doc

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/angular#621]
See #616 for more info.

**Comment by chalin** [comment]
In #616, [you wrote](https://github.com/dart-lang/angular/issues/616#issuecomment-327311046):

> There's already a webdev bug for this: dart-lang/site-webdev#857

dart-lang/site-webdev#857 has been addressed. Does that mean that we can close this issue?

**Comment by kwalrath** [comment]
Although we've fixed this issue in the webdev guides, it's still a problem in the API docs.
