### ISSUE TITLE
Forms not setting 'pristine' property on control change

### ISSUE THREAD

**Issue by sambbaron** [dart-lang/angular#627]
On form control changes, controls are only being set as dirty and not being tested for pristine status. Also, `AbstractControl` does not have related methods `markAsPristine` and `reset`.

In Angular1, NgModel captured `_originalValue` and set pristine on value change. Are there plans to implement this in the current version of Angular?

**Comment by alorenzen** [comment]
This is a duple of https://github.com/dart-lang/angular/issues/216
