### ISSUE TITLE
Bad state: No element when using routes

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/angular#630]
once I add routes to a component it throws a stack trace within the builder:

`[BuilderTransformer: Instance of 'LibraryBuilder' on mongaba_admin|primary]:
Error running TemplateGenerator for mongaba_admin|lib/app_component.dart.
Error: Bad state: No element
Stack Trace:
#0      Object&ListMixin.firstWhere (dart:collection/list.dart:133)
#1      ReflectableEmitter.emitInitReflector (package:angular_compiler/src/emitter/reflector.dart:63)
#2      buildGeneratedCode (package:angular/src/source_gen/template_compiler/code_builder.dart:55)
#3      TemplateGenerator.generate.<anonymous closure> (package:angular/src/source_gen/template_compiler/generator.dart:31)
<asynchronous suspension>
#4      _rootRun (dart:async/zone.dart:1120)
#5      _CustomZone.run (dart:async/zone.dart:1001)
#6      runZoned (dart:async/zone.dart:1467)
#7      TemplateGenerator.generate (package:angular/src/source_gen/template_compiler/generator.dart:28)
<asynchronous suspension>
#8      _generate (package:source_gen/src/builder.dart:203)
<asynchronous suspension>
#9      _Builder._generateForLibrary (package:source_gen/src/builder.dart:79)
<asynchronous suspension>
#10     _Builder.build (package:source_gen/src/builder.dart:69)
<asynchronous suspension>
#11     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:35)
<asynchronous suspension>
#12     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#13     ListIterator.moveNext (dart:_internal/iterable.dart:342)
#14     Future.wait (dart:async/future.dart:355)
#15     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:41)
#16     _rootRun (dart:async/zone.dart:1120)
#17     _CustomZone.run (dart:async/zone.dart:1001)
#18     runZoned (dart:async/zone.dart:1467)
#19     scopeLog (package:build/src/builder/logging.dart:12)
#20     runBuilder (package:build/src/generate/run_builder.dart:41)
<asynchronous suspension>
#21     BuilderTransformer._apply (package:build_barback/src/transformer/transformer.dart:94)
<asynchronous suspension>
#22     BuilderTransformer.apply.<anonymous closure> (package:build_barback/src/transformer/transformer.dart:51)
#23     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#24     ListIterator.moveNext (dart:_internal/iterable.dart:342)
#25     Future.wait (dart:async/future.dart:355)
#26     BuilderTransformer.apply (package:build_barback/src/transformer/transformer.dart:51)
<asynchronous suspension>
#27     _EagerAggregateTransformerWrapper.apply (package:angular/src/transform/common/eager_transformer_wrapper.dart:36)
#28     _serializeAggregateTransformer.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:$pub/serialize/transformer.dart:72)
#29     new Future.sync (dart:async/future.dart:206)
#30     _serializeAggregateTransformer.<anonymous closure>.<anonymous closure> (package:$pub/serialize/transformer.dart:70)
#31     respond.<anonymous closure> (package:$pub/serialize.dart:150)
#32     new Future.sync (dart:async/future.dart:206)
#33     respond (package:$pub/serialize.dart:150)
#34     _serializeAggregateTransformer.<anonymous closure> (package:$pub/serialize/transformer.dart:57)
#35     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#38     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#39     _StreamController._add (dart:async/stream_controller.dart:667)
#40     _StreamController.add (dart:async/stream_controller.dart:613)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
Build completed with 1 errors.
`
As spoken to @natebosch , 
[GuaraciBuildError.tar.gz](https://github.com/dart-lang/angular/files/1303515/GuaraciBuildError.tar.gz)
the source is attached.

**Comment by matanlurey** [comment]
Unfortunately prefixing the router library (`@router.RouteConfig`) is not supported.

I can add a better error message, but given that the old router will be deprecated in 5.x, it is not on my priority list. I recommend importing without a prefix in this case, and just using `hide` and `show` if you have conflicts. Sorry about that.

**Comment by natebosch** [comment]
Will the new router handle this usage or fail with a better message?

**Comment by matanlurey** [comment]
The new router is imperative and has no annotations to process.

**Comment by jodinathan** [comment]
The error is gone away with the removal of the prefix, however, I am still unable to use AsyncRoute with the angular_router lib.
Once I try to navigate to the route, this error prints in the console:

`EXCEPTION: No precompiled component ViewUserLoginComponent found
STACKTRACE: 
No precompiled component ViewUserLoginComponent found
    at Object.wrapException (http://local.meuwebinar.com.br:8081/main.dart.js:4382:17)
    at ReflectorComponentResolver.resolveComponentSync$1 (http://local.meuwebinar.com.br:8081/main.dart.js:27685:19)
    at Object.getComponentAnnotations (http://local.meuwebinar.com.br:8081/main.dart.js:63808:30)
    at RouteRegistry.configFromComponent$1 (http://local.meuwebinar.com.br:8081/main.dart.js:61994:25)
    at http://local.meuwebinar.com.br:8081/main.dart.js:61902:38
    at _wrapJsFunctionForAsync_closure.$protected (http://local.meuwebinar.com.br:8081/main.dart.js:7279:15)
    at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (http://local.meuwebinar.com.br:8081/main.dart.js:7791:14)
    at _awaitOnObject_closure.dart._awaitOnObject_closure.call$1 (http://local.meuwebinar.com.br:8081/main.dart.js:7779:34)
    at StaticClosure.dart._rootRunUnary.func (http://local.meuwebinar.com.br:8081/main.dart.js:7635:18)
    at _ZoneDelegate.runUnary$3 (http://local.meuwebinar.com.br:8081/main.dart.js:10724:41)`

I changed the code and added the cmpLogin.initReflector() as @matanlurey:

`
import 'package:mongaba_admin/routes/user/login_component.dart' deferred as cmpLogin;

Future<dynamic> loadUserLogin() =>
		cmpLogin.loadLibrary().then((_) {
      cmpLogin.initReflector();
  return cmpLogin.ViewUserLoginComponent;
});`

However, then it throws no such method:

`EXCEPTION: NoSuchMethodError: method not found: 'initReflector'
Receiver: ""
Arguments: []
STACKTRACE: 
NoSuchMethodError: method not found: 'initReflector'
Receiver: ""
Arguments: []
    at Object.wrapException (http://local.meuwebinar.com.br:8081/main.dart.js:4382:17)
    at Object.throwNoSuchMethod (http://local.meuwebinar.com.br:8081/main.dart.js:4861:15)
    at loadUserLogin_closure.dart.loadUserLogin_closure.call$1 (http://local.meuwebinar.com.br:8081/main.dart.js:66763:11)
    at StaticClosure.dart._rootRunUnary.func (http://local.meuwebinar.com.br:8081/main.dart.js:7638:18)
    at _ZoneDelegate.runUnary$3 (http://local.meuwebinar.com.br:8081/main.dart.js:10727:41)`

I am using SyncRoutes to develop, but will need the asyncroutes for production

**Comment by matanlurey** [comment]
You need to import the _generated_ code:

```dart
import 'package:mongaba_admin/routes/user/login_component.template.dart' 
    deferred as cmpLogin;

...
```

That is what has `initReflector` in it.

**Comment by jodinathan** [comment]
it worked. 
Jesus, it worked.

thanks
