### ISSUE TITLE
angular_router 2: can't run component tests since pubspec is incomplete, etc

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#636]
I'd like to be able to run the project local component tests but I can't. In particular because of missing entries in the pubspec (which doesn't have any of the usual dev_dependencies). I've tweaked the pubspec, but there are other issues preventing the tests from being run.

cc @kwalrath @matanlurey

**Comment by chalin** [comment]
I still can't run the tests. The `angular_router` pubspec needs at least a `dev_dependency` on `angular_router.example`.

**Comment by chalin** [comment]
It would also be helpful to add a few lines to the README about how to run tests (both the browser and vm tests).

**Comment by alorenzen** [comment]
So now that we integrate with `mono_repo` tool, this is actually really easy. You can just run `mono_repo presubmit --recursive` to essentially run the entire travis test suite locally.

Not sure where exactly we want to add this in the documentation, I could see it going in either `README.md` or `CONTRIBUTING.md`.

**Comment by matanlurey** [comment]
@alorenzen Welcome back! `CONTRIBUTING` sgtm!
