### ISSUE TITLE
Add support for new function type syntax

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#651]
I imagine we don't have support for the following syntax:

```dart
@Component(...)
class Comp {
  @Input()
  List<void Function(Animal animal)> animalFunctions;
}
```

... very-short term we could drop type information (go down to `Function`), if the compiler crashes currently with this syntax. But otherwise we need to be able to support the structurally typed function syntax in the collector/emitter.

**Comment by matanlurey** [comment]
@leonsenft did you do this already?

**Comment by leonsenft** [comment]
@matanlurey No I haven't looked into this.

**Comment by matanlurey** [comment]
I'd rather we open more specific issues, where relevant, than this one. Not actioanable.
