### ISSUE TITLE
Form Validator doesn't work when condition is passed dynamically

### ISSUE THREAD

**Issue by dnp1** [dart-lang/angular#660]
while this works:
`<input type="password" required placeholder="Senha"
               [(ngModel)]="login.password"
               minlength="12"
               #password="ngForm" [ngClass]="controlStateClasses(password)  "
               ngControl="password"/>`

This doesn't work:
`
<input type="password" required placeholder="Senha"
               [(ngModel)]="login.password"
               [attr.minlength]="passwordMinLength"
               #password="ngForm" [ngClass]="controlStateClasses(password)  "
               ngControl="password"/>
`
Inspecting the page, I can see the minlength there at DOM.

IS The same beahviour quoted in the link below:
https://stackoverflow.com/questions/44792313/angular-dart-how-can-i-make-the-attribute-minlength-to-work-with-a-dynamic-val

**Comment by dnp1** [comment]
It was already solved in Angular.io.
https://github.com/angular/angular/issues/7393

I'll submit a pull request that solves it soon.

**Comment by TedSander** [comment]
Thanks for the offer of the pull request.

I think I'd like to make this a breaking change (only allow int expressions, not strings) and not have the validator recreate itself on each change.

Since I'd like this to be a larger breaking change I'll work on getting it done. Should get it done this week.

**Comment by alorenzen** [comment]
@TedSander is this fixed?

**Comment by TedSander** [comment]
Yep sorry for not closing.
