### ISSUE TITLE
Reduce compiled templates code size

### ISSUE THREAD

**Issue by ranquild** [dart-lang/angular#665]
We have large dart/angular application that compiles to 20mb minified javascript. With dart2js_info package I checked impact of *.template.dart libraries and found that they take ~50% of space. Overhead of AOT compilation is huge and its crucial for us to have this size reduced.

**Comment by matanlurey** [comment]
Thanks for filing @ranquild. It would be good to gather some information:

* What version of Dart `dart --version`?
* What version of AngularDart? (check your _pubspec.lock_)
* What parameters to `$dart2js` (transformer) do you have?
  * `--trust-type-annotations`?
  * `--trust-primitives`?

* What is the size of your application as a debug build (`pub build --mode=debug`)?

* Are you using `dart:mirrors`?
* Are you using `noSuchMethod` at all (directly or transitively)?

If you're able to share a "dump info", even privately - that would be great:
https://github.com/dart-lang/dump-info-visualizer

----

As noted on some related issues, we are actively working on code size improvements:

* https://github.com/dart-lang/angular/issues/629

If you're able to start using `5.x-alpha` releases, there are some aggressive (and undocumented) new ways of bootstrapping AngularDart that should allow vastly more tree-shaking of `.template.dart` files, but remove support for some features - namely using `ReflectiveInjector` or `SlowComponentLoader`. As soon as there is something available I can let you know.

**Comment by kevmoo** [comment]
Also, @ranquild – are you using https://github.com/dart-lang/angular_components ?

If so, how are you referencing them?

**Comment by ranquild** [comment]
@matanlurey Hi, thanks for fast response. I was wrong in first message, compiled dart code is only 12mb and not 20 ;)
1) Dart VM version: 1.24.2
2) 3.1 currently
3) 
```
$dart2js:
    checked: false
    minify: true
    sourceMaps: true
    suppressWarnings: false
    suppressHints: false
    csp: false
    commandLineOptions:
    - --trust-primitives
    - --trust-type-annotations
```
4) in debug mode with `minify: false` - 38.4 mb.
5) no `dart:mirrors`
6) no "tricky" `noSuchMethod` used. That's why in info.json file `"noSuchMethodEnabled": false`.

@kevmoo No, angular_components are not used.

**Comment by TedSander** [comment]
Are you using perserveWhitespace: false in the components? Might want to try migrating over if you aren't we have seen significant size reductions in template files with that option.

**Comment by ranquild** [comment]
@TedSander Yes, we use `perserveWhitespace: false` in all components.

**Comment by ranquild** [comment]
@matanlurey Sent info.json in gitter in private channel.

**Comment by ranquild** [comment]
@matanlurey We will upgrade to 4.x in few months.

**Comment by alorenzen** [comment]
I'm going to go ahead and close this issue.

Code size is something we track very closely, and have improved in every release to date. Please update to 4.x or even 5.0-alpha to see improvements.

Given the comments by @matanlurey @TedSander and @kevmoo, we probably need a "best practices" doc for reducing code size.
