### ISSUE TITLE
5.0.0-alpha is broken, needs analyzer dependency revved

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#668]
Workaround:

```yaml
dependency_overrides:
  analyzer: ^0.31.0-alpha.1
```

... and `pub upgrade`. We don't have any tests that would have caught this 😢 

Additionally, @kevmoo is saying checking this in might be a problem, `pkg/test` and `pkg/build` don't support this package. It might be a requirement to use `dependency_overrides` for the time being.

**Comment by kevmoo** [comment]
I've been able to use it fine locally...with a dev SDK

**Comment by matanlurey** [comment]
It breaks if you inject a TypeDef
