### ISSUE TITLE
AppView performance investigation

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#670]
Here are some remaining elements of `AppView` that look suspect:

## `.flatRootNodes`:

```dart
List<Node> get flatRootNodes {
  return _flattenNestedViews(viewData.rootNodesOrViewContainers);
}

List<Node> _flattenNestedViews(List nodes) {
  return _flattenNestedViewRenderNodes(nodes, <Node>[]);
}

List<Node> _flattenNestedViewRenderNodes(List nodes, List<Node> renderNodes) {
  int nodeCount = nodes.length;
  for (var i = 0; i < nodeCount; i++) {
    var node = nodes[i];
    if (node is ViewContainer) {
      ViewContainer appEl = node;
      renderNodes.add(appEl.nativeElement);
      if (appEl.nestedViews != null) {
        for (var k = 0; k < appEl.nestedViews.length; k++) {
          _flattenNestedViewRenderNodes(
              appEl.nestedViews[k].viewData.rootNodesOrViewContainers,
              renderNodes);
        }
      }
    } else {
      renderNodes.add(node);
    }
  }
  return renderNodes;
}
```

@jonahwilliams noticed this was critical path in creating standalone embedded views (i.e. to use in a table, or other standalone repetitive component). He found the following API in use to get the "first" root node:

```dart
final rootNodes = (ref.hostView as EmbeddedViewRef).rootNodes;
intoDomElement.append(rootNodes.first);
return ref;
```

He tried using `ComponentRef.location`, but that seems to have (non?)significant whitespace compared to the above code, which causes tests to fail. The tests might be too strict, or it's possible we need to expose some sort of `.firstRootNode` as a convenience.

**Comment by jonahwilliams** [comment]
I did some more investigation and I haven't noticed any significant whitespace when using `componentRef.location`.  The test in question is most likely too strict.

**Comment by alorenzen** [comment]
Doesn't sound like there is any direct next steps here, so going to close for now.
