### ISSUE TITLE
Pub build hangs during CI build, local is fine

### ISSUE THREAD

**Issue by laagland** [dart-lang/angular#674]
My CI build keeps hanging during pub build. 
Strange thing is that build completes on my local dev with same dart/angular versions

When running the command on CI server with --verbose the following message gets repeated endlessly:

```
FINE: [Fine from BuilderTransformer: Instance of 'TemplatePlaceholderBuilder' on angular_router|primary]:
    | Not yet complete after 20.0s, waiting on input(s) angular|lib/angular.dart, angular|lib/src/core/linker/component_resolver.dart
FINE: [Fine from BuilderTransformer: Instance of 'TemplatePlaceholderBuilder' on angular_forms|primary]:
    | Not yet complete after 20.0s, waiting on input(s) angular|lib/angular.dart, angular|lib/src/facade/lang.dart
FINE: [Fine from BuilderTransformer: Instance of 'TemplatePlaceholderBuilder' on app|primary]:
    | Not yet complete after 20.0s, waiting on input(s) angular|lib/angular.dart, angular_forms|lib/angular_forms.dart, angular|lib/core.dart, angular|lib/security.dart, angular_router|lib/angular_router.dart
FINE: [Fine from BuilderTransformer: Instance of 'LibraryBuilder' on angular|primary]:
    | Not yet complete after 20.0s
```

I'm using the following pubspec

```
name: app

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_router: ^1.0.2
  angular_forms: ^1.0.0
  dartson:
    git: https://github.com/daniel-v/dartson.git
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- dartson
- angular:
    entry_points:
    - web/index.dart
- dart_to_js_script_rewriter
web:
  compiler:
    debug: dartdevc
```

I'm seeing other topics that seem closely related (#626 / #594)

**Comment by AlexanderJohr** [comment]
I also struggled with this.
After numerous attempts and days of failure I finally found the solution for this in my setup.

I had a lot of dart files in my "web" directory, also components for angular. Pub build hang until I moved most of the dart files into "lib." Maybe you can try that?

After the build was running again , pub showed me errors again. I see that you also use dartson. This and it's annotations @Entity and @Property caused errors so I removed it and I'm moving to the built_value package now.

**Comment by matanlurey** [comment]
Our v5 release will have a new build system, similar to pub, without this issue.
