### ISSUE TITLE
AfterViewInit has different behaviour with dartdevc and dart2js

### ISSUE THREAD

**Issue by olostan** [dart-lang/angular#675]
I am using 5.0.0-alpha and found such strange difference when using dartdevc and dart2js:

If there is a binding to component's property in template and within `ngAfterViewInit` hook the property on which bound is modified, `dartdevc` produces error:
```
 Expression has changed after it was checked. Previous value: 'This is a test 3'. Current value: 'This is a test 123'
```
however,  when using Dart2JS there is no error raised. Using `ngOnInit` is ok for both compilers.

**Comment by matanlurey** [comment]
Yup, this is WAI.

We only check for this error case in developer mode (i.e. "assertions enabled").

Is there a reason you'd want this in Dart2JS?
