### ISSUE TITLE
Add pure components

### ISSUE THREAD

**Issue by ranquild** [dart-lang/angular#679]
Currently OnPush and Stateful components are checked when any of descendant components are marked for check, because when it happens whole path from that component to root component is marked for check. In most cases (in our app at least) OnPush components are actually pure components. That means that check should be required only when inputs are actually changed. What I suggest is to add "pure" component mode so when change detection runs those components are skipped when they are not explicitly marked for check (when inputs are actually checked for this component). API can be like this:

```
@Component(
  selector: 'my-list',
  template: '<my-list-item *ngFor="let item of items" [item]="item" />,
  directives: const [NgFor, ...],
  pure: true
)
```

When one of items is marked for check, list should be skipped during change detection (NgFor should not be checked). Change detection should "fall-trough" to inner components on marked for check path.

**Comment by ranquild** [comment]
Connected to https://github.com/dart-lang/angular/issues/502. @matanlurey Any info on this?

**Comment by matanlurey** [comment]
I don't have an answer right now, but it's definitely been talked about.

**Comment by matanlurey** [comment]
I think we are going to close this one. Post V5 we are going to look at alternatives (more explicit change detection that doesn't require zones), and potentially a replacement for `*ngFor` that is much cheaper. I can't imagine this being prioritized in light of that. Thanks for the request though!
