### ISSUE TITLE
Support generic types in a Component/Directive

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/angular#68]
This occurs when I compile using dart2js, 

Say I have a Component defined as such:

`class MyComponent<T extends something>`

and I want to inject the following property:

`final Container<T> myContainer;`

I use `@Inject(Container) this.myContainer;` (generic type is not allowed here)

This generates the following warning:

```
[Warning from Dart2JS on ...]:
packages\...:
Cannot resolve type 'T'.
(Container<T> myContainer) => new MyComponent(myContainer),
          ^
```

**Comment by matanlurey** [comment]
We currently don't retain type information during the compile.

Blocked by #48.

**Comment by matanlurey** [comment]
Investigating feasibility for 4.0.0. One issue there isn't a way to express this:

```dart
@Inject(Container<String>)
```

/cc @kevmoo Is this something planned for the Dart language in the very near future?

**Comment by zoechi** [comment]
What about something like `@Inject(const InjectionToken(Container, const[String]))`

**Comment by matanlurey** [comment]
This is not planned for `4.0.0` at this time (other lower-hanging fruit).

**Comment by matanlurey** [comment]
Open question: _How should we implement this?_

**Comment by matanlurey** [comment]
We should try to gather internal data on how often generic components are used.

**Comment by matanlurey** [comment]
I think based on how Dart2 works, this is not likely to happen for V5.

I've marked this to revisit in V6+.
