### ISSUE TITLE
Add dev-mode to for zone-related stuff

### ISSUE THREAD

**Issue by ranquild** [dart-lang/angular#683]
Currently it is very easy to ruin application performance with Timers, Features and StreamSubscriptions in NgZone. It would be very helpful to have opt-in developer mode so when something is bound to NgZone, warning is somehow shown to developer (for example, print to console). So if developer notices that there are frequent `tick` calls, this mode can be enabled to find out what is the reason.

**Comment by matanlurey** [comment]
I think that we are going to lean towards finding ways to remove the necessity for zones instead of adding new tools specifically around them. I imagine this is implementable as a user feature (i.e. creating a parent zone yourself) if you feel like it.
