### ISSUE TITLE
Improve error message for * on <template> element

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular#687]
Currently using the * sytnax on a <template> element like

<template *ngIf="condition">
produces the error message

Invalid decorator in 'template' element
Providing a link to the * documentation could be more helpful for new users.

Originally filed here: dart-lang/angular_analyzer_plugin#451

**Comment by alorenzen** [comment]
I don't think anyone uses `template` elements enough to make this a high priority. Marking as obsolete.
