### ISSUE TITLE
Cant use null as an option in a select

### ISSUE THREAD

**Issue by zarisi** [dart-lang/angular#691]
Hi, today i was trying to use a ```<select>``` tath binds to a model tath can be null and i would liek to set an null option to show a default option when the object is null.

I tried with ```[ngValue]=""``` it sets the model to null but on the init of the select it doesnt select de value, and tried `[ngValue]="null"` but it set the text inside the option as the value 

This is the select im using:     
```html
<div *ngIf="!readOnly" class="form-group col-sm-6" [ngClass]="controlStateClasses(expedienteAmbito)">
            <label class="form-control-label" for="expedienteAmbito">Ámbito Reglamentario*:</label>
            <select class="form-control"
                    id="expedienteAmbito"
                    [(ngModel)]="expediente.ambito.id"
                    aria-describedby="expedienteAmbito"
                    #expedienteAmbito="ngForm"
                    ngControl="expedienteAmbito"
                    required>
                <option [ngValue]="null">Seleccione un ambito</option>
                <option *ngFor="let ambito of ambitos" [ngValue]="ambito.id">{{ambito.codigo}} -
                    {{ambito.descripcion}}
                </option>
            </select>
        </div>
```

expediente.ambito will never be null but expediente.ambito.id can be null is nothing is selected.

This was using angular 5.0.0-alpha

**Comment by matanlurey** [comment]
We don't plan to make this change.

**Comment by kleinpetr** [comment]
@matanlurey  Why? I think thats the right way to using select placeholders..   This is working in Angular
https://netbasal.com/angular-quick-tip-how-to-show-a-placeholder-in-select-control-bab688f98b98

**Comment by kleinpetr** [comment]
@matanlurey do you have another solution for this use-case? 

I am using this at now
```
String get idCountry => addressDto.idCountry ?? 'none';
set idCountry(String val) => addressDto.idCountry = (val == 'none' ? null : val);
```
in template
```
<select [(ngModel)]="idCountry">
     <option value="none" disabled>Choose country</option>
     <option *ngFor="....">...</option>
</select>
```
it is only solution what can I do. But the problem is validators, when I set required for this select thats not check for null value because the value is "none".

Do you have some solution for this situation???
Thanks
