### ISSUE TITLE
Consider supporting &#32; in addition to &ngsp;

### ISSUE THREAD

**Issue by zacharydenton** [dart-lang/angular#695]
I've started seeing the "ng space" `&ngsp;` entity (when you want to put a space in a preserveWhitespace: false template), and my first reaction was that it was a typo of `&nbsp;`. I imagine anyone familiar with HTML but not with AngularDart could also have this first reaction when seeing &ngsp;.

To avoid this confusion, can we use the standard space character entity (`&#32;`) instead of a new non-standard entity?

**Comment by kwalrath** [comment]
I, too, thought it was a typo the first time I saw it.

**Comment by matanlurey** [comment]
I haven't heard much feedback here since the initial request. We can revisit if needed.
