### ISSUE TITLE
Can't inject aliased root component with Visibility.none

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#711]
A directive with `Visibility.none` can't be injected directly, but may provide itself for injection via another token.

```dart
@Component(
  ...,
  providers: const [
    const Provider(PublicDependency, useExisting: PrivateImplementaion),
  ],
  visibility: Visibility.none,
)
class PrivateImplementation implements PublicDependency {}
```

Normally this would allow a child to later inject the directive via it's alias.

```dart
@Component(...)
class ChildComponent {
  final PublicDependency dependency;

  ChildComponent(this.dependency); // Satisfied by PrivateImplementation.
}
```

However, if `PrivateImplementation` is bootstrapped as the root component, these ceases to work, and injecting `PublicDependency` will yield an error.

```
No provider found for PublicDependency.
```

**Comment by alorenzen** [comment]
Any plans to fix this, or should we mark is as obsolete?

**Comment by matanlurey** [comment]
Ideally we should either fix it or catch it as a compile error*

_*Might not be possible since we have no idea what is a root component_

**Comment by leonsenft** [comment]
I have no recollection of why this shouldn't work.. :confused: Perhaps we should test this again and see what fixing it would entail.

**Comment by matanlurey** [comment]
It also might have been fixed by your recent changes in this area @leonsenft

**Comment by leonsenft** [comment]
@matanlurey hopefully :wink:

**Comment by leonsenft** [comment]
Yep, looks like this might have been a quirk in the original implementation. Not only does this work with, but our existing tests already test this.
