### ISSUE TITLE
ComponentResolver resolveComponentSync method removed 

### ISSUE THREAD

**Issue by rwrozelle** [dart-lang/angular#718]
I understand you are deprecating ComponentResolver, but the change included removal of resolveComponentSync method.  This is causing a **breaking change** in my code when I test with the +1 release.  This should either be documented or the method put back in the class with a deprecation flag.

**Comment by matanlurey** [comment]
This was never a supported API, and was not intended to be public, sorry.

Good news is that v5 is quite a way aways still.

**Comment by rwrozelle** [comment]
But it was public and you removed it without notice.  Agree on V5 being "quite a way aways still", I've tried the DDC with only middling results.  Much slower.

![image](https://user-images.githubusercontent.com/8890259/33389718-c75a055a-d501-11e7-82d4-437a429c90f6.png)
