### ISSUE TITLE
Travis crashing while loading Chrome

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/angular#728]
For our latest github sync (https://github.com/dart-lang/angular/pull/724), travis is failing while trying to load chrome.

This looks like an issue with package:test, or the way that package:test is using chrome.

**Comment by alorenzen** [comment]
Travis log: https://travis-ci.org/dart-lang/angular/jobs/309650767

**Comment by alorenzen** [comment]
Related to https://github.com/dart-lang/test/issues/726

**Comment by matanlurey** [comment]
Specifically @grouma mentions this might _not_ be the fault of `package:test`, but we need better logging to be sure.

**Comment by jakemac53** [comment]
https://github.com/travis-ci/travis-ci/issues/8836 looks like it was the underlying issue, which is now fixed
