### ISSUE TITLE
Router shouldn't rebuild parent route when only leaf route changes

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#732]
Consider the following route hierarchy

```
  '/parent' : ParentComponent
    '/child-a' : ChildAComponent
    '/child-b' : ChildBComponent
```

If we're at `'/parent/child-a'`, and we navigate to `'/parent/child-b'`, only the leaf component `ChildAComponent` should be destroyed and replaced with `ChildBComponent`. However, currently the router will destroy and rebuild `ParentComponent` as well if it doesn't extend `CanReuse`.

Rather than requiring the component to opt-in to this behavior, it should be made the default. Only portions of the route that change should be destroyed and replaced.

**Comment by alorenzen** [comment]
Is this something that we think we'll be able to change in the current router, or is it now considered WAI?

**Comment by leonsenft** [comment]
I think at this point it would be too breaking, despite being a better behavior. We can close this and consider it a feature of any refactor or newer version we do in the future.
