### ISSUE TITLE
Router should check for reuse during resolution, not after

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#733]
Upon navigation, the router currently goes through three "phases".

1. Resolution. Beginning at the root `<router-outlet>`, the router finds a prefix-matching route, creates the component in search of a nested `<router-outlet>` and recurses on it. As it creates these partially matching routes, it caches them for reuse upon activation. If the partially matching route is already active, it instead retrieves it from the cache.

2. Activation. Upon successful resolution, the router checks if the matching route leaf can be activated. The leaf component can implement `CanActivate` to prevent activation in particular circumstances (authentication guard for example).

3. Upon activation, each `<router-outlet>` checks if the currently activated component should be reused. If not, it's removed from cache of loaded components and rebuilt.

There are a number of issues with the order of this design

- `canActivate` is potentially invoked on the _current_ instance of the route. If this component isn't reusable, we're technically asking the wrong instance whether it can be activated.

- If a non-leaf component isn't reusable (currently default behavior https://github.com/dart-lang/angular/issues/732), destroying and rebuilding it destroys its nested `<router-outlet>`, losing the cache. This requires rebuilding and change detecting the matching route sub-tree _again_.

- Attaching default routes occurs during resolution, which leads to a subtle issue with default routes concerning https://github.com/dart-lang/angular/issues/734. The router only attempts to load a default route if it detects a `<router-outlet>` in the route leaf. This means if the `<router-outlet>` host is reusable, you can't refresh it's default routes, since they're never cleared. This perhaps is a separate issue all on its own.

Instead, I propose that the router check for reuse and activation, _during_ resolution. In addition to fixing the above issues, this would also enable a route to asynchronously load its own sub-routes during `canActivate`.

**Comment by alorenzen** [comment]
Is this still planned, or should we close?

**Comment by leonsenft** [comment]
I think at this point it would be too breaking, despite being a better behavior. We can close this and consider it a feature of any refactor or newer version we do in the future.

**Comment by leonsenft** [comment]
To clarify, I think the entire way route resolution works is a violation of Angular's lifecycle design. We really would need static route resolution that doesn't involve initializing components before a route is matched.

**Comment by chalin** [comment]
v6 feature (request)?

**Comment by matanlurey** [comment]
Router is very separate and unrelated to v5 or v6.

**Comment by joshuaimmanuel** [comment]
@leonsenft As it is planned for future, can you please keep this issue open?
