### ISSUE TITLE
`pub get` hangs after adding the `dartson` library on Angular 4.0.0

### ISSUE THREAD

**Issue by gchumillas** [dart-lang/angular#746]
I created a basic web-angular application and installed dependencies:
```bash
$ stagehand web-angular
$ pub get
```
Until now all works perfectly. The dependencies were successful downloaded and installed. But then, I included the [dartson](https://pub.dartlang.org/packages/dartson) package and `pub get` thrown the following error:
```bash
$ pub get --verbose
...
...
FINE: [Fine from BuilderTransformer: Instance of 'TemplatePlaceholderBuilder' on angular_forms|primary]:
    | Not yet complete after 40.0s, waiting on input(s) angular|lib/angular.dart, angular|lib/src/facade/lang.dart
FINE: [Fine from BuilderTransformer: Instance of 'TemplatePlaceholderBuilder' on angular_test|primary]:
    | Not yet complete after 40.0s, waiting on input(s) angular|lib/angular.dart, angular|lib/src/core/application_ref.dart, angular|lib/src/core/change_detection/constants.dart, angular|lib/src/core/linker/app_view_utils.dart, angular|lib/src/core/linker/view_ref.dart, angular|lib/src/facade/exceptions.dart, angular|lib/di.dart, angular|lib/src/debug/debug_app_view.dart, angular|lib/src/debug/debug_node.dart
FINE: [Fine from BuilderTransformer: Instance of 'TemplatePlaceholderBuilder' on angular_components|primary]:
    | Not yet complete after 40.0s, waiting on input(s) angular|lib/angular.dart, angular_forms|lib/angular_forms.dart, angular|lib/experimental.dart, angular|lib/di.dart
FINE: [Fine from BuilderTransformer: Instance of 'LibraryBuilder' on angular|primary]:
    | Not yet complete after 40.0s
```
The previous message is repeated again and again and `pub get` never ends. Attached is the example:
[example.zip](https://github.com/dart-lang/angular/files/1546014/example.zip)

Maybe this issue is related:
https://github.com/dart-lang/angular/issues/626

**More info:**
```
Ubuntu 16.04 LTS
Dart VM version: 1.24.2 (Thu Jun 22 15:42:21 2017) on "linux_x64"
Pub 1.24.2
```

**Comment by zoechi** [comment]
Looks like package resolution goes exponential because it can't find a matching set of dependency versions. `dartson` seems to have a dependency that is not compatible with other dependencies in your project.
The Dart team is working on better feedback in these situations.
You can use https://pub.dartlang.org/packages/mediator to find the conflict

**Comment by matanlurey** [comment]
What @zoechi said. Sorry about that.
