### ISSUE TITLE
DatePipe outputs in UTC when handed a [num] (millisecondsSinceEpoch)

### ISSUE THREAD

**Issue by eRaz0rHead** [dart-lang/angular#760]
https://github.com/dart-lang/angular/blob/797e015f5e1f62d48b52330515fbbd33760837ed/angular/lib/src/common/pipes/date_pipe.dart#L87

The docs for DatePipe suggest that the output date is formatted in the local time zone. 

In the case that the input is a num (millisecondsSinceEpoch) what actually happens is that the output date is in UTC, not local timezone.

Consider the following :
  var dt = new DateTime(2015, 6, 15, 21, 43, 11);
  var utc = dt.toUtc();
  assert (dt.millisecondsSinceEpoch == utc.millisecondsSinceEpoch);

  print (dt);  // 2015-06-15 21:43:11.000
  print (utc); // 2015-06-16 04:43:11.000Z
  print (new DateTime.fromMillisecondsSinceEpoch(utc.millisecondsSinceEpoch));  
         // 2015-06-15 21:43:11.000

  print (new DateTime.fromMillisecondsSinceEpoch(dt.millisecondsSinceEpoch)); 
         // 2015-06-15 21:43:11.000

  print (new DateTime.fromMillisecondsSinceEpoch(utc.millisecondsSinceEpoch, isUtc: true)); 
        // 2015-06-16 04:43:11.000Z

**Comment by dpidcock** [comment]
This isn't an issue with the docs.

Should we not expect 

{{myDate | date}}  and 
((myDate.millisecondsSinceEpoch | date}}

to display the same time?

**Comment by matanlurey** [comment]
Your the user here, I quite literally don't know what `DatePipe` does.

(If you are internal, feel free to contact dart-angular@ internally)
