### ISSUE TITLE
Bad formatting in DatePipe class

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/angular#769]
https://www.dartdocs.org/documentation/angular/5.0.0-alpha/angular/DatePipe-class.html has a badly formatted table in the Usage section. (I suspect this isn't the only place with this problem, so it might be good to search for similar tables.)

**Comment by leonsenft** [comment]
@kwalrath It seems like the formatting is fine for GFM:

| Component | Symbol | Short Form   | Long Form         | Numeric   | 2-digit   |
|-----------|:------:|--------------|-------------------|-----------|-----------|
| era       |   G    | G (AD)       | GGGG (Anno Domini)| -         | -         |
| year      |   y    | -            | -                 | y (2015)  | yy (15)   |
| month     |   M    | MMM (Sep)    | MMMM (September)  | M (9)     | MM (09)   |
| day       |   d    | -            | -                 | d (3)     | dd (03)   |
| weekday   |   E    | EEE (Sun)    | EEEE (Sunday)     | -         | -         |
| hour      |   j    | -            | -                 | j (13)    | jj (13)   |
| hour12    |   h    | -            | -                 | h (1 PM)  | hh (01 PM)|
| hour24    |   H    | -            | -                 | H (13)    | HH (13)   |
| minute    |   m    | -            | -                 | m (5)     | mm (05)   |
| second    |   s    | -            | -                 | s (9)     | ss (09)   |
| timezone  |   z    | -            | z (Pacific Standard Time)| -  | -         |
| timezone  |   Z    | Z (GMT-8:00) | -                 | -         | -         |

which dartdoc supposedly supports as of version 0.15.0. When was the last time the Angular docs were generated, and what version of dartdoc was used?

**Comment by kwalrath** [comment]
I don't know. @kevmoo or @jcollins-g, do you know [how to find] the dartdoc version info for dartdocs.org?

I thought that the generation date and dartdoc version info might be in the page source, but I didn't see it there.

**Comment by kwalrath** [comment]
Ah, I see that dartdoc was fixed only a month ago (December 4), and angular 5.0.0-alpha was released Oct 10. So this issue should be fixed once the doc is regenerated with the new dartdoc. (In fact, the dartdoc fix was for this very page, as reported in dart-lang/dartdoc#1453.)

Angular 5.0.0-alpha+2 was released December 19, but the doc hasn't successfully built ([failed build log](https://www.dartdocs.org/documentation/angular/5.0.0-alpha+2/log.txt)).

**Comment by matanlurey** [comment]
@kwalrath Is this issue still relevant?

**Comment by kwalrath** [comment]
I can't verify it's fixed by looking at the generated docs, since dartdocs.org hasn't been able to build angular docs lately. Looking at the [failure messages](https://www.dartdocs.org/failed/index.html), I think it's because angular now requires SDK version 2.0*:

```
Package angular requires SDK version >=2.0.0-dev.3.0 <2.0.0 but the current SDK is 1.24.2.
```

**Comment by kwalrath** [comment]
The generated version on our site looks OK: https://webdev-dartlang-org-dev.firebaseapp.com/api/angular/angular/DatePipe-class
