### ISSUE TITLE
Rename to pkg/angular (drop the "2")

### ISSUE THREAD

**Issue by adaojunior** [dart-lang/angular#78]
Since the beginning of the project I've been wondering, why is it `angular2` instead of `angular` with the package being `v2.0.0`, At first I thought this would be the name of the project, but seems like it is not. I know we're not following 100% of what's coming from angular ts, but seems like they're gonna have breaking changes every 6 months (as mentioned in the video I'll add bellow),  and in 6 months from now angular will be `angular 3.0`. So is dart going to migrate from `angular2` to `angular` and use the semver ?
Btw, angular ts is not using the `angular2` name, they've been using `@angular/common` for a while now. They also mention is this video that the project should be called angular and not angular2.

[Angular Special Event](https://youtu.be/xTIWBXkpvDc?t=6m15s)

**Comment by adaojunior** [comment]
Also, quoting the article posted on [angularjs.blogspot.com](http://angularjs.blogspot.com/2016/09/angular2-final.html)
> We heard loud and clear that our RC labeling was confusing. To make it easy to manage dependencies on stable Angular releases, starting today with Angular 2.0.0, we will move to semantic versioning.  Angular versioning will then follow the MAJOR.MINOR.PATCH scheme as described by semver:

**Comment by matanlurey** [comment]
You're not the only person that finds it weird 😩 

I think we may eventually rename Angular2 to Angular (version 2.0.0), but I think the naming probably is less important to getting the framework to an awesome place first, I'm sure you agree. 

We'll have more details at the Dart Dev Summit (https://events.dartlang.org/2016/summit/)

**Comment by aluanhaddad** [comment]
I prefer it went the other way around and Angular were renamed to Angular2 1.0.0. My reasoning is that it's simply not version 2. It's barely even concept compatible.

**Comment by aluanhaddad** [comment]
P.S. I'm a TypeScript user.

**Comment by zoechi** [comment]
Wasn't Angular 1 named AngularJS. So there would already be a name change that reflects the substantial changes. 
I find Angular2 1.0.0 quite confusing.
And later when there are breaking changes it would become Angular2 2.0.0 and then Angular2 3.0.0 :D

**Comment by aluanhaddad** [comment]
@zoechi I always thought the change from AngularJS to Angular2 made sense since it _officially_ supported more languages/dialects. Anyway I'm not a fan of the name Angular2 per say, but these are hardly breaking changes. It is a brand new framework, so actually I would prefer a new name altogether.

**Comment by adaojunior** [comment]
I'm revisiting this because recently there was a [presentation](https://youtu.be/aJIMoLgqU_o?t=22m50s) and seems like angular ts will be tagged as 4.0 in march and they asked everyone to stop calling it "angular 2" because it will cause confusion, I think the same applies to angular dart, one example is that we  have many `ng2_*` or `angular2_*` packages already.

**Comment by matanlurey** [comment]
This is potentially planned for `4.0.0`. I'll have an RFC when we've decided on it for sure - this is potentially a few weeks of work internally (imagine ~millions of lines of code to migrate), so I don't want to give folks false hope. We have decided we are doing this, though.

```dart
import 'packlage:angular/angular.dart'; // Soon!
```

**Comment by b-strauss** [comment]
What about the old angular (dart)?
https://pub.dartlang.org/packages/angular

**Comment by zoechi** [comment]
@b-strauss it's quite unlikely there will be a 4.0.0 version of the old Angular because it's not maintained anymore, therefore there won't be any conflict.

**Comment by alorenzen** [comment]
We've landed the change to the codebase, as of #471, and will make this the default starting in 4.0.

**Comment by b-strauss** [comment]
https://github.com/dart-lang/angular/blob/master/angular/README.md

The readme still mentions `angular2`.
