### ISSUE TITLE
Remove the angular_test runner

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/angular#787]
With the migration to build_runner, we provide a sane `test` command by default. The angular_test executable should probably do some combination of the following:

- wrap `build_runner test`
- add a deprecation warning
- delete it entirely

**Comment by matanlurey** [comment]
Thoughts? @chalin @alorenzen

**Comment by chalin** [comment]
I'm not a fan of the wrapping option. I'd vote to just drop it.

**Comment by alorenzen** [comment]
I really am not familiar with the angular_test executable. Does it add any value that is not covered by build_runner?
If not, then get ride of it.

**Comment by matanlurey** [comment]
OK, I'm taking this as a FR to remove the `angular_test` binary in the next release.
