### ISSUE TITLE
angular doesn't work with dart 2.0.0-dev.18.0

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/angular#789]
`pub get` and `pub upgrade` don't work at all on 2.0.0-dev.18.0

This is caused by https://github.com/dart-lang/pub/issues/1781.

We'll either need to wait for a new SDK release or update or SDK constraints to get travis green again.

**Comment by alorenzen** [comment]
Also tracked in https://github.com/dart-lang/sdk/issues/31940

**Comment by matanlurey** [comment]
Fixed as of 0.19.
