### ISSUE TITLE
Angular build option use_new_template_parser reported as invalid

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#791]
The [5.0.0-alpha+4 changelog](https://github.com/dart-lang/angular/blob/master/angular/CHANGELOG.md#500-alpha4) reads:

> * We have a new template parser. .
  In order to use it, you need to set the following flag in your `build.yaml`:
> ```yaml
> builders:
>   angular:
>     options:
>       use_new_template_parser: True
> ```

But in doing so I get:

```nocode
quickstart > pub run build_runner build
[INFO] ensureBuildScript: Generating build script...Unhandled exception:
Invalid argument(s): Got invalid options `[options]` for builder `angular`. Only `[builder_factories, import, build_extensions, target, auto_apply, required_inputs, is_optional, build_to, defaults]` are supported keys.
...
```

Note that I am using alpha+4:

```nocode
quickstart > grep 5.0 pubspec.*
pubspec.lock:    version: "5.0.0-alpha+4"
```

Dart VM version: 2.0.0-dev.19.0 (Fri Jan 19 08:01:12 2018 +0100) on "macos_x64"

cc @kwalrath @kevmoo

**Comment by alorenzen** [comment]
This worked just fine for me on a hello world example: https://github.com/alorenzen/angular/commit/5de417a3faa388a8a6577027ea52d840fc6f1416

Just add an un-closed `<div>` tag to the HelloWorld component and see an error in the build.

**Comment by matanlurey** [comment]
@chalin maybe your config was wrong? It does look like it works.

**Comment by chalin** [comment]
Tried again (though on a clean setup), and I'm no longer getting the "invalid options" error. It could be that there was another error in the config, though the error message seemed to imply that it was because of an invalid option. Closing.
