### ISSUE TITLE
Upgrade angular_test to package:test 0.12.30

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#794]
Package [test 0.12.30](https://pub.dartlang.org/packages/test#-changelog-tab-) has built-in support for running chrome browser tests headless. Consider upgrading to this version in the [pubspec.yaml file](https://github.com/dart-lang/angular/blob/master/angular_test/pubspec.yaml#L24).

cc @kwalrath

**Comment by matanlurey** [comment]
We should probably do this for _all_ of our packages, I think (like `_tests`).

/cc @alorenzen @jakemac53

**Comment by alorenzen** [comment]
Is there something *preventing* us from picking up test 0.12.30? That should just be picked up because of the ^.

**Comment by alorenzen** [comment]
In fact, I can verify that it *was* picked up by running `pub upgrade` in our last run on travis: 
https://travis-ci.org/dart-lang/angular/jobs/333947902

**Comment by matanlurey** [comment]
@chalin?

**Comment by chalin** [comment]
Yes, test 0.12.30 will be picked up provided angular_test isn't used as part of a project that (willingly or not) has a constraint for test that is below 0.12.30. When that happens, test 0.12.30 will not be used, and headless chrome won't be usable out-of-the-box.

If we wish to guarantee that angular_test can _always_ be used with the test package's built-in support for headless chrome, then the minimum package version for test will need to be ^0.12.30.
