### ISSUE TITLE
Our users need the dartdevc Chrome plugin

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#796]
We are `dartdevc`-only in AngularDart v5, and we need this plugin released for them.

@dgrove @kevmoo who should be assigned here?

**Comment by kevmoo** [comment]
@alan-knight is point. @vsmenon FYI

**Comment by matanlurey** [comment]
Thanks! This is definitely a requirement for our v5 release.

**Comment by matanlurey** [comment]
Duplicate of #872
