### ISSUE TITLE
TemplateGenerator reports "unexpected token" for some ngFor syntax

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#800]
The new template parser reports the following unexpected token errors when processing the [template_syntax example app](https://github.com/dart-lang/site-webdev/tree/5-dev/examples/ng/doc/template-syntax):

```nocode
[22:39:06] [SEVERE] Instance of 'LibraryBuilder' on template_syntax|lib/app_component.dart: Error running TemplateGenerator for template_syntax|lib/app_component.dart.
Template parse errors:
line 596, column 8 of AppComponent: ParseErrorLevel.FATAL: Parser Error: Unexpected token ',' at column 7 in [heroes, let i=index] in 
  <div *ngFor="let hero of heroes, let i=index">{{i + 1}} - {{hero.name}}</div>
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
line 637, column 8 of AppComponent: ParseErrorLevel.FATAL: Parser Error: Unexpected token ',' at column 7 in [heroes, trackBy: trackByHeroes] in 
  <div *ngFor="let hero of heroes, trackBy: trackByHeroes">({{hero.id}}) {{hero.name}}</div>
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
line 642, column 8 of AppComponent: ParseErrorLevel.FATAL: Parser Error: Unexpected token 'trackBy' at column 8 in [heroes trackBy: trackByHeroes] in 
  <div *ngFor="let hero of heroes trackBy: trackByHeroes">({{hero.id}}) {{hero.name}}</div>
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
line 647, column 8 of AppComponent: ParseErrorLevel.FATAL: Parser Error: Unexpected token ',' at column 7 in [heroes, trackBy: trackById] in 
  <div *ngFor="let hero of heroes, trackBy: trackById">({{hero.id}}) {{hero.name}}</div>
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'm not aware that there has been any change in syntax, so I'm assuming that this is an error in the TemplateGenerator.

cc @kwalrath

**Comment by matanlurey** [comment]
@alorenzen, I've lost track of the spec - is this a bug or?

**Comment by matanlurey** [comment]
@chalin: I think ... that `,` is no longer supported, only `;`.

We don't really have a formal spec, yet, but I know the last parser was pretty loose.

**Comment by matanlurey** [comment]
Here's code samples known to me:

https://github.com/dart-lang/angular_components/search?utf8=%E2%9C%93&q=trackBy&type=

**Comment by chalin** [comment]
Its fine if the ngFor syntax has been simplified, but then there should at least be an entry to that effect in the changelog, explaining what has been dropped, or the full remaining supported syntax.

**Comment by alorenzen** [comment]
@matanlurey is correct that `package:angular_ast` only supports `;` as a deliminator, and will fail if `,` or ` ` is used instead.

We probably could have done better with the changelog. But in the end, this was the behavior of `package:angular_ast`, not code that I was writing, so I didn't mention it in the angular change log.

**Comment by chalin** [comment]
Np. Can we take this issue as a reminder to update the changelog?

**Comment by chalin** [comment]
To give some context: these examples don't even show up in our AngularDart docs. They were leftovers in the code from our Angular TS days. Closing.
