### ISSUE TITLE
Template parser not merging interpolations

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/angular#802]
Previously, if there were multiple interpolation statements in a row, the template parser would treat them as one large statement. Now, with the new template parser based on `package:angular_ast`, we treat them as separate interpolation nodes.

We should investigate if there is a real performance improvement one way or the other, and possible replicate the old behavior in the new parser.

Example:
```html
{{ "foo" }} {{ "bar" }}
```
could be equivalent to 
```html
{{ "foo bar"}}
```

**Comment by matanlurey** [comment]
Interpolate _seems_ to only be used still for local values. For example:

```html
<div>
  {{greeting}} {{noun}}!
</div>
```

... produces ...

```dart
 void detectChangesInternal() {
    final import1.InterpolationTwoAdjacent _ctx = ctx;
    final currVal_0 = (_ctx.greeting ?? '');
    if (import6.checkBinding(_expr_0, currVal_0)) {
      _text_1.text = currVal_0;
      _expr_0 = currVal_0;
    }
    final currVal_1 = (_ctx.noun ?? '');
    if (import6.checkBinding(_expr_1, currVal_1)) {
      _text_3.text = currVal_1;
      _expr_1 = currVal_1;
    }
  }
```

While:

```html
  <div>{{"Welcome"}} {{"Home"}}!</div>
```

... produces ...

```dart
  ComponentRef<import1.InterpolationLiterals> build() {
    final _rootEl = rootEl;
    final import2.HtmlElement parentRenderNode = initViewRoot(_rootEl);
    var doc = import2.document;
    _el_0 = createDivAndAppend(doc, parentRenderNode);
    _text_1 = new import2.Text('Welcome');
    _el_0.append(_text_1);
    import2.Text _text_2 = new import2.Text(' ');
    _el_0.append(_text_2);
    _text_3 = new import2.Text('Home');
    _el_0.append(_text_3);
    import2.Text _text_4 = new import2.Text('!');
    _el_0.append(_text_4);
    init(const [], null);
    return null;
  }
```

And then even more unlikely:

```html
    <ng-container *ngFor="let bar of bars">
      <ng-container *ngFor="let foo of bar">
        Hello {{callMethod(bar)}}: {{foo}}!
      </ng-container>
    </ng-container>
```

... produces ...

```dart
  @override
  void detectChangesInternal() {
    final import1.InterpolationLocals _ctx = ctx;
    final local_bar = parentView.locals['\$implicit'];
    final local_foo = locals['\$implicit'];
    final currVal_0 = import6.interpolate0(_ctx.callMethod(local_bar));
    if (import6.checkBinding(_expr_0, currVal_0)) {
      _text_1.text = currVal_0;
      _expr_0 = currVal_0;
    }
    final currVal_1 = import6.interpolate0(local_foo);
    if (import6.checkBinding(_expr_1, currVal_1)) {
      _text_3.text = currVal_1;
      _expr_1 = currVal_1;
    }
  }
```

These definitely could be optimized, but the only terrible one is ` <div>{{"Welcome"}} {{"Home"}}!</div>`. I wonder how often code like this is even written in real applications, so I'm OK with closing this for now.

On a related note, I can't find a single use of `interpolateN` where `N > 1` _anywhere_ in `_goldens`.

Here is how the compiler even says it emits these functions:
https://github.com/dart-lang/angular/blob/0b7878f81b8441e290e436a0f651fbe1e667e522/angular/lib/src/compiler/view_compiler/expression_converter.dart#L267-L304

I'm guessing the code we are producing today is not much worse than:
https://github.com/dart-lang/angular/blob/0b7878f81b8441e290e436a0f651fbe1e667e522/angular/lib/src/core/linker/app_view_utils.dart#L107-L125

... in any case. Thoughts on closing @alorenzen @leonsenft?

**Comment by alorenzen** [comment]
Something to save for the new compiler pipeline, probably.

**Comment by matanlurey** [comment]
I looked into this, I am not sure it is very valuable to change.
