### ISSUE TITLE
Are `bindon-foo` and `ref-foo` officially deprecated/abandoned in 5.0?

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#803]
I'm getting these warnings from the new template compiler:

---

[WARNING] Instance of 'LibraryBuilder' on template_syntax|lib/app_component.dart: Template parse warnings:
line 451, column 8 of AppComponent: ParseErrorLevel.
**WARNING: "bindon-" for properties/events is no longer supported. Use "[()]" instead!***
\<input bindon-ngModel="currentHero.name">
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
line 676, column 8 of AppComponent: ParseErrorLevel.
**WARNING: "ref-" for references is no longer supported. Use "#" instead!***
\<input ref-fax placeholder="fax number">
       ^^^^^^^

---

Are `bindon-foo` and `ref-foo` official deprecated/abandoned in 5.0?

cc @kwalrath

**Comment by alorenzen** [comment]
Yes.
Those were warnings before, and now are completely unsupported.

**Comment by chalin** [comment]
Thanks, for confirming, I'll update the 5-dev docs.
(Maybe mention should also be made in the changelog.)

**Comment by alorenzen** [comment]
Ok, I spoke a little too soon. Some of the syntax previously had warnings, like `var-foo`, but `bindon-foo` did not. 

We're trying to have a goal of only having **1** way of doing things, so we removed many of these _alternate_ ways of doing things.

**Comment by chalin** [comment]
Can I have an official list of what is deprecated and/or dropped entirely in v5? I'll need that so that I can to update the 5-dev docs? (And could we keep this issue open until I get that info?) Thanks!

**Comment by alorenzen** [comment]
Getting a definitive list of everything that was changed is going to be impossible. There were so many weird quirks of the old parser that no one on the team even know existed. That's one of the biggest reasons for the switch - to make the parser more consistent and easier to reason about.

**Comment by chalin** [comment]
> Getting a definitive list of everything that was changed is going to be impossible.

I understand. How about we start with clarifying the status of `bindon-foo` and `ref-foo` for Angular 5? The template compiler message reads "no longer supported", but the message is tagged as a WARNING rather than SEVERE, so that might mean deprecated. Regardless, I can't run the resulting program. So, are these two features deprecated (which means they _should_ still work), or just no longer supported?

**Comment by alorenzen** [comment]
No longer supported. Right now they are treated as a normal attribute with
name "bindon-foo".

I'm considering just switching it to an error before 5.0 final, instead of
just the warning.

**Comment by chalin** [comment]
- `bind-foo`, for (one-way) data bindings seems to still work w/o warnings
- `on-foo`, for event bindings also seems to work.

Is that correct (or at least what is planned for Angular 5)?

**Comment by matanlurey** [comment]
I'd be surprised they still work, we don't support the syntax.

**Comment by chalin** [comment]
Here is a example to show that `bind-` and `on-` still work:

```dart
import 'package:angular/angular.dart';
import 'main.template.dart' as ng;

@Component(selector: 'app-root', template: '''
  Base: <input type="checkbox" #base [checked]="!base.checked" on-click="1"><br>
  Using bind-checked: <input type="checkbox" bind-checked="base.checked" (click)="1">
  ''')
class AppComponent {}

main() => bootstrapStatic(AppComponent, [], ng.initReflector);
```

Selecting the base checkbox causes the second checkbox to become checked:
> <img width="174" alt="screen shot 2018-02-01 at 05 33 10" src="https://user-images.githubusercontent.com/4140793/35674407-98a438c8-0712-11e8-879f-93eb9d59de4c.png">

I'm using Dart 2-dev.20, and Angular 5-alpha+4 with the new template compiler and dartdevc.

**Comment by matanlurey** [comment]
Then I'll delegate to @alorenzen - I don't understand how it still works.
