### ISSUE TITLE
Update angular_router documentation to use new ValueProvider?

### ISSUE THREAD

**Issue by 4cm4k1** [dart-lang/angular#806]
In the `angular_router` [example](https://github.com/dart-lang/angular/blob/master/angular_router/example/web/main.dart), plain Provider is used, which is soft-deprecated as of [angular 5.0.0-alpha+3](https://github.com/dart-lang/angular/blob/master/angular/CHANGELOG.md#500-alpha3):
```dart
void main() {
  bootstrapStatic(
    AppComponent,
    [
      routerProviders,
      // We use this instead of <base href="/" /> to make local development
      // nicer (i.e. load "styles.css" relatively).
      const Provider(APP_BASE_HREF, useValue: '/'),
      new Provider(Window, useValue: window),
    ],
    ng.initReflector,
  );
}
```
Would what I wrote below be a proper way to rewrite it with the new more-typed classes? If so, I can make a PR to update the documentation if that would help.
```dart
void main() {
  // I was not sure what to do with the `Window` class provided by `dart:html`
  // because static analysis was telling me that it was the wrong type.
  // This seems to work, but it could just be a coincidence.
  // Maybe ClassProvider instead, but I am not sure how to implement it.
  const WINDOW = const OpaqueToken<String>('Window');

  bootstrapStatic(
    AppComponent,
    [
      routerProviders,
      const ValueProvider.forToken(APP_BASE_HREF, '/'),
      const ValueProvider.forToken(WINDOW, 'window'),
    ],
    ng.initReflector,
  );
}
```
Thank you all for tons of great work!

**Comment by leonsenft** [comment]
Thanks @4cm4k1. Close, but your solution for the `Window` provider is no longer actually providing an instance of `Window`. You're now providing the string `'window'` for the `WINDOW` token, rather than the `Window` type. Instead this should work:

```dart
new ValueProvider(Window, window);
```

**Comment by 4cm4k1** [comment]
Thank you @leonsenft. Works great. So, I understand what the purpose of providing `'/'` as the value for `APP_BASE_HREF` is, in the context of `PathLocationStrategy`, but when I decided to upgrade `Provider` to `{Type}Provider`, it made me wonder what is it doing exactly for `Window`? Telling AngularDart that the `Window` class can be expected as the global `window` JavaScript object?

**Comment by leonsenft** [comment]
It's providing the value of `window`to be used wherever a `Window` is injected as a dependency.

In this example, the [`HeroDetailComponent` injects a `Window`](https://github.com/dart-lang/angular/blob/master/angular_router/example/lib/hero_detail_component.dart#L23).

At first glance this doesn't look very compelling because `window` is a global that could have been used directly, but it actually improves the testability of the code. You could now provide a mock implementation of `Window` for testing. For example, maybe you don't want real alerts to pop up during your tests, but still want to check that `Window.alert()` is called by your component.

Hope this helps!

**Comment by leonsenft** [comment]
Of course, you're welcome to submit a PR. Thanks!

**Comment by chalin** [comment]
> Would it be okay if I were to land a PR updating the example with the new `{Type}Provider`?

Done.

> Otherwise, I think you can mark this as closed unless the team is using this for tracking documentation issues or for https://github.com/dart-lang/site-webdev/issues/1293

@leonsenft - are you using this issue to track any doc/examples changes under this repo? If not, I'd consider it closed by https://github.com/dart-lang/site-webdev/pull/1499.

**Comment by leonsenft** [comment]
@chalin I left it open as I was expecting a PR to close it, but it looks like you have. Thanks!
