### ISSUE TITLE
Make the styles.dart file export a final, not a const

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#807]
As mentioned by @jakemac53, the current setup of `.css.dart` files emitted has (bad) effects on the build process, as any change to the CSS changes the public fields in that file, which in turn invalidates the Dart code.

We've discussed in the past moving it to `.template.dart`, with the following downsides:
* It potentially slows down the critical path (unsure if this is still true)
* Doing optimizations based on this was NP-too-hard (@leonsenft, right?)
* It would break a rarely used (but is used) feature of importing another package's CSS:

```dart
@Component(
  styleUrls: const [
    'package:another_package/foo.scss.css',
  ],
)
```

(We could still support this, but it wouldn't be shared across all instances of use)

/cc @alorenzen @leonsenft

**Comment by alorenzen** [comment]
Do we have to completely remove them, or would just reducing the public api help here, like what we did with the outliner for `.template.dart` files?

**Comment by matanlurey** [comment]
We can't reduce the public API in any real way, since the public API is relied on.

We could make it private (i.e. `_styles`), but that means we'd have to use part files.

**Comment by jakemac53** [comment]
We should also check that in fact private constants are not included in the api summary before putting much work into this - I have a sneaking suspicion that they might be.

**Comment by matanlurey** [comment]
@scheglov would you happen to know?

**Comment by scheglov** [comment]
Unlinked summaries include all constant expressions - for both public and private fields.

**Comment by leonsenft** [comment]
I don't believe part files would work, since a compiled style sheet isn't actually tied to a specific component. You can share the same style sheet URL with multiple components across different source files.

**Comment by matanlurey** [comment]
Thanks! 😢 

@jakemac53 any other ideas 😆

**Comment by matanlurey** [comment]
@leonsenft:

> I don't believe part files would work, since ...

Sure, I meant in the idea that we don't let you do that anymore. It doesn't look like it would buy us anything anyway, since private fields still impact summaries.

**Comment by jakemac53** [comment]
@matanlurey make them final instead of const? :D

Other random ideas:

- Make the styles injectable, and set up the providers inside `initReflector` which shouldn't cause an api change. This might effect the runtime speed/size though.
- Move the styles outside of Dart code entirely somehow (I don't know enough about how they are applied to suggest anything though). Technically you could even write them to JS and read with interop lol.

**Comment by matanlurey** [comment]
> Make the styles injectable

NOOOOOOO. No. No.

> Move the styles outside of Dart code entirely somehow.

Funny enough this has been talked about (@TedSander FYI), but I don't know if we've figured out a way to do this in a way that works with Dart2JS bundling, deferred loading, so on and so forth. **Maybe** we could do this just in dev-mode, but that's a dangerous practice.

**Comment by matanlurey** [comment]
To allow some build-time optimizations in Bazel, I'll be making the field final.

**Comment by jakemac53** [comment]
> To allow some build-time optimizations in Bazel, I'll be making the field final.

Should help build_runner as well :)

**Comment by TedSander** [comment]
+1 Note sharing css across packages is actually an important pattern for angular_components. We have times when we want to provide a CSS file in a dart friendly way for sharing. For example (cards, app layout, and more to come.)

I wouldn't want to see that feature removed. I'd like to be able to do it without wrapping it in a dart package, but that is a whole other can of worms.

**Comment by matanlurey** [comment]
On Thu, May 31, 2018 at 2:43 PM Ted Sander <notifications@github.com> wrote:

> +1 Note sharing css across packages is actually an important pattern for
> angular_components. We have times when we want to provide a CSS file in a
> dart friendly way for sharing. For example (cards, app layout, and more to
> come.)
>
> I wouldn't want to see that feature removed. I'd like to be able to do it
> without wrapping it in a dart package, but that is a whole other can of
> worms.
>

We wouldn't remove that feature, we just wouldn't generate a standalone
file per CSS file.

**Comment by matanlurey** [comment]
Changing this request to just keep as-is, but make the definition `final`.
