### ISSUE TITLE
Figure out a formal anti-XSS story for Dart/AngularDart

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#81]
``` dart
String testInput = '<a href="&#x3000;javascript:alert(1)">CLICKME</a>';
String expected = '<a>CLICKME</a>';
expect(sanitizeHtmlInternal(testInput), expected);
```

test: `pub run test -N mXSS -p firefox test/security/html_sanitizer_test.dart`

**Comment by matanlurey** [comment]
Sorry this has gotten ignored quite a bit. I think it's unlikely we will get to it immediately, given it doesn't seem any clients have run into this.

**Comment by matanlurey** [comment]
Re-opening to keep this active.

**Comment by matanlurey** [comment]
This hasn't gotten a lot of traction, so I'm closing for now.
