### ISSUE TITLE
@ViewChildren() with dart:html's Element does not work

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#814]
So going from...

```dart
class Comp {
  @ViewChild('foo')
  ElementRef foo;
}
```

... to ...

```dart
class Comp {
  @ViewChild('foo')
  Element foo;
}
```

... does not work. We'd need a similar fix as one from `QueryList` -> `List`.

**Comment by matanlurey** [comment]
(This isn't strictly supported, but it will make the migration much easier)

**Comment by matanlurey** [comment]
Now fixed at HEAD!

**Comment by chalin** [comment]
@matanlurey - I'm using Angular alpha+7 and it doesn't seem to work. Is there anything preventing this from making it into a release? Thanks. /cc @kwalrath

**Comment by matanlurey** [comment]
@chalin See https://github.com/dart-lang/angular/blob/master/_tests/test/regression/814_query_html_element_test.dart.

**Comment by chalin** [comment]
How about for `@ViewChildren()`?

**Comment by matanlurey** [comment]
Should work the same, AFAIK. If not it could be a bug.

**Comment by matanlurey** [comment]
This works now as #1078!
