### ISSUE TITLE
Use travis build stages when compiling

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#820]
Due to https://github.com/dart-lang/angular/issues/705, we shard our `_tests` suite manually.

Every `_tests` suite re-builds before running any tests, even though this could be done once:

https://github.com/dart-lang/angular/blob/227e479f8645afc64579d106a6bc50090130f3fd/tool/travis.sh#L34-L38

Looking at logs:

<img width="1251" alt="screen shot 2018-01-31 at 6 35 41 pm" src="https://user-images.githubusercontent.com/168174/35658315-94cbf7de-06b5-11e8-91af-d716bee7dfd5.png">

And then drilling down:

`test_05` took ~10 minutes, of which almost 8 minutes was _building_:
https://travis-ci.org/dart-lang/angular/jobs/335921719

This is a similar pattern for the rest of `test_NN`, with actual test execution time being often 20% or less than the total time to run the suite of tests. I'm not a travis expert, but there has to be a way to run a single build before running any of the test suites, and sharing the existing output directory _or_ we need to fix #705.

/cc @jakemac53 @natebosch @grouma @kevmoo @alorenzen

**Comment by kevmoo** [comment]
We could upload the build output to sort of memcache-ish thing.

With the Travis Build number.

Then check that cache before starting? Or something?

**Comment by natebosch** [comment]
https://docs.travis-ci.com/user/build-stages/

**Comment by jakemac53** [comment]
> https://docs.travis-ci.com/user/build-stages/

Nice find! I wonder if it would make sense to run all analyzer/dartfmt jobs in a stage before running actual tests as a sort of smoke test?

**Comment by jakemac53** [comment]
https://travis-ci.org/dart-lang/build/builds/336195701 doesn't look like we need to do anything special, regular caching works!

**Comment by matanlurey** [comment]
Good to know! I can try that for ourselves too :)

**Comment by matanlurey** [comment]
Stages that make sense in my head:

[ ] 1. Run analyzer (we don't run dartfmt on travis, since we are internal-first)
[ ] 2. Run build for `_tests`
[ ] 3. Run tests

**Comment by jakemac53** [comment]
> Stages that make sense in my head:
> 
> Run analyzer (we don't run dartfmt on travis, since we are internal-first)
> Run build for _tests
> Run tests

Yep that sounds good.

If you wanted to analyze the generated code you could move analyzer to after the build.

**Comment by jakemac53** [comment]
Fwiw, from playing around more with this it looks like you don't get the normal matrix expansion in custom stages, that only applies to the default "test" stage.

**Comment by matanlurey** [comment]
> Fyi, from playing around more with this it looks like you don't get the normal matrix expansion in custom stages, that only applies to the default "test" stage.
> 
> If mono_repo is setting everything up though then I don't think this is a big issue, although the yaml files are going to get larger.

Yeah I'm not sure how our current setups to be honest. @kevmoo

**Comment by kevmoo** [comment]
If we can hand-hack a root `.travis.yml` + `tool/travis.sh` file, I'm ~sure we can get `mono_repo` to play along.

I'm not expert here. Just okay running 50 travis builds to get it working.

Reading here? https://docs.travis-ci.com/user/build-stages/#Build-Stages-and-Build-Matrix-Expansion

**Comment by jakemac53** [comment]
> Reading here? https://docs.travis-ci.com/user/build-stages/#Build-Stages-and-Build-Matrix-Expansion

Ya, the key point there is `Each job included in jobs.include inherits the first value of the array that defines a matrix dimension. In the example above, without explicitly setting rvm: 2.4, the included job inherits rvm: 2.3.`.

So basically, if you have top level `env`, `dart`, etc, all stages other than the default one default to the first entry in each of those lists, and run in _only that configuration_.

**Comment by kevmoo** [comment]
See https://docs.travis-ci.com/user/build-stages/using-yaml-aliases/

Assuming we can do w/ Dart what they do with rvm here...

**Comment by matanlurey** [comment]
Anybody bored enough to want to try this?

**Comment by jakemac53** [comment]
> See https://docs.travis-ci.com/user/build-stages/using-yaml-aliases/
> 
> Assuming we can do w/ Dart what they do with rvm here...

Looks like we could remove some of the boilerplate with that ya, ill take a look

**Comment by jakemac53** [comment]
> Anybody bored enough to want to try this?

I can take a go at it, playing around in the build repo for now but once that is in a good place I will try porting the same logic to angular, and then mono_repo assuming it works how we want.

**Comment by kevmoo** [comment]
The yaml alias trick could help us DRY up the generated file, too – although it is a tiny bit tough to parse at first glance

**Comment by matanlurey** [comment]
@jakemac53 Feel free to unassign if you get busy, but for now enjoy :)
