### ISSUE TITLE
Cannot render multiple components outside of angular

### ISSUE THREAD

**Issue by jrote1** [dart-lang/angular#830]
We have a site currently that renders multiple tags out to the page and then includes our angular js file but only one of them will get rendered. Our current workaround is shown below but it seems very hacky. I think this should be more straight forward.

```
Future renderComponent(ComponentRef appComponentRef, Type componentType) async {
  var applicationRef = appComponentRef.injector.get(ApplicationRef) as ApplicationRefImpl;
  var resolver = appComponentRef.injector.get(ComponentResolver) as ComponentResolver;
  var component = await resolver.resolveComponent(componentType);
  var elements = document.querySelectorAll(component.selector);
  for(var element in elements){
    applicationRef.run(() async {
      var componentRef =  component.create(appComponentRef.injector);
      var location = componentRef.location;
      location.id = element.id;
      element.replaceWith(location);
      applicationRef.registerChangeDetector(componentRef.changeDetectorRef);
    });
  }

var componentRef = await bootstrap(AppComponent);
await renderComponent(componentRef, TestComponent);
```

**Comment by matanlurey** [comment]
Would love to get some input from the team: @hterkelsen @leonsenft @alorenzen.

**Comment by leonsenft** [comment]
To clarify, you'd like `bootstrap(MyComponent)` (or a new function) to render `MyComponent` for every `<my-component>` tag, not just the first?

**Comment by jrote1** [comment]
Yes this is what we require. But I think something that would be really cool would be something like `bootstrapAll(services)` that will find any components that tag is on the page and render, that would make it extremely flexible

**Comment by matanlurey** [comment]
I don't think it is likely we would support this in the framework.
