### ISSUE TITLE
NgFor's trackBy doesn't allow typed arguments

### ISSUE THREAD

**Issue by srawlins** [dart-lang/angular#833]
When you use `NgFor` with `trackBy`:

```html
<li *ngFor="let cat of cats; trackBy: trackByName; let i = index">
</li>
```

you cannot use a simple trackByFn that accepts typed arguments, like so:

```dart
List<Cat> _cats = [];
List<Cat> get cats => _cats;
int trackByName(int index, Cat cat) => cat.name;
```

because the `trackByFn` typedef is said to accept dynamic:

```dart
typedef dynamic TrackByFn(int index, dynamic item);
```

This violates the USES_DYNAMIC_AS_BOTTOM static analysis error. Using dynamic as bottom will be an error in Dart 2.0.

It seems like it should be possible for the compiler to understand the type of `cats` and allow functions that accept a `Cat` argument.

**Comment by matanlurey** [comment]
Uh oh. @leonsenft.

**Comment by natebosch** [comment]
Can we get an example of the specific line where we get the warning in the generated template?

We talked about how we don't have enough information to add a type to the class, I'm wondering if we could somehow make the `trackByFn` a ctor argument or something and get inference to do the work for us...

```dart
typedef dynamic TrackByFn<T>(int index, T item);

class NgFor<T> {
  final TrackByFn<T> trackBy;
  
  NgFor(this.trackBy);
}
...

var ngFor = new NgFor(trackByName); // Do we get a NgFor<Cat> because of inference??
```

**Comment by leonsenft** [comment]
Even if that worked, `ngForTrackBy` is an input, so it's not passed through the constructor, but rather bound as a property during change detection.

**Comment by natebosch** [comment]
> it's not passed through the constructor, but rather bound as a property during change detection.

How often do we think that's relied on? Would it be reasonable to require a static value?

**Comment by leonsenft** [comment]
No idea, but constructor parameters are used for dependency injection, so we'd need to write some hacky special case code for this.

**Comment by srawlins** [comment]
I haven't used angular without bazel, but here's a fudged snippet of the .template.dart that I think would be generated by my cats example, from something built internally with bazel:

```dart
// Source Component

@Component(...)
class PerformanceCatList {
  List<Cat> _cats = [];
  List<Cat> get cats => _cats;
  int trackByName(int index, Cat cat) => cat.name;
}
```

```dart
// Generated Template

class ViewPerformanceCatList0 extends DebugAppView<import8.PerformanceCatList> {
  // ...
  @override
  void detectChangesInternal() {
    final import8.PerformanceCatList _ctx = ctx;
    bool changed = false;
    bool firstCheck = (this.cdState == 0);
    if (firstCheck) {
      if (!identical(_ctx.trackByName, null)) {
        (_NgFor_0_7.ngForTrackBy = _ctx.trackByName); // <== USES_DYNAMIC_AS_BOTTOM
      }
    }
    // ...
  }
}
```

**Comment by natebosch** [comment]
It also looks like it's typical usage to pass the function through another component so it wouldn't be feasible to require it to be static.

**Comment by matanlurey** [comment]
@MichaelRFairhurst's suggestion on chat is:

> `trackByFn = (dynamic x) => userProvidedFunction(x)`

... and rely on implicit downcasts.

It would be hard to this generally, but might be easy enough to do for common cases.

**Comment by natebosch** [comment]
> ... and rely on implicit downcasts.

😭

**Comment by leonsenft** [comment]
What if we added a generic type parameter to `NgFor`, which we inferred from the bound `Iterable`? This would allow us to type the `TrackByFn`.

```dart

typedef TrackByFn<T> = dynamic Function(int, T);

class NgFor<T> {
  @Input()
  set ngForOf(Iterable<T> value) { ... }

  @Input()
  set ngForTrackBy(TrackByFn<T> fn) { ... }
}
```

We even get this type for free, since we're already inferring it on behalf of the locals optimization we made recently.

https://github.com/dart-lang/angular/blob/4bed3e81b1a9c501d1c8c3ab1e9ad245a54b871e/angular/lib/src/compiler/template_optimize.dart#L45-L54

We could then use this type when instantiating the NgFor instance in `build()`.

Thoughts?

**Comment by matanlurey** [comment]
@leonsenft I could see it! I had an idea waaaaay back to do "forced inference".

For example, imagine we defined the following `typedef`:

```dart
typedef TypeInferenceHelper = T Function<T>();
```

```dart
class NgFor<T> {
  NgFor<T>(TypeInferenceHelper<T> _);
}
```

And if you wrote:

```html
<div *ngFor="let item of items">...</div>
```

We could identify this as some sort of "special" token, which means generate:

```dart
class _View0 {
  NgFor _NgForField;

  build() {
    // Use type inference to create the right NgFor<T>.
    var _NgForLocal = new NgFor(() => ctx.items);
    // Assign it (upcast) to NgFor<dynamic>, which is OK.
    _NgForField = _NgForLocal;
  }
}
```

There aren't too many components/directives that are generically typed, so it could be reasonable to have them inject this "special" marker typedef in order to help type inference, and we could always try to figure out a better work-around with the language team later (and hopefully dart2js could detect this isn't actually used?)

WDUT? @leonsenft @natebosch @MichaelRFairhurst @srawlins

**Comment by natebosch** [comment]
If we are able to get better compile time understanding of types and don't need the "forced inference" anymore it's a fair bit to clean up.

I think in your example too the `T` would end up being `List<Something>` which doesn't necessarily give us the `Something` that we need for the trackBy function argument. We'd want the typedef to be `Iterable<T> Function<T>()` which is pretty special cased for `NgFor` so supporting this in a general way for users to take advantage of in their own directives seems like a challenge.

**Comment by matanlurey** [comment]
@natebosch I mean, we could do:

```dart
typedef Iterable<T> IterableTypeHelper<T>();
```

... since that seems to be the hard case, today.

**Comment by natebosch** [comment]
We could. We'd need some way to tell the compiler which binding to pass through it as well.

**Comment by matanlurey** [comment]
I'm guessing you'd just "look for" a setter that is expecting an `Iterable<T>`.

**Comment by natebosch** [comment]
I think it would be challenging, but at this point there may not be a ton more value in discussing hypotheticals. Does anyone have the bandwidth to put together a prototype?

**Comment by matanlurey** [comment]
> Does anyone have the bandwidth to put together a prototype?

No, but I might try anyway.

**Comment by matanlurey** [comment]
We discussed this offline, it doesn't seem worth it. 

The current view compiler is too complex :-/

I think we should document `trackBy` as requiring a cast for now, pending a future solution requiring much more refactoring to the view compiler to support well.

**Comment by matanlurey** [comment]
I added documentation a cast is required, for now.

**Comment by matanlurey** [comment]
We won't be doing anything else here. Closing.

**Comment by chalin** [comment]
> I added documentation a cast is required, for now.

@matanlurey - where did you document this? /cc @kwalrath

**Comment by chalin** [comment]
@matanlurey - nm, I found it in the TrackByFn API docs. Thanks for adding it there!

**Comment by avilladsen** [comment]
Are there plans to reconsider this with the introduction of generic directives in 5.1? Having to explicitly specify the type for each NgFor is a pain, but some people (not including myself) may prefer that to untyped trackBys.
