### ISSUE TITLE
Dart2: Compliance with ignored type cast failure

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#841]
Currently in DDC, the following type-casts are ignored, but _should_ fail:

```dart
List<dynamic> a = ['a', 'a', 'a'];

// Should be List<dynamic> cannot be List<String>.
List<String> b = a;
```

These are _warnings_ in the development console (at runtime), but not errors. The language team is attempting to make these errors in DDC, as they will also be errors in the CFE-driven backends (eventually DDK and Dart2JS on Kernel?).

This is the master tracking issue for places in AngularDart we are violating either explicitly (in the runtime, which is easier to change) or implicitly (in the code we generate, which is more difficult to change).

I believe @leonsenft knows of some cases (with list/map literals), right?

/cc @MichaelRFairhurst @srawlins @munificent @leafpetersen.

- [x] Template Literals https://github.com/dart-lang/angular/issues/844
- [x] `QueryList` (WIP) https://github.com/dart-lang/angular/issues/688

**Comment by matanlurey** [comment]
I'm working on #688 towards this end.

**Comment by kevmoo** [comment]
@matanlurey – can close?
