### ISSUE TITLE
Change detection behaviour on direct input changes and high order components

### ISSUE THREAD

**Issue by Aetet** [dart-lang/angular#846]
Hello.
I try to implement [high order component](https://reactjs.org/docs/higher-order-components.html) for redux-like selector API.

My first attempt - use attibute directive, which take component instance and set properties directly:
```
<parent #par [par]="par" state></parent>
```
Inside directive:
```
@Directive(
    selector: '[state]',
    providers: const [StateService]
)
class StateProvider implements AfterViewInit {
  @Input()
  Parent par;

  final StateService stateService;
  StateProvider(this.stateService);
  // Get some state from stateService
  void ngAfterViewInit() => par.name = stateService.name;
}
```

But there's a problem - Parent is OnPushComponent and doesn't know that his input changed. Because it happens outside angular template. And nothing changed at browser on change name.

For this we need some boilerplate code like:
```
@Component(
    selector: 'parent',
    template: '{{jackie}}',
    directives: const [Child],
    changeDetection: ChangeDetectionStrategy.OnPush,
    )
class Parent {
  ChangeDetectorRef _ref;
  Parent(this._ref);
  String name1;
  @Input()
  set name (String val) => name1 = getNewVal<String>(_ref)(val);
}

typedef K ChangeFunc<K>(K k);

ChangeFunc<K> getNewVal<K>(ChangeDetectorRef ref) {
  Object _latestValue;
  return (K val) {
    if (_latestValue != val) {
      ref.markForCheck();
    }
    return val;
  };
}
```

I think this connected to 4,5 at https://github.com/dart-lang/angular/issues/844

There's a few questions:
1. How to make selector-like API in angular-way without direct access from components to state?
2. Is it possible detect input changes without so much boilerplate?
3. There's stateful component change detection strategy, but it leaks the same problem - @Input does'not involve at change detection and need manual control.

**Comment by matanlurey** [comment]
I don't think we have a good answer for this yet, though thank you for filing.

**Comment by leonsenft** [comment]
Have you considered using [`exportAs`](https://webdev.dartlang.org/api/angular/angular/Directive/exportAs)? This would allow you to bind state from `StateProvider` to a component's inputs directly in the template.

Here's an example. I'd probably have just called the `exportAs` and `#` references all `state`, but I gave them more explicit names here to be clear what's going on.

```dart
@Directive(
  selector: '[state]',
  exportAs: 'stateExportAs',
)
class StateProvider {
  final String name;
  StateProvider(StateService service) : name = service.name;
}

@Component(
  selector: 'parent',
  ...,
)
class ParentComponent {
  @Input()
  String name;
}
```

```html
<parent
    state
    #stateRef="stateExportAs"
    [name]="stateRef.name">
  ...
</parent>
```

Does this accomplish what you're asking for in your first question?

**Comment by Aetet** [comment]
@leonsenft Yep. Thanks a lot! That's exactly what I need.

**Comment by Aetet** [comment]
@leonsenft I research example more deeply and find out that it does not work for some cases. Like:
```
@Directive(
    selector: '[state]',
    providers: const [StateService],
    exportAs: 'stateExportAs'
)
class StateProvider implements AfterViewInit {
  NgZone _zone;
  StateProvider(this._zone);
  String jack;

  @override
  void ngAfterViewInit() {
    jack = 'black';
    _zone.runOutsideAngular(() {
      new Timer(const Duration(seconds: 3), () {
          jack = 'doe';
      });
    });
  }
}
```
If there's no zone update - there's no update for onPushComponent. As workaround there's two options:
1. Pass parent ChangeDetectorRef and use change detector from there.
2. Use detectChanges from directive changeDetector. 
```dart
class StateProvider implements AfterViewInit {
  NgZone _zone;
  ChangeDetectorRef _ref;
  StateProvider(this._zone, this._ref);
  String jack;
 
  @override
  void ngAfterViewInit() {
    _zone.runOutsideAngular(() {
      new Timer(const Duration(), () {
          jack = 'doe';
          _ref.markForCheck();
      });
    });
  }
}

```

One more question. Why detectChanges launch cd-cycle, but markForCheck doesn't?

**Comment by leonsenft** [comment]
Your first example doesn't work because you're making your change outside of the Angular zone. Angular relies on the end of a zone turn to trigger the change detection. You can always re-enter the zone if you want the change to be detected, although in this example there'd really be no point in running outside the zone at all.

```dart
_zone.runOutsideAngular(() {
  new Time(const Duration(), () {
    _zone.run(() {
      jack = 'doe';
    });
  });
});
```

I'm couldn't say for certain without digging into the code and generated code, but I'm guessing `markForCheck` isn't marking the component itself since you're calling it from the directive, whereas `detectChanges` just triggers global change detection?

@ferhatb and @jonahwilliams are more knowledgeable about how change detection interacts with various `ChangeDetectionStrategy`'s. Maybe they can offer some insight.
