### ISSUE TITLE
Structural directive microsyntax doesn't parse default @Input

### ISSUE THREAD

**Issue by zacharydenton** [dart-lang/angular#848]
I'm creating a structural directive and would like users to be able to use it via the microsyntax (e.g. `*ngFor="let item of items; trackBy: trackByFn"`). My directive looks like this:

```dart
class DeferredContentDirective {
  @Input('deferredContent')
  bool isDeferredContentEnabled = true;

  @Input()
  num deferredContentWidth;

  @Input()
  num deferredContentHeight;
}
```

I can use this like `*deferredContent="shouldUseDeferredContent"` or `*deferredContent="width: 50; height: 100"`. However, if I try to combine the two (`*deferredContent="shouldUseDeferredContent; width: 50; height: 100"`), I end up with a parse error: "**Binding expression cannot contain chained expression**".

Note, I can provide all three inputs via the `<template>` syntax: 

```html
<template [deferredContent]="shouldUseDeferredContent" [deferredContentWidth]="50" [deferredContentHeight]="100">
```

Is this a bug in the microsyntax parser or am I just using it incorrectly?

**Comment by leonsenft** [comment]
@alorenzen since you just rewrote the template parser, any insight in to why this wouldn't work? This isn't just a special case for `NgFor` now is it?
