### ISSUE TITLE
AST Parser allows the build to continue

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/angular#857]
I'm getting the following error when running `pub run build_runner serve` (Using alpha+5):
```
[SEVERE] Instance of 'DevCompilerBuilder' on datingnode_app_angular|lib/datingnode_app_angular.template.module:
Error compiling dartdevc module:datingnode_app_angular|lib/datingnode_app_angular.template.ddc.js

[error] The function 'initReflector' isn't defined. (package:datingnode_app_angular/src/components/components.template.dart, line 103, col 10)

Please fix all errors before compiling (warnings are okay).
}
```

I believe the error is due to the fact I have a Library builder error ( https://github.com/dart-lang/angular/issues/856 ). I suspect this as yesterday there were two initReflector errors but I fixed one of the library errors and now there is only one initReflector error.

If this is the case maybe the error message could be useful and say something like __"Couldn't compile due to library errors"__ or similar?

**Comment by matanlurey** [comment]
@jimmyff You should be able to run with `serve --fail-on-severe`.

We are considering changing the default: https://github.com/dart-lang/build/issues/1097
