### ISSUE TITLE
Crashes building _tests on Travis

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#868]
https://travis-ci.org/dart-lang/angular/jobs/339919120

... even with `--low-resources-mode`:

```
pub run build_runner build --low-resources-mode --fail-on-severe
[INFO] Entrypoint: Generating build script completed, took 457ms
[INFO] BuildDefinition: Building new asset graph completed, took 1.4s
[INFO] BuildDefinition: Checking for unexpected pre-existing outputs. completed, took 2ms
[WARNING] View Compiler: Can't bind to 'value' since it isn't a known native property or known directive. Please fix typo or add to directives list.
[INFO] Heartbeat: ... still running (6m 11s so far)Rescheduling failed request...
[INFO] Heartbeat: ... still running (6m 31s so far)Rescheduling failed request...
[INFO] Heartbeat: ... still running (7m 56s so far)Rescheduling failed request...
[INFO] Heartbeat: ... still running (10m 30s so far)Rescheduling failed request...
[INFO] Heartbeat: ... still running (10m 58s so far)Rescheduling failed request...
[INFO] Heartbeat: ... still running (11m 53s so far)Rescheduling failed request...
[SEVERE] Instance of 'LinkedSummaryBuilder' on collection|lib/src/comparators.module: 
SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
Rescheduling failed request...
```

I'm not sure what we can do :-/

/cc @natebosch @jakemac53, you're my only hope.

**Comment by jakemac53** [comment]
We can take a look, does this happen consistently? I thought we were pretty stable so I wonder if something pushed it over the edge in one of the recent releases (performance tracking possibly?).

**Comment by matanlurey** [comment]
I can't merge at all so yeah consistently

**Comment by jakemac53** [comment]
Ok, will make this a priority today then

**Comment by matanlurey** [comment]
FWIW, this does only happen recently. So it could be something else (newest SDK, newest analyzer, changes to AngularDart in subtle ways), etc.

**Comment by jakemac53** [comment]
I am actually pretty sure its related to the performance tracker, we probably consume a decent amount of ram actually as a result of that (recording start/end times per input/builder combo).

I am working on making it so we don't track performance in low resource mode.

**Comment by matanlurey** [comment]
❤️ ❤️ ❤️

**Comment by jakemac53** [comment]
:D https://travis-ci.org/dart-lang/angular/jobs/340580281

**Comment by jakemac53** [comment]
Hmm actually weird that didn't run in low resource mode and passed?

**Comment by matanlurey** [comment]
Maybe try branching off my blocked PR? It's possible something in there
sends it over the edge?

**Comment by jakemac53** [comment]
So https://travis-ci.org/dart-lang/angular/jobs/340599170 did actually succeed but after 20 minutes (takes 3.5 locally with the same flags...). Then the travis build actually never exited which is weird. I noticed the hand edits to the travis yml file were reverted so I am trying with those re-added.

**Comment by matanlurey** [comment]
@jakemac53 Has resolved this. Thanks!
