### ISSUE TITLE
Our users need a DDC Chrome extension released

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#872]
/cc @kevmoo for triage, @terrylucas, @vsmenon.

**Comment by kevmoo** [comment]
CC @alan-knight as well

**Comment by leonsenft** [comment]
Is this not a duplicate of #796?

**Comment by matanlurey** [comment]
As much as I'd love to have this by 5.0, it seems unlikely, at this point. Pushing back.

**Comment by matanlurey** [comment]
Closing. Whatever will be available is here: https://github.com/dart-lang/devtools-frontend.
