### ISSUE TITLE
Unable to spawn isolate: barback

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/angular#877]
While I was trying to create a repro of another error, I encountered this one:

```
MBP-de-Jonathan:provider jonathanrezende$ pub run build_runner build
[INFO] Entrypoint: Generating build script completed, took 256ms
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: Unhandled exception:
Could not import "package:barback/barback.dart" from "package:angular_compiler/src/asset.dart": No mapping for 'barback' package when resolving 'package:barback/barback.dart'.
null
#0      Isolate.spawnUri (dart:isolate-patch/dart:isolate/isolate_patch.dart:454)
<asynchronous suspension>
[provider.zip](https://github.com/dart-lang/angular/files/1719608/provider.zip)

#1      main (http://localhost:59267/build_runner.dart:49)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
MBP-de-Jonathan:provider jonathanrezende$ 
```

angular: "^5.0.0-alpha+5"
angular_forms: "^1.0.1-alpha+5"
angular_router: "^2.0.0-alpha+5"
Dart VM version: 2.0.0-dev.22.0 (Thu Feb 8 18:55:13 2018 +0100) on "macos_x64"

**Comment by jodinathan** [comment]
[provider.zip](https://github.com/dart-lang/angular/files/1719613/provider.zip)

**Comment by jakemac53** [comment]
It looks like this import was removed 7 days ago (https://github.com/dart-lang/angular/commit/445400374e9facecd47c0000fcbcadd77b1b6928#diff-07cb77e8a9fa8791d74558652cd3c59dL3) but I don't know if that was published yet?

**Comment by matanlurey** [comment]
Yup, thanks for mentioning @jodinathan.

It will be fixed in the next release (this week). In the mean-time you could add:

```yaml
dev_dependencies:
  barback:
```

... just to get unblocked.
