### ISSUE TITLE
materialProviders mismatch as JSArray<Object>

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/angular#891]
Just try to add the *materialDirectives* to the bootstrapStatic provider list like:

```
void main() {
  bootstrapStatic(AppComponent, [
    ac.materialProviders
  ], ngMain.initReflector);
}
```

However, it works if you change it to popupBindings like:
```
bootstrapStatic(AppComponent, [
    ac.popupBindings
  ], ngMain.initReflector);
```

**Comment by matanlurey** [comment]
As discussed on Gitter, please file in `angular_components`.
