### ISSUE TITLE
angular_router 2 : no blank path route hangs browser

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/angular#892]
Not having a route declared with a blank path hangs Chrome. Even if I specify useAsDefault. I've had this on two separate projects.

**Comment by matanlurey** [comment]
@leonsenft

**Comment by leonsenft** [comment]
@jimmyff Could you please provide a reproduction case? I haven't experienced this issue myself.

**Comment by jimmyff** [comment]
Ah. I think it's this that was my half-baked 404 that was causing the issue:

```dart
    new RouteDefinition.redirect(
      path: '.*', 
      redirectTo: 'not-found',
    ),
```

I know the redirectTo should be a route.toUrl() but I hadn't got around to adding a 404 component  yet. So it hangs the browser probably endlessly looping which I guess is what you'd expect if you have a not implemented 404

**Comment by leonsenft** [comment]
Ah yes, the router doesn't prevent against redirect loops. I wonder if we should just limit redirection to one route?

Change

https://github.com/dart-lang/angular/blob/4bed3e81b1a9c501d1c8c3ab1e9ad245a54b871e/angular_router/lib/src/router/router_impl.dart#L147-L150
to

```dart
 if (nextState.routes.isNotEmpty && 
     nextState.routes.last is RedirectRouteDefinition) {
  if (isRedirect) return NavigationResult.INVALID_ROUTE;
  var redirectUrl = 
      (nextState.routes.last as RedirectRouteDefinition).redirectTo;
  ...
  }
}
```
