### ISSUE TITLE
build_runner + sass_builder: could not read file: null

### ISSUE THREAD

**Issue by zsyphon** [dart-lang/angular#896]
Just upgraded every package I am using to the newest version and running on sdk 2.0.0-dev.26.0.

Now I am getting errors during the build that start:
`[INFO] Entrypoint: Generating build script completed, took 455ms
[INFO] BuildDefinition: Building new asset graph completed, took 2.1s
[INFO] BuildDefinition: Checking for unexpected pre-existing outputs. completed, took 1ms
[SEVERE] sass_builder: could not read file: null
[SEVERE] sass_builder: could not read file: null
[SEVERE] sass_builder: could not read file: null
[SEVERE] sass_builder: could not read file: null`

And warnings:
`[WARNING] Instance of 'WebEntrypointBuilder' on my_proj|web/main.dart: Missing module my_proj|lib/src/core/components/card/card_component.scss.css.shim.module
[WARNING] Instance of 'WebEntrypointBuilder' on my_proj|web/main.dart: Missing module my_proj|lib/src/core/components/veenee/logo/logo_component.scss.css.shim.module
[WARNING] Instance of 'WebEntrypointBuilder' on my_proj|web/main.dart: Missing module my_proj|lib/src/core/components/navigation/sidebar/sidebar_component.scss.css.shim.module
[WARNING] Instance of 'WebEntrypointBuilder' on my_proj|web/main.dart: Missing module my_proj|lib/src/core/components/layout/footer/footer_component.scss.css.shim.module
[WARNING] Instance of 'WebEntrypointBuilder' on my_proj|web/main.dart: Missing module my_proj|lib/src/core/components/layout/header/header_component.scss.css.shim.module`

Ending with the build not producing anything runnable. The final errors look like:
`[SEVERE] Instance of 'DevCompilerBuilder' on my_proj|lib/src/app/dashboard/dashboard_component.template.module: 
Error compiling dartdevc my_proj|lib/src/app/dashboard/dashboard_component.template.ddc.js

[error] Target of URI doesn't exist: 'package:my_proj/src/app/dashboard/dashboard_component.scss.css.shim.dart'. (package:my_proj/src/app/dashboard/dashboard_component.template.dart, line 42, col 8)
[error] Target of URI doesn't exist: 'package:my_proj/src/app/dashboard/dashboard_component_responsive.scss.css.shim.dart'. (package:my_proj/src/app/dashboard/dashboard_component.template.dart, line 43, col 8)
[error] Const variables must be initialized with a constant value. (package:my_proj/src/app/dashboard/dashboard_component.template.dart, line 71, col 56)
[error] The values in a const list literal must be constants. (package:my_proj/src/app/dashboard/dashboard_component.template.dart, line 71, col 56)
[error] Const variables must be initialized with a constant value. (package:my_proj/src/app/dashboard/dashboard_component.template.dart, line 71, col 72)
[error] The values in a const list literal must be constants. (package:my_proj/src/app/dashboard/dashboard_component.template.dart, line 71, col 72)

Please fix all errors before compiling (warnings are okay).
`
For reference my pubspec is:
`name: my_proj
description: A web app that uses AngularDart Components
version: 0.0.1

environment:
  sdk: '>=1.24.0 <=2.0.0-dev.26.0'

dependencies:
  angular: ^5.0.0-alpha+5
  angular_components: ^0.9.0-alpha+5
  angular_router: ^2.0.0-alpha+5
  http: ^0.11.3+16
  bootstrap_sass: 4.0.0-alpha.5+1
  async: ^2.0.4
  quiver: ^0.28.0
dev_dependencies:
  build_runner: ^0.7.10+1
  build_web_compilers: ^0.3.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  sass_builder: ^1.1.3
dependency_overrides:
    #analyzer: ^0.31.0-alpha.1
analyzer:
    strong-mode: true
transformers:
- sass_builder:
    outputExtension: .scss.css
- angular:
    entry_points:
      - web/main.dart
- dart_to_js_script_rewriter`

**Comment by matanlurey** [comment]
This issue was moved to dart-lang/build#1020
