### ISSUE TITLE
Add future-proof BuildError.forElement

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#902]
I'd like to give my team an ergonomic, easy API for emitting build errors, such as:

```dart
import 'package:analyzer/dart/element/element.dart';
import 'package:source_span/source_span.dart';

class BuildError extends Error {
  // ...

  factory BuildError.forElement(
    Element element,
    String message, [
    Trace trace,
  ]) {
    final node = element.computeNode();
    if (node == null) {
      return new BuildError(message, trace);
    }
    final span = new SourceSpan(
      new SourceLocation(
        node.offset,
        sourceUrl: element.source.uri,
      ),
      new SourceLocation(
        node.offset + node.length,
        sourceUrl: element.source.uri,
      ),
      element.source.contents.data,
    );
    return new BuildError(span.message(message), trace);
  }

  // ...
}
```

... however, this requires:

* ~~`element.source`~~ OK via @MichaelRFairhurst 
* ~~`element.source.uri`~~ OK via @MichaelRFairhurst 
* ~~`element.source.contents.data`~~ OK via @MichaelRFairhurst 
* `element.computeNode()`

... and I'm not sure it's future-proof for driver/kernel goodness. At the same time, I really need the capability to be able to emit good error messages that point back to the offending user code wherever possible.

/cc @scheglov @MichaelRFairhurst could I get some help/advice here?

**Comment by MichaelRFairhurst** [comment]
Do you need `element.computeNode`? How about `element.nameOffset` instead? There are some differences, like, you'll get just the offset of the class/method name instead of the entire class/method body, so it might not do what you want, but I figured I'd check!

**Comment by MichaelRFairhurst** [comment]
These should all be future proofed through kernel and beyond:

element.source
element.source.uri
element.source.contents.data

so if you don't need `computeNode` then we are good on all counts I think

**Comment by matanlurey** [comment]
Hmm. The `nameOffset` might be OK, though I worry it will not have enough information in some cases. Though I'm happy to start here and complain if I see that error messages aren't readable enough.

**Comment by scheglov** [comment]
Don't use `element.source.contents` - it reads the contents of the source at the moment of invocation. The file might have been already changed. `AnalysisDriver.getResult()` returns you `AnalysisResult` that has everything - the `content` that was resolved, the resolved `CompilationUnit`, and the `LibraryElement`.

Don't use `element.computeNode()`, again, `AnalysisDriver.getResult()` will get you everything - resolved unit and elements. Remember them and  use one to get another. Then you can use `NodeLocator` to find the node for an element.

**Comment by matanlurey** [comment]
In this particular case it's when the compiler is going to hard fail so I'm not worried about performance

**Comment by matanlurey** [comment]
Done, thanks @scheglov and @MichaelRFairhurst:

https://github.com/dart-lang/angular/blob/1d79577139085d927d6ee1b4a8cb9e41256d1336/angular_compiler/lib/src/cli/logging.dart#L69-L94
