### ISSUE TITLE
We emit stale "[WARNING]: Invalid @Injectable()..."

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#906]
This code looks really suspect:
https://github.com/dart-lang/angular/blob/1abcb5c62fc8a8267f1abdb2081d07f40567c56f/angular/lib/src/source_gen/template_compiler/compile_metadata.dart#L54-L86

... because we don't process `@Injectable()` at all in this file anymore (it was all moved to `angular_compiler` a few months back). I think this is used by other parts of the compiler, and at worst emits misleading messages (or wrong ones).

For example the internal bug looks like this:

> I noticed a `@Injectable()` warning but not sure what it means:
> 
> ```
> [WARNING]: Invalid `@Injectable()` annotation: Found a constructor for abstract class WorkflowActivityBuilderFactory but it is not a "factory", and cannot be invoked
> ```
> 
> ```dart
> // Factory interface to create [WorkflowActivityBuilder].
> abstract class WorkflowActivityBuilderFactory {}
> 
> @Injectable()
> class WorkflowActivityBuilderFactoryImpl implements ... {}
> ```

**Comment by alorenzen** [comment]
If you're looking for a repro case inside our repo, I'm seeing this warning for `ControlValueAccessor` in `angular_forms`.
