### ISSUE TITLE
Dart2: Component provider fields are not properly typed

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#920]
This is causing cast exceptions from `JSArray` -> `List<ExplicitType>`.

For `angular_components`, we see the following case:

Line 465 on `material_popup_example.template.dart` confirms this is our view compiler being bad:

```dart
  List<dynamic> _defaultPopupPositions_136_20;
```

Line 1345 on ":

```dart
_defaultPopupPositions_136_20 = const [
  const import56.RelativePosition(animationOrigin: 'top center'),
  const import56.RelativePosition(
      animationOrigin: 'top right',
      originX: const import56.Alignment('End', 'flex-end')),
  const import56.RelativePosition(
      animationOrigin: 'top left',
      originX: const import56.Alignment('Start', 'flex-start')),
  const import56.RelativePosition(
      animationOrigin: 'bottom center',
      originY: const import56.Alignment('End', 'flex-end')),
  const import56.RelativePosition(
      animationOrigin: 'bottom right',
      originX: const import56.Alignment('End', 'flex-end'),
      originY: const import56.Alignment('End', 'flex-end')),
  const import56.RelativePosition(
      animationOrigin: 'bottom left',
      originX: const import56.Alignment('Start', 'flex-start'),
      originY: const import56.Alignment('End', 'flex-end'))
];
```

... so, while this is _expected_ to infer the "right" type, it doesn't, because it will be inferred as `List<dynamic>` instead.

Two possible fixes:

1. Use a local variable, i.e.:

```dart
  var localDefaultPopup" = ...
  _defaultPopupPositions = localDefaultPopup;
```

... not ideal, because it will cause runtime checks for DDC (also potentially Dart2JS)

2. Correctly type the field as `List<RelativePosition>`

... I'd prefer to do (2).

Will look into first adding a regression test, and then fixing the bug.

**Comment by matanlurey** [comment]
Note this specifically effects `useValue: const [ ... ]` or similar. 

I think `useFactory` or anything that would flow types automatically is unaffected. 

Still fixing :)

**Comment by matanlurey** [comment]
OK tracing it down, seeing some funkiness with types being dropped:

(Debug messages so I remember what I was doing)

`compile_view.dart`: `[WARNING]: Adding __usPresidents_0_5`
`dart_emitter.dart`:

```
[WARNING]: __usPresidents_0_5 with type of ...
[WARNING]: Printing List<null>
```

... so it looks like we go from a `List<String>` to `List<null>`.

**Comment by matanlurey** [comment]
Added a bit more debugging in `compile_view.dart:

```dart
      // We don't have to eagerly initialize this object. Add an uninitialized
      // class field and provide a getter to construct the provider on demand.
      var internalField = '_$propName';
      logWarning('Adding $internalField as ${(type as o.ExternalType).typeParams.map((e) => (e as o.ExternalType).value.name)}');
```

**Comment by matanlurey** [comment]
... shows that type.typeParams is `null`. Waaaaa?

**Comment by matanlurey** [comment]
Further debugging:

```
[WARNING]: genericTypes: [List<String>]
[WARNING]: Importing a typeArgument...
[WARNING]: Adding __usPresidents_0_5 as null
```

... so it starts right, it looks from `fromDartType` might be blowing up.

**Comment by matanlurey** [comment]
```dart
      if (!genericType.isDynamic) {
        _logger.warning('genericTypes: $typeArguments | ${((fromDartType(typeArguments.first) as o.ExternalType).typeParams.first as o.ExternalType).value.name}');
```

... outputs ...

```
[WARNING]: genericTypes: [List<String>] | String
```

... so that is right! Again, something is dropping this argument.

**Comment by matanlurey** [comment]
```dart
    _logger.warning(((providerTypeArgument.genericTypes.first as o.ExternalType).typeParams as dynamic).first.value.name);
```

... outputs ...

```
[WARNING] String
```

... so the problem is definitely not in `template_compiler/compile_metadata.dart`.

**Comment by matanlurey** [comment]
Figured it out. CL will be out soon.

**Comment by alorenzen** [comment]
Was this fixed, or is the CL still pending?

**Comment by matanlurey** [comment]
Yup, this is fixed enough to close this.
