### ISSUE TITLE
rename `Router.stream`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular#922]
I think it should be `onNavigation` or similar instead. 
There is `onNavigationStart` and it would be consistent with the whole `dart:html` API if event streams would have a name following that pattern.

**Comment by matanlurey** [comment]
Thoughts @leonsenft?

**Comment by leonsenft** [comment]
Absolutely agreed, `stream` is a terribly nondescript name. When I added `onNavigationStart` I thought about renaming `stream` to `onNavigationEnd`, but was worried that would encourage writing APIs that assumed the two complemented each other (they don't necessarily, see `onNavigationStart` documentation).

Anyone have any strong feelings about the name? Some ideas:

- onNavigation
- onNavigationEnd
- onRouteChanged
- onRouteActivated

**Comment by zoechi** [comment]
+1 for `onRouteActivated`
