### ISSUE TITLE
angular_router.dart should export ComponentRouteDefinition

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular#923]
`angular_router.dart` should export `ComponentRouteDefinition` and the other subclasses of `RouteDefinition`

so I can do `is ComponentRouteDefinition` checks  for example when I want to search in `routes` array for a specific route that matches a router event but only a `RouteDefinition` of type `ComponentRouteDefinition` has a `routePath` property.

**Comment by matanlurey** [comment]
That sounds reasonable. WDUT @leonsenft?

**Comment by leonsenft** [comment]
So this was originally marked this type as `@visibleForTesting` which was commonly, but incorrectly used to indicate package private visibility. The author clearly did not intend for this type to be exported.

This is the only field the type has, is this what you want access to?
 https://github.com/dart-lang/angular/blob/262b10780f331a40ffcc13b6d6a4bc79116a5970/angular_router/lib/src/route_definition.dart#L181-L182

None of the `RouteDefinition` types retain the `routePath` parameter, it's simply used during construction.

Could you describe more precisely what it is you're trying to do @zoechi? Perhaps there's a simpler way.

**Comment by zoechi** [comment]
What I am actually trying to do is figure out what route is the current route.

**Comment by leonsenft** [comment]
Does neither

https://github.com/dart-lang/angular/blob/11c05e29fafcea13e4d54f246e70402460777e94/angular_router/lib/src/router/router.dart#L32-L36

nor

https://github.com/dart-lang/angular/blob/11c05e29fafcea13e4d54f246e70402460777e94/angular_router/lib/src/lifecycle.dart#L154-L159

accomplish what you need?

**Comment by zoechi** [comment]
I'll have another look tomorrow.

I tried these and I get a 'RouteState` but I haven't found a good way to match it with my routes to figure out which of my routes exactly the state represents.

Also I tried to get the current route at the component that contains the `<router-outlet>`.
I can pass that to the parent using a service but that is a bit cumbersome to implement in all possible child components.

**Comment by leonsenft** [comment]
What is the goal of finding which route matched the component though?

If you're trying to do something different within the same component that multiple routes render, have you considered using `addditionalData` to pass some contextual information to your component?

https://github.com/dart-lang/angular/blob/262b10780f331a40ffcc13b6d6a4bc79116a5970/angular_router/lib/src/route_definition.dart#L30-L33

Here's an example of how the same component is used to render different data feeds depending on the route that matched.

https://github.com/dart-lang/angular/blob/master/examples/hacker_news_pwa/lib/src/routes.dart

**Comment by zoechi** [comment]
Yes, I experimented with `additionalData`. I had to fight some other unrelated issues today. 
Thanks for the pointers. I'll report back.

**Comment by matanlurey** [comment]
Closing as it looks like this isn't needed. Pleas re-open if I'm incorrect.
