### ISSUE TITLE
hacker_news_pwa: breaks w/ DDC

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#938]
Sync to head: ec4dc9fb

```console
> pub upgrade
> pub run build_runner serve
```

Hit `localhost:8080`

![screen shot 2018-02-26 at 3 52 31 pm](https://user-images.githubusercontent.com/17034/36702717-16bacfd4-1b0d-11e8-8381-03851585de9d.png)

guessing this has to do with how DDC bootstraps scripts?

**Comment by matanlurey** [comment]
Maybe PWA doesn't work with DDC? I doubt it was ever tried.

**Comment by kevmoo** [comment]
> Maybe PWA doesn't work with DDC? I doubt it was ever tried.

Likely. Will talk to DDC folks – see if we need a corresponding DDC issue, etc

**Comment by matanlurey** [comment]
@kevmoo I assume it works in Dart2JS still, so we could still do #939

**Comment by kevmoo** [comment]
> @kevmoo I assume it works in Dart2JS still, so we could still do #939

Yup, and it looks like getting https://github.com/dart-lang/build/issues/1059 fixed shouldn't be too hard.

...took me 30 minutes to hack it together

**Comment by matanlurey** [comment]
Fixed
