### ISSUE TITLE
Should we auto-publish examples/ to github.io?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#941]
Thoughts @filiph @kevmoo.

Basically on every green master, use travis to push.

**Comment by kevmoo** [comment]
Uh...sure?

Maybe just hacker news – it's really the only interesting one, right?

**Comment by matanlurey** [comment]
The other ones are interesting for code-size purposes (and looking at the generated code), but yeah, I get what you mean.

**Comment by matanlurey** [comment]
Duplicate of #939.
