### ISSUE TITLE
Intent to Deprecate: DebugElement (and related)

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#952]
We intend to remove the "debug" variant of code generation.

This made a lot of sense at one point, and lesser today - most tests don't require it, and there was never any tooling built out for "debug mode" (i.e. Chrome extensions) that justify the weight of this feature (code size, slower runtime in DDC, etc).

Lots of steps here:

* [x] Migrate enough internal tests ourselves to validate.
* [x] Mark APIs `@Deprecated`.
* [x] Stop replying on debug mode in our own tests/code.
* [x] Remove support for debug mode from `angular_test`.
* [x] Stop replying on debug mode internally.
* [x] Remove support for debug mode from the internal test bed.
* [x] Remove support for debug mode from the compiler, and golden files.

**Comment by matanlurey** [comment]
@liuming0 has done the internal bits, I think we are ready to do the rest.

**Comment by leonsenft** [comment]
@matanlurey This checklist seems out of date, mind confirming which tasks remain?

**Comment by matanlurey** [comment]
@leonsenft Done!

**Comment by matanlurey** [comment]
Blocked by https://github.com/dart-lang/angular/issues/1396.
