### ISSUE TITLE
Benchmarks: Web Platform

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#968]
We want to create a small series of Dart4Web "platform" tests for the library and language team to help us improve after Dart2 lands. We're going to concentrate on 4 areas for now:

* [ ] Using `XmlHttpRequest` (XHR) via `pkg/http` to download data.
* [ ] Encoding and decoding JSON.
* [ ] UI Programming: Manipulating DOM via `dart:html`, registering callbacks.
* [ ] Using core collections (`List`, `Map`, `Iterable`) and RTTI.

I'll be looking to organize the `_benchmarks` folder a bit as a result:

```
dev/
  benchmarks/
    platform/
      xhr/
      json/
      dom/
      collections/ 
```

... we'll likely slowly move the other dev-only packages into `dev`.

I would love to create a top-level `packages` folder similar to Flutter (https://github.com/flutter/flutter), but I don't know if that is feasible.

**Comment by leonsenft** [comment]
Do these even belong in the Angular repository? It sounds like all of these could be standalone benchmarks, or do you want to benchmark them in context of an Angular application?

What's infeasible about a top-level `packages` folder?

**Comment by matanlurey** [comment]
> Do these even belong in the Angular repository

Since we care about them, it's better to keep here. Can always move later.

> What's infeasible about a top-level `packages` folder?

It would cause you to write, internally:

```
import 'package:third_party.dart_src.angular.packages.angular/angular.dart'
```

Doesn't seem worth it, at least not yet.

**Comment by alorenzen** [comment]
> It would cause you to write, internally:
> `import 'package:third_party.dart_src.angular.packages.angular/angular.dart'`
>Doesn't seem worth it, at least not yet.

Not necessarily. Have you seen how complex the copybara config is for angular_components? I'm sure we could do this entirely as a transformation if we really wanted to.

**Comment by leonsenft** [comment]
> Since we care about them, it's better to keep here. Can always move later.

Fair enough.

> It would cause you to write, internally:

Couldn't we leave the internal directory structure unchanged, but insert the directory in our Copybara script?

**Comment by matanlurey** [comment]
Yes, potentially. Not sure its worth it right now.

Happy to do the CopyBara change if folks want it...

**Comment by alorenzen** [comment]
You're the one that filed the issue...

**Comment by matanlurey** [comment]
Right, I'm not planning on doing the CopyBara refactor.

Feel free to.

**Comment by matanlurey** [comment]
Lets move this elsewhere.
