### ISSUE TITLE
HN example: Increase firebase cache times for important assets

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#969]
See https://www.webpagetest.org/performance_optimization.php?test=180228_Y9_308b0df83539fbb26d30a51ea3067c7b&run=3#cache_static_content

Add 24-hour expire for `pwa.dart.js`, `images/logo.svg`

...and `main.dart.js` ?

**Comment by matanlurey** [comment]
As far as I know I did?

https://github.com/dart-lang/angular/blob/7024dbe70531f5b8b3450992dfcd957d2e798e3b/examples/hacker_news_pwa/firebase.json#L15-L26

@kevmoo

**Comment by leonsenft** [comment]
Is there someway to indicate a request isn't a static asset? The 80/100 score for using CDN on static assets blames a REST API we hit, which isn't a static asset.

**Comment by matanlurey** [comment]
I think we did this. Feel free to re-open if I'm mistaken @kevmoo.

**Comment by kevmoo** [comment]
You did it for the root file, but not the other stuff...

I'll dig in...
