### ISSUE TITLE
Change detection issue

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular#976]
```dart
@Component(
  selector: 'post-list',
  directives: const [],
  pipes: const [AsyncPipe],
  templateUrl: 'post_list_component.html',
  changeDetection: ChangeDetectionStrategy.OnPush, // also tried with default
)
class PostListComponent {
  PostListComponent(this._appControllerService,
    this._router, this._cdRef) {
    print('create');
    onPosts.listen((posts) {
        _posts = posts;
        print('onPosts: $posts}');
        _cdRef.detectChanges();
      });
  }

  BuiltList<PostController> _posts;
  BuiltList<PostController> get posts {
    print('get posts: $_posts');
    return _posts;
  }

  void selectPost(PostController post) async {
    print('selectPost ${post.id}');
    _postEditorController.selectPost(post);
    await _router.navigate(postViewRoute.toUrl(parameters: {
      postFilterParameter: postFilter,
      postIdParameter: '${post.id}'
    }));
  }
}
```

The first time the component is rendered it shows a value, but after executing `selectPost(...)`

```
create
get posts: null
dart_sdk.js:19876 onPosts: [Instance of 'PostController', Instance of 'PostController', Instance of 'PostController']}
```

Somehow I wasn't able to make the view fetch the data when it is available. 
It always fetches `null` and then the data is set.

I also tried `{{onPosts | async}}` with the same effect.

`Dart VM version: 2.0.0-dev.24.0 (Mon Feb 12 18:55:09 2018 +0100) on "macos_x64"`

angular: 5.0.0-alpha+6
angular_compiler: 0.4.0-alpha+6
angular_components: 0.9.0-alpha+6

**Comment by zoechi** [comment]
I just tried Dart 2.0.0-dev.31.0 but no change
I switched back to dev.24 because later versions result in lots of false analyzer errors (dart-lang/sdk#32335)

**Comment by zoechi** [comment]
Changing all components (except `AppComponent`) to `OnPush` seems to have fixed it.

**Comment by matanlurey** [comment]
I don't know how OnPush works with pipes, unfortunately.

**Comment by zoechi** [comment]
It used to just work. I haven't seen such behavior before.

**Comment by leonsenft** [comment]
Unfortunately it's pretty difficult to say what's going wrong from the single component you've provided. If you can condense this into a smaller, but complete reproduction I'd be happy to debug and fix the issue for you.

**Comment by alorenzen** [comment]
No idea how pipes interact with everything, but it is worth pointing out that `OnPush` Components require that all of their children are *also* `OnPush`.

It's possible that this wasn't the case until you made every component *except* the root `OnPush`.

**Comment by zoechi** [comment]
@alorenzen I wasn't aware of that, but I guess that was the case.
I thought mixing strategy is fine.
What can I do if I use `OnPush` and then want to use 3rd party components that don't use `OnPush` inside it?

**Comment by zoechi** [comment]
Parent component

```dart
class ScaffoldComponent {
  /// Control the drawer
  bool end = false;

  ScaffoldComponent(
    this._activeRouteService,
    this._appControllerService,
    this._cdRef,
  ) {
    _appController.onUserProfileChanged
        .where((s) =>
            s.prev[_appController.authenticatedUserId] !=
            s.next[_appController.authenticatedUserId])
        .listen((_) {
          print('user profile changed $loggedInUserAvatarUrl');
          _cdRef.detectChanges();
        });
  }
```

Child component
```dart
  @override
  void ngDoCheck() {
    print('avatar ngDoCheck - isLoaded: $isLoaded, src: $src');
  }
```

![image](https://user-images.githubusercontent.com/405837/36938094-dbf66ec6-1f1c-11e8-8b7f-4ed4fc319bfc.png)


When I point the mouse over a menu item with an mouseover event handler

![image](https://user-images.githubusercontent.com/405837/36938100-f368b820-1f1c-11e8-9277-d4b04d24a103.png)

I think `_cdRef.detectChanges();` should cause the child component to re-check

**Comment by matanlurey** [comment]
Have you tried `_cdRef.markAsCheck()`?

We don't expect `detectChanges()` to be called by the user.

**Comment by zoechi** [comment]
Thanks a lot. That fixed it 👍 

The docs don't tell that (rather the opposite) 
and I was used to `detectChanges()` to work for that in TS.

**Comment by matanlurey** [comment]
Filed https://github.com/dart-lang/angular/issues/1013. Thanks!
