### ISSUE TITLE
HN firebase deploy: include a message w/ the commit SHA?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#978]
https://github.com/dart-lang/angular/blob/dd1fc24b3c20c47d2c2e1faa2272f367bfbfc3db/tool/deploy.sh#L14

See https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

We can use `TRAVIS_COMMIT` env variable

`firebase deploy --non-interactive -m "For commit $TRAVIS_COMMIT"` or something...

**Comment by matanlurey** [comment]
I don't think we can... use the environment variable in the site, can we?

**Comment by kevmoo** [comment]
It's just the message showing up on the firebase admin page – so we can see which commit is currently deployed – or if it's just me messing around, etc...

**Comment by matanlurey** [comment]
If you don't mess around we don't need to check what the commit is :)

**Comment by kevmoo** [comment]
<img width="974" alt="screen shot 2018-02-28 at 9 37 23 am" src="https://user-images.githubusercontent.com/17034/36802916-07fa6e50-1c6b-11e8-877e-f8cb4da1b4b0.png">

Imagine the message at the bottom was "Auto-deployed from Travis at commit XYZ123" – that's all I want...

**Comment by matanlurey** [comment]
<img width="949" alt="screen shot 2018-03-02 at 6 45 17 pm" src="https://user-images.githubusercontent.com/168174/36929724-e733cd20-1e49-11e8-9ce0-fce5a2dd2252.png">

Looks like its done at HEAD! @kevmoo
