### ISSUE TITLE
async pipe cases "boolean expression must not be null"

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular#979]
```
[disabled]="!(onHasUnsavedChangesChanged | async)">
```

```dart
final bool currVal_3 = !_pipe_async_0.transform(_ctx.onHasUnsavedChangesChanged);
```

![image](https://user-images.githubusercontent.com/405837/36802653-d1fda042-1cb5-11e8-873e-09f0b1854be2.png)

```
Dart VM version: 2.0.0-dev.24.0 (Mon Feb 12 18:55:09 2018 +0100) on "macos_x64"
```
Angular `5.0.0-alpha+6`

I'm sure that `onHasUnsavedChangesChanged` is never `null` and never emits `null`

(store is from `built_redux`)

```dart
Stream<bool> get onHasUnsavedChangesChanged => store
      .substateStream((s) => s.postEditor)
      .where((s) =>
          s.prev.editedPosts.isNotEmpty != s.next.editedPosts.isNotEmpty ||
          s.prev.createdPosts.isNotEmpty != s.next.createdPosts.isNotEmpty)
      .map((s) =>
          s.next.editedPosts.isNotEmpty || s.next.createdPosts.isNotEmpty);
```

**Comment by leonsenft** [comment]
`AsyncPipe` will return null the first time before any data is made available by the stream, and you're negating that result. In other words, you're seeing an exception for calling `!null`.

Fix it by providing a default value when null:

```html
<div [disabled]="!((onHasUnsavedChangesChanged | async) ?? false)">
```

**Comment by zoechi** [comment]
@leonsenft sounds reasonable now after you mention it :D
Thanks a lot.
