### ISSUE TITLE
Could we be using the official HN API? github.com/HackerNews/API

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#983]
https://github.com/dart-lang/angular/blob/dd1fc24b3c20c47d2c2e1faa2272f367bfbfc3db/examples/hacker_news_pwa/lib/hacker_news_service.dart#L7

https://github.com/HackerNews/API

Just curious...

**Comment by leonsenft** [comment]
Possible, but I think this would require implementing a server without it being a performance hit. See https://github.com/dart-lang/angular/issues/974#issuecomment-369319632.

**Comment by kevmoo** [comment]
Right.

We could do it as a cloud function -
https://firebase.google.com/docs/hosting/functions

:-)

**Comment by leonsenft** [comment]
That would alleviate the need for a server, but I imagine it would still be sub-optimal to do a request for every feed item on each request from the client.

**Comment by kevmoo** [comment]
My crazy idea:

   - Populate our own firestore w/ the the ideal data
   - Set up a cloud function on a cron-job to update the data every 10
   minutes...

**Comment by leonsenft** [comment]
Yeah that would work, but I feel like at that point we may as well just write a simple server.

**Comment by kevmoo** [comment]
Hrm...yeah...I'd be nice not to have to babysit a server...

**Comment by matanlurey** [comment]
Closing as it sounds like this isn't actionable.
