### ISSUE TITLE
CanDeactivate change route uri even if return false

### ISSUE THREAD

**Issue by muzuro** [dart-lang/angular#984]
- Overview of the Issue:
I am using [`CanDeactivate`](https://webdev.dartlang.org/angular/guide/router/5#candeactivate-hook-to-handle-unsaved-changes). I created component which implements `CanDeactivate`, in `routerCanDeactivate` i return `false`, but when user press back browser button url changes.
- Angular Version
```
  angular: ^4.0.0+2
  angular_components: ^0.8.0
  angular_forms: ^1.0.0
  angular_router: ^1.0.2
```
- Motivation or Use Case
I am expecting url not change.
- Browsers and Operating System
Dartium  50.0.2661.108, Windows 10.
- Reproduce the Error
I created fork of tour of heroes with  reproduce application: https://github.com/muzuro/toh-6. In hero details i have added [changes](https://github.com/muzuro/toh-6/commit/4c14378531488667691b7df874a883d2bf2f90aa).
Here is video how it looks: http://take.ms/aAlPf
- Related Issues
#985 

What i need - is to ignore back button action(don`t change route url and active component) on some conditions in component.

**Comment by muzuro** [comment]
I found workaround for this issue:
```
bool routerCanDeactivate(ComponentInstruction nextInstruction, ComponentInstruction prevInstruction) {
    var result = shouldDeactivate();
    if (result == false) {
      nextInstruction.urlPath = prevInstruction.urlPath;
    }
    return result;
  }
```

**Comment by matanlurey** [comment]
Unfortunately we're not able to offer support for the original router in 4.0, but I'm glad you found a workaround!
