### ISSUE TITLE
CanDeactivate callback function is calling twice on single browser back button click

### ISSUE THREAD

**Issue by muzuro** [dart-lang/angular#985]
- Overview of the Issue:
I am using [`CanDeactivate`](https://webdev.dartlang.org/angular/guide/router/5#candeactivate-hook-to-handle-unsaved-changes). I created component which implements `CanDeactivate`, when i click back browser button `routerCanDeactivate` is called twice.
- Angular Version
```
  angular: ^4.0.0+2
  angular_components: ^0.8.0
  angular_forms: ^1.0.0
  angular_router: ^1.0.2
```
- Motivation or Use Case
I am expecting `routerCanDeactivate` is called once.
- Browsers and Operating System
Dartium  50.0.2661.108, Windows 10.
- Reproduce the Error
I created fork of tour of heroes with  reproduce application: https://github.com/muzuro/toh-6. In hero details i have added [changes](https://github.com/muzuro/toh-6/commit/4c14378531488667691b7df874a883d2bf2f90aa).
- Related Issues
#984

**Comment by matanlurey** [comment]
Unfortunately we're not able to offer support for the original router in 4.0.

**Comment by muzuro** [comment]
@matanlurey Is there some other router? not original?

**Comment by leonsenft** [comment]
@muzuro The router has been rewritten for version 2. It's currently under alpha release.

https://pub.dartlang.org/packages/angular_router/versions/2.0.0-alpha%2B6

**Comment by muzuro** [comment]
@leonsenft Thanks! Perhaps should try with angular5 alpha
