### ISSUE TITLE
Fix "Progressive Web App" Score no WebPageTest on Mobile

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#986]
See https://www.webpagetest.org/lighthouse.php?test=180301_6A_5ef9c6748da9e69bbf2c599ac0361e2b&run=2

We're getting a 91 instead of 100.

Blocked by https://github.com/GoogleChrome/lighthouse/issues/2363

**Comment by matanlurey** [comment]
This was closed in https://github.com/GoogleChrome/lighthouse/issues/2363.
