### ISSUE TITLE
Consider making the angular builder optional

### ISSUE THREAD

**Issue by natebosch** [dart-lang/angular#988]
Pros:
- Can avoid running the template compiler for components which are unused. Can reduce build times especially in the case where you import package:angular_component and only use a few of them.

Cons:
- Need a dep on `build_resolvers` to make sure the version is new enough that this works.
- Maybe something else? We should do some testing.

Try adding `is_optional: true` in your builder definition in build.yaml

**Comment by matanlurey** [comment]
@natebosch:

> Need a dep on `build_resolvers` to make sure the version is new enough that this works.

What does this mean? 

> Maybe something else? We should do some testing.

I could create a branch if you wanted to just hack around.

**Comment by natebosch** [comment]
> What does this mean?

Today there is no dep on `build_resolvers` because it's an implementation detail. In order to be optional we'd need to start relying on a particular behavior of `build_resolvers` only available in the latest version. I think it's a minor point I think, but still something to think about anytime we introduce new potential version conflicts against `build_runner` etc.

> I could create a branch if you wanted to just hack around.

@jakemac53 and I have both tried this out with good results. I think I'd like someone from the angular team to also try it and give an opinion.

**Comment by matanlurey** [comment]
Sure! As soon as the travis refactor goes I'll give it a shot.

**Comment by jakemac53** [comment]
> Can reduce build times especially in the case where you import package:angular_component and only use a few of them.

To be clear anything reachable by imports will still get compiled, but I have seen a ~10 second reduction in build times with this change for angular_components_example.

**Comment by matanlurey** [comment]
@jakemac53 @natebosch What version of resolvers do I need to try?

**Comment by natebosch** [comment]
> What version of resolvers do I need to try?

`0.2.0`

**Comment by matanlurey** [comment]
Done
